from typing import Literal

_constant: bool
DIGITS: str
TEST_SYNC_ID: str | None

def check_sync_id(sync_id: str) -> bool: ...
def get_sync_id() -> str: ...
def hash_game() -> str: ...
def key_and_hash(sync_id: str) -> tuple[bytes, str]: ...
def verbose_error(e: BaseException) -> str: ...
def upload_content(content: bytes, url: str) -> str | None: ...
def download_content(url: str) -> tuple[bool, str | bytes]: ...
def report_error(message: str) -> None: ...
def upload() -> None: ...
def download() -> Literal[True] | None: ...
