from _typeshed import Incomplete
from renpy.compat import (
    PY2 as PY2,
    basestring as basestring,
    bchr as bchr,
    bord as bord,
    chr as chr,
    open as open,
    pystr as pystr,
    range as range,
    round as round,
    str as str,
    tobytes as tobytes,
    unicode as unicode,
)

def hash_data(data): ...
def hash_list(data): ...
def dump(d) -> None: ...

COMPRESS_NONE: int
COMPRESS_ZLIB: int

class Segment:
    offset: Incomplete
    size: Incomplete
    hash: Incomplete
    compressed: Incomplete
    def __init__(self, offset, size, hash, compressed) -> None: ...
    def __eq__(self, other): ...
    def to_json(self): ...
    @staticmethod
    def from_json(d): ...

class Directory:
    name: Incomplete
    def __init__(self, name) -> None: ...
    def to_json(self): ...
    @staticmethod
    def from_json(d): ...

class File:
    name: Incomplete
    data_filename: Incomplete
    segments: Incomplete
    mtime: Incomplete
    xbit: Incomplete
    def __init__(self, name, data_filename=None, segments=None, mtime: int = 0, xbit: bool = False) -> None: ...
    def to_json(self): ...
    @staticmethod
    def from_json(d): ...
    def scan_segments(self, f, offset, size) -> None: ...
    def scan_rpa(self, f, total_size) -> None: ...
    def scan(self) -> None: ...
    def add_data_filename(self, path) -> None: ...

class FileList:
    directories: Incomplete
    files: Incomplete
    blocks: Incomplete
    def __init__(self) -> None: ...
    def to_json(self): ...
    @staticmethod
    def from_json(d): ...
    def to_current_json(self): ...
    @staticmethod
    def from_current_json(d): ...
    def add_directory(self, name) -> None: ...
    def add_file(self, name, path, xbit) -> None: ...
    def scan(self, root, data_filename: bool = True): ...
    def encode(self): ...
    @staticmethod
    def decode(data): ...
