DEFERRED_UPDATE_FILE: str
DELETED_DIRECTORY: str
first_deferred_delete: bool

def delete(fn: str) -> None: ...
def process_deferred_line(l: str) -> bool: ...
def process_deferred() -> bool: ...
def process_deleted() -> None: ...
def defer_rename(fn: str) -> None: ...
def defer_delete(fn: str) -> None: ...
def init() -> bool: ...
