DEFERRED_UPDATE_FILE: str
DELETED_DIRECTORY: str
first_deferred_delete: bool

def delete(fn: str): ...
def process_deferred_line(l): ...
def process_deferred(): ...
def process_deleted() -> None: ...
def defer_rename(fn) -> None: ...
def defer_delete(fn) -> None: ...
def init(): ...
