from _typeshed import Incomplete

DEFERRED_UPDATE_FILE: str
DELETED_DIRECTORY: str
first_deferred_delete: bool

def delete(fn: str) -> Incomplete: ...
def process_deferred_line(l: Incomplete) -> Incomplete: ...
def process_deferred() -> Incomplete: ...
def process_deleted() -> None: ...
def defer_rename(fn: Incomplete) -> None: ...
def defer_delete(fn: Incomplete) -> None: ...
def init() -> Incomplete: ...
