from _typeshed import Incomplete as Incomplete

def byte_ranges(ranges: Incomplete) -> Incomplete: ...
def write_range(f: Incomplete, headers: Incomplete, content: Incomplete) -> Incomplete: ...
def write_multipart(f: Incomplete, headers: Incomplete, content: Incomplete) -> Incomplete: ...
def download_ranges(
    url: Incomplete, ranges: Incomplete, destination: Incomplete, progress_callback: Incomplete = None
) -> Incomplete: ...
def download(
    url: Incomplete, ranges: Incomplete, destination: Incomplete, progress_callback: Incomplete = None
) -> None: ...
