from collections.abc import Callable, MutableMapping
from typing import TYPE_CHECKING, BinaryIO

if TYPE_CHECKING:
    type Range = tuple[int, int]

def byte_ranges(ranges: list[Range]) -> list[Range]: ...
def write_range(f: BinaryIO, headers: MutableMapping[str, str], content: bytes) -> list[Range]: ...
def write_multipart(f: BinaryIO, headers: MutableMapping[str, str], content: bytes) -> list[Range]: ...
def download_ranges(
    url: str, ranges: list[Range], destination: str, progress_callback: Callable[[int, int], None] | None = None
) -> bool: ...
def download(
    url: str, ranges: list[Range], destination: str, progress_callback: Callable[[int, int], None] | None = None
) -> None: ...
