from . import common as common
from _typeshed import Incomplete as Incomplete

class BlockGenerator:
    lock: Incomplete
    targetdir: Incomplete
    seen_hashes: Incomplete
    max_rpu_size: Incomplete
    blocks: Incomplete
    filelist: Incomplete
    segments: Incomplete
    new_rpu: Incomplete
    def __init__(self, targetdir: Incomplete, max_rpu_size: Incomplete = ...) -> None: ...
    def path(self, name: Incomplete) -> Incomplete: ...
    def open_new_rpu(self) -> None: ...
    def close_new_rpu(self) -> None: ...
    def generate_segment(self, f: Incomplete, seg: Incomplete) -> None: ...
    def generate(self, name: Incomplete, filelist: Incomplete, progress: Incomplete = None) -> Incomplete: ...
