from . import common as common, deferred as deferred, download as download
from _typeshed import Incomplete
from renpy.compat import (
    PY2 as PY2,
    basestring as basestring,
    bchr as bchr,
    bord as bord,
    chr as chr,
    open as open,
    pystr as pystr,
    range as range,
    round as round,
    str as str,
    tobytes as tobytes,
    unicode as unicode,
)

PREPARING: str
DOWNLOADING: str
UNPACKING: str
FINISHING: str

class UpdateError(Exception): ...

class Plan:
    block: Incomplete
    old_filename: Incomplete
    old_offset: Incomplete
    old_size: Incomplete
    compressed: Incomplete
    new_filename: Incomplete
    new_offset: Incomplete
    new_size: Incomplete
    hash: Incomplete
    def __init__(
        self, block, old_filename, old_offset, old_size, compressed, new_filename, new_offset, new_size, hash
    ) -> None: ...

class Update:
    url: Incomplete
    targetdir: Incomplete
    oldlists: Incomplete
    newlists: Incomplete
    old_directories: Incomplete
    new_directories: Incomplete
    new_files: Incomplete
    old_files: Incomplete
    block_files: Incomplete
    old_disk_total: int
    new_disk_total: int
    download_total: int
    download_done: int
    write_total: int
    write_done: int
    plan: Incomplete
    destination_filename: Incomplete
    destination_fp: Incomplete
    aggressive_removal: Incomplete
    progress_callback: Incomplete
    removals: set[str]
    updatedir: Incomplete
    blockdir: Incomplete
    deleteddir: Incomplete
    logfile: Incomplete
    def __init__(
        self, url, newlists, targetdir, oldlists, progress_callback=None, logfile=None, aggressive_removal: bool = False
    ) -> None: ...
    def init(self) -> None: ...
    def update(self) -> None: ...
    def progress(self, message, done) -> None: ...
    def log(self, message, *args) -> None: ...
    def delete(self, filename) -> None: ...
    def rename(self, old_filename, new_filename) -> None: ...
    def make_directories(self): ...
    def find_incomplete_files(self) -> None: ...
    def write_padding(self) -> None: ...
    def scan_old_files(self) -> None: ...
    def prepare_new_files(self) -> None: ...
    def remove_identical_files(self) -> None: ...
    def create_plan(self): ...
    def compute_totals(self) -> None: ...
    def find_removals(self) -> None: ...
    def write_destination(self, filename, offset, data) -> None: ...
    def download_patch_progress(self) -> None: ...
    def download_block_file(self, filename, plan): ...
    def execute_file_plan(self, plan) -> None: ...
    def execute_plan(self) -> None: ...
    def create_empty_new_files(self) -> None: ...
    def rename_new_files(self) -> None: ...
    def remove_old_files(self) -> None: ...
    def set_xbit(self) -> None: ...

def main() -> None: ...
