from collections.abc import Iterable
from typing import Any

from renpy.display.displayable import DisplayableArguments as DisplayableArguments
from renpy.text.textsupport import DISPLAYABLE as DISPLAYABLE
from renpy.text.textsupport import PARAGRAPH as PARAGRAPH
from renpy.text.textsupport import TAG as TAG

text_tags: dict[str, bool]

def check_text_tags(s: str, check_unclosed: bool = False) -> str | None: ...
def filter_text_tags(s: str, allow: Iterable[str] | None = None, deny: Iterable[str] | None = None) -> str: ...
def filter_alt_text(s: Any) -> str: ...

class ParameterizedText:
    style: str
    properties: dict[str, Any]
    def __init__(self, style: str = "default", **properties) -> None: ...
    _duplicatable: bool
    def _duplicate(self, args: DisplayableArguments | None = None) -> ParameterizedText: ...

def textwrap(s: str, width: int = 78, asian: bool = False) -> list[str]: ...
def thaic90(s: str) -> str: ...
