from _typeshed import Incomplete as Incomplete
from renpy.text.textsupport import DISPLAYABLE as DISPLAYABLE, PARAGRAPH as PARAGRAPH, TAG as TAG

text_tags: Incomplete

def check_text_tags(s: Incomplete, check_unclosed: bool = False) -> Incomplete: ...
def filter_text_tags(s: Incomplete, allow=None, deny=None) -> Incomplete: ...
def filter_alt_text(s: Incomplete) -> str: ...

class ParameterizedText:
    style: Incomplete
    properties: Incomplete
    def __init__(self, style: str = "default", **properties) -> None: ...

def textwrap(s: Incomplete, width: int = 78, asian: bool = False) -> Incomplete: ...
def thaic90(s: Incomplete) -> Incomplete: ...
