from renpy.text.textsupport import DISPLAYABLE as DISPLAYABLE, PARAGRAPH as PARAGRAPH, TAG as TAG
from renpy.display.displayable import DisplayableArguments as DisplayableArguments
from typing import Iterable, Any

text_tags: dict[str, bool]

def check_text_tags(s: str, check_unclosed: bool = False) -> str | None: ...
def filter_text_tags(s: str, allow: Iterable[str] | None = None, deny: Iterable[str] | None = None) -> str: ...
def filter_alt_text(s: str) -> str: ...

class ParameterizedText:
    style: str
    properties: dict[str, Any]
    def __init__(self, style: str = "default", **properties) -> None: ...
    _duplicatable: bool
    def _duplicate(self, args: DisplayableArguments | None = None) -> ParameterizedText: ...

def textwrap(s: str, width: int = 78, asian: bool = False) -> list[str]: ...
def thaic90(s: str) -> str: ...
