from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

class FTFace:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class FTFont:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def bounds(self, glyphs: Incomplete, bounds: Incomplete) -> None: ...
    def draw(
        self,
        pysurf: Incomplete,
        xo: float,
        yo: int,
        color: Incomplete,
        glyphs: list,
        underline: int,
        strikethrough: bool,
        black_color: Incomplete,
    ) -> Incomplete: ...
    def glyphs(self, s: str, level: int) -> Incomplete: ...

class FreetypeError(Exception):
    def __init__(self, code: Incomplete) -> None: ...

def init() -> None: ...
