from _frozen_importlib import BuiltinImporter as BuiltinImporter

class FTFace:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...

class FTFont:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def bounds(self, glyphs, bounds) -> None: ...
    def draw(
        self, pysurf, xo: float, yo: int, color, glyphs: list, underline: int, strikethrough: bool, black_color
    ): ...
    def glyphs(self, s: str, level: int): ...

class FreetypeError(Exception):
    def __init__(self, code) -> None: ...

def init() -> None: ...
