class FTFace:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...

class FTFont:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...
    def bounds(self, glyphs, bounds): ...
    def draw(
        self, pysurf, xo: float, yo: int, color, glyphs: list, underline: int, strikethrough: bool, black_color
    ): ...
    def glyphs(self, s: str, level: int): ...

class FreetypeError(Exception):
    def __init__(self, code): ...

    pass

def init(): ...
