from _frozen_importlib import BuiltinImporter as BuiltinImporter

class Axis:
    def __init__(self, index, minimum, default, maximum) -> None: ...

class Features:
    def __init__(self, features) -> None: ...
    def __reduce__(self) -> None: ...
    @staticmethod
    def get(features) -> None: ...

class FreetypeError(Exception):
    def __init__(self, code) -> None: ...

class HBFace:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...

class HBFont:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def bounds(self, glyphs, bounds) -> None: ...
    def draw(
        self, pysurf, xo: float, yo: int, color, glyphs: list, underline: int, strikethrough: bool, black_color
    ): ...
    def glyphs(self, s: str, level: int): ...

class Variations:
    def __init__(self) -> None: ...

def init() -> None: ...
