class Axis:
    def __init__(self, index, minimum, default, maximum): ...
    def __repr__(self): ...

class Features:
    def __init__(self, features): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...
    @staticmethod
    def get(features): ...

class FreetypeError(Exception):
    def __init__(self, code): ...

    pass

class HBFace:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...

class HBFont:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...
    def bounds(self, glyphs, bounds): ...
    def draw(
        self, pysurf, xo: float, yo: int, color, glyphs: list, underline: int, strikethrough: bool, black_color
    ): ...
    def glyphs(self, s: str, level: int): ...

class Variations:
    def __init__(
        self,
    ): ...
    def __repr__(self): ...

    _console_always_long: int

def init(): ...
