from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

class Axis:
    def __init__(self, index: Incomplete, minimum: Incomplete, default: Incomplete, maximum: Incomplete) -> None: ...

class Features:
    def __init__(self, features: Incomplete) -> None: ...
    def __reduce__(self) -> None: ...
    @staticmethod
    def get(features: Incomplete) -> None: ...

class FreetypeError(Exception):
    def __init__(self, code: Incomplete) -> None: ...

class HBFace:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...

class HBFont:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def bounds(self, glyphs: Incomplete, bounds: Incomplete) -> None: ...
    def draw(
        self,
        pysurf: Incomplete,
        xo: float,
        yo: int,
        color: Incomplete,
        glyphs: list,
        underline: int,
        strikethrough: bool,
        black_color: Incomplete,
    ) -> None: ...
    def glyphs(self, s: str, level: int) -> Incomplete: ...

class Variations:
    def __init__(self) -> None: ...

def init() -> None: ...
