import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from renpy.text.shader import TextShader as TextShader
from typing import Any, Literal

split_name: dict[int, str]

class Glyph:
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    x: int
    y: int
    delta_x_adjustment: int
    character: int
    variation: int
    split: int
    ruby: int
    ascent: int
    descent: int
    line_spacing: int
    width: float
    advance: float
    time: float
    hyperlink: int
    draw: bool
    add_left: int
    add_top: int
    add_right: int
    add_bottom: int
    rtl: bool
    duration: float
    shader: renpy.text.shader.TextShader | None
    index: int

class Line:
    def __init__(self, y: int, baseline: int, height: int, glyphs: list[Glyph]) -> None: ...
    y: int
    height: int
    baseline: int
    glyphs: list[Glyph]
    max_time: float
    eop: bool

def adjust_glyph_spacing(glyphs: list[Glyph], lines: list[Line], dx: float, dy: float, w: float, h: float) -> None: ...
def align_and_justify(lines: list[Line], width: int, text_align: float, justify: bool) -> None: ...
def annotate_anywhere(glyphs: list[Glyph]) -> None: ...
def annotate_unicode(glyphs: list[Glyph], no_ideographs: bool, cjk: int) -> None: ...
def annotate_western(glyphs: list[Glyph]) -> None: ...
def assign_index(index: int, glyphs: list[Glyph]) -> int: ...  # TODO: double check index/return types. May be float
def assign_times(t: float, gps: float, glyphs: list[Glyph]) -> float: ...
def copy_splits(source: list[Glyph], dest: list[Glyph]) -> None: ...
def get_textshader_set(glyphs: list[Glyph]) -> set[renpy.text.shader.TextShader]: ...
def hyperlink_areas(
    l: list[Line],
) -> list[tuple[int, int, int, int, int, float]]: ...  # TODO: double check return types
def kerning(glyphs: list[Glyph], amount: float) -> None: ...
def language_tailor(chars: str, cls: str) -> None: ...
def lenticular_bracket_ruby(s: str) -> list[tuple[int, str]]: ...
def linebreak_debug(glyphs: list[Glyph]) -> str: ...
def linebreak_greedy(glyphs: list[Glyph], first_width: int, rest_width: int) -> None: ...
def linebreak_list(glyphs: list[Glyph]) -> list[str]: ...
def linebreak_nobreak(glyphs: list[Glyph]) -> None: ...
def mark_altruby_top(l: list[Line]) -> None: ...
def mark_ruby_bottom(l: list[Line]) -> None: ...
def mark_ruby_top(l: list[Line]) -> None: ...
def max_times(l: list[Line]) -> float: ...
def move_glyphs(glyphs: list[Glyph], x: int, y: int) -> None: ...
def place_horizontal(glyphs: list[Glyph], start_x: float, first_indent: float, rest_indent: float) -> float: ...
def place_ruby(
    glyphs: list[Glyph], ruby_offset: int, altruby_offset: int, surf_width: int, surf_height: int
) -> None: ...
def place_vertical(
    glyphs: list[Glyph], y: int, spacing: int, leading: int, ruby_line_leading: int
) -> tuple[list[Line], int]: ...
def reverse_lines(glyphs: list[Glyph]) -> list[Glyph]: ...
def tokenize(s: str) -> list[tuple[int, str]]: ...

DISPLAYABLE: Literal[4]
PARAGRAPH: Literal[3]
TAG: Literal[2]
TEXT: Literal[1]
