import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from renpy.text.shader import TextShader as TextShader
from _typeshed import Incomplete

class Glyph:
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    x: int
    y: int
    delta_x_adjustment: int
    character: int
    variation: int
    split: int
    ruby: int
    ascent: int
    descent: int
    line_spacing: int
    width: float
    advance: float
    time: float
    hyperlink: int
    draw: bool
    add_left: int
    add_top: int
    add_right: int
    add_bottom: int
    rtl: bool
    duration: float
    shader: renpy.text.shader.TextShader | None
    index: short

class Line:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    y: int
    height: int
    baseline: int
    glyphs: list[Glyph]
    max_time: float
    eop: bool

def adjust_glyph_spacing(glyphs: list, lines: list, dx: float, dy: float, w: float, h: float) -> Incomplete: ...
def align_and_justify(lines: list, width: int, text_align: float, justify: bool) -> Incomplete: ...
def annotate_anywhere(glyphs: list) -> Incomplete: ...
def annotate_unicode(glyphs: list, no_ideographs: bool, cjk: int) -> Incomplete: ...
def annotate_western(glyphs: list) -> Incomplete: ...
def assign_index(index: Incomplete, glyphs: list) -> Incomplete: ...
def assign_times(t: float, gps: float, glyphs: list) -> Incomplete: ...
def chr(i: Incomplete, /) -> None: ...
def copy_splits(source: list, dest: list) -> Incomplete: ...
def get_textshader_set(glyphs: list) -> Incomplete: ...
def hyperlink_areas(l: list) -> Incomplete: ...
def kerning(glyphs: list, amount: float) -> Incomplete: ...
def language_tailor(chars: Incomplete, cls: Incomplete) -> None: ...
def lenticular_bracket_ruby(s: Incomplete) -> None: ...
def linebreak_debug(glyphs: list) -> Incomplete: ...
def linebreak_greedy(glyphs: list, first_width: int, rest_width: int) -> Incomplete: ...
def linebreak_list(glyphs: list) -> Incomplete: ...
def linebreak_nobreak(glyphs: list) -> Incomplete: ...
def mark_altruby_top(l: list) -> Incomplete: ...
def mark_ruby_bottom(l: list) -> Incomplete: ...
def mark_ruby_top(l: list) -> Incomplete: ...
def max_times(l: list) -> Incomplete: ...
def move_glyphs(glyphs: list, x: int, y: int) -> Incomplete: ...
def place_horizontal(glyphs: list, start_x: float, first_indent: float, rest_indent: float) -> Incomplete: ...
def place_ruby(
    glyphs: list, ruby_offset: int, altruby_offset: int, surf_width: int, surf_height: int
) -> Incomplete: ...
def place_vertical(glyphs: list, y: int, spacing: int, leading: int, ruby_line_leading: int) -> Incomplete: ...
def reverse_lines(glyphs: list) -> Incomplete: ...
def tokenize(s: str) -> Incomplete: ...

DISPLAYABLE: int
PARAGRAPH: int
TAG: int
TEXT: int
i: int
