from _frozen_importlib import BuiltinImporter as BuiltinImporter

class WordWrapper:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...

def linebreak_tex(glyphs, first_width, rest_width, subtitle) -> None: ...
