class WordWrapper:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...

def linebreak_tex(glyphs, first_width, rest_width, subtitle): ...
