import io
from _typeshed import Incomplete

FSENCODING: Incomplete
old_stdout: Incomplete
old_stderr: Incomplete

class NullFile(io.IOBase):
    def write(self, s) -> None: ...
    def read(self, length=None) -> None: ...
    def flush(self) -> None: ...

def null_files() -> None: ...

trace_file: Incomplete
trace_local: Incomplete

def trace_function(frame, event, arg): ...
def enable_trace(level) -> None: ...
def mac_start(fn) -> None: ...
def popen_del(self, *args, **kwargs) -> None: ...
def get_alternate_base(basedir, always: bool = False): ...
def excepthook(type, value, traceback) -> None: ...
def relaunch() -> None: ...
def bootstrap(renpy_base) -> None: ...
