from _typeshed import Incomplete
from collections.abc import Generator
from renpy.compat.pickle import loads as loads
from renpy.pygame.rwobject import RWopsIO as RWopsIO
from renpy.webloader import DownloadNeeded as DownloadNeeded
from typing import Literal

def get_path(fn): ...

apks: Incomplete
game_apks: Incomplete
split_apks: Incomplete

def find_apks() -> None: ...

archives: Incomplete
lower_map: dict[str, str]

class ArchiveHandlers:
    exts: Incomplete
    peek: Incomplete
    def __init__(self) -> None: ...
    def append(self, handler) -> None: ...
    def spec(self, ext): ...

archive_handlers: Incomplete

class RPAv3ArchiveHandler:
    archive_extension: str
    @staticmethod
    def get_supported_extensions(): ...
    @staticmethod
    def get_supported_headers(): ...
    @staticmethod
    def read_index(infile): ...

class RPAv2ArchiveHandler:
    archive_extension: str
    @staticmethod
    def get_supported_extensions(): ...
    @staticmethod
    def get_supported_headers(): ...
    @staticmethod
    def read_index(infile): ...

class RPAv1ArchiveHandler:
    archive_extension: str
    @staticmethod
    def get_supported_extensions(): ...
    @staticmethod
    def get_supported_headers(): ...
    @staticmethod
    def read_index(infile): ...

def index_files() -> None: ...
def index_archives() -> None: ...
def walkdir(path, elide=None) -> Generator[Incomplete, Incomplete]: ...

arc_files: Incomplete
common_files: list[tuple[str, str]]
game_files: list[tuple[str, str]]
loadable_cache: Incomplete
remote_files: Incomplete
scandirfiles_callbacks: Incomplete
type TreeEntry = dict[str, "TreeEntry"] | Literal[True]
tree: TreeEntry

def scandirfiles() -> None: ...
def scandirfiles_from_apk(add, seen) -> None: ...
def scandirfiles_from_remote_file(add, seen) -> None: ...
def scandirfiles_from_filesystem(add, seen) -> None: ...
def scandirfiles_from_archives(add, seen) -> None: ...
def listdirfiles(common: bool = True, game: bool = True): ...

open_file = RWopsIO
file_open_callbacks: Incomplete

def load_core(name): ...
def load_from_file_open_callback(name): ...
def load_from_filesystem(name): ...
def load_from_archive(name): ...
def load_from_apk(name): ...
def load_from_remote_file(name) -> None: ...
def check_name(name) -> None: ...
def get_prefixes(tl: bool = True, directory=None): ...
def load(name, directory=None, tl: bool = True): ...
def loadable_core(name): ...
def loadable(name, tl: bool = True, directory=None): ...
def transpath(path: str) -> str | None: ...
def transfn(name: bytes | str) -> str: ...

hash_cache: Incomplete

def get_hash(name: str) -> int: ...

needs_autoreload: Incomplete
auto_mtimes: Incomplete
auto_thread: Incomplete
auto_quit_flag: bool
auto_lock: Incomplete
auto_blacklisted: Incomplete

def auto_mtime(fn): ...
def add_auto(fn, force: bool = False) -> None: ...

max_mtime: int

def auto_thread_function() -> None: ...
def check_git_index_lock(): ...

reloading: bool

def check_autoreload() -> None: ...
def auto_init() -> None: ...
def auto_quit() -> None: ...
