def Allpass(frequency=350, q=1.0): ...

class AudioFilter:
    def __reduce__(self): ...
    def __repr__(self, /): ...
    def __setstate__(self, __pyx_state): ...
    def prepare(self, samplerate): ...

def Bandpass(frequency=350, q=1.0): ...

class Biquad(AudioFilter):
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def prepare(self, samplerate): ...

class Comb(AudioFilter):
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def prepare(self, samplerate: int): ...

class Crossfade(AudioFilter):
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def prepare(self, samplerate: int): ...

class Delay(AudioFilter):
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def prepare(self, samplerate: int): ...

class DelayBuffer:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...

class FilterList:
    def __init__(self, /, *args, **kwargs): ...
    def __iter__(self, /): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...

def Gain(db): ...
def Highpass(frequency=350, q=1.0): ...
def Highshelf(frequency=350, gain=0): ...
def Lowpass(frequency=350, q=1.0): ...
def Lowshelf(frequency=350, gain=0): ...

class Mix(AudioFilter):
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def prepare(self, samplerate: int): ...

class Multiply(AudioFilter):
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def prepare(self, samplerate: int): ...

def Notch(frequency=350, q=1.0): ...

class Null(AudioFilter):
    def __reduce__(self): ...
    def prepare(self, samplerate: int): ...

def Peaking(frequency=350, q=1.0, gain=0): ...
def Reverb(
    resonance=0.5,
    dampening=880,
    wet=1.0,
    dry=1.0,
    delay_multiplier=1.0,
    delay_times=[0.0253, 0.0269, 0.029, 0.0307, 0.0322, 0.0338, 0.0353, 0.0367],
    delay_subchannel=0.001,
    allpass_frequences=[225, 556, 441, 341],
): ...

class Sequence(AudioFilter):
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def prepare(self, samplerate: int): ...

class WetDry(AudioFilter):
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def prepare(self, samplerate: int): ...

def to_audio_filter(o): ...
