from _frozen_importlib import BuiltinImporter as BuiltinImporter

def Allpass(frequency: int = 350, q: float = 1.0) -> None: ...

class AudioFilter:
    def __reduce__(self) -> None: ...
    def prepare(self, samplerate) -> None: ...

def Bandpass(frequency: int = 350, q: float = 1.0) -> None: ...

class Biquad(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def prepare(self, samplerate) -> None: ...

class Comb(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def prepare(self, samplerate: int): ...

class Crossfade(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def prepare(self, samplerate: int): ...

class Delay(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def prepare(self, samplerate: int): ...

class DelayBuffer:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...

class FilterList:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __iter__(self): ...
    def __reduce__(self) -> None: ...

def Gain(db) -> None: ...
def Highpass(frequency: int = 350, q: float = 1.0) -> None: ...
def Highshelf(frequency: int = 350, gain: int = 0) -> None: ...
def Lowpass(frequency: int = 350, q: float = 1.0) -> None: ...
def Lowshelf(frequency: int = 350, gain: int = 0) -> None: ...

class Mix(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def prepare(self, samplerate: int): ...

class Multiply(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def prepare(self, samplerate: int): ...

def Notch(frequency: int = 350, q: float = 1.0) -> None: ...

class Null(AudioFilter):
    def __reduce__(self) -> None: ...
    def prepare(self, samplerate: int): ...

def Peaking(frequency: int = 350, q: float = 1.0, gain: int = 0) -> None: ...
def Reverb(
    resonance: float = 0.5,
    dampening: int = 880,
    wet: float = 1.0,
    dry: float = 1.0,
    delay_multiplier: float = 1.0,
    delay_times=[0.0253, 0.0269, 0.029, 0.0307, 0.0322, 0.0338, 0.0353, 0.0367],
    delay_subchannel: float = 0.001,
    allpass_frequences=[225, 556, 441, 341],
) -> None: ...

class Sequence(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def prepare(self, samplerate: int): ...

class WetDry(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def prepare(self, samplerate: int): ...

def to_audio_filter(o) -> None: ...
