from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete
from typing import overload

def Allpass(frequency: int = 350, q: float = 1.0) -> None: ...

class AudioFilter:
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def prepare(self, samplerate: int) -> None: ...

def Bandpass(frequency: int = 350, q: float = 1.0) -> None: ...

class Biquad(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def prepare(self, samplerate: int) -> None: ...

class Comb(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def prepare(self, samplerate: int) -> Incomplete: ...

class Crossfade(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def prepare(self, samplerate: int) -> Incomplete: ...

class Delay(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def prepare(self, samplerate: int) -> Incomplete: ...

class DelayBuffer:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class FilterList:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __iter__(self) -> Incomplete: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

def Gain(db: Incomplete) -> None: ...
def Highpass(frequency: int = 350, q: float = 1.0) -> None: ...
def Highshelf(frequency: int = 350, gain: int = 0) -> None: ...
def Lowpass(frequency: int = 350, q: float = 1.0) -> None: ...
def Lowshelf(frequency: int = 350, gain: int = 0) -> None: ...

class Mix(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def prepare(self, samplerate: int) -> Incomplete: ...

class Multiply(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def prepare(self, samplerate: int) -> Incomplete: ...

def Notch(frequency: int = 350, q: float = 1.0) -> None: ...

class Null(AudioFilter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def prepare(self, samplerate: int) -> Incomplete: ...

def Peaking(frequency: int = 350, q: float = 1.0, gain: int = 0) -> None: ...
def Reverb(
    resonance: float = 0.5,
    dampening: int = 880,
    wet: float = 1.0,
    dry: float = 1.0,
    delay_multiplier: float = 1.0,
    delay_times=[0.0253, 0.0269, 0.029, 0.0307, 0.0322, 0.0338, 0.0353, 0.0367],
    delay_subchannel: float = 0.001,
    allpass_frequences=[225, 556, 441, 341],
) -> None: ...

class Sequence(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def prepare(self, samplerate: int) -> Incomplete: ...

class WetDry(AudioFilter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def prepare(self, samplerate: int) -> Incomplete: ...

@overload
def to_audio_filter(o: list[AudioFilter]) -> list[AudioFilter]: ...
@overload
def to_audio_filter(o: AudioFilter) -> AudioFilter: ...
def to_audio_filter(o: list[AudioFilter] | AudioFilter) -> AudioFilter | list[AudioFilter]: ...
