from renpy.audio.audio import (
    alias_channel as alias_channel,
    get_channel as get_channel,
    get_serial as get_serial,
    register_channel as register_channel,
)

def play(
    filenames,
    channel: str = "music",
    loop=None,
    fadeout=None,
    synchro_start=None,
    fadein: int = 0,
    tight=None,
    if_changed: bool = False,
    relative_volume: float = 1.0,
) -> None: ...
def queue(
    filenames,
    channel: str = "music",
    loop=None,
    clear_queue: bool = True,
    fadein: int = 0,
    tight=None,
    relative_volume: float = 1.0,
) -> None: ...
def playable(filename, channel: str = "music"): ...
def stop(channel: str = "music", fadeout=None) -> None: ...
def set_music(channel, flag, default: bool = False) -> None: ...
def is_music(channel): ...
def get_delay(time, channel: str = "music"): ...
def get_pos(channel: str = "music"): ...
def get_duration(channel: str = "music"): ...
def get_playing(channel: str = "music"): ...
def is_playing(channel: str = "music"): ...
def get_loop(channel: str = "music"): ...
def set_volume(volume, delay: int = 0, channel: str = "music") -> None: ...
def set_pan(pan, delay, channel: str = "music") -> None: ...
def set_queue_empty_callback(callback, channel: str = "music") -> None: ...
def set_pause(value, channel: str = "music") -> None: ...
def get_pause(channel: str = "music"): ...
def pump() -> None: ...
def set_mixer(channel, mixer, default: bool = False) -> None: ...
def get_all_mixers(): ...
def channel_defined(channel): ...
def set_audio_filter(channel, audio_filter, replace: bool = False, duration: float = 0.016) -> None: ...
