import renpy
from renpy.audio.audio import (
    alias_channel as alias_channel,
    get_channel as get_channel,
    get_serial as get_serial,
    register_channel as register_channel,
)
from typing import Callable

def play(
    filenames: str | list[str],
    channel: str = "music",
    loop: bool | None = None,
    fadeout: float | None = None,
    synchro_start: bool | None = None,
    fadein: float = 0,
    tight: bool | None = None,
    if_changed: bool = False,
    relative_volume: float = 1.0,
) -> None: ...
def queue(
    filenames: str | list[str] | None,
    channel: str = "music",
    loop: bool | None = None,
    clear_queue: bool = True,
    fadein: float = 0,
    tight: bool | None = None,
    relative_volume: float = 1.0,
) -> None: ...
def playable(filename: str, channel: str = "music") -> bool: ...
def stop(channel: str = "music", fadeout: float | None = None) -> None: ...
def set_music(channel: str, flag: bool, default: bool = False) -> None: ...
def is_music(channel: str) -> bool: ...
def get_delay(time: float, channel: str = "music") -> float | None: ...
def get_pos(channel: str = "music") -> float | None: ...
def get_duration(channel: str = "music") -> float: ...
def get_playing(channel: str = "music") -> str | None: ...
def is_playing(channel: str = "music") -> bool: ...
def get_loop(channel: str = "music") -> list[str] | None: ...
def set_volume(volume: float, delay: float = 0, channel: str = "music") -> None: ...
def set_pan(pan: float, delay: float, channel: str = "music") -> None: ...
def set_queue_empty_callback(callback: Callable[[], None], channel: str = "music") -> None: ...
def set_pause(value: bool, channel: str = "music") -> None: ...
def get_pause(channel: str = "music") -> bool: ...
def pump() -> None: ...
def set_mixer(channel: str, mixer: str, default: bool = False) -> None: ...
def get_all_mixers() -> list[str]: ...
def channel_defined(channel: str) -> bool: ...
def set_audio_filter(
    channel: str,
    audio_filter: renpy.audio.filter.AudioFilter | list[renpy.audio.filter.AudioFilter],
    replace: bool = False,
    duration: float = 0.016,
) -> None: ...
