from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

from renpy.pygame.surface import Surface
from renpy.audio.filter import AudioFilter

def advance_time() -> None: ...
def busy(channel: int) -> bool: ...
def check_error() -> None: ...
def deallocate_audio_filter(audio_filter: AudioFilter) -> None: ...
def dequeue(channel: int, even_tight: bool = False) -> None: ...
def fadeout(channel: int, delay: float) -> None: ...
def get_duration(channel: int) -> float: ...
def get_pos(channel: int) -> float: ...
def get_sample_rate() -> int: ...
def get_volume(channel: int) -> float: ...
def global_pause(pause: int) -> None: ...
def init(
    freq: int,
    stereo: int,
    samples: int,
    status: bool = False,
    equal_mono: bool = False,
    linear_fades: bool = False,
) -> None: ...
def pause(channel: int) -> None: ...
def periodic() -> None: ...
def play(
    channel: int,
    file: Incomplete,
    name: str,
    synchro_start: bool = False,
    fadein: int = 0,
    tight: bool = False,
    start: float = 0,
    end: float = 0,
    relative_volume: float = 1.0,
    audio_filter: AudioFilter | None = None,
) -> None: ...
def playing_name(channel: int) -> str | None: ...
def queue(
    channel: int,
    file: Incomplete,
    name: str,
    synchro_start: bool = False,
    fadein: int = 0,
    tight: bool = False,
    start: float = 0,
    end: float = 0,
    relative_volume: float = 1.0,
    audio_filter: AudioFilter | None = None,
) -> None: ...
def queue_depth(channel: int) -> int: ...
def quit() -> None: ...
def read_video(channel: int) -> Surface: ...
def replace_audio_filter(channel: int, audio_filter: AudioFilter, playing: bool) -> None: ...
def sample_surfaces(rgb: Surface, rgba: Surface) -> None: ...
def set_channel_count(count: int) -> None: ...
def set_generate_audio_c_function(fn: int) -> None: ...
def set_pan(channel: int, pan: float, delay: float) -> None: ...
def set_secondary_volume(channel: int, volume: float, delay: float) -> None: ...
def set_video(channel: int, video: int, loop: bool = False) -> None: ...
def set_volume(channel: int, volume: float) -> None: ...
def stop(channel: int) -> None: ...
def unpause(channel: int) -> None: ...
def video_ready(channel: int) -> int: ...

DROP_VIDEO: int
NODROP_VIDEO: int
NO_VIDEO: int
is_webaudio: bool
rgb_surface = Surface | None
rgba_surface = Surface | None
