from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

from renpy.pygame.surface import Surface

def advance_time() -> None: ...
def busy(channel: Incomplete) -> None: ...
def check_error() -> None: ...
def deallocate_audio_filter(audio_filter: Incomplete) -> None: ...
def dequeue(channel: Incomplete, even_tight: bool = False) -> None: ...
def fadeout(channel: Incomplete, delay: Incomplete) -> None: ...
def get_duration(channel: Incomplete) -> None: ...
def get_pos(channel: Incomplete) -> None: ...
def get_sample_rate() -> None: ...
def get_volume(channel: Incomplete) -> None: ...
def global_pause(pause: Incomplete) -> None: ...
def init(
    freq: Incomplete,
    stereo: Incomplete,
    samples: Incomplete,
    status: bool = False,
    equal_mono: bool = False,
    linear_fades: bool = False,
) -> None: ...
def pause(channel: Incomplete) -> None: ...
def periodic() -> None: ...
def play(
    channel: Incomplete,
    file: Incomplete,
    name: Incomplete,
    synchro_start: bool = False,
    fadein: int = 0,
    tight: bool = False,
    start: int = 0,
    end: int = 0,
    relative_volume: float = 1.0,
    audio_filter: Incomplete = None,
) -> None: ...
def playing_name(channel: Incomplete) -> None: ...
def queue(
    channel: Incomplete,
    file: Incomplete,
    name: Incomplete,
    synchro_start: bool = False,
    fadein: int = 0,
    tight: bool = False,
    start: int = 0,
    end: int = 0,
    relative_volume: float = 1.0,
    audio_filter: Incomplete = None,
) -> None: ...
def queue_depth(channel: Incomplete) -> None: ...
def quit() -> None: ...
def read_video(channel: int) -> Surface: ...
def replace_audio_filter(channel: Incomplete, audio_filter: Incomplete, playing: Incomplete) -> None: ...
def sample_surfaces(rgb: Incomplete, rgba: Incomplete) -> None: ...
def set_channel_count(count: Incomplete) -> None: ...
def set_generate_audio_c_function(fn: Incomplete) -> None: ...
def set_pan(channel: Incomplete, pan: Incomplete, delay: Incomplete) -> None: ...
def set_secondary_volume(channel: Incomplete, volume: Incomplete, delay: Incomplete) -> None: ...
def set_video(channel: Incomplete, video: Incomplete, loop: bool = False) -> None: ...
def set_volume(channel: Incomplete, volume: Incomplete) -> None: ...
def stop(channel: Incomplete) -> None: ...
def unpause(channel: Incomplete) -> None: ...
def video_ready(channel: Incomplete) -> None: ...

DROP_VIDEO: int
NODROP_VIDEO: int
NO_VIDEO: int
is_webaudio: int
