from _frozen_importlib import BuiltinImporter as BuiltinImporter

def advance_time() -> None: ...
def busy(channel) -> None: ...
def check_error() -> None: ...
def deallocate_audio_filter(audio_filter) -> None: ...
def dequeue(channel, even_tight: bool = False) -> None: ...
def fadeout(channel, delay) -> None: ...
def get_duration(channel) -> None: ...
def get_pos(channel) -> None: ...
def get_sample_rate() -> None: ...
def get_volume(channel) -> None: ...
def global_pause(pause) -> None: ...
def init(freq, stereo, samples, status: bool = False, equal_mono: bool = False, linear_fades: bool = False) -> None: ...
def pause(channel) -> None: ...
def periodic() -> None: ...
def play(
    channel,
    file,
    name,
    synchro_start: bool = False,
    fadein: int = 0,
    tight: bool = False,
    start: int = 0,
    end: int = 0,
    relative_volume: float = 1.0,
    audio_filter=None,
) -> None: ...
def playing_name(channel) -> None: ...
def queue(
    channel,
    file,
    name,
    synchro_start: bool = False,
    fadein: int = 0,
    tight: bool = False,
    start: int = 0,
    end: int = 0,
    relative_volume: float = 1.0,
    audio_filter=None,
) -> None: ...
def queue_depth(channel) -> None: ...
def quit() -> None: ...
def read_video(channel) -> None: ...
def replace_audio_filter(channel, audio_filter, playing) -> None: ...
def sample_surfaces(rgb, rgba) -> None: ...
def set_channel_count(count) -> None: ...
def set_generate_audio_c_function(fn) -> None: ...
def set_pan(channel, pan, delay) -> None: ...
def set_secondary_volume(channel, volume, delay) -> None: ...
def set_video(channel, video, loop: bool = False) -> None: ...
def set_volume(channel, volume) -> None: ...
def stop(channel) -> None: ...
def unpause(channel) -> None: ...
def video_ready(channel) -> None: ...

DROP_VIDEO: int
NODROP_VIDEO: int
NO_VIDEO: int
is_webaudio: int
