from _typeshed import Incomplete as Incomplete

video_only: bool

def call(function, *args) -> None: ...
def call_int(function, *args): ...
def call_str(function, *args): ...

audio_channels: Incomplete

def set_movie_channel(channel, movie) -> None: ...
def set_channel_count(count) -> None: ...

renpysound_funcs: Incomplete

def proxy_with_channel(func): ...
def proxy_call_both(func): ...
@proxy_with_channel
def play(
    channel,
    file,
    name,
    synchro_start: bool = False,
    fadein: int = 0,
    tight: bool = False,
    start: int = 0,
    end: int = 0,
    relative_volume: float = 1.0,
    audio_filter=None,
) -> None: ...
@proxy_with_channel
def queue(
    channel,
    file,
    name,
    synchro_start: bool = False,
    fadein: int = 0,
    tight: bool = False,
    start: int = 0,
    end: int = 0,
    relative_volume: float = 1.0,
    audio_filter=None,
) -> None: ...
@proxy_with_channel
def stop(channel) -> None: ...
@proxy_with_channel
def dequeue(channel, even_tight: bool = False) -> None: ...
@proxy_with_channel
def queue_depth(channel): ...
@proxy_with_channel
def playing_name(channel): ...
@proxy_with_channel
def pause(channel) -> None: ...
@proxy_with_channel
def unpause(channel) -> None: ...
def global_pause(pause) -> None: ...
@proxy_with_channel
def fadeout(channel, delay) -> None: ...
@proxy_with_channel
def busy(channel): ...
@proxy_with_channel
def get_pos(channel): ...
@proxy_with_channel
def get_duration(channel): ...
@proxy_with_channel
def set_volume(channel, volume) -> None: ...
@proxy_with_channel
def set_pan(channel, pan, delay) -> None: ...
@proxy_with_channel
def set_secondary_volume(channel, volume, delay) -> None: ...
@proxy_with_channel
def replace_audio_filter(channel, audio_filter, primary) -> None: ...
def audio_filter_constructor(f): ...

audio_filter_ids: Incomplete
audio_filter_serial: int
print_audio_filter: bool

def load_audio_filter(af): ...
def deallocate_audio_filter(audio_filter) -> None: ...
@proxy_with_channel
def get_volume(channel): ...
@proxy_with_channel
def video_ready(channel): ...

channel_size: Incomplete

@proxy_with_channel
def read_video(channel): ...

NO_VIDEO: int
NODROP_VIDEO: int
DROP_VIDEO: int

@proxy_with_channel
def set_video(channel, video, loop: bool = False) -> None: ...
def video_supported(): ...

loaded: bool

def load_script() -> None: ...
@proxy_call_both
def init(freq, stereo, samples, status: bool = False, equal_mono: bool = False, linear_fades: bool = False): ...
@proxy_call_both
def quit() -> None: ...
@proxy_call_both
def periodic() -> None: ...
@proxy_call_both
def advance_time() -> None: ...
@proxy_call_both
def sample_surfaces(rgb, rgba) -> None: ...
def can_play_types(types): ...
