from _typeshed import Incomplete as Incomplete

video_only: bool

def call(function: Incomplete, *args) -> None: ...
def call_int(function: Incomplete, *args) -> Incomplete: ...
def call_str(function: Incomplete, *args) -> Incomplete: ...

audio_channels: Incomplete

def set_movie_channel(channel: Incomplete, movie: Incomplete) -> None: ...
def set_channel_count(count: Incomplete) -> None: ...

renpysound_funcs: Incomplete

def proxy_with_channel(func: Incomplete) -> Incomplete: ...
def proxy_call_both(func: Incomplete) -> Incomplete: ...
@proxy_with_channel
def play(
    channel: Incomplete,
    file: Incomplete,
    name: Incomplete,
    synchro_start: bool = False,
    fadein: int = 0,
    tight: bool = False,
    start: int = 0,
    end: int = 0,
    relative_volume: float = 1.0,
    audio_filter: Incomplete = None,
) -> None: ...
@proxy_with_channel
def queue(
    channel: Incomplete,
    file: Incomplete,
    name: Incomplete,
    synchro_start: bool = False,
    fadein: int = 0,
    tight: bool = False,
    start: int = 0,
    end: int = 0,
    relative_volume: float = 1.0,
    audio_filter: Incomplete = None,
) -> None: ...
@proxy_with_channel
def stop(channel: Incomplete) -> None: ...
@proxy_with_channel
def dequeue(channel: Incomplete, even_tight: bool = False) -> None: ...
@proxy_with_channel
def queue_depth(channel: Incomplete) -> Incomplete: ...
@proxy_with_channel
def playing_name(channel: Incomplete) -> Incomplete: ...
@proxy_with_channel
def pause(channel: Incomplete) -> None: ...
@proxy_with_channel
def unpause(channel: Incomplete) -> None: ...
def global_pause(pause: Incomplete) -> None: ...
@proxy_with_channel
def fadeout(channel: Incomplete, delay: Incomplete) -> None: ...
@proxy_with_channel
def busy(channel: Incomplete) -> Incomplete: ...
@proxy_with_channel
def get_pos(channel: Incomplete) -> Incomplete: ...
@proxy_with_channel
def get_duration(channel: Incomplete) -> Incomplete: ...
@proxy_with_channel
def set_volume(channel: Incomplete, volume: Incomplete) -> None: ...
@proxy_with_channel
def set_pan(channel: Incomplete, pan: Incomplete, delay: Incomplete) -> None: ...
@proxy_with_channel
def set_secondary_volume(channel: Incomplete, volume: Incomplete, delay: Incomplete) -> None: ...
@proxy_with_channel
def replace_audio_filter(channel: Incomplete, audio_filter: Incomplete, primary: Incomplete) -> None: ...
def audio_filter_constructor(f: Incomplete) -> Incomplete: ...

audio_filter_ids: Incomplete
audio_filter_serial: int
print_audio_filter: bool

def load_audio_filter(af: Incomplete) -> Incomplete: ...
def deallocate_audio_filter(audio_filter: Incomplete) -> None: ...
@proxy_with_channel
def get_volume(channel: Incomplete) -> Incomplete: ...
@proxy_with_channel
def video_ready(channel: Incomplete) -> Incomplete: ...

channel_size: Incomplete

@proxy_with_channel
def read_video(channel: Incomplete) -> Incomplete: ...

NO_VIDEO: int
NODROP_VIDEO: int
DROP_VIDEO: int

@proxy_with_channel
def set_video(channel: Incomplete, video: Incomplete, loop: bool = False) -> None: ...
def video_supported() -> Incomplete: ...

loaded: bool

def load_script() -> None: ...
@proxy_call_both
def init(
    freq: Incomplete,
    stereo: Incomplete,
    samples: Incomplete,
    status: bool = False,
    equal_mono: bool = False,
    linear_fades: bool = False,
) -> Incomplete: ...
@proxy_call_both
def quit() -> None: ...
@proxy_call_both
def periodic() -> None: ...
@proxy_call_both
def advance_time() -> None: ...
@proxy_call_both
def sample_surfaces(rgb: Incomplete, rgba: Incomplete) -> None: ...
def can_play_types(types: Incomplete) -> Incomplete: ...
