import renpy
from _typeshed import Incomplete as Incomplete
from renpy.audio.filter import AudioFilter as AudioFilter
from renpy.pygame.surface import Surface as Surface
from typing import Any, Callable, Protocol

class SoundFunction(Protocol):
    __name__: str
    def __call__(self, channel: int, *args, **kwargs) -> Any: ...

video_only: bool

def call(function: str, *args) -> None: ...
def call_int(function: str, *args) -> int: ...
def call_str(function: str, *args) -> str: ...

audio_channels: set[int]

def set_movie_channel(channel: int, movie: bool) -> None: ...
def set_channel_count(count: int) -> None: ...

renpysound_funcs: dict[str, SoundFunction]

def proxy_with_channel[T: SoundFunction](func: T) -> T: ...
def proxy_call_both[T: Callable](func: T) -> T: ...
@proxy_with_channel
def play(
    channel: int,
    file: Incomplete,
    name: str,
    synchro_start: bool = False,
    fadein: float = 0,
    tight: bool = False,
    start: float = 0,
    end: float = 0,
    relative_volume: float = 1.0,
    audio_filter: AudioFilter | None = None,
) -> None: ...
@proxy_with_channel
def queue(
    channel: int,
    file: Incomplete,
    name: str,
    synchro_start: bool = False,
    fadein: float = 0,
    tight: bool = False,
    start: float = 0,
    end: float = 0,
    relative_volume: float = 1.0,
    audio_filter: AudioFilter | None = None,
) -> None: ...
@proxy_with_channel
def stop(channel: int) -> None: ...
@proxy_with_channel
def dequeue(channel: int, even_tight: bool = False) -> None: ...
@proxy_with_channel
def queue_depth(channel: int) -> int: ...
@proxy_with_channel
def playing_name(channel: int) -> str | None: ...
@proxy_with_channel
def pause(channel: int) -> None: ...
@proxy_with_channel
def unpause(channel: int) -> None: ...
def global_pause(pause: int) -> None: ...
@proxy_with_channel
def fadeout(channel: int, delay: float) -> None: ...
@proxy_with_channel
def busy(channel: int) -> bool: ...
@proxy_with_channel
def get_pos(channel: int) -> float | None: ...
@proxy_with_channel
def get_duration(channel: int) -> float | None: ...
@proxy_with_channel
def set_volume(channel: int, volume: float) -> None: ...
@proxy_with_channel
def set_pan(channel: int, pan: float, delay: float) -> None: ...
@proxy_with_channel
def set_secondary_volume(channel: int, volume: float, delay: float) -> None: ...
@proxy_with_channel
def replace_audio_filter(channel: int, audio_filter: AudioFilter, primary: bool) -> None: ...
def audio_filter_constructor(f: AudioFilter) -> str: ...

audio_filter_ids: dict[int, int]
audio_filter_serial: int
print_audio_filter: bool

def load_audio_filter(af: AudioFilter | None) -> int: ...
def deallocate_audio_filter(audio_filter: AudioFilter) -> None: ...
@proxy_with_channel
def get_volume(channel: int) -> float: ...
@proxy_with_channel
def video_ready(channel: int) -> int: ...

channel_size: dict[int, list[int]]

@proxy_with_channel
def read_video(channel: int) -> renpy.gl2.gl2texture.Texture | None: ...

NO_VIDEO: int
NODROP_VIDEO: int
DROP_VIDEO: int

@proxy_with_channel
def set_video(channel: int, video: int, loop: bool = False) -> None: ...
def video_supported() -> bool: ...

loaded: bool

def load_script() -> None: ...
@proxy_call_both
def init(
    freq: int, stereo: int, samples: int, status: bool = False, equal_mono: bool = False, linear_fades: bool = False
) -> None: ...
@proxy_call_both
def quit() -> None: ...
@proxy_call_both
def periodic() -> None: ...
@proxy_call_both
def advance_time() -> None: ...
@proxy_call_both
def sample_surfaces(rgb: Surface, rgba: Surface) -> None: ...
def can_play_types(types: list[str]) -> int: ...
