import renpy
import types
from _typeshed import Incomplete
from renpy.compat import (
    PY2 as PY2,
    basestring as basestring,
    bchr as bchr,
    bord as bord,
    chr as chr,
    open as open,
    pystr as pystr,
    range as range,
    round as round,
    str as str,
    tobytes as tobytes,
    unicode as unicode,
)
from renpy.display.render import Render as Render, render as render

compute_raw: Incomplete

def xyminimums(style, width, height): ...

class Null(renpy.display.displayable.Displayable):
    width: Incomplete
    height: Incomplete
    def __init__(self, width: int = 0, height: int = 0, **properties) -> None: ...
    def render(self, width, height, st, at): ...

class Container(renpy.display.displayable.Displayable):
    children: list
    child: renpy.display.displayable.Displayable | None
    offsets: list[tuple[int, int]]
    def __init__(self, *args, **properties) -> None: ...
    def set_transform_event(self, event) -> None: ...
    def set_style_prefix(self, prefix, root) -> None: ...
    def add(self, d) -> None: ...
    def remove(self, d) -> None: ...
    def update(self) -> None: ...
    def render(self, width, height, st, at): ...
    def event(self, ev, x, y, st): ...
    def visit(self): ...
    def __enter__(self): ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None
    ): ...

def Composite(size, *args, **properties): ...

LiveComposite = Composite

class Position(Container):
    def __init__(self, child, style: str = "image_placement", **properties) -> None: ...
    offsets: Incomplete
    def render(self, width, height, st, at): ...
    def get_placement(self): ...

class Grid(Container):
    allow_underfull: Incomplete
    gridmap: Incomplete
    cols: Incomplete
    rows: Incomplete
    transpose: Incomplete
    right_to_left: Incomplete
    bottom_to_top: Incomplete
    def __init__(
        self,
        cols,
        rows,
        padding=None,
        transpose: bool = False,
        style: str = "grid",
        allow_underfull=None,
        *,
        right_to_left: bool = False,
        bottom_to_top: bool = False,
        **properties,
    ) -> None: ...
    offsets: Incomplete
    def render(self, width, height, st, at): ...
    def add(self, d) -> None: ...
    def per_interact(self) -> None: ...
    def generate_gridmap(self): ...

class IgnoreLayers(Exception): ...

def default_modal_function(ev, x, y, w, h): ...
def check_modal(modal, ev, x, y, w, h): ...

class MultiBox(Container):
    layer_name: Incomplete
    first: bool
    order_reverse: bool
    layout: Incomplete
    layers: dict | None
    untransformed_layer: renpy.display.layout.MultiBox | None
    adjust_times: bool
    default_layout: Incomplete
    start_times: Incomplete
    anim_times: Incomplete
    scene_list: Incomplete
    def __init__(self, spacing=None, layout=None, style: str = "default", **properties) -> None: ...
    def add(self, widget, start_time=None, anim_time=None) -> None: ...
    def append_scene_list(self, l) -> None: ...
    def update_times(self) -> None: ...
    offsets: Incomplete
    def render(self, width, height, st, at): ...
    def event(self, ev, x, y, st): ...

def Fixed(**properties): ...

class SizeGroup(renpy.object.Object):
    members: Incomplete
    computing_width: bool
    def __init__(self) -> None: ...
    def width(self, width, height, st, at): ...

size_groups: Incomplete

class Window(Container):
    window_size: Incomplete
    current_child: Incomplete
    def __init__(self, child=None, style: str = "window", **properties) -> None: ...
    def visit(self): ...
    def get_child(self): ...
    def per_interact(self) -> None: ...
    offsets: Incomplete
    def render(self, width, height, st, at): ...
    def event(self, ev, x, y, st): ...

def dynamic_displayable_compat(st, at, expr): ...

class DynamicDisplayable(renpy.display.displayable.Displayable):
    nosave: Incomplete
    raw_child: Incomplete
    last_st: int
    last_at: int
    child: Incomplete
    def after_setstate(self) -> None: ...
    predict_function: Incomplete
    function: Incomplete
    args: Incomplete
    kwargs: Incomplete
    def __init__(self, function, *args, **kwargs) -> None: ...
    def visit(self): ...
    def update(self, st, at): ...
    def per_interact(self) -> None: ...
    def render(self, w, h, st, at): ...
    def predict_one(self) -> None: ...
    def get_placement(self): ...
    def event(self, ev, x, y, st): ...

cond_cache: Incomplete

def condition_switch_pick(switch): ...
def condition_switch_show(st, at, switch, predict_all=None): ...
def condition_switch_predict(switch, predict_all=None): ...
def ConditionSwitch(*args, **kwargs): ...
def ShowingSwitch(*args, **kwargs): ...

class IgnoresEvents(Container):
    def __init__(self, child, **properties) -> None: ...
    def render(self, w, h, st, at): ...
    def get_placement(self): ...
    def event(self, ev, x, y, st) -> None: ...

def Crop(rect, child, **properties): ...

LiveCrop = Crop

class Side(Container):
    possible_positions: Incomplete
    sized: bool
    def after_setstate(self) -> None: ...
    positions: Incomplete
    def __init__(self, positions, style: str = "side", **properties) -> None: ...
    def add(self, d) -> None: ...
    def per_interact(self) -> None: ...
    cwidth: Incomplete
    cheight: Incomplete
    top: Incomplete
    bottom: Incomplete
    left: Incomplete
    right: Incomplete
    offsets: Incomplete
    def render(self, width, height, st, at): ...

class Alpha(renpy.display.displayable.Displayable):
    start: Incomplete
    end: Incomplete
    time: Incomplete
    child: Incomplete
    repeat: Incomplete
    anim_timebase: Incomplete
    time_warp: Incomplete
    def __init__(
        self,
        start,
        end,
        time,
        child=None,
        repeat: bool = False,
        bounce: bool = False,
        anim_timebase: bool = False,
        time_warp=None,
        **properties,
    ) -> None: ...
    def visit(self): ...
    def render(self, height, width, st, at): ...

class AdjustTimes(Container):
    start_time: Incomplete
    anim_time: Incomplete
    def __init__(self, child, start_time, anim_time, **properties) -> None: ...
    def adjusted_times(self): ...
    offsets: Incomplete
    def render(self, w, h, st, at): ...
    def event(self, ev, x, y, st): ...
    def get_placement(self): ...

class MatchTimes(Container):
    target: Incomplete
    def __init__(self, child, target, **properties) -> None: ...
    offsets: Incomplete
    def render(self, w, h, st, at): ...
    def get_placement(self): ...

class Tile(Container):
    def __init__(self, child, style: str = "tile", **properties) -> None: ...
    def render(self, width, height, st, at): ...

LiveTile = Tile

class Flatten(Container):
    drawable_resolution: bool
    def __init__(self, child, drawable_resolution: bool = True, **properties) -> None: ...
    offsets: Incomplete
    def render(self, width, height, st, at): ...
    def get_placement(self): ...

class AlphaMask(Container):
    invert: bool
    mask: Incomplete
    def __init__(self, child, mask, invert: bool = False, **properties) -> None: ...
    def visit(self): ...
    offsets: Incomplete
    def render(self, width, height, st, at): ...

class NearRect(Container):
    preferred_side: str
    invert_offsets: bool
    possible_positions: Incomplete
    parent_rect: Incomplete
    focus_rect: Incomplete
    hide_parent_rect: Incomplete
    def __init__(
        self,
        child=None,
        rect=None,
        focus=None,
        preferred_side: bool = False,
        invert_offsets: bool = False,
        replaces=None,
        **properties,
    ) -> None: ...
    def per_interact(self) -> None: ...
    offsets: Incomplete
    def render(self, width, height, st, at): ...
    def event(self, ev, x, y, st): ...

class Layer(AdjustTimes):
    layers: Incomplete
    layer: Incomplete
    def __init__(self, layer, **properties) -> None: ...
    start_time: Incomplete
    anim_time: Incomplete
    def add(self, d, st=None, at=None) -> None: ...
    def visit_all(self, callback, seen=None) -> None: ...
    def per_interact(self) -> None: ...
