from _typeshed import Incomplete
from renpy.compat import (
    PY2 as PY2,
    basestring as basestring,
    bchr as bchr,
    bord as bord,
    chr as chr,
    open as open,
    pystr as pystr,
    range as range,
    round as round,
    str as str,
    tobytes as tobytes,
    unicode as unicode,
)
from renpy.display.render import (
    BLIT as BLIT,
    DISSOLVE as DISSOLVE,
    FLATTEN as FLATTEN,
    IDENTITY as IDENTITY,
    IMAGEDISSOLVE as IMAGEDISSOLVE,
    PIXELLATE as PIXELLATE,
    blit_lock as blit_lock,
)

class Clipper:
    blits: Incomplete
    old_blits: Incomplete
    forced: Incomplete
    old_forced: Incomplete
    mutated: Incomplete
    def __init__(self) -> None: ...
    def compute(self, full_redraw): ...

clippers: Incomplete

def surface(w, h, alpha): ...
def copy_surface(surf): ...
def draw_special(what, dest, x, y) -> None: ...
def draw(dest, clip, what, xo, yo, screen) -> None: ...
def draw_transformed(dest, clip, what, xo, yo, alpha, forward, reverse) -> None: ...
def do_draw_screen(screen_render, full_redraw, swdraw): ...

class SWDraw:
    display_info: Incomplete
    def __init__(self) -> None: ...
    suppressed_blit: bool
    next_frame: int
    info: Incomplete
    scale_factor: float
    screen: Incomplete
    window: Incomplete
    def reset(self) -> None: ...
    def get_texture_size(self): ...
    draw_per_virt: float
    virt_to_draw: Incomplete
    draw_to_virt: Incomplete
    full_redraw: bool
    fullscreen_surface: Incomplete
    def init(self, virtual_size): ...
    def update(self, force: bool = True) -> None: ...
    def resize(self) -> None: ...
    def quit(self) -> None: ...
    def translate_point(self, x, y): ...
    def untranslate_point(self, x, y): ...
    def mouse_event(self, ev): ...
    def get_mouse_pos(self): ...
    def set_mouse_pos(self, x, y): ...
    def screenshot(self, surftree): ...
    def can_block(self): ...
    def should_redraw(self, needs_redraw, first_pass, can_block): ...
    def draw_screen(self, surftree) -> None: ...
    def render_to_texture(self, render, alpha): ...
    def is_pixel_opaque(self, what): ...
    def mutated_surface(self, surf) -> None: ...
    def load_texture(self, surf, transient: bool = False, properties={}): ...
    def ready_one_texture(self): ...
    def solid_texture(self, w, h, color): ...
    def kill_textures(self) -> None: ...
    def event_peek_sleep(self) -> None: ...
    def get_physical_size(self): ...
