from _typeshed import Incomplete
from typing import Any

def notify(message: str) -> None: ...
def display_notify(message: str) -> None: ...
def confirm(message: str, **kwargs: Incomplete) -> Any: ...
