def get_clipboard_text() -> str: ...
def put_clipboard_text(text: str) -> None: ...
def get_clipboard_data(mime_type: str) -> bytes: ...
def get_clipboard_mime_types() -> list[str]: ...
def put_clipboard_data(data_dict: dict[str | bytes, str | bytes]) -> None: ...
def put_clipboard_image_file(filename: str, absolute_path: bool = False) -> None: ...
def put_clipboard_text_file(filename: str, absolute_path: bool = False) -> None: ...
