from collections.abc import Callable

def renpy_pure[T: str | Callable](fn: T) -> T: ...
def callback(f: str | Callable | None = None, name: str | None = None, *, late: bool = False) -> Callable: ...
