import renpy
from _typeshed import Incomplete as Incomplete
from renpy.exports.commonexports import renpy_pure as renpy_pure

def context(): ...
def context_nesting_level(): ...
def jump_out_of_context(label) -> None: ...
def current_interact_type(): ...
def last_interact_type(): ...
def dynamic(*variables, **kwargs) -> None: ...
def context_dynamic(*variables) -> None: ...

call_in_new_context = renpy.game.call_in_new_context
curried_call_in_new_context: Incomplete
invoke_in_new_context = renpy.game.invoke_in_new_context
curried_invoke_in_new_context: Incomplete
call_replay = renpy.game.call_replay

def scry(): ...
def pop_call() -> None: ...

pop_return = pop_call

def call_stack_depth(): ...
def game_menu(screen=None) -> None: ...
def mode(mode) -> None: ...
def get_mode(): ...
def end_replay() -> None: ...
def get_return_stack(): ...
def set_return_stack(stack) -> None: ...
def get_line_log(): ...
def clear_line_log() -> None: ...
def get_skipping(): ...
def is_skipping(): ...
def stop_skipping() -> None: ...
def is_init_phase(): ...
def add_to_all_stores(name, value) -> None: ...
def clear_game_runtime() -> None: ...
def get_game_runtime(): ...
def get_statement_name(): ...
def is_in_test(): ...
