import renpy
from _typeshed import Incomplete as Incomplete
from typing import Never, Any, Literal
from renpy.exports.commonexports import renpy_pure as renpy_pure

def context() -> renpy.revertable.RevertableObject: ...
def context_nesting_level() -> int: ...
def jump_out_of_context(label: str) -> Never: ...
def current_interact_type() -> str: ...
def last_interact_type() -> str: ...
def dynamic(*variables: str, **kwargs: Any) -> None: ...
def context_dynamic(*variables: str) -> None: ...

call_in_new_context = renpy.game.call_in_new_context
curried_call_in_new_context: Incomplete
invoke_in_new_context = renpy.game.invoke_in_new_context
curried_invoke_in_new_context: Incomplete
call_replay = renpy.game.call_replay

def scry() -> renpy.ast.Scry: ...
def pop_call() -> None: ...

pop_return = pop_call

def call_stack_depth() -> int: ...
def game_menu(screen: str | None = None) -> None: ...
def mode(mode: str) -> None: ...
def get_mode() -> str: ...
def end_replay() -> None: ...
def get_return_stack() -> Incomplete: ...
def set_return_stack(stack: Incomplete) -> None: ...
def get_line_log() -> Incomplete: ...
def clear_line_log() -> None: ...
def get_skipping() -> Literal["slow", "fast", None]: ...
def is_skipping() -> bool: ...
def stop_skipping() -> None: ...
def is_init_phase() -> bool: ...
def add_to_all_stores(name: Incomplete, value: Incomplete) -> None: ...
def clear_game_runtime() -> None: ...
def get_game_runtime() -> float: ...
def get_statement_name() -> str: ...
def is_in_test() -> bool: ...
