import contextlib
from _typeshed import Incomplete as Incomplete
from renpy.exports.commonexports import renpy_pure as renpy_pure

def warp_to_line(warp_spec: Incomplete) -> None: ...

filename_line_override_stack: list[tuple[str, int]]

@contextlib.contextmanager
def filename_line_override(filename: str, line: int) -> Incomplete: ...
def get_filename_line() -> Incomplete: ...

logfile: Incomplete

def log(msg: Incomplete) -> None: ...
def push_error_handler(eh: Incomplete) -> None: ...
def pop_error_handler() -> None: ...
def error(msg: Incomplete) -> None: ...
def write_log(s: Incomplete, *args: Incomplete) -> None: ...
