import renpy
from _typeshed import Incomplete as Incomplete
from collections.abc import Generator
from renpy.display.core import RendererInfo as RendererInfo
from renpy.display.displayable import Displayable as Displayable
from renpy.display.layout import Container as Container
from renpy.exports.commonexports import renpy_pure as renpy_pure
from renpy.revertable import RevertableObject as RevertableObject

scene_lists = renpy.display.scenelists.scene_lists

def count_displayables_in_layer(layer: Incomplete) -> Incomplete: ...
def image(name: Incomplete, d: Incomplete) -> None: ...
def copy_images(old: Incomplete, new: Incomplete) -> None: ...
def default_layer(layer: Incomplete, tag: Incomplete, expression: bool = False) -> Incomplete: ...
def can_show(name: Incomplete, layer: Incomplete = None, tag: Incomplete = None) -> Incomplete: ...
def showing(name: Incomplete, layer: Incomplete = None) -> Incomplete: ...
def get_showing_tags(layer: str = "master", sort: bool = False) -> Incomplete: ...
def get_hidden_tags(layer: str = "master") -> Incomplete: ...
def get_attributes(tag: Incomplete, layer: Incomplete = None, if_hidden: Incomplete = None) -> Incomplete: ...
def clear_attributes(tag: Incomplete, layer: Incomplete = None) -> None: ...
def predict_show(
    name: Incomplete,
    layer: Incomplete = None,
    what: Incomplete = None,
    tag: Incomplete = None,
    at_list: Incomplete = [],
) -> None: ...
def set_tag_attributes(name: Incomplete, layer: Incomplete = None) -> None: ...
def show(
    name: Incomplete,
    at_list: Incomplete = [],
    layer: Incomplete = None,
    what: Incomplete = None,
    zorder: Incomplete = None,
    tag: Incomplete = None,
    behind: Incomplete = [],
    atl: Incomplete = None,
    transient: bool = False,
    munge_name: bool = True,
) -> None: ...
def hide(name: Incomplete, layer: Incomplete = None) -> None: ...
def scene(layer: str | None = "master") -> None: ...
def toggle_fullscreen() -> None: ...
def take_screenshot(scale: Incomplete = None, background: bool = False, keep_existing: bool = False) -> None: ...
def screenshot(filename: Incomplete) -> Incomplete: ...
def screenshot_to_bytes(size: Incomplete) -> Incomplete: ...
def transition(trans: Incomplete, layer: Incomplete = None, always: bool = False, force: bool = False) -> None: ...
def get_transition(layer: Incomplete = None) -> Incomplete: ...
def get_ongoing_transition(layer: Incomplete = None) -> Incomplete: ...
def restart_interaction() -> None: ...
def force_full_redraw() -> None: ...
def image_size(im: Incomplete) -> Incomplete: ...
def get_at_list(name: Incomplete, layer: Incomplete = None) -> Incomplete: ...
def show_layer_at(at_list: Incomplete, layer: str = "master", reset: bool = True, camera: bool = False) -> None: ...

layer_at_list = show_layer_at

def free_memory() -> None: ...
def flush_cache_file(fn: Incomplete) -> None: ...
@renpy_pure
def easy_displayable(d: Incomplete, none: bool = False) -> Incomplete: ...
def quit_event() -> None: ...
def iconify() -> None: ...
def timeout(seconds: Incomplete) -> None: ...
def end_interaction(value: Incomplete) -> None: ...
def shown_window() -> None: ...

class placement(renpy.revertable.RevertableObject):
    xpos: Incomplete
    ypos: Incomplete
    xanchor: Incomplete
    yanchor: Incomplete
    xoffset: Incomplete
    yoffset: Incomplete
    subpixel: Incomplete
    def __init__(self, p: Incomplete) -> None: ...
    @property
    def pos(self) -> Incomplete: ...
    @property
    def anchor(self) -> Incomplete: ...
    @property
    def offset(self) -> Incomplete: ...

def get_placement(d: Incomplete) -> Incomplete: ...
def get_image_bounds(
    tag: Incomplete, width: Incomplete = None, height: Incomplete = None, layer: Incomplete = None
) -> Incomplete: ...

Render = renpy.display.render.Render
render = renpy.display.render.render
IgnoreEvent = renpy.display.core.IgnoreEvent
redraw = renpy.display.render.redraw

def is_pixel_opaque(
    d: Incomplete, width: Incomplete, height: Incomplete, st: Incomplete, at: Incomplete, x: Incomplete, y: Incomplete
) -> Incomplete: ...

class Displayable(renpy.display.displayable.Displayable, renpy.revertable.RevertableObject): ...
class Container(renpy.display.layout.Container, renpy.revertable.RevertableObject): ...

def get_renderer_info() -> renpy.display.core.RendererInfo: ...
def display_reset() -> None: ...
def get_physical_size() -> Incomplete: ...
def set_physical_size(size: Incomplete) -> None: ...
def reset_physical_size() -> None: ...
def get_image_load_log(age: Incomplete = None) -> Generator[Incomplete]: ...
def get_mouse_pos() -> Incomplete: ...
def set_mouse_pos(x: Incomplete, y: Incomplete, duration: int = 0) -> None: ...
def cancel_gesture() -> None: ...
def add_layer(
    layer: Incomplete,
    above: Incomplete = None,
    below: Incomplete = None,
    menu_clear: bool = True,
    sticky: Incomplete = None,
) -> None: ...
def maximum_framerate(t: Incomplete) -> None: ...
def is_start_interact() -> Incomplete: ...
def get_refresh_rate(precision: int = 5) -> Incomplete: ...
def get_adjustment(bar_value: Incomplete) -> Incomplete: ...
def get_texture_size() -> Incomplete: ...
def get_zorder_list(layer: Incomplete) -> Incomplete: ...
def change_zorder(layer: Incomplete, tag: Incomplete, zorder: Incomplete) -> None: ...
def is_mouse_visible() -> Incomplete: ...
def get_mouse_name(interaction: bool = False) -> Incomplete: ...
def get_mouse_names() -> Incomplete: ...
def set_focus(screen: Incomplete, id: Incomplete, layer: str = "screens") -> None: ...
def clear_retain(layer: str = "screens", prefix: str = "_retain") -> None: ...
def can_fullscreen() -> Incomplete: ...
def render_to_surface(
    d: Incomplete, width: Incomplete = None, height: Incomplete = None, st: float = 0.0, at=None, resize: bool = False
) -> Incomplete: ...
def render_to_file(
    d: Incomplete,
    filename: Incomplete,
    width: Incomplete = None,
    height: Incomplete = None,
    st: float = 0.0,
    at=None,
    resize: bool = False,
) -> None: ...
