import renpy
from _typeshed import Incomplete as Incomplete
from collections.abc import Generator
from renpy.display.core import RendererInfo as RendererInfo
from renpy.display.displayable import Displayable as _Displayable
from renpy.display.layout import Container as Container
from renpy.display.scenelists import AtList as AtList
from renpy.exports.commonexports import renpy_pure as renpy_pure
from renpy.revertable import RevertableObject as RevertableObject
from renpy.types import DisplayableLike as DisplayableLike
from typing import Any, Literal, NoReturn, overload, Mapping

scene_lists = renpy.display.scenelists.scene_lists

def count_displayables_in_layer(layer: str) -> int: ...
def image(name: str | tuple[str, ...], d: DisplayableLike) -> None: ...
def copy_images(old: str | tuple[str, ...], new: str | tuple[str, ...]) -> None: ...
def default_layer(layer: str | None, tag: str | tuple[str, ...] | None, expression: bool = False) -> str: ...
def can_show(
    name: str | tuple[str, ...], layer: str | None = None, tag: str | tuple[str, ...] | None = None
) -> tuple[str, ...] | None: ...
def showing(name: str | tuple[str, ...], layer: str | None = None) -> bool | None: ...
@overload
def get_showing_tags(layer: str = "master", sort: Literal[True] = ...) -> set[str]: ...
@overload
def get_showing_tags(layer: str = "master", sort: Literal[False] = False) -> list[str]: ...
def get_hidden_tags(layer: str = "master") -> set[str]: ...
def get_attributes(
    tag: str, layer: str | None = None, if_hidden: tuple[str, ...] | None = None
) -> tuple[str, ...] | None: ...
def clear_attributes(tag: str, layer: str | None = None) -> None: ...
def _find_image(
    layer: str | None, key: str, name: tuple[str, ...], what: str | tuple[str, ...] | None
) -> tuple[tuple[str, ...], tuple[str, ...]]: ...
def predict_show(
    name: tuple[str, ...],
    layer: str | None = None,
    what: str | tuple[str, ...] | _Displayable | None = None,
    tag: str | None = None,
    at_list: AtList | None = None,
) -> None: ...
def set_tag_attributes(name: str | tuple[str, ...], layer: str | None = None) -> None: ...
def show(
    name: str | tuple[str, ...],
    at_list: AtList = [],
    layer: str | None = None,
    what: str | tuple[str, ...] | _Displayable | None = None,
    zorder: int | None = None,
    tag: str | None = None,
    behind: list[str] = [],
    atl: renpy.display.transform.ATLTransform | renpy.ast.RawBlock | None = None,
    transient: bool = False,
    munge_name: bool = True,
) -> None: ...
def hide(name: str | tuple[str, ...], layer: str | None = None) -> None: ...
def scene(layer: str | None = "master") -> None: ...
def toggle_fullscreen() -> None: ...
def take_screenshot(
    scale: tuple[float, float] | None = None, background: bool = False, keep_existing: bool = False
) -> None: ...
def screenshot(filename: str) -> bool: ...
def screenshot_to_bytes(size: tuple[float, float]) -> bytes | None: ...
def transition(
    trans: renpy.display.transition.TransitionFunction
    | Mapping[str | None, renpy.display.transition.TransitionFunction | None]
    | None,
    layer: str | None = None,
    always: bool = False,
    force: bool = False,
) -> None: ...
def get_transition(layer: str | None = None) -> renpy.display.transition.TransitionFunction | None: ...
def get_ongoing_transition(layer: str | None = None) -> renpy.display.transition.TransitionFunction | None: ...
def restart_interaction() -> None: ...
def force_full_redraw() -> None: ...
def image_size(im: str) -> tuple[int, int]: ...
def get_at_list(name: str | tuple[str, ...], layer: str | None = None) -> list[AtList] | None: ...
def show_layer_at(at_list: AtList, layer: str = "master", reset: bool = True, camera: bool = False) -> None: ...

layer_at_list = show_layer_at

def free_memory() -> None: ...
def flush_cache_file(fn: str) -> None: ...
@overload
def easy_displayable(d: DisplayableLike, none: Literal[False] = ...) -> _Displayable: ...
@overload
def easy_displayable(d: DisplayableLike, none: Literal[True] = ...) -> _Displayable | None: ...
def quit_event() -> None: ...
def iconify() -> None: ...
def timeout(seconds: float) -> None: ...
@overload
def end_interaction(value: None) -> None: ...
@overload
def end_interaction(value: Any) -> NoReturn: ...
def shown_window() -> None: ...

class placement(renpy.revertable.RevertableObject):
    xpos: float | None
    ypos: float | None
    xanchor: float | None
    yanchor: float | None
    xoffset: float | None
    yoffset: float | None
    subpixel: bool
    def __init__(self, p: renpy.display.displayable.Placement) -> None: ...
    @property
    def pos(self) -> tuple[float | None, float | None]: ...
    @property
    def anchor(self) -> tuple[float | None, float | None]: ...
    @property
    def offset(self) -> tuple[float | None, float | None]: ...

def get_placement(d: Displayable) -> placement: ...
def get_image_bounds(
    tag: str, width: float | None = None, height: float | None = None, layer: str | None = None
) -> tuple[float, float, float, float] | None: ...

Render = renpy.display.render.Render
render = renpy.display.render.render
IgnoreEvent = renpy.display.core.IgnoreEvent
redraw = renpy.display.render.redraw

def is_pixel_opaque(
    d: DisplayableLike, width: float, height: float, st: float, at: float, x: float, y: float
) -> bool: ...

class Displayable(renpy.display.displayable.Displayable, renpy.revertable.RevertableObject): ...

class Container(renpy.display.layout.Container, renpy.revertable.RevertableObject):
    _list_type = renpy.revertable.RevertableList

def get_renderer_info() -> renpy.display.core.RendererInfo: ...
def display_reset() -> None: ...
def get_physical_size() -> tuple[int, int]: ...
def set_physical_size(size: tuple[float, float]) -> None: ...
def reset_physical_size() -> None: ...
def get_image_load_log(age: float | None = None) -> Generator[tuple[float, str, bool], None, None]: ...
def get_mouse_pos() -> tuple[int, int]: ...
def set_mouse_pos(x: float, y: float, duration: float | None = 0) -> None: ...
def cancel_gesture() -> None: ...
def add_layer(
    layer: str, above: str | None = None, below: str | None = None, menu_clear: bool = True, sticky: bool | None = None
) -> None: ...
def maximum_framerate(t: float | None) -> None: ...
def is_start_interact() -> bool: ...
def get_refresh_rate(precision: int = 5) -> float: ...
def get_adjustment(bar_value: Incomplete) -> Incomplete: ...
def get_texture_size() -> tuple[int, int]: ...
def get_zorder_list(layer: str) -> list[tuple[str, int]]: ...
def change_zorder(layer: str, tag: str, zorder: int) -> None: ...
def is_mouse_visible() -> bool: ...
def get_mouse_name(interaction: bool = False) -> str: ...
def get_mouse_names() -> list[str]: ...
def set_focus(
    screen: str | tuple[str, ...] | renpy.display.screen.ScreenDisplayable | None,
    id: str,
    layer: str | None = "screens",
) -> None: ...
def clear_retain(layer: str = "screens", prefix: str = "_retain") -> None: ...
def can_fullscreen() -> bool: ...
def render_to_surface(
    d: DisplayableLike | Render,
    width: float | None = None,
    height: float | None = None,
    st: float = 0.0,
    at: float | None = None,
    resize: bool = False,
) -> renpy.pygame.surface.Surface: ...
def render_to_file(
    d: DisplayableLike | Render,
    filename: str,
    width: float | None = None,
    height: float | None = None,
    st: float = 0.0,
    at: float | None = None,
    resize: bool = False,
) -> None: ...
