import io
from renpy.exports.commonexports import renpy_pure as renpy_pure
from typing import IO, Literal, overload

@renpy_pure
def loadable(filename: str, directory: str | None = None, tl: bool = True) -> bool: ...
@renpy_pure
def exists(filename: str) -> bool: ...
def open_file(fn: str, encoding: str | None = None, directory: str | None = None) -> io.BufferedReader: ...
def file(fn: str, encoding: str | None = None) -> io.BufferedReader: ...
def notl_file(fn: str) -> IO: ...
@renpy_pure
def list_files(common: bool = False) -> list[str]: ...
@overload
def fsencode[T](s: T, force: Literal[True] = ...) -> T: ...
@overload
def fsencode(s: bytes, force: Literal[False] = ...) -> bytes: ...
@overload
def fsencode(s: str, force: Literal[False] = ...) -> str: ...
@renpy_pure
def fsdecode(s: bytes | str) -> str: ...
def munge(name: str, filename: str | None = None) -> str: ...
