from renpy.exports.commonexports import renpy_pure as renpy_pure

@renpy_pure
def loadable(filename, directory=None, tl: bool = True): ...
@renpy_pure
def exists(filename): ...
def open_file(fn, encoding=None, directory=None): ...
def file(fn, encoding=None): ...
def notl_file(fn): ...
@renpy_pure
def list_files(common: bool = False): ...
@renpy_pure
def fsencode(s: str, force: bool = False) -> str: ...
@renpy_pure
def fsdecode(s: bytes | str) -> str: ...
def munge(name, filename=None): ...
