from renpy.exports.commonexports import renpy_pure as renpy_pure
from _typeshed import Incomplete as Incomplete

@renpy_pure
def loadable(filename: Incomplete, directory: Incomplete = None, tl: bool = True) -> Incomplete: ...
@renpy_pure
def exists(filename: Incomplete) -> Incomplete: ...
def open_file(fn: Incomplete, encoding: Incomplete = None, directory: Incomplete = None) -> Incomplete: ...
def file(fn: Incomplete, encoding: Incomplete = None) -> Incomplete: ...
def notl_file(fn: Incomplete) -> Incomplete: ...
@renpy_pure
def list_files(common: bool = False) -> list[str]: ...
@renpy_pure
def fsencode(s: str, force: bool = False) -> str: ...
@renpy_pure
def fsdecode(s: bytes | str) -> str: ...
def munge(name: Incomplete, filename: Incomplete = None) -> Incomplete: ...
