from renpy.exports.commonexports import renpy_pure as renpy_pure
from _typeshed import Incomplete as Incomplete

def movie_cutscene(
    filename: Incomplete, delay: Incomplete = None, loops: int = 0, stop_music: bool = True
) -> Incomplete: ...
def toggle_music() -> None: ...
def music_start(filename: Incomplete, loops: bool = True, fadeout: Incomplete = None, fadein: int = 0) -> None: ...
def music_stop(fadeout: Incomplete = None) -> None: ...
def play(filename: Incomplete, channel: Incomplete = None, **kwargs) -> None: ...
