from renpy.exports.commonexports import renpy_pure as renpy_pure

def movie_cutscene(filename: str, delay: float | None = None, loops: int = 0, stop_music: bool = True) -> bool: ...
def toggle_music() -> None: ...
def music_start(
    filename: str | list[str] | None, loops: bool = True, fadeout: float | None = None, fadein: float = 0
) -> None: ...
def music_stop(fadeout: float | None = None) -> None: ...
def play(filename: str | list[str] | None, channel: str | None = None, **kwargs) -> None: ...
