from renpy.exports.commonexports import renpy_pure as renpy_pure

def movie_cutscene(filename, delay=None, loops: int = 0, stop_music: bool = True): ...
def toggle_music() -> None: ...
def music_start(filename, loops: bool = True, fadeout=None, fadein: int = 0) -> None: ...
def music_stop(fadeout=None) -> None: ...
def play(filename, channel=None, **kwargs) -> None: ...
