from renpy.ast import NodeName

def seen_label(label: NodeName) -> bool: ...
def mark_label_seen(label: NodeName) -> None: ...
def mark_label_unseen(label: NodeName) -> None: ...
def seen_audio(filename: str) -> bool: ...
def mark_audio_seen(filename: str) -> None: ...
def mark_audio_unseen(filename: str) -> None: ...
def seen_image(name: str | tuple[str, ...]) -> bool: ...
def mark_image_seen(name: str | tuple[str, ...]) -> None: ...
def mark_image_unseen(name: str | tuple[str, ...]) -> None: ...
def seen_translation(tlid: str) -> bool: ...
def mark_translation_seen(tlid: str) -> None: ...
def mark_translation_unseen(tlid: str) -> None: ...
def save_persistent() -> None: ...
def is_seen(ever: bool = True) -> bool: ...
def is_seen_allowed() -> bool: ...
