from _typeshed import Incomplete as Incomplete

def seen_label(label: Incomplete) -> Incomplete: ...
def mark_label_seen(label: Incomplete) -> None: ...
def mark_label_unseen(label: Incomplete) -> None: ...
def seen_audio(filename: Incomplete) -> Incomplete: ...
def mark_audio_seen(filename: Incomplete) -> None: ...
def mark_audio_unseen(filename: Incomplete) -> None: ...
def seen_image(name: Incomplete) -> Incomplete: ...
def mark_image_seen(name: Incomplete) -> None: ...
def mark_image_unseen(name: Incomplete) -> None: ...
def seen_translation(tlid: Incomplete) -> bool: ...
def mark_translation_seen(tlid: Incomplete) -> None: ...
def mark_translation_unseen(tlid: str) -> None: ...
def save_persistent() -> None: ...
def is_seen(ever: bool = True) -> Incomplete: ...
def is_seen_allowed() -> Incomplete: ...
