def seen_label(label): ...
def mark_label_seen(label) -> None: ...
def mark_label_unseen(label) -> None: ...
def seen_audio(filename): ...
def mark_audio_seen(filename) -> None: ...
def mark_audio_unseen(filename) -> None: ...
def seen_image(name): ...
def mark_image_seen(name) -> None: ...
def mark_image_unseen(name) -> None: ...
def seen_translation(tlid: str) -> bool: ...
def mark_translation_seen(tlid: str) -> None: ...
def mark_translation_unseen(tlid: str) -> None: ...
def save_persistent() -> None: ...
def is_seen(ever: bool = True): ...
def is_seen_allowed(): ...
