from collections.abc import Callable, Iterable
from typing import Any, Literal

from renpy.exports.commonexports import renpy_pure as renpy_pure

try:
    import ctypes
except ImportError:
    pass

@renpy_pure
def variant(name: str | Iterable[str | None]) -> bool: ...
def vibrate(duration: float) -> None: ...
def invoke_in_thread(fn: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...
def invoke_in_main_thread(fn: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...

old_battery: bool

def get_on_battery() -> bool: ...

sdl_dll: ctypes.CDLL | Literal[False] | None

def get_sdl_dll() -> ctypes.CDLL | None: ...
def get_sdl_window_pointer() -> ctypes.c_void_p | None: ...
def check_permission(permission: str) -> bool: ...
def request_permission(permission: str) -> bool: ...
def open_url(url: str) -> None: ...
def get_user_age() -> tuple[int, int]: ...
