from renpy.exports.commonexports import renpy_pure as renpy_pure

@renpy_pure
def variant(name): ...
def vibrate(duration) -> None: ...
def invoke_in_thread(fn, *args, **kwargs) -> None: ...
def invoke_in_main_thread(fn, *args, **kwargs) -> None: ...

old_battery: bool

def get_on_battery(): ...

sdl_dll: bool

def get_sdl_dll(): ...
def get_sdl_window_pointer(): ...
def check_permission(permission): ...
def request_permission(permission): ...
def open_url(url) -> None: ...
