from _typeshed import Incomplete
from typing import overload

def cache_pin(*args: Incomplete) -> None: ...
def cache_unpin(*args: Incomplete) -> None: ...
@overload
def expand_predict(d: str) -> list[str]: ...
@overload
def expand_predict[T](d: T) -> list[T]: ...
def start_predict(*args) -> None: ...
def stop_predict(*args) -> None: ...
def start_predict_screen(_screen_name: str, *args: Incomplete, **kwargs: Incomplete) -> None: ...
def stop_predict_screen(name: str) -> None: ...
def predicting() -> bool: ...
