def cache_pin(*args) -> None: ...
def cache_unpin(*args) -> None: ...
def expand_predict(d): ...
def start_predict(*args) -> None: ...
def stop_predict(*args) -> None: ...
def start_predict_screen(_screen_name, *args, **kwargs) -> None: ...
def stop_predict_screen(name) -> None: ...
def predicting(): ...
