from renpy.exports.commonexports import renpy_pure as renpy_pure
from _typeshed import Incomplete

def full_restart(
    transition: bool = False, label: str = "_invoke_main_menu", target: str = "_main_menu", save: bool = False
) -> None: ...
def utter_restart(keep_renderer: bool = False) -> None: ...
def reload_script() -> None: ...
def quit(relaunch: bool = False, status: int = 0, save: bool = False) -> None: ...
def set_autoreload(autoreload: Incomplete) -> None: ...
def get_autoreload() -> Incomplete: ...
