from _typeshed import Incomplete

def roll_forward_info() -> Incomplete: ...
def roll_forward_core(value: Incomplete = None) -> Incomplete: ...
def in_rollback() -> Incomplete: ...
def can_rollback() -> Incomplete: ...
def in_fixed_rollback() -> Incomplete: ...
def checkpoint(data: Incomplete = None, keep_rollback: Incomplete = None, hard: bool = True) -> None: ...
def block_rollback(purge: bool = False) -> None: ...
def suspend_rollback(flag: Incomplete) -> None: ...
def fix_rollback() -> None: ...
def retain_after_load() -> None: ...
def rollback(
    force: bool = False,
    checkpoints: int = 1,
    defer: bool = False,
    greedy: bool = True,
    label: Incomplete = None,
    abnormal: bool = True,
    current_label: Incomplete = None,
) -> None: ...
def get_roll_forward() -> Incomplete: ...
def get_identifier_checkpoints(identifier: Incomplete) -> Incomplete: ...
