import renpy
from typing import Any

def roll_forward_info() -> Any | None: ...
def roll_forward_core[T](value: T | None = None) -> T | None: ...
def in_rollback() -> bool: ...
def can_rollback() -> bool: ...
def in_fixed_rollback() -> bool: ...
def checkpoint(data: Any | None = None, keep_rollback: bool | None = None, hard: bool = True) -> None: ...
def block_rollback(purge: bool = False) -> None: ...
def suspend_rollback(flag: bool) -> None: ...
def fix_rollback() -> None: ...
def retain_after_load() -> None: ...
def rollback(
    force: bool = False,
    checkpoints: int = 1,
    defer: bool = False,
    greedy: bool = True,
    label: str | None = None,
    abnormal: bool = True,
    current_label: str | None = None,
) -> None: ...
def get_roll_forward() -> bool: ...
def get_identifier_checkpoints(identifier: renpy.rollback.RollbackIdentifier) -> int | None: ...
