def roll_forward_info(): ...
def roll_forward_core(value=None): ...
def in_rollback(): ...
def can_rollback(): ...
def in_fixed_rollback(): ...
def checkpoint(data=None, keep_rollback=None, hard: bool = True) -> None: ...
def block_rollback(purge: bool = False) -> None: ...
def suspend_rollback(flag) -> None: ...
def fix_rollback() -> None: ...
def retain_after_load() -> None: ...
def rollback(
    force: bool = False,
    checkpoints: int = 1,
    defer: bool = False,
    greedy: bool = True,
    label=None,
    abnormal: bool = True,
    current_label=None,
) -> None: ...
def get_roll_forward(): ...
def get_identifier_checkpoints(identifier): ...
