from _typeshed import Incomplete as Incomplete
from renpy.exports.commonexports import renpy_pure as renpy_pure

class TagQuotingDict:
    def __getitem__(self, key): ...

tag_quoting_dict: Incomplete

def predict_say(who, what): ...
def scry_say(who, what, scry) -> None: ...
def say(who, what, *args, **kwargs) -> None: ...
def do_reshow_say(who, what, interact: bool = False, *args, **kwargs) -> None: ...

curried_do_reshow_say: Incomplete

def get_reshow_say(**kwargs): ...
def reshow_say(**kwargs) -> None: ...
def get_say_attributes(): ...
def get_side_image(prefix_tag, image_tag=None, not_showing=None, layer=None): ...
def count_dialogue_blocks(): ...
def count_seen_dialogue_blocks(): ...
def count_newly_seen_dialogue_blocks(): ...
def substitute(s, scope=None, translate: bool = True): ...
def get_say_image_tag(): ...

class LastSay:
    what: Incomplete
    args: Incomplete
    kwargs: Incomplete
    def __init__(self, who, what, args, kwargs) -> None: ...
    @property
    def who(self): ...

def last_say(): ...
