from _typeshed import Incomplete as Incomplete
from renpy.exports.commonexports import renpy_pure as renpy_pure

class TagQuotingDict:
    def __getitem__(self, key: Incomplete) -> Incomplete: ...

tag_quoting_dict: Incomplete

def predict_say(who: Incomplete, what: Incomplete) -> Incomplete: ...
def scry_say(who: Incomplete, what: Incomplete, scry: Incomplete) -> None: ...
def say(who: Incomplete, what: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> None: ...
def do_reshow_say(
    who: Incomplete, what: Incomplete, interact: bool = False, *args: Incomplete, **kwargs: Incomplete
) -> None: ...

curried_do_reshow_say: Incomplete

def get_reshow_say(**kwargs) -> Incomplete: ...
def reshow_say(**kwargs) -> None: ...
def get_say_attributes() -> Incomplete: ...
def get_side_image(
    prefix_tag: Incomplete, image_tag: Incomplete = None, not_showing: Incomplete = None, layer: Incomplete = None
) -> Incomplete: ...
def count_dialogue_blocks() -> Incomplete: ...
def count_seen_dialogue_blocks() -> Incomplete: ...
def count_newly_seen_dialogue_blocks() -> Incomplete: ...
def substitute(s: Incomplete, scope: Incomplete = None, translate: bool = True) -> Incomplete: ...
def get_say_image_tag() -> Incomplete: ...

class LastSay:
    what: Incomplete
    args: Incomplete
    kwargs: Incomplete
    def __init__(self, who: Incomplete, what: Incomplete, args: Incomplete, kwargs: Incomplete) -> None: ...
    @property
    def who(self) -> Incomplete: ...

def last_say() -> Incomplete: ...
