import renpy
from _typeshed import Incomplete as Incomplete
from renpy.curry import Partial as Partial
from renpy.exports.commonexports import renpy_pure as renpy_pure
from typing import Any

class TagQuotingDict:
    def __getitem__(self, key: str) -> str: ...

tag_quoting_dict: TagQuotingDict

def predict_say(who: Incomplete | str | None, what: str) -> Incomplete: ...
def scry_say(who: Incomplete, what: str, scry: renpy.ast.Scry) -> None: ...
def say(who: Incomplete | str | None, what: str, *args, **kwargs) -> None: ...
def do_reshow_say(who: str | None, what: str, interact: bool = False, *args, **kwargs) -> None: ...

curried_do_reshow_say: Partial[Partial[None]]

def get_reshow_say(**kwargs) -> Partial[None]: ...
def reshow_say(**kwargs) -> None: ...
def get_say_attributes() -> tuple[str, ...] | None: ...
def get_side_image(
    prefix_tag: str, image_tag: str | None = None, not_showing: bool | None = None, layer: str | None = None
) -> tuple[str, ...] | None: ...
def count_dialogue_blocks() -> int: ...
def count_seen_dialogue_blocks() -> int: ...
def count_newly_seen_dialogue_blocks() -> int: ...
def substitute(s: str, scope: dict[str, Any] | None = None, translate: bool = True) -> str: ...
def get_say_image_tag() -> str | None: ...

class LastSay:
    _who: Incomplete | str | None
    what: str | None
    args: tuple[Any]
    kwargs: dict[str, Any]
    def __init__(
        self, who: Incomplete | str | None, what: str | None, args: tuple[Any], kwargs: dict[str, Any]
    ) -> None: ...
    @property
    def who(self) -> Incomplete: ...

def last_say() -> LastSay: ...
