from _typeshed import Incomplete as Incomplete
from renpy.exports.commonexports import renpy_pure as renpy_pure

@renpy_pure
def has_label(name: Incomplete) -> Incomplete: ...
@renpy_pure
def get_all_labels() -> Incomplete: ...
@renpy_pure
def munged_filename() -> Incomplete: ...

loaded_modules: Incomplete

def load_module(name: Incomplete, **kwargs) -> None: ...
def load_string(s: Incomplete, filename: str = "<string>") -> None: ...
def load_language(language: Incomplete) -> None: ...
def include_module(name: Incomplete) -> None: ...
