import renpy
from renpy.exports.commonexports import renpy_pure as renpy_pure

@renpy_pure
def has_label(name: renpy.ast.NodeName) -> bool: ...
@renpy_pure
def get_all_labels() -> renpy.revertable.RevertableSet[str]: ...
@renpy_pure
def munged_filename() -> str: ...

loaded_modules: set[str]

def load_module(name: str, **kwargs) -> None: ...
def load_string(s: str, filename: str = "<string>") -> renpy.ast.NodeName | None: ...
def load_language(language: str | None) -> None: ...
def include_module(name: str) -> None: ...
