from _typeshed import Incomplete
from renpy.exports.commonexports import renpy_pure as renpy_pure

@renpy_pure
def has_label(name): ...
@renpy_pure
def get_all_labels(): ...
@renpy_pure
def munged_filename(): ...

loaded_modules: Incomplete

def load_module(name, **kwargs) -> None: ...
def load_string(s, filename: str = "<string>"): ...
def load_language(language) -> None: ...
def include_module(name) -> None: ...
