from renpy.exports.commonexports import renpy_pure as renpy_pure
from typing import Never

def imagemap(
    ground,
    selected,
    hotspots,
    unselected=None,
    overlays: bool = False,
    style: str = "imagemap",
    mouse: str = "imagemap",
    with_none=None,
    **properties,
): ...
def pause(
    delay=None, music=None, with_none=None, hard: bool = False, predict: bool = False, checkpoint=None, modal=None
): ...
def with_statement(trans, always: bool = False, paired=None, clear: bool = True): ...
def jump(label) -> Never: ...
def call(label, *args, **kwargs) -> None: ...
def return_statement(value=None) -> None: ...
def call_screen(_screen_name, *args, **kwargs): ...
def execute_default_statement(start: bool = False) -> None: ...
