from _typeshed import Incomplete
from typing import Callable, Sequence, Any

from renpy.color import ColorLike
from renpy.display.imagelike import Frame
from renpy.display.transform import Transform
from renpy.types import DisplayableLike

class _Theme:
    def __call__(self, func: Callable) -> Callable: ...

_theme: _Theme
theme: _Theme

def RoundRect(color: Incomplete, small: bool = False) -> Incomplete: ...
def _m1_00themes__AWTBox(colour: ColorLike) -> Frame: ...
def _m1_00themes__AWTButton(image: str, colour: ColorLike, highlight: bool, low_sat: bool = False) -> Frame: ...
def _m1_00themes__AWTBullet(image: DisplayableLike) -> Transform: ...
def _display_button_menu(menuitems: Sequence[tuple[str, Any]]) -> Any: ...
def _button_menu() -> None: ...
