from typing import Sequence

from renpy.ui import Action
from renpy.store import FieldEquality

_m1_00action_data__Sentinel: object

def _get_field[VT](obj: object, name: str, kind: str) -> VT: ...
def _set_field[VT](obj: object, name: str, value: VT, kind: str) -> None: ...

class AddToSet[VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    set: set[VT]
    value: VT
    def __init__(self, set: set[VT], value: VT) -> None: ...
    def get_sensitive(self) -> bool: ...
    def __call__(self) -> None: ...

class RemoveFromSet[VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    set: set[VT]
    value: VT
    def __init__(self, set: set[VT], value: VT) -> None: ...
    def get_sensitive(self) -> bool: ...
    def __call__(self) -> None: ...

class ToggleSetMembership[VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    set: set[VT]
    value: VT
    def __init__(self, set: set[VT], value: VT) -> None: ...
    def get_selected(self) -> bool: ...
    def __call__(self) -> None: ...

#############################

class CycleDict[KT, VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str

    dict: dict[KT, VT]
    key: KT
    values: tuple[VT, ...]
    loop: bool
    def __init__(
        self, dict: dict[KT, VT], key: KT, values: Sequence[VT], *, reverse: bool = False, loop: bool = True
    ) -> None: ...
    def __call__(self) -> None: ...
    def current_value(self) -> VT: ...
    def value_to_set(self) -> VT: ...
    def get_sensitive(self) -> bool: ...

class CycleField[VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str

    object: object
    field: str
    values: tuple[VT, ...]
    loop: bool
    def __init__(
        self, object: object, field: str, values: Sequence[VT], *, reverse: bool = False, loop: bool = True
    ) -> None: ...
    def __call__(self) -> None: ...
    def current_value(self) -> VT: ...
    def value_to_set(self) -> VT: ...
    def get_sensitive(self) -> bool: ...

class CycleLocalVariable[VT](CycleDict[str, VT]):
    def __init__(self, name: str, values: Sequence[VT], *, reverse: bool = False, loop: bool = True) -> None: ...

class CycleScreenVariable[VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str

    name: str
    values: tuple[VT, ...]
    loop: bool
    def __init__(self, name: str, values: Sequence[VT], *, reverse: bool = False, loop: bool = True) -> None: ...
    def __call__(self) -> None: ...
    def current_value(self) -> VT: ...
    def value_to_set(self) -> VT: ...
    def get_sensitive(self) -> bool: ...

class CycleVariable[VT](CycleField[VT]):
    def __init__(self, name: str, values: Sequence[VT], *, reverse: bool = False, loop: bool = True) -> None: ...

class IncrementDict[KT, VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str

    dict: dict[KT, VT]
    key: KT
    amount: VT
    def __init__(self, dict: dict[KT, VT], key: KT, amount: VT = 1) -> None: ...
    def __call__(self) -> None: ...
    def current_value(self) -> VT: ...
    def value_to_set(self) -> VT: ...
    def get_sensitive(self) -> bool: ...

class IncrementField[VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str

    object: object
    field: str
    amount: VT
    def __init__(self, object: object, field: str, amount: VT = 1) -> None: ...
    def __call__(self) -> None: ...
    def current_value(self) -> VT: ...
    def value_to_set(self) -> VT: ...
    def get_sensitive(self) -> bool: ...

class IncrementLocalVariable[VT](IncrementDict[str, VT]):
    def __init__(self, name: str, amount: VT = 1) -> None: ...

class IncrementScreenVariable[VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str

    name: str
    amount: VT
    def __init__(self, name: str, amount: VT = 1) -> None: ...
    def __call__(self) -> None: ...
    def current_value(self) -> VT: ...
    def value_to_set(self) -> VT: ...
    def get_sensitive(self) -> bool: ...

class IncrementVariable[VT](IncrementField):
    def __init__(self, name: str, amount: VT = 1) -> None: ...

class SetDict[KT, VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str

    dict: dict[KT, VT]
    key: KT
    value: VT
    def __init__(self, dict: dict[KT, VT], key: KT, value: VT) -> None: ...
    def __call__(self) -> None: ...
    def current_value(self) -> VT: ...
    def value_to_set(self) -> VT: ...
    def get_sensitive(self) -> bool: ...

class SetField[VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str

    object: object
    field: str
    value: VT
    def __init__(self, object: object, field: str, value: VT) -> None: ...
    def __call__(self) -> None: ...
    def current_value(self) -> VT: ...
    def value_to_set(self) -> VT: ...
    def get_sensitive(self) -> bool: ...

class SetLocalVariable[VT](SetDict[str, VT]):
    def __init__(self, name: str, value: VT) -> None: ...

class SetScreenVariable[VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str

    name: str
    value: VT
    def __init__(self, name: str, value: VT) -> None: ...
    def __call__(self) -> None: ...
    def current_value(self) -> VT: ...
    def value_to_set(self) -> VT: ...
    def get_sensitive(self) -> bool: ...

class SetVariable[VT](SetField[VT]):
    def __init__(self, name: str, value: VT) -> None: ...

class ToggleDict[KT, VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str

    dict: dict[KT, VT]
    key: KT
    true_value: VT
    false_value: VT
    def __init__(self, dict: dict[KT, VT], key: KT, true_value: VT = None, false_value: VT = None) -> None: ...
    def __call__(self) -> None: ...
    def current_value(self) -> VT: ...
    def value_to_set(self) -> VT: ...
    def get_sensitive(self) -> bool: ...

class ToggleField[VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str

    object: object
    field: str
    true_value: VT
    false_value: VT
    def __init__(self, object: object, field: str, true_value: VT = None, false_value: VT = None) -> None: ...
    def __call__(self) -> None: ...
    def current_value(self) -> VT: ...
    def value_to_set(self) -> VT: ...
    def get_sensitive(self) -> bool: ...

class ToggleLocalVariable[VT](SetDict[str, VT]):
    def __init__(self, name: str, true_value: VT = None, false_value: VT = None) -> None: ...

class ToggleScreenVariable[VT](Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str

    name: str
    true_value: VT
    false_value: VT
    def __init__(self, name: str, true_value: VT = None, false_value: VT = None) -> None: ...
    def __call__(self) -> None: ...
    def current_value(self) -> VT: ...
    def value_to_set(self) -> VT: ...
    def get_sensitive(self) -> bool: ...

class ToggleVariable[VT](SetField[VT]):
    def __init__(self, name: str, true_value: VT = None, false_value: VT = None) -> None: ...
