from typing import Any

from renpy.types import DisplayableLike
from renpy.style import StyleCore

def _vol(n: float) -> float: ...
def _apply_default_preferences() -> None: ...
def _locale_to_language_function(locale: str, region: str) -> str: ...
def _imagemap_auto_function(auto_param: str, variant: str) -> DisplayableLike: ...
def hyperlink_styler(target: str) -> StyleCore: ...
def hyperlink_function(target: str) -> Any | None: ...
def hyperlink_sensitive(target: str) -> bool: ...

_version: str
