from _typeshed import Incomplete
from typing import Any, Sequence

import renpy
from renpy.display.behavior import ActionType

class DictEquality:
    def __eq__(self, o: object) -> bool: ...
    def __ne__(self, o: object) -> bool: ...
    def __hash__(self) -> int: ...

class FieldEquality:
    equality_fields: Sequence[str]
    identity_fields: Sequence[str]
    def __eq__(self, o: object) -> bool: ...
    def __ne__(self, o: object) -> bool: ...
    def __hash__(self) -> int: ...

save_name: str
preferences: renpy.preferences.Preference
_preferences: renpy.preferences.Preference

def _default_empty_window() -> None: ...

class _Extend:
    def get_who(self: Incomplete) -> Incomplete: ...
    def __call__(self, what: Incomplete, interact: bool = True, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    record_say: bool
    def get_extend_text(self, what: str) -> str: ...
    @property
    def statement_name(self: Incomplete) -> Incomplete: ...

extend: _Extend

def _skip_indicator() -> None: ...
def _predict_statements(current: renpy.ast.NodeName) -> list[renpy.ast.NodeName]: ...
def _predict_screens() -> None: ...

name_only: renpy.character.ADVCharacter

def predict_say(who: Incomplete, what: Incomplete) -> None: ...
def say(who: Incomplete, what: Incomplete, interact: bool = True, *args: Incomplete, **kwargs: Incomplete) -> None: ...

_history: bool
_history_list: list[renpy.character.HistoryEntry]

def _button_factory(
    label: str,
    type: str | None = None,
    selected: bool | None = None,
    disabled: bool = False,
    clicked: ActionType | None = None,
    properties: dict[str, Any] = {},
    index: str | None = None,
    **props,
) -> None: ...
def _label_factory(label: str, type: str, properties: dict[str, Any] = {}, **props) -> None: ...
