from _typeshed import Incomplete

_game_menu_screen: Incomplete

def _enter_menu() -> None: ...
def _invoke_game_menu() -> None: ...

_menu: bool
_load_prompt: bool
_scratch: Incomplete

def _game_nav(screen: Incomplete, buttons: bool = True) -> None: ...
def _game_interact() -> Incomplete: ...
def _render_savefile(
    index: Incomplete,
    name: Incomplete,
    filename: Incomplete,
    extra_info: Incomplete,
    screenshot: Incomplete,
    mtime: Incomplete,
    newest: Incomplete,
    clickable: Incomplete,
    **positions: Incomplete,
) -> None: ...
def _render_new_slot(
    index: Incomplete, name: Incomplete, filename: Incomplete, clickable: Incomplete, **positions: Incomplete
) -> None: ...
def _file_picker_pages() -> Incomplete: ...
def _file_picker_page_files(page: Incomplete) -> Incomplete: ...
def _file_picker_file_page(filename: Incomplete) -> Incomplete: ...
def _file_picker_process_screenshot(s: Incomplete) -> Incomplete: ...
def _file_picker(selected: Incomplete, save: Incomplete) -> Incomplete: ...
def _yesno_prompt(screen: Incomplete, message: Incomplete) -> Incomplete: ...
def _quit_prompt(screen: str = "quit") -> Incomplete: ...
def _mainmenu_prompt(screen: str = "mainmenu") -> Incomplete: ...
