from _typeshed import Incomplete
from typing import Any, Callable, Sequence

from renpy.display.behavior import Adjustment
from renpy.ui import BarValue
from renpy.store import DictEquality, FieldEquality

class StaticValue(BarValue, DictEquality):
    value: float
    range: float
    def __init__(self, value: float = 0.0, range: float = 1.0) -> None: ...
    def get_adjustment(self) -> Adjustment: ...

class AnimatedValue(BarValue, DictEquality):
    value: float
    range: float
    delay: float
    old_value: float | None
    start_time: float | None
    adjustment: Adjustment | None
    def __init__(self, value: float = 0.0, range: float = 1.0, delay: float = 1.0, old_value=None) -> None: ...
    def get_adjustment(self) -> Adjustment: ...
    def periodic(self, st: float) -> float | None: ...
    def replaces(self, other: "AnimatedValue") -> None: ...

class CallableValue(BarValue, DictEquality):
    _callable: Callable[[], int | float]
    range: float
    delay: float
    adjustment: Adjustment | None
    st: float | None
    def __init__(self, _callable: Callable[[], int | float], range: float = 1.0, delay: float = 0.0) -> None: ...
    def periodic(self, st: float) -> float | None: ...
    def get_adjustment(self) -> Adjustment: ...

class _m1_00barvalues__GenericValue(BarValue, FieldEquality):
    offset: int
    action: Incomplete
    force_step: bool
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    _max = max
    range: Incomplete
    max_is_zero: Incomplete
    style: Incomplete
    step: Incomplete
    def __init__(
        self,
        range: Incomplete = None,
        max_is_zero: bool = False,
        style: str = "bar",
        offset: int = 0,
        step: Incomplete = None,
        action: Incomplete = None,
        force_step: bool = False,
        min: Incomplete = None,
        max: Incomplete = None,
    ) -> None: ...
    def changed(self, value: Incomplete) -> Incomplete: ...
    def get_adjustment(self) -> Adjustment: ...
    def get_style(self) -> tuple[str, str]: ...

class DictValue(_m1_00barvalues__GenericValue):
    kind: str
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    dict: Incomplete
    key: Incomplete
    def __init__(self, dict: Incomplete, key: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def get_value(self) -> Incomplete: ...
    def set_value(self, value: Incomplete) -> None: ...

class FieldValue(_m1_00barvalues__GenericValue):
    kind: str
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    object: Incomplete
    field: Incomplete
    def __init__(self, object: Incomplete, field: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def get_value(self) -> Incomplete: ...
    def set_value(self, value: Incomplete) -> None: ...

class VariableValue(FieldValue):
    kind: str
    def __init__(self, variable: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> None: ...

class ScreenVariableValue(_m1_00barvalues__GenericValue):
    kind: str
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    variable: Incomplete
    def __init__(self, variable: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def get_value(self) -> Incomplete: ...
    def set_value(self, value: Incomplete) -> None: ...

class LocalVariableValue(DictValue):
    kind: str
    def __init__(self, variable: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> None: ...

class MixerValue(BarValue, DictEquality):
    step: int | float | None
    force_step: bool
    mixer: int
    def __init__(self, mixer: int, step: int | float | None = None, force_step: bool = False) -> None: ...
    def get_volume(self) -> float: ...
    def set_volume(self, volume: float) -> None: ...
    def set_mixer(self, value: float) -> None: ...
    def get_mixer(self) -> float: ...
    def get_adjustment(self) -> Adjustment: ...
    def get_style(self) -> tuple[str, str]: ...

class _CharacterVolumeValue(MixerValue):
    voice_tag: str
    def __init__(self, voice_tag: str) -> None: ...
    def get_volume(self) -> float: ...
    def set_volume(self, volume: float) -> None: ...

class XScrollValue(BarValue, FieldEquality):
    equality_fields: Sequence[str]
    viewport: str
    def __init__(self, viewport: str) -> None: ...
    def get_adjustment(self) -> Adjustment: ...
    def get_style(self) -> tuple[str, str]: ...

class YScrollValue(BarValue, FieldEquality):
    equality_fields: Sequence[str]
    viewport: str
    def __init__(self, viewport: str) -> None: ...
    def get_adjustment(self) -> Adjustment: ...
    def get_style(self) -> tuple[str, str]: ...

class AudioPositionValue(BarValue, DictEquality):
    channel: str
    update_interval: float
    adjustment: Adjustment
    def __init__(self, channel: str = "music", update_interval: float = 0.1) -> None: ...
    def get_pos_duration(self) -> tuple[float, float]: ...
    def get_adjustment(self) -> Adjustment: ...
    def periodic(self, st: float) -> float | None: ...
