from _typeshed import Incomplete
import renpy
from renpy.ui import Action, BarValue

def _error_hyperlink_styler(target: Incomplete) -> Incomplete: ...
def _error_hyperlink_function(target: Incomplete) -> None: ...
def _(s: Incomplete) -> Incomplete: ...

class _ExceptionPrintContext(renpy.error.TextIOExceptionPrintContext):
    BRIGHT_RED: str
    RED: str
    def __init__(self, *, filter_private: bool, emit_context: bool = True) -> None: ...
    def _escape_limit(self, s: str) -> Incomplete: ...
    def _color(self, text: str, color: str) -> Incomplete: ...
    def location(self, filename: Incomplete, lineno: Incomplete, name: Incomplete) -> None: ...
    def source_carets(self, line: Incomplete, carets: Incomplete) -> Incomplete: ...
    def string(self, text: str) -> Incomplete: ...
    def final_exception_line(self, exc_type: str, text: str | None) -> Incomplete: ...

def _m1__errorhandling__simple_traceback(traceback_exception: Incomplete) -> Incomplete: ...
def _m1__errorhandling__full_traceback(traceback_exception: Incomplete) -> Incomplete: ...
def _m1__errorhandling__format_parse_errors(errors: list[str]) -> Incomplete: ...

class _EditFile(Action):
    filename: Incomplete
    line: Incomplete
    def __init__(self, filename: Incomplete, line: int = 1) -> None: ...
    def __call__(self) -> None: ...

class _CopyFile(Action):
    filename: Incomplete
    template: Incomplete
    def __init__(self, filename: Incomplete, template: Incomplete) -> None: ...
    def __call__(self) -> None: ...

def _m1__errorhandling__can_open_traceback() -> Incomplete: ...

class _m1__errorhandling__TooltipAction:
    tooltip: Incomplete
    value: Incomplete
    def __init__(self, tooltip: Incomplete, value: Incomplete) -> None: ...
    def __call__(self) -> None: ...
    def unhovered(self) -> None: ...

class _m1__errorhandling__Tooltip:
    value: Incomplete
    default: Incomplete
    def __init__(self, default: Incomplete) -> None: ...
    def action(self, value: Incomplete) -> Incomplete: ...

class _m1__errorhandling__XScrollValue(BarValue):
    viewport: Incomplete
    def __init__(self, viewport: Incomplete) -> None: ...
    def get_adjustment(self) -> Incomplete: ...
    def get_style(self) -> tuple[str, str]: ...

class _m1__errorhandling__YScrollValue(BarValue):
    viewport: Incomplete
    def __init__(self, viewport: Incomplete) -> None: ...
    def get_adjustment(self) -> Incomplete: ...
    def get_style(self) -> tuple[str, str]: ...

class _m1__errorhandling__ErrorQuit(Action):
    def __call__(self) -> None: ...

class _m1__errorhandling__EnterConsole(Action):
    def __call__(self) -> Incomplete: ...
