from _typeshed import Incomplete
from typing import Any

import renpy
from renpy.ui import Action
from renpy.store import DictEquality

_m1_00action_menu__NoShowTransition: renpy.object.Sentinel

class ShowMenu(Action, DictEquality):
    transition: Incomplete
    screen: str | tuple[str, ...] | None
    args: tuple[Any, ...]
    kwargs: dict[str, Any]
    def __init__(
        self, screen: str | tuple[str, ...] | None = None, *args: Incomplete, **kwargs: Incomplete
    ) -> None: ...
    def predict(self) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...
    def get_sensitive(self) -> bool: ...

class Continue(Action, DictEquality):
    regexp: str
    confirm: bool
    def __init__(self, regexp: str = "[^_]", confirm: bool = True) -> None: ...
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

class Start(Action, DictEquality):
    label: renpy.ast.NodeName
    def __init__(self, label: renpy.ast.NodeName = "start") -> None: ...
    def __call__(self) -> None: ...

class MainMenu(Action, DictEquality):
    save: bool
    confirm: bool
    def __init__(self, confirm: bool = True, save: bool = True) -> None: ...
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

_confirm_quit: bool

class Quit(Action, DictEquality):
    confirm: bool | None
    def __init__(self, confirm: bool | None = None) -> None: ...
    def __call__(self) -> None: ...

class Skip(Action, DictEquality):
    fast: bool
    confirm: bool
    def __init__(self, fast: bool = False, confirm: bool = False) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...
    def get_sensitive(self) -> bool: ...

class Help(Action, DictEquality):
    help: str | None
    def __init__(self, help: str | None = None) -> None: ...
    def __call__(self) -> None: ...
