from _typeshed import Incomplete
from renpy.ui import Action

_m1_00stylepreferences__preferences: Incomplete
_m1_00stylepreferences__alternatives: Incomplete
_m1_00stylepreferences__spdirty: Incomplete

def _m1_00stylepreferences__register_style_preference(
    preference: Incomplete, alternative: Incomplete, style: Incomplete, property: Incomplete, value: Incomplete
) -> None: ...
def _m1_00stylepreferences__init() -> None: ...
def _m1_00stylepreferences__update() -> None: ...
def _m1_00stylepreferences__apply_styles() -> None: ...
def _m1_00stylepreferences__check(preference: Incomplete, alternative: Incomplete = None) -> None: ...
def _m1_00stylepreferences__set_style_preference(preference: Incomplete, alternative: Incomplete) -> None: ...
def _m1_00stylepreferences__get_style_preference(preference: Incomplete) -> Incomplete: ...

class StylePreference(Action):
    preference: Incomplete
    alternative: Incomplete
    def __init__(self, preference: Incomplete, alternative: Incomplete) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...
