from _typeshed import Incomplete

from renpy.display.render import Render
from renpy.display.displayable import Displayable

class MouseDisplayable(Displayable):
    cursor: Incomplete
    cursors: Incomplete
    last_cursor: str
    last_cursor_st: int
    def __init__(self, cursor: Incomplete, x: int = 0, y: int = 0) -> None: ...
    def add(self, name: Incomplete, cursor: Incomplete, x: int = 0, y: int = 0) -> Incomplete: ...
    def get_cursor_name(self) -> Incomplete: ...
    def _has_mouse_cursor(self) -> Incomplete: ...
    def render(self, width: float, height: float, st: float, at: float) -> Render: ...
    def visit(self) -> Incomplete: ...
