from _typeshed import Incomplete
from typing import Any, Sequence

import renpy
from renpy.ui import Action
from renpy.store import DictEquality, FieldEquality

_voice: Incomplete
_last_voice_play: str | None

def _invoke_voice_callbacks(event: str) -> None: ...
def voice(filename: str, tag: str | None = None) -> None: ...
def voice_sustain(ignored: str = "", **kwargs: Incomplete) -> None: ...
def voice_replay() -> None: ...
def voice_can_replay() -> bool: ...

class SetVoiceMute(Action, DictEquality):
    voice_tag: str
    mute: bool
    def __init__(self, voice_tag: str, mute: bool) -> None: ...
    def get_selected(self) -> bool: ...
    def __call__(self) -> None: ...

@renpy.exports.pure
def SetCharacterVolume(voice_tag: str, volume: float | None = None) -> Incomplete: ...
def GetCharacterVolume(voice_tag: str) -> float: ...

class PlayCharacterVoice(Action, FieldEquality):
    equality_fields: Sequence[str]
    can_be_selected: bool
    selected: bool
    voice_tag: str
    sample: str | list[str]
    def __init__(self, voice_tag: str, sample: str | list[str], selected: bool = False) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...
    def periodic(self, st: float) -> float | None: ...

class ToggleVoiceMute(Action, DictEquality):
    voice_tag: str
    invert: bool
    def __init__(self, voice_tag: str, invert: bool = False) -> None: ...
    def get_selected(self) -> bool: ...
    def __call__(self) -> None: ...

class VoiceReplay(Action, DictEquality):
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

class VoiceInfo:
    filename: str | None
    sustain: bool
    tag: str | None
    auto_filename: str | None
    tlid: str | None
    def __init__(self, predict: bool = False, tag: str | None = None) -> None: ...

def _get_voice_info() -> VoiceInfo: ...
def _voice_history_callback(h: renpy.character.HistoryEntry) -> None: ...
