from _typeshed import Incomplete
from typing import Any, Sequence, Literal

import renpy
from renpy.ui import Action
from renpy.store import FieldEquality

class _InputValueAction(Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    input_value: InputValue
    action: Literal["enable", "disable", "toggle"]
    def __init__(self, input_value: InputValue, action: Literal["enable", "disable", "toggle"]) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class DisableAllInputValues(Action):
    def __call__(self) -> None: ...

class InputValue(renpy.object.Object):
    default: bool
    editable: bool
    returnable: bool
    def get_text(self) -> str: ...
    def set_text(self, s: str) -> None: ...
    def enter(self) -> str | None: ...
    def Enable(self) -> _InputValueAction | None: ...
    def Disable(self) -> _InputValueAction | None: ...
    def Toggle(self) -> _InputValueAction | None: ...

class _m1_00inputvalues__GenericInputValue(InputValue, FieldEquality):
    equality_fields: Sequence[str]
    default: bool
    returnable: bool
    def __init__(self, default: bool = True, returnable: bool = False) -> None: ...

class ScreenVariableInputValue(_m1_00inputvalues__GenericInputValue):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    variable: str
    screen: renpy.display.screen.ScreenDisplayable | None
    def __init__(self, variable: str, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def get_text(self) -> str: ...
    def set_text(self, s: str) -> None: ...

class FieldInputValue(_m1_00inputvalues__GenericInputValue):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    kind: str
    object: object
    field: str
    def __init__(self, object: object, field: str, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def get_text(self) -> str: ...
    def set_text(self, s: str) -> None: ...

class VariableInputValue(FieldInputValue):
    __version__: int
    kind: str
    object: renpy.python.StoreModule
    field: str
    def after_upgrade(self, version: int) -> None: ...
    def __init__(self, variable: str, *args: Incomplete, **kwargs: Incomplete) -> None: ...

class DictInputValue[KT, VT](_m1_00inputvalues__GenericInputValue):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    dict: dict[KT, VT]
    key: KT
    def __init__(self, dict: dict[KT, VT], key: KT, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def get_text(self) -> str: ...
    def set_text(self, s: str) -> None: ...

class LocalVariableInputValue(DictInputValue):
    def __init__(self, variable: str, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def get_text(self) -> str: ...
