from _typeshed import Incomplete

from renpy.ui import Action

class _SetRenderer(Action):
    renderer: str
    def __init__(self, renderer: str) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

def _m1_00gltest__gl_test() -> None: ...
def _gl_performance_test() -> None: ...
