from _typeshed import Incomplete
from typing import Any, Sequence

import renpy
from renpy.character import ADVCharacter

nvl_list: list[tuple[Incomplete, str, dict[str, dict[str, Any]]]] | None
nvl_variant: Incomplete

def _m1_00nvl_mode__s(s: Incomplete) -> Incomplete: ...

class _NVLEntry(tuple): ...

def _m1_00nvl_mode__nvl_screen_dialogue() -> Incomplete: ...
def _m1_00nvl_mode__nvl_show_screen(screen_name: Incomplete, **scope) -> Incomplete: ...
def nvl_show_core(
    who: Incomplete | None = None, what: Incomplete | None = None, multiple: Incomplete | None = None
) -> Incomplete: ...
def nvl_window() -> None: ...
def nvl_show(with_: Incomplete) -> None: ...
def nvl_hide(with_: Incomplete, modes: bool = True) -> None: ...
def nvl_erase() -> None: ...
def nvl_clear_next() -> bool | None: ...

class NVLCharacter(ADVCharacter):
    clear: bool
    def __init__(self, who: Incomplete = ..., kind: NVLCharacter | None = None, **properties) -> None: ...
    def push_nvl_list(self, who: Incomplete, what: Incomplete, multiple: Incomplete | None = None) -> None: ...
    def pop_nvl_list(self) -> None: ...
    def do_add(self, who: Incomplete, what: Incomplete, multiple: Incomplete | None = None) -> None: ...
    def do_display(
        self,
        who: Incomplete,
        what: Incomplete,
        multiple: Incomplete | None = None,
        retain: Incomplete | None = None,
        **display_args: Incomplete,
    ) -> None: ...
    def do_done(self, who: Incomplete, what: Incomplete, multiple: Incomplete | None = None) -> None: ...
    def do_extend(self) -> None: ...

nvl: NVLCharacter
nvl_narrator: NVLCharacter

def nvl_clear() -> None: ...
def nvl_menu(items: Incomplete) -> Any | None: ...

NVLSpeaker = NVLCharacter

def _nvl_adv_callback(mode: str, old_modes: Sequence[str]) -> None: ...

_nvl_language: str | None
