from _typeshed import Incomplete
from typing import Sequence, Any
from renpy.display.displayable import Displayable

def _m1_inspector__format_style(name: Sequence[str]) -> str: ...
def _m1_inspector__format_location(l: tuple[str, int]) -> Incomplete: ...
def _m1_inspector__safe_repr(name: Any) -> str: ...
def _m1_inspector__inspect(tree: Sequence[tuple[int, float, float, Displayable]]) -> None: ...
def _inspector_repr(d: Displayable) -> Incomplete: ...
