from _typeshed import Incomplete

_load_prompt: bool
_m1_classic_load_save__scratch: Incomplete

def _render_savefile(
    index: Incomplete,
    name: Incomplete,
    extra_info: Incomplete,
    screenshot: Incomplete,
    mtime: Incomplete,
    newest: Incomplete,
    clicked: Incomplete,
) -> None: ...
def _render_new_slot(index: Incomplete, name: Incomplete, clicked: Incomplete) -> None: ...
def _file_picker_pages() -> Incomplete: ...
def _file_picker_page_files(page: Incomplete) -> Incomplete: ...
def _file_picker_file_page(filename: Incomplete) -> Incomplete: ...
def _file_picker_process_screenshot(s: Incomplete) -> Incomplete: ...
def _file_picker(screen: Incomplete, save: Incomplete) -> Incomplete: ...
