from _typeshed import Incomplete
from typing import Sequence, Protocol, Any

import renpy
from renpy.ui import Action
from renpy.store import FieldEquality
from renpy.types import DisplayableLike

class GalleryCondition(Protocol):
    def check(self, all_prior: bool) -> bool: ...

class _m1_00gallery__GalleryAllPriorCondition(GalleryCondition):
    def check(self, all_prior: bool) -> bool: ...

class _m1_00gallery__GalleryArbitraryCondition(GalleryCondition):
    condition: str
    def __init__(self, condition: str) -> None: ...
    def check(self, all_prior: bool) -> bool: ...

class _m1_00gallery__GalleryUnlockCondition(GalleryCondition):
    images: Sequence[str | tuple[str]]
    def __init__(self, images: Sequence[str | tuple[str]]) -> None: ...
    def check(self, all_prior: bool) -> bool: ...

class _m1_00gallery__GalleryImage:
    show_properties: Incomplete
    movie: bool
    gallery: Gallery
    conditions: list[GalleryCondition]
    displayables: Incomplete
    transforms: Incomplete
    def __init__(self, gallery: Gallery, displayables: Incomplete, movie: bool = False, **properties) -> None: ...
    def check_unlock(self, all_prior: bool) -> bool: ...
    def show(self, locked: bool, index: int, count: int, first: bool) -> Any | None: ...

class _m1_00gallery__GalleryButton:
    gallery: Gallery
    images: list[_m1_00gallery__GalleryImage]
    conditions: list[GalleryCondition]
    index: int
    def __init__(self, gallery: Gallery, index: int) -> None: ...
    def check_unlock(self) -> bool: ...

class _m1_00gallery__GalleryToggleSlideshow(Action, FieldEquality):
    identity_fields: Sequence[str]
    gallery: Gallery
    def __init__(self, gallery: Gallery) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class _m1_00gallery__GalleryAction(Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    gallery: Gallery
    index: int
    def __init__(self, gallery: Gallery, index: int) -> None: ...
    def __call__(self) -> None: ...

class Gallery:
    transition: Incomplete | None
    hover_border: Incomplete | None
    idle_border: Incomplete | None
    locked_button: Incomplete | None
    image_screen: str
    buttons: dict[str, _m1_00gallery__GalleryButton]
    button_list: list[Incomplete]
    button_: Incomplete | None
    image_: _m1_00gallery__GalleryImage | None
    unlockable: Incomplete | None
    unlocked_advance: bool
    navigation: bool
    span_buttons: bool
    slideshow_delay: int
    slideshow: bool
    def __init__(self) -> None: ...
    def button(self, name: str) -> None: ...
    def image(self, *displayables: Incomplete, **properties) -> None: ...
    display = image
    def transform(self, *transforms: Incomplete) -> None: ...
    def unlock(self, *images: Incomplete) -> None: ...
    def condition(self, expression: str) -> None: ...
    def allprior(self) -> None: ...
    def unlock_image(self, *images: Incomplete, **properties) -> None: ...
    def Action(self, name: str) -> _m1_00gallery__GalleryAction | None: ...
    def make_button(
        self,
        name: str,
        unlocked: DisplayableLike,
        locked: DisplayableLike | None = None,
        hover_border: Incomplete | None = None,
        idle_border: Incomplete | None = None,
        style: Incomplete | None = None,
        **properties: Incomplete,
    ) -> Incomplete: ...
    def get_fraction(self, name: str | None, format: str = "{seen}/{total}") -> str: ...
    def show(self, button: int = 0, image: int = 0) -> None: ...
    def Return(self) -> renpy.curry.Partial[str]: ...
    def Next(self, unlocked: bool = False) -> renpy.curry.Partial[str]: ...
    def Previous(self, unlocked: bool = False) -> renpy.curry.Partial[str]: ...
    def ToggleSlideshow(self) -> _m1_00gallery__GalleryToggleSlideshow: ...
