from typing import Any

from renpy.display.displayable import Displayable
from renpy.display.render import Render

class MouseDisplayable(Displayable):
    cursor: Displayable | None
    cursors: dict[str, Displayable]
    last_cursor: str
    last_cursor_st: int
    def __init__(self, cursor: Displayable | None, x: int = 0, y: int = 0) -> None: ...
    def add(self, name: str, cursor: Displayable | None, x: int = 0, y: int = 0) -> None: ...
    def get_cursor_name(self) -> str | None: ...
    def _has_mouse_cursor(self) -> bool: ...
    def render(self, width: float, height: float, st: float, at: float) -> Render: ...
    def visit(self) -> list[Displayable | None]: ...
