_window_auto: bool
_window_next: bool

def _window_show(trans: bool | None = False, auto: bool = False) -> None: ...
def _window_hide(trans: bool | None = False, auto: bool = False) -> None: ...
def _window_auto_callback(statement: str) -> None: ...
def _init_window() -> None: ...
