from typing import Any

import renpy
from renpy.display.behavior import Adjustment
from renpy.ui import Action, BarValue

def _error_hyperlink_styler(target: str) -> str: ...
def _error_hyperlink_function(target: str) -> None: ...
def _(s: str) -> str: ...

class _ExceptionPrintContext(renpy.error.TextIOExceptionPrintContext):
    BRIGHT_RED: str
    RED: str
    def __init__(self, *, filter_private: bool, emit_context: bool = True) -> None: ...
    def _escape_limit(self, s: str) -> str: ...
    def _color(self, text: str, color: str) -> str: ...
    def location(self, filename: str, lineno: int, name: str) -> None: ...
    def source_carets(self, line: str, carets: str) -> str: ...
    def string(self, text: str) -> str: ...
    def final_exception_line(self, exc_type: str, text: str | None) -> str: ...

def _m1__errorhandling__simple_traceback(traceback_exception: Any) -> str: ...
def _m1__errorhandling__full_traceback(traceback_exception: Any) -> str: ...
def _m1__errorhandling__format_parse_errors(errors: list[str]) -> str: ...

class _EditFile(Action):
    filename: str
    line: int
    def __init__(self, filename: str, line: int = 1) -> None: ...
    def __call__(self) -> None: ...

class _CopyFile(Action):
    filename: str
    template: str
    def __init__(self, filename: str, template: str) -> None: ...
    def __call__(self) -> None: ...

def _m1__errorhandling__can_open_traceback() -> bool: ...

class _m1__errorhandling__TooltipAction:
    tooltip: Any
    value: Any
    def __init__(self, tooltip: Any, value: Any) -> None: ...
    def __call__(self) -> None: ...
    def unhovered(self) -> None: ...

class _m1__errorhandling__Tooltip:
    value: Any
    default: Any
    def __init__(self, default: Any) -> None: ...
    def action(self, value: Any) -> _m1__errorhandling__TooltipAction: ...

class _m1__errorhandling__XScrollValue(BarValue):
    viewport: str
    def __init__(self, viewport: str) -> None: ...
    def get_adjustment(self) -> Adjustment: ...
    def get_style(self) -> tuple[str, str]: ...

class _m1__errorhandling__YScrollValue(BarValue):
    viewport: str
    def __init__(self, viewport: str) -> None: ...
    def get_adjustment(self) -> Adjustment: ...
    def get_style(self) -> tuple[str, str]: ...

class _m1__errorhandling__ErrorQuit(Action):
    def __call__(self) -> None: ...

class _m1__errorhandling__EnterConsole(Action):
    def __call__(self) -> None: ...
