import time
from typing import Any

import renpy
from renpy.display.behavior import ActionType
from renpy.display.im import ImageBase
from renpy.store import DictEquality, InputValue
from renpy.ui import Action

_weekday_name_long: list[str]
_weekday_name_short: list[str]
_month_name_long: list[str]
_month_name_short: list[str]

def _strftime(format: str, t: time.struct_time) -> str: ...
def _m1_00action_file__slotname(name: int | str, page: int | str | None = None, slot: bool = False) -> str: ...
def _m1_00action_file__newest_slot() -> str | None: ...
def _m1_00action_file__unused_slot_name(page: int | str | None) -> str: ...
def FileCurrentPage() -> str: ...
def FileUsedSlots(page: int | str | None = None, highest_first: bool = True) -> list[int]: ...
def FileLoadable(name: int | str, page: int | str | None = None, slot: bool = False) -> bool: ...
def FileScreenshot(
    name: int | str, empty: ImageBase | None = None, page: int | str | None = None, slot: bool = False
) -> ImageBase: ...
def FileTime(
    name: int | str, format: str = ..., empty: str = "", page: int | str | None = None, slot: bool = False
) -> str: ...
def FileJson[T, M](
    name: int | str,
    key: str | None = None,
    empty: T = None,
    missing: M = None,
    page: int | str | None = None,
    slot: bool = False,
) -> dict[str, Any] | T | M: ...
def FileSaveName(name: int | str, empty: str = "", page: int | str | None = None, slot: bool = False) -> str: ...
def FileNewest(name: int | str, page=None, slot: bool = False) -> bool: ...

class FileSave(Action, DictEquality):
    alt: str
    slot: bool | None
    action: ActionType
    name: int | str
    confirm: bool
    page: int | str | None
    cycle: bool
    def __init__(
        self,
        name: int | str | None,
        confirm: bool = True,
        newest: bool = True,
        page: int | str | None = None,
        cycle: bool = False,
        slot: bool = False,
        action: ActionType | None = None,
    ) -> None: ...
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...
    def get_selected(self) -> bool: ...

class FileLoad(Action, DictEquality):
    alt: str
    slot: bool | None
    name: int | str | None
    confirm: bool
    page: int | str | None
    newest: bool
    def __init__(
        self,
        name: int | str | None,
        confirm: bool = True,
        page: int | str | None = None,
        newest: bool = True,
        cycle: bool = False,
        slot: bool = False,
    ) -> None: ...
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...
    def get_selected(self) -> bool: ...

class FileDelete(Action, DictEquality):
    alt: str
    slot: bool | None
    name: int | str | None
    confirm: bool
    page: int | str | None
    def __init__(
        self, name: int | str | None, confirm: bool = True, page: int | str | None = None, slot: bool = False
    ) -> None: ...
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

def FileAction(name: int | str | None, page: int | str | None = None, **kwargs: Any) -> None: ...
def _predict_file_page(page: int | str | None) -> None: ...

class FilePage(Action, DictEquality):
    page: int | str
    alt: str
    def __init__(self, page: int | str) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...
    def predict(self) -> None: ...

def FilePageName(auto: str = "a", quick: str = "q") -> str: ...

class FilePageNameInputValue(InputValue, DictEquality):
    pattern: str
    auto: str
    quick: str
    _page: int | str | None
    default: bool
    def __init__(
        self,
        pattern: str = ...,
        auto: str = ...,
        quick: str = ...,
        page: int | str | None = None,
        default: bool = False,
    ) -> None: ...
    def get_page(self) -> int | str: ...
    @property
    def editable(self) -> bool: ...
    def get_text(self) -> str: ...
    def set_text(self, s: str) -> None: ...
    def enter(self) -> None: ...

def FileSlotName(
    slot: int | str, slots_per_page: int, auto: str = "a", quick: str = "q", format: str = "%s%d"
) -> str: ...

class FilePageNext(Action, DictEquality):
    alt: str
    page: int | str | None
    def __init__(
        self, max: int | str | None = None, wrap: bool = False, auto: bool = True, quick: bool = True
    ) -> None: ...
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...
    def predict(self) -> None: ...

class FilePagePrevious(Action, DictEquality):
    alt: str
    page: int | str | None
    def __init__(
        self, max: int | str | None = None, wrap: bool = False, auto: bool = True, quick: bool = True
    ) -> None: ...
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...
    def predict(self) -> None: ...

class FileTakeScreenshot(Action, DictEquality):
    def __call__(self) -> None: ...

@renpy.exports.pure
def QuickSave(message: str = ..., newest: bool = False) -> list[Action]: ...
@renpy.exports.pure
def QuickLoad(confirm: bool = True) -> Action: ...
