from renpy.display.behavior import Keymap

class _keymap_list(list):
    def remove(self, a: str) -> None: ...

_windows_hidden: bool

def _keymap_toggle_afm() -> None: ...
def _toggle_skipping() -> None: ...

toggle_skipping = _toggle_skipping

def _keymap_toggle_skipping() -> None: ...
def _help(help: str | None = None) -> None: ...
def _screenshot_core() -> None: ...
def _screenshot() -> None: ...
def _screenshot_callback(fn: str) -> None: ...
def _fast_skip() -> None: ...
def _reload_game() -> None: ...
def _launch_editor() -> None: ...
def _developer() -> None: ...
def _profile_once() -> None: ...
def _memory_profile() -> None: ...
def _progress_screen() -> None: ...

_default_keymap: Keymap
