from collections.abc import Sequence
from typing import Any

from renpy.display.displayable import Displayable

def _m1_inspector__format_style(name: Sequence[str]) -> str: ...
def _m1_inspector__format_location(l: tuple[str, int]) -> str: ...
def _m1_inspector__safe_repr(name: Any) -> str: ...
def _m1_inspector__inspect(tree: Sequence[tuple[int, float, float, Displayable]]) -> None: ...
def _inspector_repr(d: Displayable) -> str: ...
