from collections.abc import Callable, Sequence
from typing import Any

import renpy
from renpy.display.behavior import Adjustment
from renpy.store import DictEquality, FieldEquality
from renpy.ui import Action, BarValue

class StaticValue(BarValue, DictEquality):
    value: float
    range: float
    def __init__(self, value: float = 0.0, range: float = 1.0) -> None: ...
    def get_adjustment(self) -> Adjustment: ...

class AnimatedValue(BarValue, DictEquality):
    value: float
    range: float
    delay: float
    old_value: float | None
    start_time: float | None
    adjustment: Adjustment | None
    def __init__(self, value: float = 0.0, range: float = 1.0, delay: float = 1.0, old_value=None) -> None: ...
    def get_adjustment(self) -> Adjustment: ...
    def periodic(self, st: float) -> float | None: ...
    def replaces(self, other: AnimatedValue) -> None: ...

class CallableValue(BarValue, DictEquality):
    _callable: Callable[[], int | float]
    range: float
    delay: float
    adjustment: Adjustment | None
    st: float | None
    def __init__(self, _callable: Callable[[], int | float], range: float = 1.0, delay: float = 0.0) -> None: ...
    def periodic(self, st: float) -> float | None: ...
    def get_adjustment(self) -> Adjustment: ...

class _m1_00barvalues__GenericValue(BarValue, FieldEquality):
    offset: int
    action: Action | None
    force_step: bool
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    _max = max
    range: int | float
    max_is_zero: bool
    style: str
    step: int | float
    def __init__(
        self,
        range: int | float | None = None,
        max_is_zero: bool = False,
        style: str = "bar",
        offset: int = 0,
        step: int | float | None = None,
        action: Action | None = None,
        force_step: bool = False,
        min: int | float | None = None,
        max: int | float | None = None,
    ) -> None: ...
    def changed(self, value: int | float) -> Any: ...
    def get_adjustment(self) -> Adjustment: ...
    def get_style(self) -> tuple[str, str]: ...

class DictValue(_m1_00barvalues__GenericValue):
    kind: str
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    dict: dict[Any, Any] | list[Any]
    key: Any
    def __init__(self, dict: dict[Any, Any] | list[Any], key: Any, *args: Any, **kwargs: Any) -> None: ...
    def get_value(self) -> Any: ...
    def set_value(self, value: Any) -> None: ...

class FieldValue(_m1_00barvalues__GenericValue):
    kind: str
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    object: Any
    field: str
    def __init__(self, object: Any, field: str, *args: Any, **kwargs: Any) -> None: ...
    def get_value(self) -> Any: ...
    def set_value(self, value: Any) -> None: ...

class VariableValue(FieldValue):
    kind: str
    def __init__(self, variable: str, *args: Any, **kwargs: Any) -> None: ...

class ScreenVariableValue(_m1_00barvalues__GenericValue):
    kind: str
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    variable: str
    def __init__(self, variable: str, *args: Any, **kwargs: Any) -> None: ...
    def get_value(self) -> Any: ...
    def set_value(self, value: Any) -> None: ...

class LocalVariableValue(DictValue):
    kind: str
    def __init__(self, variable: str, *args: Any, **kwargs: Any) -> None: ...

class MixerValue(BarValue, DictEquality):
    step: int | float | None
    force_step: bool
    mixer: int
    def __init__(self, mixer: int, step: int | float | None = None, force_step: bool = False) -> None: ...
    def get_volume(self) -> float: ...
    def set_volume(self, volume: float) -> None: ...
    def set_mixer(self, value: float) -> None: ...
    def get_mixer(self) -> float: ...
    def get_adjustment(self) -> Adjustment: ...
    def get_style(self) -> tuple[str, str]: ...

class _CharacterVolumeValue(MixerValue):
    voice_tag: str
    def __init__(self, voice_tag: str) -> None: ...
    def get_volume(self) -> float: ...
    def set_volume(self, volume: float) -> None: ...

class XScrollValue(BarValue, FieldEquality):
    equality_fields: Sequence[str]
    viewport: str
    def __init__(self, viewport: str) -> None: ...
    def get_adjustment(self) -> Adjustment: ...
    def get_style(self) -> tuple[str, str]: ...

class YScrollValue(BarValue, FieldEquality):
    equality_fields: Sequence[str]
    viewport: str
    def __init__(self, viewport: str) -> None: ...
    def get_adjustment(self) -> Adjustment: ...
    def get_style(self) -> tuple[str, str]: ...

class AudioPositionValue(BarValue, DictEquality):
    channel: str
    update_interval: float
    adjustment: Adjustment
    def __init__(self, channel: str = "music", update_interval: float = 0.1) -> None: ...
    def get_pos_duration(self) -> tuple[float, float]: ...
    def get_adjustment(self) -> Adjustment: ...
    def periodic(self, st: float) -> float | None: ...
