from collections.abc import Callable, Sequence
from typing import TYPE_CHECKING, Any, Literal

import renpy
from renpy.display.behavior import ActionType
from renpy.store import DictEquality, FieldEquality
from renpy.ui import Action

if TYPE_CHECKING:
    type ScrollDirection = Literal[
        "increase", "decrease", "horizontal increase", "horizontal decrease", "vertical increase", "vertical decrease"
    ]

class InvertSelected(Action, DictEquality):
    action: Action
    alt: str | None
    def __init__(self, action: Action) -> None: ...
    def __call__(self) -> Any | None: ...
    def get_selected(self) -> bool: ...
    def get_sensitive(self) -> bool: ...
    def periodic(self, st: float) -> float | None: ...
    def predict(self) -> None: ...

@renpy.exports.pure
def If(expression: bool, true: ActionType | None = None, false: ActionType | None = None) -> ActionType | None: ...

class _ActionList(Action, DictEquality):
    actions: ActionType
    def __init__(self, actions: ActionType) -> None: ...
    def get_selected(self) -> bool: ...
    def get_sensitive(self) -> bool: ...
    def get_tooltip(self) -> Any | None: ...
    def periodic(self, st: float) -> float | None: ...
    def unhovered(self) -> None: ...
    def __call__(self) -> Any: ...

class SelectedIf(Action, DictEquality):
    expression: ActionType
    def __init__(self, expression: ActionType) -> None: ...
    def __call__(self) -> Any | None: ...
    def get_selected(self) -> bool: ...

class SensitiveIf(Action, DictEquality):
    expression: ActionType
    def __init__(self, expression: ActionType) -> None: ...
    def __call__(self) -> Any | None: ...
    def get_sensitive(self) -> bool: ...

class Screenshot(Action, DictEquality):
    def __call__(self) -> None: ...

class HideInterface(Action, DictEquality):
    def __call__(self) -> None: ...

class OpenURL(Action, DictEquality):
    url: str
    def __init__(self, url: str) -> None: ...
    def __call__(self) -> None: ...

class With(Action, DictEquality):
    transition: renpy.display.transition.TransitionFunction
    def __init__(self, transition: renpy.display.transition.TransitionFunction) -> None: ...
    def __call__(self) -> None: ...

class Notify(Action, DictEquality):
    message: str
    def __init__(self, message: str) -> None: ...
    def predict(self) -> None: ...
    def __call__(self) -> None: ...

class Rollback(Action, DictEquality):
    args: tuple[Any, ...]
    kwargs: dict[str, Any]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

class RollbackToIdentifier(Action, DictEquality):
    identifier: renpy.rollback.RollbackIdentifier
    def __init__(self, identifier: renpy.rollback.RollbackIdentifier) -> None: ...
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

class RestartStatement(Action, DictEquality):
    def __call__(self) -> None: ...

class RollForward(Action, DictEquality):
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

def GetTooltip(screen: str | None = None, last: bool = False) -> Any | None: ...

class _m1_00action_other__TooltipAction(Action, FieldEquality):
    identity_fields: Sequence[str]
    tooltip: Tooltip
    value: Any
    def __init__(self, tooltip: Tooltip, value: Any) -> None: ...
    def __call__(self) -> None: ...
    def unhovered(self) -> None: ...

_m1_00screen__TooltipAction = _m1_00action_other__TooltipAction

class Tooltip:
    value: Any
    default: Any
    def __init__(self, default: Any) -> None: ...
    def Action(self, value: Any) -> _m1_00action_other__TooltipAction: ...
    action = Action

class Language(Action, DictEquality):
    alt: str
    language: str | None
    def __init__(self, language: str | None) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...
    def get_sensitive(self) -> bool: ...

class Replay(Action, DictEquality):
    label: renpy.ast.NodeName
    scope: dict[str, Any]
    locked: bool | None
    def __init__(self, label: renpy.ast.NodeName, scope: dict[str, Any] = {}, locked: bool | None = None) -> None: ...
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

class EndReplay(Action, DictEquality):
    confirm: bool
    def __init__(self, confirm: bool = True) -> None: ...
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

class MouseMove(Action, DictEquality):
    x: float
    y: float
    duration: float | None
    def __init__(self, x: float, y: float, duration: float | None = 0) -> None: ...
    def __call__(self) -> None: ...

class QueueEvent(Action, DictEquality):
    event: str
    up: bool
    def __init__(self, event: str, up: bool = False) -> None: ...
    def __call__(self) -> None: ...

class Function(Action):
    update_screens: bool
    def __eq__(self, other: object) -> bool: ...
    callable: Callable[..., Any]
    args: tuple[Any, ...]
    kwargs: dict[str, Any]
    def __init__(self, callable: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...
    def __call__(self) -> Any: ...

class Confirm(Action, DictEquality):
    kwargs: dict[str, Any]
    prompt: str
    yes: ActionType | None
    no: ActionType | None
    confirm_selected: bool
    def __init__(
        self,
        prompt: str,
        yes: ActionType | None,
        no: ActionType | None = None,
        confirm_selected: bool = False,
        **kwargs: Any,
    ) -> None: ...
    def __call__(self) -> Any | None: ...
    def get_sensitive(self) -> bool: ...
    def get_selected(self) -> bool: ...
    def get_tooltip(self) -> Any: ...

class Scroll(Action, DictEquality):
    delay: float
    id: str
    direction: ScrollDirection
    amount: Literal["step", "page"] | float
    def __init__(
        self, id: str, direction: ScrollDirection, amount: Literal["step", "page"] | float = "step", delay: float = 0.0
    ) -> None: ...
    def get_adjustment_and_delta(self) -> tuple[renpy.display.behavior.Adjustment | None, int]: ...
    def get_sensitive(self) -> bool: ...
    def __call__(self) -> None: ...

class OpenDirectory(Action, DictEquality):
    alt: str
    directory: str
    def __init__(self, directory: str, absolute: bool = False) -> None: ...
    def get_sensitive(self) -> bool: ...
    def __call__(self) -> None: ...

class CaptureFocus(Action, DictEquality):
    name: str
    def __init__(self, name: str = "default") -> None: ...
    def __call__(self) -> None: ...

class ToggleFocus(Action, DictEquality):
    name: str
    def __init__(self, name: str = "default") -> None: ...
    def __call__(self) -> None: ...

class ClearFocus(Action, DictEquality):
    name: str
    def __init__(self, name: str = "default") -> None: ...
    def __call__(self) -> None: ...

def GetFocusRect(name: str = "default") -> tuple[int, int, int, int] | None: ...

class ExecJS(Action, DictEquality):
    code: str
    def __init__(self, code: str) -> None: ...
    def __call__(self) -> None: ...

def CurrentScreenName() -> str | None: ...

class CopyToClipboard(Action):
    s: str
    def __init__(self, s: str) -> None: ...
    def __call__(self) -> None: ...

class EditFile(Action):
    filename: str | None
    line: int
    def __init__(self, filename: str | None = None, line: int = 1) -> None: ...
    def __call__(self) -> None: ...
