from typing import Any

from renpy.ui import Action

_m1_00stylepreferences__preferences: dict[str, list[Any]]
_m1_00stylepreferences__alternatives: dict[str, list[str]]
_m1_00stylepreferences__spdirty: bool

def _m1_00stylepreferences__register_style_preference(
    preference: str, alternative: str, style: str, property: str, value: Any
) -> None: ...
def _m1_00stylepreferences__init() -> None: ...
def _m1_00stylepreferences__update() -> None: ...
def _m1_00stylepreferences__apply_styles() -> None: ...
def _m1_00stylepreferences__check(preference: str, alternative: str | None = None) -> None: ...
def _m1_00stylepreferences__set_style_preference(preference: str, alternative: str) -> None: ...
def _m1_00stylepreferences__get_style_preference(preference: str) -> str | None: ...

class StylePreference(Action):
    preference: str
    alternative: str
    def __init__(self, preference: str, alternative: str) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...
