import renpy

class _m1_developer__ImageLocationPickerData:
    position: tuple[float, float]
    rectangle: tuple[int, int, int, int] | None
    clipboard: str | None
    def __init__(self) -> None: ...
    def set_position(self, position: tuple[float, float]) -> None: ...
    def set_rectangle(self, rectangle: tuple[int, int, int, int] | None) -> None: ...
    def finish_rectangle(self, rectangle: tuple[int, int, int, int]) -> None: ...
    def get_text(self) -> str: ...

def _m1_developer__missing_show_callback(
    name: tuple[str, ...], what: tuple[str, ...], layer: str
) -> renpy.display.displayable.Displayable: ...
def _m1_developer__missing_hide_callback(name: tuple[str, ...], layer: str) -> bool: ...
def _m1_developer__missing_scene_callback(layer: str) -> bool: ...
