from renpy.ui import Action

class UploadSync(Action):
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

class DownloadSync(Action):
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...
