from collections.abc import ItemsView, Iterable, KeysView, ValuesView
from typing import Any

class _JSONDBDict[KT, VT](dict[KT, VT]):
    changed: bool
    dirty: bool
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def check(self, value: VT | None) -> None: ...
    def __setitem__(self, key: KT, value: VT) -> None: ...
    def __delitem__(self, key: KT) -> None: ...
    def clear(self) -> None: ...
    def setdefault(self, key: KT, default: VT | None = None) -> VT: ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def __ior__(self, other: _JSONDBDict[KT, VT]) -> _JSONDBDict[KT, VT]: ...

class JSONDB:
    fn: str
    data: dict[str | None, _JSONDBDict]
    dirty: bool
    default: dict[str | None, Any]
    def __init__(self, filename: str, default: dict[str | None, Any] | None = None) -> None: ...
    def save(self) -> None: ...
    def __getitem__(self, key: str | None) -> Any: ...
    def __delitem__(self, key: str | None) -> None: ...
    def __setitem__(self, key: str | None, value: Any) -> None: ...
    def __iter__(self) -> Iterable[Any]: ...
    def __reversed__(self) -> Iterable[Any]: ...
    def values(self) -> ValuesView[Any]: ...
    def keys(self) -> KeysView[str]: ...
    def items(self) -> ItemsView[str, Any]: ...
    def __len__(self) -> int: ...
    @property
    def dialogue(self) -> _JSONDBDict: ...
