from collections.abc import Sequence
from typing import Any

from renpy.store import DictEquality, FieldEquality
from renpy.ui import Action

class Play(Action, FieldEquality):
    equality_fields: Sequence[str]
    can_be_selected: bool
    channel: str
    file: str | list[str] | None
    kwargs: dict[str, Any]
    def __init__(
        self, channel: str, file: str | list[str] | None, selected: bool | None = None, **kwargs: Any
    ) -> None: ...
    def __call__(self) -> None: ...
    selected: bool
    def get_selected(self) -> bool: ...
    def periodic(self, st: float) -> float | None: ...

class Queue(Action, DictEquality):
    channel: str
    file: str | list[str] | None
    kwargs: dict[str, Any]
    def __init__(self, channel: str, file: str | list[str] | None, **kwargs: Any) -> None: ...
    def __call__(self) -> None: ...

class Stop(Action, DictEquality):
    channel: str
    kwargs: dict[str, Any]
    def __init__(self, channel: str, **kwargs: Any) -> None: ...
    def __call__(self) -> None: ...

class SetMixer(Action, DictEquality):
    mixer: str
    volume: float
    def __init__(self, mixer: str, volume: float) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

def GetMixer(mixer: str, db: bool = False) -> float: ...

class SetMute(Action, DictEquality):
    mixers: list[str]
    mute: bool
    def __init__(self, mixer: str | list[str], mute: bool) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class ToggleMute(Action, DictEquality):
    mixers: list[str]
    def __init__(self, mixer: str | list[str]) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class PauseAudio(Action, DictEquality):
    channel: str
    value: bool
    def __init__(self, channel: str, value: bool = True) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...
