from collections.abc import Sequence

from renpy.display.behavior import ActionType
from renpy.store import FieldEquality
from renpy.ui import Action

class _m1_00musicroom__MusicRoomPlay(Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    mr: MusicRoom
    filename: str
    selected: bool
    def __init__(self, mr: MusicRoom, filename: str) -> None: ...
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...
    def get_selected(self) -> bool: ...
    def periodic(self, st: float) -> float | None: ...

class _m1_00musicroom__MusicRoomRandomPlay(Action, FieldEquality):
    identity_fields: Sequence[str]
    mr: MusicRoom
    def __init__(self, mr: MusicRoom) -> None: ...
    def __call__(self) -> None: ...

class _m1_00musicroom__MusicRoomTogglePlay(Action, FieldEquality):
    identity_fields: Sequence[str]
    mr: MusicRoom
    def __init__(self, mr: MusicRoom) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class _m1_00musicroom__MusicRoomTogglePause(Action, FieldEquality):
    identity_fields: Sequence[str]
    mr: MusicRoom
    def __init__(self, mr: MusicRoom) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...
    def get_sensitive(self) -> bool: ...
    def periodic(self, st: float) -> float | None: ...

class _m1_00musicroom__MusicRoomStop(Action, FieldEquality):
    identity_fields: Sequence[str]
    mr: MusicRoom
    selected: bool
    def __init__(self, mr: MusicRoom) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...
    def periodic(self, st: float) -> float | None: ...

class MusicRoom:
    loop: bool
    loop_compat: bool
    channel: str
    fadeout: float
    fadein: float
    action: dict[str | list[str], ActionType]
    last_playing: str | list[str] | None
    playlist: list[str]
    shuffled: list[str] | None
    filenames: set[str]
    always_unlocked: set[str]
    single_track: bool
    shuffle: bool
    st: float
    def __init__(
        self,
        channel: str = "music",
        fadeout: float = 0.0,
        fadein: float = 0.0,
        loop: bool = True,
        single_track: bool = False,
        shuffle: bool = False,
        stop_action: ActionType | None = None,
    ) -> None: ...
    def periodic(self, st: float) -> None: ...
    def add(self, filename: str, always_unlocked: bool = False, action: ActionType | None = None) -> None: ...
    def is_unlocked(self, filename: str) -> bool: ...
    def unlocked_playlist(self, filename: str | None = None) -> list[str]: ...
    def play(self, filename: str | None = None, offset: int = 0, queue: bool = False) -> None: ...
    def queue_if_playing(self) -> None: ...
    def stop(self) -> None: ...
    def next(self) -> None: ...
    def previous(self) -> None: ...
    def Play(self, filename: str | None = None) -> ActionType: ...
    def RandomPlay(self) -> ActionType: ...
    def TogglePlay(self) -> ActionType: ...
    def TogglePause(self) -> ActionType: ...
    def Stop(self) -> ActionType: ...
    def Next(self) -> ActionType: ...
    def Previous(self) -> ActionType: ...
    def SetLoop(self, value: bool) -> ActionType: ...
    def SetSingleTrack(self, value: bool) -> ActionType: ...
    def SetShuffle(self, value: bool) -> ActionType: ...
    def ToggleLoop(self) -> ActionType: ...
    def ToggleSingleTrack(self) -> ActionType: ...
    def ToggleShuffle(self) -> ActionType: ...
