from typing import Any

def _joystick_select_binding() -> None: ...
def _joystick_get_binding() -> None: ...
def _joystick_take_binding(binding: str | Any, key: str) -> None: ...
def _joystick_preferences() -> None: ...
