from collections.abc import Sequence
from typing import Any

import renpy
from renpy.character import ADVCharacter

nvl_list: list[tuple[str | None, str, dict[str, Any]]] | None
nvl_variant: str | None

def _m1_00nvl_mode__s(s: str) -> renpy.style.Style: ...

class _NVLEntry(tuple): ...

def _m1_00nvl_mode__nvl_screen_dialogue() -> tuple[dict[str, Any], list[_NVLEntry], dict[str, Any]]: ...
def _m1_00nvl_mode__nvl_show_screen(screen_name: str, **scope: Any) -> renpy.display.displayable.Displayable | None: ...
def nvl_show_core(who: str | None = None, what: str | None = None, multiple: tuple[int, int] | None = None) -> None: ...
def nvl_window() -> None: ...
def nvl_show(with_: renpy.display.displayable.Displayable | None) -> None: ...
def nvl_hide(with_: renpy.display.displayable.Displayable | None, modes: bool = True) -> None: ...
def nvl_erase() -> None: ...
def nvl_clear_next() -> bool | None: ...

class NVLCharacter(ADVCharacter):
    clear: bool
    def __init__(
        self, who: str | renpy.object.Sentinel = ..., kind: NVLCharacter | None = None, **properties: Any
    ) -> None: ...
    def push_nvl_list(self, who: str | None, what: str, multiple: tuple[int, int] | None = None) -> None: ...
    def pop_nvl_list(self) -> None: ...
    def do_add(self, who: str | None, what: str, multiple: tuple[int, int] | None = None) -> None: ...
    def do_display(
        self,
        who: str | None,
        what: str,
        multiple: tuple[int, int] | None = None,
        retain: str | None = None,
        **display_args: Any,
    ) -> None: ...
    def do_done(self, who: str | None, what: str, multiple: tuple[int, int] | None = None) -> None: ...
    def do_extend(self) -> None: ...

nvl: NVLCharacter
nvl_narrator: NVLCharacter

def nvl_clear() -> None: ...
def nvl_menu(items: list[tuple[str, Any]]) -> Any | None: ...

NVLSpeaker = NVLCharacter

def _nvl_adv_callback(mode: str, old_modes: Sequence[str]) -> None: ...

_nvl_language: str | None
