from renpy.color import Color, ColorLike
from renpy.display.matrix import Matrix
from renpy.store import DictEquality

class _BaseMatrix:
    value: float
    def __init__(self, value: float = 1.0) -> None: ...
    def __call__(self, other: _BaseMatrix | None, done: float) -> Matrix: ...
    def __mul__(self, other: _BaseMatrix) -> _MultiplyMatrix: ...

class SplineMatrix(_BaseMatrix):
    matrix: _BaseMatrix
    spline: list[float]
    def __init__(self, matrix: _BaseMatrix, spline: list[float]) -> None: ...
    def __call__(self, other: _BaseMatrix | None, done: float) -> Matrix: ...

class ColorMatrix(_BaseMatrix): ...

class _MultiplyMatrix(ColorMatrix, DictEquality):
    left: _BaseMatrix
    right: _BaseMatrix
    value: float
    def __init__(self, left: _BaseMatrix, right: _BaseMatrix) -> None: ...
    def __call__(self, other: _BaseMatrix | None, done: float) -> Matrix: ...

class IdentityMatrix(ColorMatrix, DictEquality):
    def get(self, value: float) -> Matrix: ...

class SaturationMatrix(ColorMatrix, DictEquality):
    value: float
    desat: tuple[float, float, float]
    def __init__(self, value: float, desat: tuple[float, float, float] = (0.2126, 0.7152, 0.0722)) -> None: ...
    def get(self, value: float) -> Matrix: ...

class TintMatrix(ColorMatrix, DictEquality):
    color: Color
    def __init__(self, color: ColorLike) -> None: ...
    def __call__(self, other: _BaseMatrix | None, done: float) -> Matrix: ...

class BrightnessMatrix(ColorMatrix, DictEquality):
    def get(self, value: float) -> Matrix: ...

class OpacityMatrix(ColorMatrix, DictEquality):
    def get(self, value: float) -> Matrix: ...

class ContrastMatrix(ColorMatrix, DictEquality):
    def get(self, value: float) -> Matrix: ...

class ColorizeMatrix(ColorMatrix, DictEquality):
    black: Color
    white: Color
    def __init__(self, black_color: ColorLike, white_color: ColorLike) -> None: ...
    def __call__(self, other: _BaseMatrix | None, done: float) -> Matrix: ...

class HueMatrix(ColorMatrix, DictEquality):
    def get(self, value: float) -> Matrix: ...

class InvertMatrix(ColorMatrix, DictEquality):
    def get(self, value: float) -> Matrix: ...

def SepiaMatrix(
    tint: str = "#ffeec2", desat: tuple[float, float, float] = (0.2126, 0.7152, 0.0722)
) -> _MultiplyMatrix: ...
