from typing import Any

import renpy

_game_menu_screen: str | None

def _enter_menu() -> None: ...
def _invoke_game_menu() -> None: ...

_menu: bool
_load_prompt: bool
_scratch: renpy.display.displayable.Displayable | None

def _game_nav(screen: str, buttons: bool = True) -> None: ...
def _game_interact() -> bool: ...
def _render_savefile(
    index: int,
    name: str,
    filename: str,
    extra_info: str,
    screenshot: renpy.display.displayable.Displayable | None,
    mtime: int,
    newest: bool,
    clickable: bool,
    **positions: Any,
) -> None: ...
def _render_new_slot(index: int, name: str, filename: str, clickable: bool, **positions: Any) -> None: ...
def _file_picker_pages() -> list[tuple[str, str]]: ...
def _file_picker_page_files(page: str) -> list[str]: ...
def _file_picker_file_page(filename: str) -> str | None: ...
def _file_picker_process_screenshot(
    s: renpy.display.displayable.Displayable,
) -> renpy.display.displayable.Displayable: ...
def _file_picker(selected: str, save: bool) -> None: ...
def _yesno_prompt(screen: str, message: str) -> None: ...
def _quit_prompt(screen: str = "quit") -> None: ...
def _mainmenu_prompt(screen: str = "mainmenu") -> None: ...
