from collections.abc import Sequence
from typing import TYPE_CHECKING, Any, Protocol

import renpy
from renpy.store import FieldEquality
from renpy.types import DisplayableLike
from renpy.ui import Action

if TYPE_CHECKING:
    class GalleryCondition(Protocol):
        def check(self, all_prior: bool) -> bool: ...

class _m1_00gallery__GalleryAllPriorCondition(GalleryCondition):
    def check(self, all_prior: bool) -> bool: ...

class _m1_00gallery__GalleryArbitraryCondition(GalleryCondition):
    condition: str
    def __init__(self, condition: str) -> None: ...
    def check(self, all_prior: bool) -> bool: ...

class _m1_00gallery__GalleryUnlockCondition(GalleryCondition):
    images: Sequence[str | tuple[str]]
    def __init__(self, images: Sequence[str | tuple[str]]) -> None: ...
    def check(self, all_prior: bool) -> bool: ...

class _m1_00gallery__GalleryImage:
    show_properties: dict[str, Any] | None
    movie: bool
    gallery: Gallery
    conditions: list[GalleryCondition]
    displayables: tuple[DisplayableLike, ...]
    transforms: list[renpy.display.transform.Transform | None]
    def __init__(
        self, gallery: Gallery, displayables: tuple[DisplayableLike, ...], movie: bool = False, **properties: Any
    ) -> None: ...
    def check_unlock(self, all_prior: bool) -> bool: ...
    def show(self, locked: bool, index: int, count: int, first: bool) -> Any | None: ...

class _m1_00gallery__GalleryButton:
    gallery: Gallery
    images: list[_m1_00gallery__GalleryImage]
    conditions: list[GalleryCondition]
    index: int
    def __init__(self, gallery: Gallery, index: int) -> None: ...
    def check_unlock(self) -> bool: ...

class _m1_00gallery__GalleryToggleSlideshow(Action, FieldEquality):
    identity_fields: Sequence[str]
    gallery: Gallery
    def __init__(self, gallery: Gallery) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class _m1_00gallery__GalleryAction(Action, FieldEquality):
    identity_fields: Sequence[str]
    equality_fields: Sequence[str]
    gallery: Gallery
    index: int
    def __init__(self, gallery: Gallery, index: int) -> None: ...
    def __call__(self) -> None: ...

class Gallery:
    transition: renpy.display.transition.TransitionFunction | None
    hover_border: DisplayableLike | None
    idle_border: DisplayableLike | None
    locked_button: DisplayableLike | None
    image_screen: str
    buttons: dict[str, _m1_00gallery__GalleryButton]
    button_list: list[_m1_00gallery__GalleryButton]
    button_: _m1_00gallery__GalleryButton | None
    image_: _m1_00gallery__GalleryImage | None
    unlockable: _m1_00gallery__GalleryImage | _m1_00gallery__GalleryButton | None
    unlocked_advance: bool
    navigation: bool
    span_buttons: bool
    slideshow_delay: int
    slideshow: bool
    def __init__(self) -> None: ...
    def button(self, name: str) -> None: ...
    def image(self, *displayables: DisplayableLike, **properties: Any) -> None: ...
    display = image
    def transform(self, *transforms: renpy.display.transform.Transform | None) -> None: ...
    def unlock(self, *images: str) -> None: ...
    def condition(self, expression: str) -> None: ...
    def allprior(self) -> None: ...
    def unlock_image(self, *images: str, **properties: Any) -> None: ...
    def Action(self, name: str) -> _m1_00gallery__GalleryAction | None: ...
    def make_button(
        self,
        name: str,
        unlocked: DisplayableLike,
        locked: DisplayableLike | None = None,
        hover_border: DisplayableLike | None = None,
        idle_border: DisplayableLike | None = None,
        style: str | None = None,
        **properties: Any,
    ) -> renpy.display.behavior.Button: ...
    def get_fraction(self, name: str | None, format: str = "{seen}/{total}") -> str: ...
    def show(self, button: int = 0, image: int = 0) -> None: ...
    def Return(self) -> renpy.curry.Partial[str]: ...
    def Next(self, unlocked: bool = False) -> renpy.curry.Partial[str]: ...
    def Previous(self, unlocked: bool = False) -> renpy.curry.Partial[str]: ...
    def ToggleSlideshow(self) -> _m1_00gallery__GalleryToggleSlideshow: ...
