from collections import OrderedDict, defaultdict
from collections.abc import Callable
from reprlib import Repr
from typing import Any, dict_items, dict_keys, dict_values

import renpy
from renpy.lexer import Lexer
from renpy.rollback import NoRollback

class PrettyRepr(Repr):
    _ellipsis: str
    def _repr_bytes(self, x: bytes, level: int) -> str: ...
    def _repr_string(self, x: str, level: int) -> str: ...
    repr_bytes = _repr_bytes
    repr_str = _repr_string
    def repr_tuple(self, x: tuple, level: int) -> str: ...
    def repr_list(self, x: list, level: int) -> str: ...
    repr_RevertableList = repr_list
    def repr_set(self, x: set, level: int) -> str: ...
    repr_RevertableSet = repr_set
    def repr_frozenset(self, x: frozenset, level: int) -> str: ...
    def repr_dict(self, x: dict, level: int) -> str: ...
    repr_RevertableDict = repr_dict
    def repr_defaultdict(self, x: defaultdict, level: int) -> str: ...
    def repr_OrderedDict(self, x: OrderedDict, level: int) -> str: ...
    def repr_dict_keys(self, x: dict_keys, level: int) -> str: ...
    def repr_dict_values(self, x: dict_values, level: int) -> str: ...
    def repr_dict_items(self, x: dict_items, level: int) -> str: ...
    class _PrettyDictItem:
        key: Any
        value: Any
        def __init__(self, key: Any, value: Any) -> None: ...

    def repr__PrettyDictItem(self, x: _PrettyDictItem, level: int) -> str: ...
    def _make_pretty_items(self, x: dict, iter_keys, left: str, right: str) -> list[Any]: ...
    def _repr_iterable(self, iter_x: Any, level: int, left: str, right: str) -> str: ...
    def _to_shorted_list(self, x: list, maxlen: int, sort: bool = False) -> list[Any]: ...
    def repr_Matrix(self, x: renpy.display.matrix.Matrix, level: int) -> str: ...

aRepr: PrettyRepr
traced_aRepr: PrettyRepr

class TracedExpressionsList(NoRollback, list): ...

class BoundedList[T](list[T]):
    size: int
    lines: int | None
    def __init__(self, size: int, lines: int | None = None) -> None: ...
    def append(self, value: T) -> None: ...
    def clear(self) -> None: ...

class ConsoleHistoryEntry:
    lines: int
    command: str | None
    result: str | None
    is_error: bool
    def __init__(self, command: str | None, result: str | None = None, is_error: bool = False) -> None: ...
    def update_lines(self) -> None: ...

HistoryEntry = ConsoleHistoryEntry
stdio_lines: list[tuple[bool, str]]

def _strip_ansi(s: str) -> str: ...
def stdout_line(l: Lexer) -> None: ...
def stderr_line(l: Lexer) -> None: ...

class ScriptErrorHandler:
    target_depth: int
    def __init__(self) -> None: ...
    def __call__(self, traceback_exception: renpy.error.TracebackException) -> None: ...

class DebugConsole:
    history: BoundedList[ConsoleHistoryEntry]
    line_history: BoundedList[list[str]]
    line_index: int
    first_time: bool
    did_short_warning: bool
    def __init__(self) -> None: ...
    def backup(self) -> None: ...
    def start(self) -> None: ...
    lines: list[str]
    def reset(self) -> None: ...
    def recall_line(self, offset: int) -> None: ...
    def older(self) -> None: ...
    def newer(self) -> None: ...
    def interact(self) -> str | None: ...
    def show_stdio(self) -> None: ...
    def can_renpy(self) -> bool: ...
    def format_exception_only(self, e: BaseException) -> Any: ...
    def format_exception(self, e: BaseException) -> Any: ...
    def run(self, lines: str | list[str]) -> None: ...

console: DebugConsole

def enter() -> None: ...
def command[T: Callable](help: str | None = None) -> Callable[[T], T]: ...
@command()
def help(l: Lexer, doc_generate: bool = False) -> str: ...
@command()
def halp(l: Lexer) -> str: ...
@command()
def clear(l: Lexer) -> None: ...
@command()
def exit(l: Lexer) -> None: ...
@command()
def quit(l: Lexer) -> None: ...
@command()
def stack(l: Lexer) -> None: ...
@command()
def load(l: Lexer) -> None: ...
@command()
def save(l: Lexer) -> str: ...
@command()
def reload(l: Lexer) -> None: ...
@command()
def R(l: Lexer) -> None: ...
@command()
def watch(l: Lexer) -> None: ...
def renpy_watch(expr: str) -> None: ...
@command()
def unwatch(l: Lexer) -> None: ...
def watch_after_load() -> None: ...
def renpy_unwatch(expr: str) -> None: ...
@command()
def unwatchall(l: Lexer) -> None: ...
def renpy_unwatchall() -> None: ...
@command()
def jump(l: Lexer) -> None: ...
@command()
def short(l: Lexer) -> None: ...
@command()
def long(l: Lexer) -> None: ...
@command()
def escape(l: Lexer) -> None: ...
@command()
def unescape(l: Lexer) -> None: ...

traced_expressions: TracedExpressionsList
