from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

def check_missing_functions(required: Incomplete) -> None: ...
def clear_missing_functions() -> None: ...
def load() -> None: ...
