from renpy.atl import atl_warper, instant as instant, pause as pause

_constant: bool

@atl_warper
def linear(t: float) -> float: ...
@atl_warper
def easeout(x: float) -> float: ...
@atl_warper
def easein(x: float) -> float: ...
@atl_warper
def ease(x: float) -> float: ...
@atl_warper
def easeout_quad(t: float) -> float: ...
@atl_warper
def easein_quad(t: float) -> float: ...
@atl_warper
def ease_quad(t: float) -> float: ...
@atl_warper
def easeout_cubic(t: float) -> float: ...
@atl_warper
def easein_cubic(t: float) -> float: ...
@atl_warper
def ease_cubic(t: float) -> float: ...
@atl_warper
def easeout_quart(t: float) -> float: ...
@atl_warper
def easein_quart(t: float) -> float: ...
@atl_warper
def ease_quart(t: float) -> float: ...
@atl_warper
def easeout_quint(t: float) -> float: ...
@atl_warper
def easein_quint(t: float) -> float: ...
@atl_warper
def ease_quint(t: float) -> float: ...
@atl_warper
def easeout_expo(t: float) -> float: ...
@atl_warper
def easein_expo(t: float) -> float: ...
@atl_warper
def ease_expo(t: float) -> float: ...
@atl_warper
def easeout_circ(t: float) -> float: ...
@atl_warper
def easein_circ(t: float) -> float: ...
@atl_warper
def ease_circ(t: float) -> float: ...
@atl_warper
def easeout_back(t: float) -> float: ...
@atl_warper
def easein_back(t: float) -> float: ...
@atl_warper
def ease_back(t: float) -> float: ...
@atl_warper
def easein_elastic(t: float) -> float: ...
@atl_warper
def easeout_elastic(t: float) -> float: ...
@atl_warper
def ease_elastic(t: float) -> float: ...
@atl_warper
def easein_bounce(t: float) -> float: ...
@atl_warper
def easeout_bounce(t: float) -> float: ...
@atl_warper
def ease_bounce(t: float) -> float: ...
