from _typeshed import Incomplete
from renpy.minstore import _dict, _object

class _JSONDBDict(_dict):
    changed: bool
    dirty: bool
    def __init__(self, *args, **kwargs) -> None: ...
    def check(self, value) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def clear(self) -> None: ...
    def setdefault(self, key, default=None): ...
    def update(self, *args, **kwargs) -> None: ...
    def __ior__(self, other): ...

class JSONDB(_object):
    fn: Incomplete
    data: Incomplete
    dirty: bool
    default: Incomplete
    def __init__(self, filename, default=None) -> None: ...
    def save(self) -> None: ...
    def __getitem__(self, key): ...
    def __delitem__(self, key) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __iter__(self): ...
    def __reversed__(self): ...
    def values(self): ...
    def keys(self): ...
    def items(self): ...
    def __len__(self) -> int: ...
    @property
    def dialogue(self): ...
