from _typeshed import Incomplete as Incomplete
from renpy.minstore import _dict, _object

class _JSONDBDict(_dict):
    changed: bool
    dirty: bool
    def __init__(self, *args, **kwargs) -> None: ...
    def check(self, value: Incomplete) -> None: ...
    def __setitem__(self, key: Incomplete, value: Incomplete) -> None: ...
    def __delitem__(self, key: Incomplete) -> None: ...
    def clear(self) -> None: ...
    def setdefault(self, key: Incomplete, default: Incomplete = None) -> Incomplete: ...
    def update(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def __ior__(self, other: Incomplete) -> Incomplete: ...

class JSONDB(_object):
    fn: Incomplete
    data: Incomplete
    dirty: bool
    default: Incomplete
    def __init__(self, filename: Incomplete, default: Incomplete = None) -> None: ...
    def save(self) -> None: ...
    def __getitem__(self, key: Incomplete) -> Incomplete: ...
    def __delitem__(self, key: Incomplete) -> None: ...
    def __setitem__(self, key: Incomplete, value: Incomplete) -> None: ...
    def __iter__(self) -> Incomplete: ...
    def __reversed__(self) -> Incomplete: ...
    def values(self) -> Incomplete: ...
    def keys(self) -> Incomplete: ...
    def items(self) -> Incomplete: ...
    def __len__(self) -> int: ...
    @property
    def dialogue(self) -> Incomplete: ...
