from renpy.pygame.error import *
from renpy.pygame.locals import *
from typing import Callable

init_functions: list[Callable[[], None]]
quit_functions: list[Callable[[], None]]

def register_init(fn): ...
def register_quit(fn): ...
def init(): ...
def quit() -> None: ...
def import_as_pygame() -> None: ...
def get_sdl_byteorder(): ...
def get_sdl_version(): ...
def get_platform() -> str: ...

HAVE_NEWBUF: bool
