from renpy.pygame.error import *
from renpy.pygame.locals import *
from typing import Callable
from _typeshed import Incomplete as Incomplete

init_functions: list[Callable[[], None]]
quit_functions: list[Callable[[], None]]

def register_init(fn: Incomplete) -> Incomplete: ...
def register_quit(fn: Incomplete) -> Incomplete: ...
def init() -> Incomplete: ...
def quit() -> None: ...
def import_as_pygame() -> None: ...
def get_sdl_byteorder() -> Incomplete: ...
def get_sdl_version() -> Incomplete: ...
def get_platform() -> str: ...

HAVE_NEWBUF: bool

# Generated by scripts/relative_imports.py, do not edit below this line.
from . import color as color
from . import controller as controller
from . import display as display
from . import draw as draw
from . import error as error
from . import event as event
from . import gfxdraw as gfxdraw
from . import image as image
from . import joystick as joystick
from . import key as key
from . import locals as locals
from . import mouse as mouse
from . import power as power
from . import pygame_time as pygame_time
from . import rect as rect
from . import rwobject as rwobject
from . import scrap as scrap
from . import surface as surface
from . import sysfont as sysfont
from . import time as time
from . import transform as transform
from . import version as version
