from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

class Color:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __delitem__(self, key: Incomplete) -> None: ...
    def __div__(self, rhs: Color) -> Incomplete: ...
    def __eq__(self, value: object) -> bool: ...
    def __float__(self) -> float: ...
    def __ge__(self, value: object) -> bool: ...
    def __getitem__(self, key: Incomplete) -> None: ...
    def __gt__(self, value: object) -> bool: ...
    def __hex__(self) -> None: ...
    def __int__(self) -> int: ...
    def __le__(self, value: object) -> bool: ...
    def __len__(self) -> int: ...
    def __lt__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...
    def __oct__(self) -> None: ...
    def __radd__(self, value: Incomplete) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def __rfloordiv__(self, value: Incomplete) -> None: ...
    def __rmod__(self, value: Incomplete) -> None: ...
    def __rmul__(self, value: Incomplete) -> None: ...
    def __rsub__(self, value: Incomplete) -> None: ...
    def __setitem__(self, key: Incomplete, value: Incomplete) -> None: ...
    def correct_gamma(self, gamma: Incomplete) -> None: ...
    def normalize(self) -> None: ...
    def set_length(self, n: Incomplete) -> None: ...
