from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete
from renpy.color import ColorLike

class Color:
    cmy: tuple[float, float, float]
    hsva: tuple[float, float, float, float]
    hsla: tuple[float, float, float, float]
    i1i2i3: tuple[float, float, float]
    r: int
    g: int
    b: int
    a: int

    def __init__(self, *args: ColorLike) -> None: ...
    def __delitem__(self, key: Incomplete) -> None: ...
    def __div__(self, rhs: Color) -> Incomplete: ...
    def __eq__(self, value: object) -> bool: ...
    def __float__(self) -> float: ...
    def __ge__(self, value: object) -> bool: ...
    def __getitem__(self, key: Incomplete) -> None: ...
    def __gt__(self, value: object) -> bool: ...
    def __hex__(self) -> None: ...
    def __int__(self) -> int: ...
    def __le__(self, value: object) -> bool: ...
    def __len__(self) -> int: ...
    def __lt__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...
    def __oct__(self) -> None: ...
    def __radd__(self, value: Incomplete) -> None: ...
    def __rfloordiv__(self, value: Incomplete) -> None: ...
    def __rmod__(self, value: Incomplete) -> None: ...
    def __rmul__(self, value: Incomplete) -> None: ...
    def __rsub__(self, value: Incomplete) -> None: ...
    def __setitem__(self, key: Incomplete, value: Incomplete) -> None: ...
    def correct_gamma(self, gamma: float) -> tuple[int, int, int, int]: ...
    def normalize(self) -> tuple[float, float, float, float]: ...
    def set_length(self, n: int) -> None: ...
