from _frozen_importlib import BuiltinImporter as BuiltinImporter

class Color:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __div__(self, rhs: Color): ...
    def __eq__(self, value): ...
    def __float__(self) -> float: ...
    def __ge__(self, value): ...
    def __getitem__(self, key) -> None: ...
    def __gt__(self, value): ...
    def __hex__(self) -> None: ...
    def __int__(self) -> int: ...
    def __le__(self, value): ...
    def __len__(self) -> int: ...
    def __lt__(self, value): ...
    def __ne__(self, value): ...
    def __oct__(self) -> None: ...
    def __radd__(self, value) -> None: ...
    def __reduce__(self) -> None: ...
    def __rfloordiv__(self, value) -> None: ...
    def __rmod__(self, value) -> None: ...
    def __rmul__(self, value) -> None: ...
    def __rsub__(self, value) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def correct_gamma(self, gamma) -> None: ...
    def normalize(self) -> None: ...
    def set_length(self, n) -> None: ...
