import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter

class Controller:
    def __init__(self, index) -> None: ...
    def __reduce__(self) -> None: ...
    def get_axis(self, axis) -> None: ...
    def get_button(self, button) -> None: ...
    def get_guid_string(self) -> None: ...
    def get_init(self) -> None: ...
    def get_name(self) -> None: ...
    def init(self) -> None: ...
    def is_controller(self) -> None: ...
    def quit(self) -> None: ...

def add_mapping(mapping) -> None: ...
def add_mappings(mapping_file) -> None: ...

error = renpy.pygame.error.error

def get_axis_from_string(name) -> None: ...
def get_button_from_string(name) -> None: ...
def get_count() -> None: ...
def get_init() -> None: ...
def get_string_for_axis(axis) -> None: ...
def get_string_for_button(button) -> None: ...
def init() -> None: ...
def quit() -> None: ...
def register_init(fn) -> None: ...
def register_quit(fn) -> None: ...
