import renpy

class Controller:
    def __init__(self, index): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...
    def get_axis(self, axis): ...
    def get_button(self, button): ...
    def get_guid_string(self): ...
    def get_init(self): ...
    def get_name(self): ...
    def init(self): ...
    def is_controller(self): ...
    def quit(self): ...

def add_mapping(mapping): ...
def add_mappings(mapping_file): ...

error = renpy.pygame.error.error

def get_axis_from_string(name): ...
def get_button_from_string(name): ...
def get_count(): ...
def get_init(): ...
def get_string_for_axis(axis): ...
def get_string_for_button(button): ...
def init(): ...
def quit(): ...
def register_init(fn): ...
def register_quit(fn): ...
