import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete
from typing import Literal

class Controller:
    def __init__(self, index) -> None: ...
    def __reduce__(self) -> None: ...
    def get_axis(self, axis: int) -> int: ...
    def get_button(self, button: int) -> Literal[0, 1]: ...
    def get_guid_string(self) -> str: ...
    def get_init(self) -> bool: ...
    def get_name(self) -> str: ...
    def init(self) -> None: ...
    def is_controller(self) -> bool: ...
    def quit(self) -> None: ...

def add_mapping(mapping: str) -> None: ...
def add_mappings(mapping_file: Incomplete) -> None: ...

error = renpy.pygame.error.error

def get_axis_from_string(name: str) -> int: ...
def get_button_from_string(name: str) -> int: ...
def get_count() -> int: ...
def get_init() -> bool: ...
def get_string_for_axis(axis: int) -> str | None: ...
def get_string_for_button(button: int) -> str | None: ...
def init() -> None: ...
def quit() -> None: ...
def register_init(fn) -> None: ...
def register_quit(fn) -> None: ...
