import renpy

class Info:
    def __init__(
        self,
    ): ...
    def __repr__(self): ...

class Window:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...
    def create_surface(self): ...
    def destroy(self): ...
    def flip(self): ...
    def get_active(self): ...
    def get_drawable_size(self): ...
    def get_position(self): ...
    def get_sdl_window_pointer(self): ...
    def get_size(self): ...
    def get_surface(self): ...
    def get_window_flags(self): ...
    def get_wm_info(self): ...
    def iconify(self): ...
    def maximize(self): ...
    def minimize(self): ...
    def proxy_window_surface(self): ...
    def recreate_gl_context(self, always=False): ...
    def resize(self, size, opengl=False, fullscreen=None, maximized=None): ...
    def restore(self): ...
    def set_caption(self, title): ...
    def set_gamma(self, red, green=None, blue=None): ...
    def set_gamma_ramp(self, red, green, blue): ...
    def set_icon(self, surface: "Surface"): ...
    def set_position(self, pos): ...
    def toggle_fullscreen(self): ...
    def update(self, rectangles=None): ...

def _get_hint(hint, default): ...
def destroy(): ...

error = renpy.pygame.error.error

def flip(): ...
def get_active(): ...
def get_caption(): ...
def get_display_bounds(index): ...
def get_drawable_size(): ...
def get_driver(): ...
def get_init(): ...
def get_num_video_displays(): ...
def get_platform(): ...
def get_position(): ...
def get_size(): ...
def get_surface(): ...
def get_window(): ...
def get_wm_info(): ...
def gl_get_attribute(flag): ...
def gl_load_library(path): ...
def gl_reset_attributes(): ...
def gl_set_attribute(flag, value): ...
def gl_unload_library(): ...
def hint(hint, value, priority=1): ...
def iconify(): ...
def init(): ...
def list_modes(depth=0, flags=0, display=0): ...
def mode_ok(size, flags=0, depth=0): ...
def quit(): ...
def register_init(fn): ...
def register_quit(fn): ...
def sdl_main_init(): ...
def set_caption(title, icontitle=None): ...
def set_gamma(red, green=None, blue=None): ...
def set_gamma_ramp(red, green, blue): ...
def set_icon(surface): ...
def set_mode(resolution=(0, 0), flags=0, depth=0, pos=(SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED)): ...
def set_position(pos): ...
def set_screensaver(state): ...
def toggle_fullscreen(): ...
def update(rectangles=None): ...

GL_SWAP_CONTROL: int
SRCALPHA: int
default_swap_control: int
init_done: int
ios: int
main_done: int
