from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete
import ctypes
from typing import Any
from renpy.pygame.surface import Surface as Surface

class Info:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

class Window:
    surface: Surface
    def __init__(
        self,
        title: str,
        resolution: tuple[int, int] = (0, 0),
        flags: int = 0,
        depth: int = 0,
        pos: tuple[int, int] = (SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED),
        shape: Surface | None = None,
    ) -> None: ...
    def create_surface(self) -> None: ...
    def destroy(self) -> None: ...
    def flip(self) -> None: ...
    def get_active(self) -> bool: ...
    def get_drawable_size(self) -> tuple[int, int]: ...
    def get_position(self) -> tuple[int, int]: ...
    def get_sdl_window_pointer(self) -> ctypes.c_void_p: ...
    def get_size(self) -> tuple[int, int]: ...
    def get_surface(self) -> Surface | None: ...
    def get_window_flags(self) -> int: ...
    def get_wm_info(self) -> dict: ...
    def iconify(self) -> bool: ...
    def maximize(self) -> None: ...
    def minimize(self) -> None: ...
    def proxy_window_surface(self) -> None: ...
    def recreate_gl_context(self, always: bool = False) -> bool: ...
    def resize(
        self, size: tuple[int, int], opengl: bool = False, fullscreen: bool | None = None, maximized: bool | None = None
    ) -> None: ...
    def restore(self) -> None: ...
    def set_caption(self, title: str | bytes) -> None: ...
    def set_gamma(self, red: float, green: float | None = None, blue: float | None = None) -> bool: ...
    def set_gamma_ramp(self, red: list[int], green: list[int], blue: list[int]) -> bool: ...
    def set_icon(self, surface: Surface) -> None: ...
    def set_position(self, pos: tuple[int, int]) -> None: ...
    def toggle_fullscreen(self) -> bool: ...
    def update(self, rectangles: tuple[int, int, int, int] | list[tuple[int, int, int, int]] | None = None) -> None: ...

def _get_hint(hint: str, default: str) -> str: ...
def destroy() -> None: ...
def flip() -> None: ...
def get_active() -> bool: ...
def get_caption() -> str | bytes: ...
def get_display_bounds(index: int) -> tuple[int, int, int, int]: ...
def get_drawable_size() -> tuple[int, int]: ...
def get_driver() -> str: ...
def get_init() -> bool: ...
def get_num_video_displays() -> int: ...
def get_platform() -> str: ...
def get_position() -> tuple[int, int]: ...
def get_size() -> tuple[int, int] | None: ...
def get_surface() -> Surface | None: ...
def get_window() -> Window | None: ...
def get_wm_info() -> dict: ...
def gl_get_attribute(flag: int) -> int: ...
def gl_load_library(path: str) -> None: ...
def gl_reset_attributes() -> None: ...
def gl_set_attribute(flag: int, value: int) -> None: ...
def gl_unload_library() -> None: ...
def hint(hint: str | bytes, value: str | bytes, priority: int = 1) -> None: ...
def iconify() -> bool: ...
def init() -> None: ...
def list_modes(depth: int = 0, flags: int = 0, display: int = 0) -> list[tuple[int, int]]: ...
def mode_ok(size: tuple[int, int], flags: int = 0, depth: int = 0) -> bool: ...
def quit() -> None: ...
def sdl_main_init() -> None: ...
def set_caption(title: str | bytes, icontitle: None = None) -> None: ...
def set_gamma(red: float, green: float | None = None, blue: float | None = None) -> bool: ...
def set_gamma_ramp(red: list[int], green: list[int], blue: list[int]) -> bool: ...
def set_icon(surface: Surface) -> None: ...
def set_mode(
    resolution: tuple[int, int] = (0, 0),
    flags: int = 0,
    depth: int = 0,
    pos: tuple[int, int] = (0x1FFF0000, 0x1FFF0000),
) -> None: ...
def set_position(pos: tuple[int, int]) -> None: ...
def set_screensaver(state: bool) -> None: ...
def toggle_fullscreen() -> bool: ...
def update(rectangles: tuple[int, int, int, int] | list[tuple[int, int, int, int]] | None = None) -> None: ...

GL_SWAP_CONTROL: int
SRCALPHA: int
default_swap_control: int
init_done: int
ios: int
main_done: int
