from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete

class Info:
    def __init__(self) -> None: ...

class Window:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def create_surface(self) -> None: ...
    def destroy(self) -> None: ...
    def flip(self) -> None: ...
    def get_active(self) -> None: ...
    def get_drawable_size(self) -> None: ...
    def get_position(self) -> None: ...
    def get_sdl_window_pointer(self) -> None: ...
    def get_size(self) -> None: ...
    def get_surface(self) -> None: ...
    def get_window_flags(self) -> None: ...
    def get_wm_info(self) -> None: ...
    def iconify(self) -> None: ...
    def maximize(self) -> None: ...
    def minimize(self) -> None: ...
    def proxy_window_surface(self) -> None: ...
    def recreate_gl_context(self, always: bool = False) -> None: ...
    def resize(self, size, opengl: bool = False, fullscreen=None, maximized=None) -> None: ...
    def restore(self) -> None: ...
    def set_caption(self, title) -> None: ...
    def set_gamma(self, red, green=None, blue=None) -> None: ...
    def set_gamma_ramp(self, red, green, blue) -> None: ...
    def set_icon(self, surface: Surface): ...
    def set_position(self, pos) -> None: ...
    def toggle_fullscreen(self) -> None: ...
    def update(self, rectangles=None) -> None: ...

def destroy() -> None: ...

error: Incomplete

def flip() -> None: ...
def get_active() -> None: ...
def get_caption() -> None: ...
def get_display_bounds(index) -> None: ...
def get_drawable_size() -> None: ...
def get_driver() -> None: ...
def get_init() -> None: ...
def get_num_video_displays() -> None: ...
def get_platform() -> None: ...
def get_position() -> None: ...
def get_size() -> None: ...
def get_surface() -> None: ...
def get_window() -> None: ...
def get_wm_info() -> None: ...
def gl_get_attribute(flag) -> None: ...
def gl_load_library(path) -> None: ...
def gl_reset_attributes() -> None: ...
def gl_set_attribute(flag, value) -> None: ...
def gl_unload_library() -> None: ...
def hint(hint, value, priority: int = 1) -> None: ...
def iconify() -> None: ...
def init() -> None: ...
def list_modes(depth: int = 0, flags: int = 0, display: int = 0) -> None: ...
def mode_ok(size, flags: int = 0, depth: int = 0) -> None: ...
def quit() -> None: ...
def register_init(fn) -> None: ...
def register_quit(fn) -> None: ...
def sdl_main_init() -> None: ...
def set_caption(title, icontitle=None) -> None: ...
def set_gamma(red, green=None, blue=None) -> None: ...
def set_gamma_ramp(red, green, blue) -> None: ...
def set_icon(surface) -> None: ...
def set_mode(resolution=(0, 0), flags: int = 0, depth: int = 0, pos=...) -> None: ...
def set_position(pos) -> None: ...
def set_screensaver(state) -> None: ...
def toggle_fullscreen() -> None: ...
def update(rectangles=None) -> None: ...

GL_SWAP_CONTROL: int
SRCALPHA: int
default_swap_control: int
init_done: int
ios: int
main_done: int
