import renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete

Rect = renpy.pygame.rect.Rect

def aaline(surface: Surface, color, startpos, endpos, blend: int = 1): ...
def aalines(surface: Surface, color, closed, pointlist, blend: int = 1): ...
def arc(surface: Surface, color, rect, start_angle, stop_angle, width: int = 1): ...
def circle(surface: Surface, color, pos, radius, width: int = 0): ...
def ellipse(surface: Surface, color, rect, width: int = 0): ...

error: Incomplete

def line(surface: Surface, color, start_pos, end_pos, width: int = 1): ...
def lines(surface: Surface, color, closed, pointlist, width: int = 1): ...
def polygon(surface: Surface, color, pointlist, width: int = 0): ...
def rect(surface: Surface, color, rect, width: int = 0): ...
