import renpy

Rect = renpy.pygame.rect.Rect

def aaline(surface: "Surface", color, startpos, endpos, blend=1): ...
def aalines(surface: "Surface", color, closed, pointlist, blend=1): ...
def arc(surface: "Surface", color, rect, start_angle, stop_angle, width=1): ...
def circle(surface: "Surface", color, pos, radius, width=0): ...
def ellipse(surface: "Surface", color, rect, width=0): ...

error = renpy.pygame.error.error

def line(surface: "Surface", color, start_pos, end_pos, width=1): ...
def lines(surface: "Surface", color, closed, pointlist, width=1): ...
def polygon(surface: "Surface", color, pointlist, width=0): ...
def rect(surface: "Surface", color, rect, width=0): ...
