from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

class error(RuntimeError):
    def __init__(self, message: Incomplete = None) -> None: ...

def get_error() -> None: ...
def set_error(message: Incomplete) -> None: ...
