from _frozen_importlib import BuiltinImporter as BuiltinImporter

class error(RuntimeError):
    def __init__(self, message=None) -> None: ...

def get_error() -> None: ...
def set_error(message) -> None: ...
