from _frozen_importlib import BuiltinImporter as BuiltinImporter

class error(RuntimeError):
    def __init__(self, message: str | None = None) -> None: ...

def get_error() -> None: ...
def set_error(message: str) -> None: ...
