from _frozen_importlib import BuiltinImporter as BuiltinImporter

Event = EventType

class EventType:
    def __init__(self, type: int, dict=None, **kwargs) -> None: ...
    @property
    def dict(self): ...
    @property
    def type(self) -> int: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __nonzero__(self) -> None: ...
    def __repr__(self) -> str: ...

def clear(t=None) -> None: ...
def copy_event_queue() -> None: ...
def event_name(t) -> None: ...
def get(t=None) -> list[EventType]: ...
def get_blocked(t) -> None: ...
def get_grab() -> None: ...
def get_mousewheel_buttons() -> None: ...
def get_standard_events() -> list[int]: ...
def init() -> None: ...
def peek(t=None) -> None: ...
def poll() -> EventType: ...
def post(e: EventType) -> None: ...
def pump() -> None: ...
def register(name: str) -> int: ...
def set_allowed(t=None) -> None: ...
def set_blocked(t=None) -> None: ...
def set_grab(on) -> None: ...
def set_mousewheel_buttons(flag) -> None: ...
def unichr(i, /) -> None: ...
def wait() -> EventType: ...

ACTIVEEVENT: int
USEREVENT_MAX: int
VIDEOEXPOSE: int
VIDEORESIZE: int
WINDOWMOVED: int
