Event = EventType

class EventType:
    def __init__(self, type, dict=None, **kwargs): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __nonzero__(self): ...
    def __repr__(self): ...

def clear(t=None): ...
def copy_event_queue(): ...
def event_name(t): ...
def get(t=None): ...
def get_blocked(t): ...
def get_grab(): ...
def get_mousewheel_buttons(): ...
def get_standard_events(): ...
def init(): ...
def peek(t=None): ...
def poll(): ...
def post(e): ...
def pump(): ...
def register(name): ...
def set_allowed(t=None): ...
def set_blocked(t=None): ...
def set_grab(on): ...
def set_mousewheel_buttons(flag): ...
def unichr(i, /): ...
def wait(): ...

ACTIVEEVENT: int
USEREVENT_MAX: int
VIDEOEXPOSE: int
VIDEORESIZE: int
WINDOWMOVED: int
