from _frozen_importlib import BuiltinImporter as BuiltinImporter
from typing import Any, Iterable

Event = EventType

class EventType:
    _type = int
    def __init__(self, type: int, dict: dict[str, Any] | None = None, **kwargs) -> None: ...
    @property
    def dict(self) -> dict[str, Any]: ...
    @property
    def type(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __nonzero__(self) -> bool: ...
    def __repr__(self) -> str: ...

def clear(t: int | Iterable[int] | None = None) -> None: ...
def copy_event_queue() -> list[EventType]: ...
def event_name(t: int) -> str: ...
def get(t: int | Iterable[int] | None = None) -> list[EventType]: ...
def get_blocked(t: int) -> bool: ...
def get_grab() -> bool: ...
def get_mousewheel_buttons() -> bool: ...
def get_standard_events() -> list[int]: ...
def init() -> None: ...
def peek(t: int | Iterable[int] | None = None) -> bool: ...
def poll() -> EventType: ...
def post(e: EventType) -> None: ...
def pump() -> None: ...
def register(name: str) -> int: ...
def set_allowed(t: int | Iterable[int] | None = None) -> None: ...
def set_blocked(t: int | Iterable[int] | None = None) -> None: ...
def set_grab(on: bool) -> None: ...
def set_mousewheel_buttons(flag: bool) -> None: ...
def unichr(i: int) -> str: ...
def wait() -> EventType: ...

ACTIVEEVENT: int
USEREVENT_MAX: int
VIDEOEXPOSE: int
VIDEORESIZE: int
WINDOWMOVED: int
