import renpy

Rect = renpy.pygame.rect.Rect

def aacircle(surface: "Surface", x, y, r, color): ...
def aaellipse(surface: "Surface", x, y, rx, ry, color): ...
def aaline(surface: "Surface", x1, y1, x2, y2, color): ...
def aapolygon(surface: "Surface", points, color): ...
def aatrigon(surface: "Surface", x1, y1, x2, y2, x3, y3, color): ...
def arc(surface: "Surface", x, y, r, start, end, color): ...
def bezier(surface: "Surface", points, steps, color): ...
def box(surface: "Surface", rect, color): ...
def circle(surface: "Surface", x, y, r, color): ...
def ellipse(surface: "Surface", x, y, rx, ry, color): ...

error = renpy.pygame.error.error

def filled_circle(surface: "Surface", x, y, r, color): ...
def filled_ellipse(surface: "Surface", x, y, rx, ry, color): ...
def filled_pie(surface: "Surface", x, y, r, start, end, color): ...
def filled_polygon(surface: "Surface", points, color): ...
def filled_trigon(surface: "Surface", x1, y1, x2, y2, x3, y3, color): ...
def hline(surface: "Surface", x1, x2, y, color): ...
def line(surface: "Surface", x1, y1, x2, y2, color): ...
def pie(surface: "Surface", x, y, r, start, end, color): ...
def pixel(surface: "Surface", x, y, color): ...
def polygon(surface: "Surface", points, color): ...
def rectangle(surface: "Surface", rect, color): ...
def rounded_box(surface: "Surface", rect, rad, color): ...
def rounded_rectangle(surface: "Surface", rect, rad, color): ...
def textured_polygon(surface: "Surface", points, texture: "Surface", tx, ty): ...
def thick_line(surface: "Surface", x1, y1, x2, y2, width, color): ...
def trigon(surface: "Surface", x1, y1, x2, y2, x3, y3, color): ...
def vline(surface: "Surface", x, y1, y2, color): ...
