import renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete

Rect = renpy.pygame.rect.Rect

def aacircle(surface: Surface, x, y, r, color) -> Incomplete: ...
def aaellipse(surface: Surface, x, y, rx, ry, color) -> Incomplete: ...
def aaline(surface: Surface, x1, y1, x2, y2, color) -> Incomplete: ...
def aapolygon(surface: Surface, points, color) -> Incomplete: ...
def aatrigon(surface: Surface, x1, y1, x2, y2, x3, y3, color) -> Incomplete: ...
def arc(surface: Surface, x, y, r, start, end, color) -> Incomplete: ...
def bezier(surface: Surface, points, steps, color) -> Incomplete: ...
def box(surface: Surface, rect, color) -> Incomplete: ...
def circle(surface: Surface, x, y, r, color) -> Incomplete: ...
def ellipse(surface: Surface, x, y, rx, ry, color) -> Incomplete: ...

error: Incomplete

def filled_circle(surface: Surface, x, y, r, color) -> Incomplete: ...
def filled_ellipse(surface: Surface, x, y, rx, ry, color) -> Incomplete: ...
def filled_pie(surface: Surface, x, y, r, start, end, color) -> Incomplete: ...
def filled_polygon(surface: Surface, points, color) -> Incomplete: ...
def filled_trigon(surface: Surface, x1, y1, x2, y2, x3, y3, color) -> Incomplete: ...
def hline(surface: Surface, x1, x2, y, color) -> Incomplete: ...
def line(surface: Surface, x1, y1, x2, y2, color) -> Incomplete: ...
def pie(surface: Surface, x, y, r, start, end, color) -> Incomplete: ...
def pixel(surface: Surface, x, y, color) -> Incomplete: ...
def polygon(surface: Surface, points, color) -> Incomplete: ...
def rectangle(surface: Surface, rect, color) -> Incomplete: ...
def rounded_box(surface: Surface, rect, rad, color) -> Incomplete: ...
def rounded_rectangle(surface: Surface, rect, rad, color) -> Incomplete: ...
def textured_polygon(surface: Surface, points, texture: Surface, tx, ty) -> Incomplete: ...
def thick_line(surface: Surface, x1, y1, x2, y2, width, color) -> Incomplete: ...
def trigon(surface: Surface, x1, y1, x2, y2, x3, y3, color) -> Incomplete: ...
def vline(surface: Surface, x, y1, y2, color) -> Incomplete: ...
