from _frozen_importlib import BuiltinImporter as BuiltinImporter

from renpy.color import ColorLike
from renpy.pygame.rect import Rect as Rect
from renpy.pygame.surface import Surface as Surface

def aacircle(surface: Surface, x: int, y: int, r: int, color: ColorLike) -> None: ...
def aaellipse(surface: Surface, x: int, y: int, rx: int, ry: int, color: ColorLike) -> None: ...
def aaline(surface: Surface, x1: int, y1: int, x2: int, y2: int, color: ColorLike) -> None: ...
def aapolygon(surface: Surface, points: list[tuple[int, int]], color: ColorLike) -> None: ...
def aatrigon(surface: Surface, x1: int, y1: int, x2: int, y2: int, x3: int, y3: int, color: ColorLike) -> None: ...
def arc(surface: Surface, x: int, y: int, r: int, start: float, end: float, color: ColorLike) -> None: ...
def bezier(surface: Surface, points: list[tuple[int, int]], steps: int, color: ColorLike) -> None: ...
def box(surface: Surface, rect: Rect | tuple[int, int, int, int], color: ColorLike) -> None: ...
def circle(surface: Surface, x: int, y: int, r: int, color: ColorLike) -> None: ...
def ellipse(surface: Surface, x: int, y: int, rx: int, ry: int, color: ColorLike) -> None: ...
def filled_circle(surface: Surface, x: int, y: int, r: int, color: ColorLike) -> None: ...
def filled_ellipse(surface: Surface, x: int, y: int, rx: int, ry: int, color: ColorLike) -> None: ...
def filled_pie(surface: Surface, x: int, y: int, r: int, start: float, end: float, color: ColorLike) -> None: ...
def filled_polygon(surface: Surface, points: list[tuple[int, int]], color: ColorLike) -> None: ...
def filled_trigon(surface: Surface, x1: int, y1: int, x2: int, y2: int, x3: int, y3: int, color: ColorLike) -> None: ...
def hline(surface: Surface, x1: int, x2: int, y: int, color: ColorLike) -> None: ...
def line(surface: Surface, x1: int, y1: int, x2: int, y2: int, color: ColorLike) -> None: ...
def pie(surface: Surface, x: int, y: int, r: int, start: float, end: float, color: ColorLike) -> None: ...
def pixel(surface: Surface, x: int, y: int, color: ColorLike) -> None: ...
def polygon(surface: Surface, points: list[tuple[int, int]], color: ColorLike) -> None: ...
def rectangle(surface: Surface, rect: Rect | tuple[int, int, int, int], color: ColorLike) -> None: ...
def rounded_box(surface: Surface, rect: Rect | tuple[int, int, int, int], rad: int, color: ColorLike) -> None: ...
def rounded_rectangle(surface: Surface, rect: Rect | tuple[int, int, int, int], rad: int, color: ColorLike) -> None: ...
def textured_polygon(surface: Surface, points: list[tuple[int, int]], texture: Surface, tx: int, ty: int) -> None: ...
def thick_line(surface: Surface, x1: int, y1: int, x2: int, y2: int, width: int, color: ColorLike) -> None: ...
def trigon(surface: Surface, x1: int, y1: int, x2: int, y2: int, x3: int, y3: int, color: ColorLike) -> None: ...
def vline(surface: Surface, x: int, y1: int, y2: int, color: ColorLike) -> None: ...
