import renpy

error = renpy.pygame.error.error

def filesystem_encode(u): ...
def get_extended(): ...
def has_init(flags: int): ...
def init(): ...
def load(fi, namehint="", size=None): ...
def quit(): ...
def save(surface: "Surface", filename, compression=-1): ...

INIT_AVIF: int
INIT_JPG: int
INIT_JXL: int
INIT_PNG: int
INIT_TIF: int
INIT_WEBP: int
