from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete
from io import IOBase
from renpy.pygame.surface import Surface as Surface

def get_extended() -> bool: ...
def has_init(flags: int) -> bool: ...
def init() -> None: ...
def load(fi: str | IOBase, namehint: str = "", size: tuple[int, int] | None = None) -> Surface: ...
def quit() -> None: ...
def save(surface: Surface, filename: str, compression: int = -1) -> None: ...

INIT_AVIF: int
INIT_JPG: int
INIT_JXL: int
INIT_PNG: int
INIT_TIF: int
INIT_WEBP: int
