from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete
from builtins import bytes as bytes, str

error: Incomplete

def filesystem_encode(u) -> None: ...
def get_extended() -> None: ...
def has_init(flags: int): ...
def init() -> None: ...
def load(fi, namehint: str = "", size=None) -> None: ...
def quit() -> None: ...
def save(surface: Surface, filename, compression: int = -1): ...

INIT_AVIF: int
INIT_JPG: int
INIT_JXL: int
INIT_PNG: int
INIT_TIF: int
INIT_WEBP: int
