from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete

class Joystick:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def get_axis(self, axis_number) -> None: ...
    def get_ball(self, ball_number) -> None: ...
    def get_button(self, button) -> None: ...
    def get_hat(self, hat_number) -> None: ...
    def get_id(self) -> None: ...
    def get_init(self) -> None: ...
    def get_name(self) -> None: ...
    def get_numaxes(self) -> None: ...
    def get_numballs(self) -> None: ...
    def get_numbuttons(self) -> None: ...
    def get_numhats(self) -> None: ...
    def init(self) -> None: ...
    def quit(self) -> None: ...

error: Incomplete

def get_count() -> None: ...
def get_init() -> None: ...
def init() -> None: ...
def quit() -> None: ...
def register_init(fn) -> None: ...
def register_quit(fn) -> None: ...
