from _frozen_importlib import BuiltinImporter as BuiltinImporter
from typing import Literal

class Joystick:
    def __init__(self, id: int) -> None: ...
    def __reduce__(self) -> None: ...
    def get_axis(self, axis_number: int) -> float: ...
    def get_ball(self, ball_number: int) -> tuple[int, int]: ...
    def get_button(self, button: int) -> bool: ...
    def get_hat(self, hat_number: int) -> tuple[Literal[-1, 0, 1], Literal[-1, 0, 1]]: ...
    def get_id(self) -> int: ...
    def get_init(self) -> bool: ...
    def get_name(self) -> str | None: ...
    def get_numaxes(self) -> int: ...
    def get_numballs(self) -> int: ...
    def get_numbuttons(self) -> int: ...
    def get_numhats(self) -> int: ...
    def init(self) -> None: ...
    def quit(self) -> None: ...

def get_count() -> int: ...
def get_init() -> bool: ...
def init() -> None: ...
def quit() -> None: ...
def register_init(fn) -> None: ...
def register_quit(fn) -> None: ...
