import renpy

class Joystick:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...
    def get_axis(self, axis_number): ...
    def get_ball(self, ball_number): ...
    def get_button(self, button): ...
    def get_hat(self, hat_number): ...
    def get_id(self): ...
    def get_init(self): ...
    def get_name(self): ...
    def get_numaxes(self): ...
    def get_numballs(self): ...
    def get_numbuttons(self): ...
    def get_numhats(self): ...
    def init(self): ...
    def quit(self): ...

error = renpy.pygame.error.error

def get_count(): ...
def get_init(): ...
def init(): ...
def quit(): ...
def register_init(fn): ...
def register_quit(fn): ...
