from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete

class KeyboardState:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __getitem__(self, key) -> None: ...
    def __reduce__(self) -> None: ...

error: Incomplete

def get_focused() -> None: ...
def get_mods() -> None: ...
def get_pressed() -> None: ...
def get_repeat() -> None: ...
def has_screen_keyboard_support() -> None: ...
def is_screen_keyboard_shown(window: Window = None): ...
def name(key) -> None: ...
def set_mods(state) -> None: ...
def set_repeat(delay: int = 0, interval: int = 0) -> None: ...
def set_text_input_rect(rect) -> None: ...
def start_text_input() -> None: ...
def stop_text_input() -> None: ...

text_input: int
