import renpy

class KeyboardState:
    def __init__(self, /, *args, **kwargs): ...
    def __getitem__(self, key, /): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...

error = renpy.pygame.error.error

def get_focused(): ...
def get_mods(): ...
def get_pressed(): ...
def get_repeat(): ...
def has_screen_keyboard_support(): ...
def is_screen_keyboard_shown(window: "Window" = None): ...
def name(key): ...
def set_mods(state): ...
def set_repeat(delay=0, interval=0): ...
def set_text_input_rect(rect): ...
def start_text_input(): ...
def stop_text_input(): ...

text_input: int
