from _frozen_importlib import BuiltinImporter as BuiltinImporter

import renpy

Color = renpy.pygame.color.Color
Rect = renpy.pygame.rect.Rect
ACTIVEEVENT: int
APP_DIDENTERBACKGROUND: int
APP_DIDENTERFOREGROUND: int
APP_LOWMEMORY: int
APP_TERMINATING: int
APP_WILLENTERBACKGROUND: int
APP_WILLENTERFOREGROUND: int
AUDIODEVICEADDED: int
AUDIODEVICEREMOVED: int
BIG_ENDIAN: int
BLEND_ADD: int
BLEND_MAX: int
BLEND_MIN: int
BLEND_MULT: int
BLEND_PREMULTIPLIED: int
BLEND_RGBA_ADD: int
BLEND_RGBA_MAX: int
BLEND_RGBA_MIN: int
BLEND_RGBA_MULT: int
BLEND_RGBA_SUB: int
BLEND_RGB_ADD: int
BLEND_RGB_MAX: int
BLEND_RGB_MIN: int
BLEND_RGB_MULT: int
BLEND_RGB_SUB: int
BLEND_SUB: int
BYTEORDER: int
CLIPBOARDUPDATE: int
CONTROLLERAXISMOTION: int
CONTROLLERBUTTONDOWN: int
CONTROLLERBUTTONUP: int
CONTROLLERDEVICEADDED: int
CONTROLLERDEVICEREMAPPED: int
CONTROLLERDEVICEREMOVED: int
CONTROLLER_AXIS_INVALID: int
CONTROLLER_AXIS_LEFTX: int
CONTROLLER_AXIS_LEFTY: int
CONTROLLER_AXIS_MAX: int
CONTROLLER_AXIS_RIGHTX: int
CONTROLLER_AXIS_RIGHTY: int
CONTROLLER_AXIS_TRIGGERLEFT: int
CONTROLLER_AXIS_TRIGGERRIGHT: int
CONTROLLER_BUTTON_A: int
CONTROLLER_BUTTON_B: int
CONTROLLER_BUTTON_BACK: int
CONTROLLER_BUTTON_DPAD_DOWN: int
CONTROLLER_BUTTON_DPAD_LEFT: int
CONTROLLER_BUTTON_DPAD_RIGHT: int
CONTROLLER_BUTTON_DPAD_UP: int
CONTROLLER_BUTTON_GUIDE: int
CONTROLLER_BUTTON_INVALID: int
CONTROLLER_BUTTON_LEFTSHOULDER: int
CONTROLLER_BUTTON_LEFTSTICK: int
CONTROLLER_BUTTON_MAX: int
CONTROLLER_BUTTON_RIGHTSHOULDER: int
CONTROLLER_BUTTON_RIGHTSTICK: int
CONTROLLER_BUTTON_START: int
CONTROLLER_BUTTON_X: int
CONTROLLER_BUTTON_Y: int
DISPLAYEVENT: int
DOLLARGESTURE: int
DOLLARRECORD: int
DOUBLEBUF: int
DROPBEGIN: int
DROPCOMPLETE: int
DROPFILE: int
DROPTEXT: int
FINGERDOWN: int
FINGERMOTION: int
FINGERUP: int
FULLSCREEN: int
GL_ACCELERATED_VISUAL: int
GL_ACCUM_ALPHA_SIZE: int
GL_ACCUM_BLUE_SIZE: int
GL_ACCUM_GREEN_SIZE: int
GL_ACCUM_RED_SIZE: int
GL_ALPHA_SIZE: int
GL_BLUE_SIZE: int
GL_BUFFER_SIZE: int
GL_CONTEXT_EGL: int
GL_CONTEXT_FLAGS: int
GL_CONTEXT_MAJOR_VERSION: int
GL_CONTEXT_MINOR_VERSION: int
GL_CONTEXT_NO_ERROR: int
GL_CONTEXT_PROFILE_COMPATIBILITY: int
GL_CONTEXT_PROFILE_CORE: int
GL_CONTEXT_PROFILE_ES: int
GL_CONTEXT_PROFILE_MASK: int
GL_CONTEXT_RELEASE_BEHAVIOR: int
GL_CONTEXT_RESET_NOTIFICATION: int
GL_DEPTH_SIZE: int
GL_DOUBLEBUFFER: int
GL_FRAMEBUFFER_SRGB_CAPABLE: int
GL_GREEN_SIZE: int
GL_MULTISAMPLEBUFFERS: int
GL_MULTISAMPLESAMPLES: int
GL_RED_SIZE: int
GL_RETAINED_BACKING: int
GL_SHARE_WITH_CURRENT_CONTEXT: int
GL_STENCIL_SIZE: int
GL_STEREO: int
GL_SWAP_CONTROL: int
HWSURFACE: int
JOYAXISMOTION: int
JOYBALLMOTION: int
JOYBUTTONDOWN: int
JOYBUTTONUP: int
JOYDEVICEADDED: int
JOYDEVICEREMOVED: int
JOYHATMOTION: int
KEYDOWN: int
KEYMAPCHANGED: int
KEYUP: int
KMOD_ALT: int
KMOD_CAPS: int
KMOD_CTRL: int
KMOD_GUI: int
KMOD_LALT: int
KMOD_LCTRL: int
KMOD_LGUI: int
KMOD_LMETA: int
KMOD_LSHIFT: int
KMOD_META: int
KMOD_MODE: int
KMOD_NONE: int
KMOD_NUM: int
KMOD_RALT: int
KMOD_RCTRL: int
KMOD_RGUI: int
KMOD_RMETA: int
KMOD_RSHIFT: int
KMOD_SHIFT: int
K_0: int
K_1: int
K_2: int
K_3: int
K_4: int
K_5: int
K_6: int
K_7: int
K_8: int
K_9: int
K_AC_BACK: int
K_AC_BOOKMARKS: int
K_AC_FORWARD: int
K_AC_HOME: int
K_AC_REFRESH: int
K_AC_SEARCH: int
K_AC_STOP: int
K_AGAIN: int
K_ALTERASE: int
K_AMPERSAND: int
K_APP1: int
K_APP2: int
K_APPLICATION: int
K_ASTERISK: int
K_AT: int
K_AUDIOFASTFORWARD: int
K_AUDIOMUTE: int
K_AUDIONEXT: int
K_AUDIOPLAY: int
K_AUDIOPREV: int
K_AUDIOREWIND: int
K_AUDIOSTOP: int
K_BACKQUOTE: int
K_BACKSLASH: int
K_BACKSPACE: int
K_BREAK: int
K_BRIGHTNESSDOWN: int
K_BRIGHTNESSUP: int
K_CALCULATOR: int
K_CANCEL: int
K_CAPSLOCK: int
K_CARET: int
K_CLEAR: int
K_CLEARAGAIN: int
K_COLON: int
K_COMMA: int
K_COMPUTER: int
K_COPY: int
K_CRSEL: int
K_CURRENCYSUBUNIT: int
K_CURRENCYUNIT: int
K_CUT: int
K_DECIMALSEPARATOR: int
K_DELETE: int
K_DISPLAYSWITCH: int
K_DOLLAR: int
K_DOWN: int
K_EJECT: int
K_END: int
K_EQUALS: int
K_ESCAPE: int
K_EURO: int
K_EXCLAIM: int
K_EXECUTE: int
K_EXSEL: int
K_F1: int
K_F10: int
K_F11: int
K_F12: int
K_F13: int
K_F14: int
K_F15: int
K_F16: int
K_F17: int
K_F18: int
K_F19: int
K_F2: int
K_F20: int
K_F21: int
K_F22: int
K_F23: int
K_F24: int
K_F3: int
K_F4: int
K_F5: int
K_F6: int
K_F7: int
K_F8: int
K_F9: int
K_FIND: int
K_FIRST: int
K_GREATER: int
K_HASH: int
K_HELP: int
K_HOME: int
K_INSERT: int
K_KBDILLUMDOWN: int
K_KBDILLUMTOGGLE: int
K_KBDILLUMUP: int
K_KP0: int
K_KP1: int
K_KP2: int
K_KP3: int
K_KP4: int
K_KP5: int
K_KP6: int
K_KP7: int
K_KP8: int
K_KP9: int
K_KP_0: int
K_KP_00: int
K_KP_000: int
K_KP_1: int
K_KP_2: int
K_KP_3: int
K_KP_4: int
K_KP_5: int
K_KP_6: int
K_KP_7: int
K_KP_8: int
K_KP_9: int
K_KP_A: int
K_KP_AMPERSAND: int
K_KP_AT: int
K_KP_B: int
K_KP_BACKSPACE: int
K_KP_BINARY: int
K_KP_C: int
K_KP_CLEAR: int
K_KP_CLEARENTRY: int
K_KP_COLON: int
K_KP_COMMA: int
K_KP_D: int
K_KP_DBLAMPERSAND: int
K_KP_DBLVERTICALBAR: int
K_KP_DECIMAL: int
K_KP_DIVIDE: int
K_KP_E: int
K_KP_ENTER: int
K_KP_EQUALS: int
K_KP_EQUALSAS400: int
K_KP_EXCLAM: int
K_KP_F: int
K_KP_GREATER: int
K_KP_HASH: int
K_KP_HEXADECIMAL: int
K_KP_LEFTBRACE: int
K_KP_LEFTPAREN: int
K_KP_LESS: int
K_KP_MEMADD: int
K_KP_MEMCLEAR: int
K_KP_MEMDIVIDE: int
K_KP_MEMMULTIPLY: int
K_KP_MEMRECALL: int
K_KP_MEMSTORE: int
K_KP_MEMSUBTRACT: int
K_KP_MINUS: int
K_KP_MULTIPLY: int
K_KP_OCTAL: int
K_KP_PERCENT: int
K_KP_PERIOD: int
K_KP_PLUS: int
K_KP_PLUSMINUS: int
K_KP_POWER: int
K_KP_RIGHTBRACE: int
K_KP_RIGHTPAREN: int
K_KP_SPACE: int
K_KP_TAB: int
K_KP_VERTICALBAR: int
K_KP_XOR: int
K_LALT: int
K_LAST: int
K_LCTRL: int
K_LEFT: int
K_LEFTBRACKET: int
K_LEFTPAREN: int
K_LESS: int
K_LGUI: int
K_LMETA: int
K_LSHIFT: int
K_LSUPER: int
K_MAIL: int
K_MEDIASELECT: int
K_MENU: int
K_MINUS: int
K_MODE: int
K_MUTE: int
K_NUMLOCK: int
K_NUMLOCKCLEAR: int
K_OPER: int
K_OUT: int
K_PAGEDOWN: int
K_PAGEUP: int
K_PASTE: int
K_PAUSE: int
K_PERCENT: int
K_PERIOD: int
K_PLUS: int
K_POWER: int
K_PRINT: int
K_PRINTSCREEN: int
K_PRIOR: int
K_QUESTION: int
K_QUOTE: int
K_QUOTEDBL: int
K_RALT: int
K_RCTRL: int
K_RETURN: int
K_RETURN2: int
K_RGUI: int
K_RIGHT: int
K_RIGHTBRACKET: int
K_RIGHTPAREN: int
K_RMETA: int
K_RSHIFT: int
K_RSUPER: int
K_SCROLLLOCK: int
K_SCROLLOCK: int
K_SELECT: int
K_SEMICOLON: int
K_SEPARATOR: int
K_SLASH: int
K_SLEEP: int
K_SPACE: int
K_STOP: int
K_SYSREQ: int
K_TAB: int
K_THOUSANDSSEPARATOR: int
K_UNDERSCORE: int
K_UNDO: int
K_UNKNOWN: int
K_UP: int
K_VOLUMEDOWN: int
K_VOLUMEUP: int
K_WWW: int
K_a: int
K_b: int
K_c: int
K_d: int
K_e: int
K_f: int
K_g: int
K_h: int
K_i: int
K_j: int
K_k: int
K_l: int
K_m: int
K_n: int
K_o: int
K_p: int
K_q: int
K_r: int
K_s: int
K_t: int
K_u: int
K_v: int
K_w: int
K_x: int
K_y: int
K_z: int
LASTEVENT: int
LIL_ENDIAN: int
MOUSEBUTTONDOWN: int
MOUSEBUTTONUP: int
MOUSEMOTION: int
MOUSEWHEEL: int
MULTIGESTURE: int
NOEVENT: int
NOFRAME: int
OPENGL: int
POWERSTATE_CHARGED: int
POWERSTATE_CHARGING: int
POWERSTATE_NO_BATTERY: int
POWERSTATE_ON_BATTERY: int
POWERSTATE_UNKNOWN: int
QUIT: int
RENDER_DEVICE_RESET: int
RENDER_TARGETS_RESET: int
RESIZABLE: int
RLEACCEL: int
SCRAP_TEXT: str
SENSORUPDATE: int
SRCALPHA: int
SRCCOLORKEY: int
SWSURFACE: int
SYSWMEVENT: int
TEXTEDITING: int
TEXTINPUT: int
TOUCH_MOUSEID: int
USEREVENT: int
VIDEOEXPOSE: int
VIDEORESIZE: int
WINDOWEVENT: int
WINDOWMOVED: int
WINDOWPOS_CENTERED: int
WINDOWPOS_UNDEFINED: int
WINDOW_ALLOW_HIGHDPI: int
WINDOW_BORDERLESS: int
WINDOW_FOREIGN: int
WINDOW_FULLSCREEN: int
WINDOW_FULLSCREEN_DESKTOP: int
WINDOW_HIDDEN: int
WINDOW_INPUT_FOCUS: int
WINDOW_INPUT_GRABBED: int
WINDOW_MAXIMIZED: int
WINDOW_MINIMIZED: int
WINDOW_NOFRAME: int
WINDOW_OPENGL: int
WINDOW_RESIZABLE: int
WINDOW_SHOWN: int

__all__ = [
    "ACTIVEEVENT",
    "APP_DIDENTERBACKGROUND",
    "APP_DIDENTERFOREGROUND",
    "APP_LOWMEMORY",
    "APP_TERMINATING",
    "APP_WILLENTERBACKGROUND",
    "APP_WILLENTERFOREGROUND",
    "AUDIODEVICEADDED",
    "AUDIODEVICEREMOVED",
    "BIG_ENDIAN",
    "BLEND_ADD",
    "BLEND_MAX",
    "BLEND_MIN",
    "BLEND_MULT",
    "BLEND_PREMULTIPLIED",
    "BLEND_RGBA_ADD",
    "BLEND_RGBA_MAX",
    "BLEND_RGBA_MIN",
    "BLEND_RGBA_MULT",
    "BLEND_RGBA_SUB",
    "BLEND_RGB_ADD",
    "BLEND_RGB_MAX",
    "BLEND_RGB_MIN",
    "BLEND_RGB_MULT",
    "BLEND_RGB_SUB",
    "BLEND_SUB",
    "BYTEORDER",
    "CLIPBOARDUPDATE",
    "CONTROLLERAXISMOTION",
    "CONTROLLERBUTTONDOWN",
    "CONTROLLERBUTTONUP",
    "CONTROLLERDEVICEADDED",
    "CONTROLLERDEVICEREMAPPED",
    "CONTROLLERDEVICEREMOVED",
    "CONTROLLER_AXIS_INVALID",
    "CONTROLLER_AXIS_LEFTX",
    "CONTROLLER_AXIS_LEFTY",
    "CONTROLLER_AXIS_MAX",
    "CONTROLLER_AXIS_RIGHTX",
    "CONTROLLER_AXIS_RIGHTY",
    "CONTROLLER_AXIS_TRIGGERLEFT",
    "CONTROLLER_AXIS_TRIGGERRIGHT",
    "CONTROLLER_BUTTON_A",
    "CONTROLLER_BUTTON_B",
    "CONTROLLER_BUTTON_BACK",
    "CONTROLLER_BUTTON_DPAD_DOWN",
    "CONTROLLER_BUTTON_DPAD_LEFT",
    "CONTROLLER_BUTTON_DPAD_RIGHT",
    "CONTROLLER_BUTTON_DPAD_UP",
    "CONTROLLER_BUTTON_GUIDE",
    "CONTROLLER_BUTTON_INVALID",
    "CONTROLLER_BUTTON_LEFTSHOULDER",
    "CONTROLLER_BUTTON_LEFTSTICK",
    "CONTROLLER_BUTTON_MAX",
    "CONTROLLER_BUTTON_RIGHTSHOULDER",
    "CONTROLLER_BUTTON_RIGHTSTICK",
    "CONTROLLER_BUTTON_START",
    "CONTROLLER_BUTTON_X",
    "CONTROLLER_BUTTON_Y",
    "DISPLAYEVENT",
    "DOLLARGESTURE",
    "DOLLARRECORD",
    "DOUBLEBUF",
    "DROPBEGIN",
    "DROPCOMPLETE",
    "DROPFILE",
    "DROPTEXT",
    "FINGERDOWN",
    "FINGERMOTION",
    "FINGERUP",
    "FULLSCREEN",
    "GL_ACCELERATED_VISUAL",
    "GL_ACCUM_ALPHA_SIZE",
    "GL_ACCUM_BLUE_SIZE",
    "GL_ACCUM_GREEN_SIZE",
    "GL_ACCUM_RED_SIZE",
    "GL_ALPHA_SIZE",
    "GL_BLUE_SIZE",
    "GL_BUFFER_SIZE",
    "GL_CONTEXT_EGL",
    "GL_CONTEXT_FLAGS",
    "GL_CONTEXT_MAJOR_VERSION",
    "GL_CONTEXT_MINOR_VERSION",
    "GL_CONTEXT_NO_ERROR",
    "GL_CONTEXT_PROFILE_COMPATIBILITY",
    "GL_CONTEXT_PROFILE_CORE",
    "GL_CONTEXT_PROFILE_ES",
    "GL_CONTEXT_PROFILE_MASK",
    "GL_CONTEXT_RELEASE_BEHAVIOR",
    "GL_CONTEXT_RESET_NOTIFICATION",
    "GL_DEPTH_SIZE",
    "GL_DOUBLEBUFFER",
    "GL_FRAMEBUFFER_SRGB_CAPABLE",
    "GL_GREEN_SIZE",
    "GL_MULTISAMPLEBUFFERS",
    "GL_MULTISAMPLESAMPLES",
    "GL_RED_SIZE",
    "GL_RETAINED_BACKING",
    "GL_SHARE_WITH_CURRENT_CONTEXT",
    "GL_STENCIL_SIZE",
    "GL_STEREO",
    "GL_SWAP_CONTROL",
    "HWSURFACE",
    "JOYAXISMOTION",
    "JOYBALLMOTION",
    "JOYBUTTONDOWN",
    "JOYBUTTONUP",
    "JOYDEVICEADDED",
    "JOYDEVICEREMOVED",
    "JOYHATMOTION",
    "KEYDOWN",
    "KEYMAPCHANGED",
    "KEYUP",
    "KMOD_ALT",
    "KMOD_CAPS",
    "KMOD_CTRL",
    "KMOD_GUI",
    "KMOD_LALT",
    "KMOD_LCTRL",
    "KMOD_LGUI",
    "KMOD_LMETA",
    "KMOD_LSHIFT",
    "KMOD_META",
    "KMOD_MODE",
    "KMOD_NONE",
    "KMOD_NUM",
    "KMOD_RALT",
    "KMOD_RCTRL",
    "KMOD_RGUI",
    "KMOD_RMETA",
    "KMOD_RSHIFT",
    "KMOD_SHIFT",
    "K_0",
    "K_1",
    "K_2",
    "K_3",
    "K_4",
    "K_5",
    "K_6",
    "K_7",
    "K_8",
    "K_9",
    "K_AC_BACK",
    "K_AC_BOOKMARKS",
    "K_AC_FORWARD",
    "K_AC_HOME",
    "K_AC_REFRESH",
    "K_AC_SEARCH",
    "K_AC_STOP",
    "K_AGAIN",
    "K_ALTERASE",
    "K_AMPERSAND",
    "K_APP1",
    "K_APP2",
    "K_APPLICATION",
    "K_ASTERISK",
    "K_AT",
    "K_AUDIOFASTFORWARD",
    "K_AUDIOMUTE",
    "K_AUDIONEXT",
    "K_AUDIOPLAY",
    "K_AUDIOPREV",
    "K_AUDIOREWIND",
    "K_AUDIOSTOP",
    "K_BACKQUOTE",
    "K_BACKSLASH",
    "K_BACKSPACE",
    "K_BREAK",
    "K_BRIGHTNESSDOWN",
    "K_BRIGHTNESSUP",
    "K_CALCULATOR",
    "K_CANCEL",
    "K_CAPSLOCK",
    "K_CARET",
    "K_CLEAR",
    "K_CLEARAGAIN",
    "K_COLON",
    "K_COMMA",
    "K_COMPUTER",
    "K_COPY",
    "K_CRSEL",
    "K_CURRENCYSUBUNIT",
    "K_CURRENCYUNIT",
    "K_CUT",
    "K_DECIMALSEPARATOR",
    "K_DELETE",
    "K_DISPLAYSWITCH",
    "K_DOLLAR",
    "K_DOWN",
    "K_EJECT",
    "K_END",
    "K_EQUALS",
    "K_ESCAPE",
    "K_EURO",
    "K_EXCLAIM",
    "K_EXECUTE",
    "K_EXSEL",
    "K_F1",
    "K_F2",
    "K_F3",
    "K_F4",
    "K_F5",
    "K_F6",
    "K_F7",
    "K_F8",
    "K_F9",
    "K_F10",
    "K_F11",
    "K_F12",
    "K_F13",
    "K_F14",
    "K_F15",
    "K_F16",
    "K_F17",
    "K_F18",
    "K_F19",
    "K_F20",
    "K_F21",
    "K_F22",
    "K_F23",
    "K_F24",
    "K_FIND",
    "K_FIRST",
    "K_GREATER",
    "K_HASH",
    "K_HELP",
    "K_HOME",
    "K_INSERT",
    "K_KBDILLUMDOWN",
    "K_KBDILLUMTOGGLE",
    "K_KBDILLUMUP",
    "K_KP0",
    "K_KP1",
    "K_KP2",
    "K_KP3",
    "K_KP4",
    "K_KP5",
    "K_KP6",
    "K_KP7",
    "K_KP8",
    "K_KP9",
    "K_KP_0",
    "K_KP_00",
    "K_KP_000",
    "K_KP_1",
    "K_KP_2",
    "K_KP_3",
    "K_KP_4",
    "K_KP_5",
    "K_KP_6",
    "K_KP_7",
    "K_KP_8",
    "K_KP_9",
    "K_KP_A",
    "K_KP_AMPERSAND",
    "K_KP_AT",
    "K_KP_B",
    "K_KP_BACKSPACE",
    "K_KP_BINARY",
    "K_KP_C",
    "K_KP_CLEAR",
    "K_KP_CLEARENTRY",
    "K_KP_COLON",
    "K_KP_COMMA",
    "K_KP_D",
    "K_KP_DBLAMPERSAND",
    "K_KP_DBLVERTICALBAR",
    "K_KP_DECIMAL",
    "K_KP_DIVIDE",
    "K_KP_E",
    "K_KP_ENTER",
    "K_KP_EQUALS",
    "K_KP_EQUALSAS400",
    "K_KP_EXCLAM",
    "K_KP_F",
    "K_KP_GREATER",
    "K_KP_HASH",
    "K_KP_HEXADECIMAL",
    "K_KP_LEFTBRACE",
    "K_KP_LEFTPAREN",
    "K_KP_LESS",
    "K_KP_MEMADD",
    "K_KP_MEMCLEAR",
    "K_KP_MEMDIVIDE",
    "K_KP_MEMMULTIPLY",
    "K_KP_MEMRECALL",
    "K_KP_MEMSTORE",
    "K_KP_MEMSUBTRACT",
    "K_KP_MINUS",
    "K_KP_MULTIPLY",
    "K_KP_OCTAL",
    "K_KP_PERCENT",
    "K_KP_PERIOD",
    "K_KP_PLUS",
    "K_KP_PLUSMINUS",
    "K_KP_POWER",
    "K_KP_RIGHTBRACE",
    "K_KP_RIGHTPAREN",
    "K_KP_SPACE",
    "K_KP_TAB",
    "K_KP_VERTICALBAR",
    "K_KP_XOR",
    "K_LALT",
    "K_LAST",
    "K_LCTRL",
    "K_LEFT",
    "K_LEFTBRACKET",
    "K_LEFTPAREN",
    "K_LESS",
    "K_LGUI",
    "K_LMETA",
    "K_LSHIFT",
    "K_LSUPER",
    "K_MAIL",
    "K_MEDIASELECT",
    "K_MENU",
    "K_MINUS",
    "K_MODE",
    "K_MUTE",
    "K_NUMLOCK",
    "K_NUMLOCKCLEAR",
    "K_OPER",
    "K_OUT",
    "K_PAGEDOWN",
    "K_PAGEUP",
    "K_PASTE",
    "K_PAUSE",
    "K_PERCENT",
    "K_PERIOD",
    "K_PLUS",
    "K_POWER",
    "K_PRINT",
    "K_PRINTSCREEN",
    "K_PRIOR",
    "K_QUESTION",
    "K_QUOTE",
    "K_QUOTEDBL",
    "K_RALT",
    "K_RCTRL",
    "K_RETURN",
    "K_RETURN2",
    "K_RGUI",
    "K_RIGHT",
    "K_RIGHTBRACKET",
    "K_RIGHTPAREN",
    "K_RMETA",
    "K_RSHIFT",
    "K_RSUPER",
    "K_SCROLLLOCK",
    "K_SCROLLOCK",
    "K_SELECT",
    "K_SEMICOLON",
    "K_SEPARATOR",
    "K_SLASH",
    "K_SLEEP",
    "K_SPACE",
    "K_STOP",
    "K_SYSREQ",
    "K_TAB",
    "K_THOUSANDSSEPARATOR",
    "K_UNDERSCORE",
    "K_UNDO",
    "K_UNKNOWN",
    "K_UP",
    "K_VOLUMEDOWN",
    "K_VOLUMEUP",
    "K_WWW",
    "LASTEVENT",
    "LIL_ENDIAN",
    "MOUSEBUTTONDOWN",
    "MOUSEBUTTONUP",
    "MOUSEMOTION",
    "MOUSEWHEEL",
    "MULTIGESTURE",
    "NOEVENT",
    "NOFRAME",
    "OPENGL",
    "POWERSTATE_CHARGED",
    "POWERSTATE_CHARGING",
    "POWERSTATE_NO_BATTERY",
    "POWERSTATE_ON_BATTERY",
    "POWERSTATE_UNKNOWN",
    "QUIT",
    "RENDER_DEVICE_RESET",
    "RENDER_TARGETS_RESET",
    "RESIZABLE",
    "RLEACCEL",
    "SCRAP_TEXT",
    "SENSORUPDATE",
    "SRCALPHA",
    "SRCCOLORKEY",
    "SWSURFACE",
    "SYSWMEVENT",
    "TEXTEDITING",
    "TEXTINPUT",
    "TOUCH_MOUSEID",
    "USEREVENT",
    "VIDEOEXPOSE",
    "VIDEORESIZE",
    "WINDOWEVENT",
    "WINDOWMOVED",
    "WINDOWPOS_CENTERED",
    "WINDOWPOS_UNDEFINED",
    "WINDOW_ALLOW_HIGHDPI",
    "WINDOW_BORDERLESS",
    "WINDOW_FOREIGN",
    "WINDOW_FULLSCREEN",
    "WINDOW_FULLSCREEN_DESKTOP",
    "WINDOW_HIDDEN",
    "WINDOW_INPUT_FOCUS",
    "WINDOW_INPUT_GRABBED",
    "WINDOW_MAXIMIZED",
    "WINDOW_MINIMIZED",
    "WINDOW_NOFRAME",
    "WINDOW_OPENGL",
    "WINDOW_RESIZABLE",
    "WINDOW_SHOWN",
    "Color",
    "K_a",
    "K_b",
    "K_c",
    "K_d",
    "K_e",
    "K_f",
    "K_g",
    "K_h",
    "K_i",
    "K_j",
    "K_k",
    "K_l",
    "K_m",
    "K_n",
    "K_o",
    "K_p",
    "K_q",
    "K_r",
    "K_s",
    "K_t",
    "K_u",
    "K_v",
    "K_w",
    "K_x",
    "K_y",
    "K_z",
    "Rect",
]
