from _frozen_importlib import BuiltinImporter as BuiltinImporter
from renpy.types import Unused
from _typeshed import Incomplete

class ColorCursor:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def activate(self) -> None: ...

def get_cursor() -> None: ...
def get_focused() -> bool: ...
def get_pos() -> tuple[int, int]: ...
def get_pressed() -> tuple[int, int, int]: ...
def get_rel() -> tuple[int, int]: ...
def init() -> None: ...
def quit() -> None: ...
def reset() -> None: ...
def set_cursor(size: Incomplete, hotspot: Unused, xormasks: Unused, andmasks: Unused) -> None: ...
def set_pos(pos: tuple[int, int]) -> None: ...
def set_visible(visible: bool) -> None: ...

active_cursor: int
