class ColorCursor:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...
    def activate(self): ...

def get_cursor(): ...
def get_focused(): ...
def get_pos(): ...
def get_pressed(): ...
def get_rel(): ...
def init(): ...
def quit(): ...
def reset(): ...
def set_cursor(size, hotspot, xormasks, andmasks): ...
def set_pos(pos): ...
def set_visible(visible): ...

active_cursor: int
