from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete

class Clock:
    def __init__(self) -> None: ...
    def get_fps(self) -> None: ...
    def get_rawtime(self) -> None: ...
    def get_time(self) -> None: ...
    def tick(self, framerate: int = 0) -> None: ...
    def tick_busy_loop(self, framerate: int = 0) -> None: ...

def delay(milliseconds) -> None: ...

error: Incomplete

def get_ticks() -> None: ...
def init() -> None: ...
def quit() -> None: ...
def register_init(fn) -> None: ...
def register_quit(fn) -> None: ...
def set_timer(eventid, milliseconds) -> None: ...
def wait(milliseconds: int): ...
