from _frozen_importlib import BuiltinImporter as BuiltinImporter

class Clock:
    def __init__(self) -> None: ...
    def get_fps(self) -> float: ...
    def get_rawtime(self) -> int: ...
    def get_time(self) -> int: ...
    def tick(self, framerate: float = 0) -> int: ...
    def tick_busy_loop(self, framerate: float = 0) -> int: ...

def delay(milliseconds: int) -> None: ...
def get_ticks() -> int: ...
def init() -> None: ...
def quit() -> None: ...
def register_init(fn) -> None: ...
def register_quit(fn) -> None: ...
def set_timer(eventid: int, milliseconds: int) -> None: ...
def wait(milliseconds: int): ...
