import renpy

class Clock:
    def __init__(
        self,
    ): ...
    def get_fps(self): ...
    def get_rawtime(self): ...
    def get_time(self): ...
    def tick(self, framerate=0): ...
    def tick_busy_loop(self, framerate=0): ...

def delay(milliseconds): ...

error = renpy.pygame.error.error

def get_ticks(): ...
def init(): ...
def quit(): ...
def register_init(fn): ...
def register_quit(fn): ...
def set_timer(eventid, milliseconds): ...
def wait(milliseconds: int): ...
