from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

class Rect:
    x: int
    y: int
    w: int
    h: int
    def __init__(self, *args: RectLike) -> None: ...
    def __delitem__(self, key: Incomplete) -> None: ...
    def __eq__(self, value: object) -> bool: ...
    def __ge__(self, value: object) -> bool: ...
    def __getitem__(self, key: Incomplete) -> None: ...
    def __gt__(self, value: object) -> bool: ...
    def __iter__(self) -> Incomplete: ...
    def __le__(self, value: object) -> bool: ...
    def __len__(self) -> int: ...
    def __lt__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...
    def __setitem__(self, key: Incomplete, value: Incomplete) -> None: ...
    def clamp(self, other: Incomplete) -> None: ...
    def clamp_ip(self, other: Incomplete) -> None: ...
    def clip(self, other: Incomplete, y: Incomplete = None, w: Incomplete = None, h: Incomplete = None) -> None: ...
    def collidedict(self, other_dict: Incomplete, rects_values: int = 0) -> None: ...
    def collidedictall(self, other_dict: Incomplete, rects_values: int = 0) -> None: ...
    def collidelist(self, other_list: Incomplete) -> None: ...
    def collidelistall(self, other_list: Incomplete) -> None: ...
    def collidepoint(self, x: Incomplete, y: Incomplete = None) -> None: ...
    def colliderect(self, other: Incomplete) -> None: ...
    def contains(self, other: Incomplete) -> None: ...
    def copy(self) -> None: ...
    def fit(self, other: Incomplete) -> None: ...
    def inflate(self, *args: Incomplete) -> None: ...
    def inflate_ip(self, *args: Incomplete) -> None: ...
    def move(self, *args: Incomplete) -> None: ...
    def move_ip(self, *args: Incomplete) -> None: ...
    def normalize(self) -> None: ...
    def union(self, other: Incomplete) -> None: ...
    def union_ip(self, other: Incomplete) -> None: ...
    def unionall(self, other_seq: Incomplete) -> None: ...
    def unionall_ip(self, other_seq: Incomplete) -> None: ...

type RectLike = Rect | tuple[int, int, int, int] | tuple[int, int]

def flatten(*args: Incomplete) -> None: ...
