from _frozen_importlib import BuiltinImporter as BuiltinImporter

class Rect:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __eq__(self, value): ...
    def __ge__(self, value): ...
    def __getitem__(self, key) -> None: ...
    def __gt__(self, value): ...
    def __iter__(self): ...
    def __le__(self, value): ...
    def __len__(self) -> int: ...
    def __lt__(self, value): ...
    def __ne__(self, value): ...
    def __reduce__(self) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def clamp(self, other) -> None: ...
    def clamp_ip(self, other) -> None: ...
    def clip(self, other, y=None, w=None, h=None) -> None: ...
    def collidedict(self, other_dict, rects_values: int = 0) -> None: ...
    def collidedictall(self, other_dict, rects_values: int = 0) -> None: ...
    def collidelist(self, other_list) -> None: ...
    def collidelistall(self, other_list) -> None: ...
    def collidepoint(self, x, y=None) -> None: ...
    def colliderect(self, other) -> None: ...
    def contains(self, other) -> None: ...
    def copy(self) -> None: ...
    def fit(self, other) -> None: ...
    def inflate(self, *args) -> None: ...
    def inflate_ip(self, *args) -> None: ...
    def move(self, *args) -> None: ...
    def move_ip(self, *args) -> None: ...
    def normalize(self) -> None: ...
    def union(self, other) -> None: ...
    def union_ip(self, other) -> None: ...
    def unionall(self, other_seq) -> None: ...
    def unionall_ip(self, other_seq) -> None: ...

def flatten(*args) -> None: ...
