class Rect:
    def __init__(self, /, *args, **kwargs): ...
    def __delitem__(self, key, /): ...
    def __eq__(self, value, /): ...
    def __ge__(self, value, /): ...
    def __getitem__(self, key, /): ...
    def __gt__(self, value, /): ...
    def __iter__(self, /): ...
    def __le__(self, value, /): ...
    def __len__(self, /): ...
    def __lt__(self, value, /): ...
    def __ne__(self, value, /): ...
    def __reduce__(self): ...
    def __repr__(self, /): ...
    def __setitem__(self, key, value, /): ...
    def clamp(self, other): ...
    def clamp_ip(self, other): ...
    def clip(self, other, y=None, w=None, h=None): ...
    def collidedict(self, other_dict, rects_values=0): ...
    def collidedictall(self, other_dict, rects_values=0): ...
    def collidelist(self, other_list): ...
    def collidelistall(self, other_list): ...
    def collidepoint(self, x, y=None): ...
    def colliderect(self, other): ...
    def contains(self, other): ...
    def copy(self): ...
    def fit(self, other): ...
    def inflate(self, *args): ...
    def inflate_ip(self, *args): ...
    def move(self, *args): ...
    def move_ip(self, *args): ...
    def normalize(self): ...
    def union(self, other): ...
    def union_ip(self, other): ...
    def unionall(self, other_seq): ...
    def unionall_ip(self, other_seq): ...

def flatten(*args): ...
