import io as io
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _io import FileIO as FileIO
from builtins import bytes as bytes, str
from _typeshed import Incomplete

class RWopsIO(io.RawIOBase):
    def __init__(
        self,
        filelike: Incomplete,
        mode: str = "rb",
        base: Incomplete = None,
        length: Incomplete = None,
        name: Incomplete = None,
    ) -> None: ...
    def fileno(self) -> None: ...
    @staticmethod
    def from_buffer(buffer: Incomplete, mode: str = "rb", name: Incomplete = None) -> None: ...
    @staticmethod
    def from_split(a: Incomplete, b: Incomplete, name: Incomplete = None) -> None: ...
    def readable(self) -> None: ...
    def seekable(self) -> None: ...
    def truncate(self, size: Incomplete = None) -> None: ...
    def writable(self) -> None: ...

class RWopsIOImpl:
    def __init__(
        self,
        filelike: Incomplete,
        mode: str = "rb",
        base: Incomplete = None,
        length: Incomplete = None,
        name: Incomplete = None,
    ) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def close(self) -> None: ...
    def is_closed(self) -> None: ...
    def readinto(self, b: Incomplete) -> None: ...
    def seek(self, offset: int, whence: int = 0) -> None: ...
    def tell(self) -> None: ...
    def write(self, b: Incomplete) -> None: ...
