import io as io
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _io import FileIO as FileIO
from builtins import bytes as bytes, str

class RWopsIO(io.RawIOBase):
    def __init__(self, filelike, mode: str = "rb", base=None, length=None, name=None) -> None: ...
    def fileno(self) -> None: ...
    @staticmethod
    def from_buffer(buffer, mode: str = "rb", name=None) -> None: ...
    @staticmethod
    def from_split(a, b, name=None) -> None: ...
    def readable(self) -> None: ...
    def seekable(self) -> None: ...
    def truncate(self, size=None) -> None: ...
    def writable(self) -> None: ...

class RWopsIOImpl:
    def __init__(self, filelike, mode: str = "rb", base=None, length=None, name=None) -> None: ...
    def __reduce__(self) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> None: ...
    def readinto(self, b) -> None: ...
    def seek(self, offset: int, whence: int = 0): ...
    def tell(self) -> None: ...
    def write(self, b) -> None: ...
