import io as io

class RWopsIO(io.RawIOBase):
    def __init__(self, filelike, mode="rb", base=None, length=None, name=None): ...
    def __repr__(self): ...
    def fileno(self): ...
    @staticmethod
    def from_buffer(buffer, mode="rb", name=None): ...
    @staticmethod
    def from_split(a, b, name=None): ...
    def readable(self): ...
    def seekable(self): ...
    def truncate(self, size=None): ...
    def writable(self): ...

class RWopsIOImpl:
    def __init__(self, filelike, mode="rb", base=None, length=None, name=None): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...
    def close(self): ...
    def is_closed(self): ...
    def readinto(self, b): ...
    def seek(self, offset: int, whence=0): ...
    def tell(self): ...
    def write(self, b): ...
