from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete
from builtins import bytes as bytes

def contains(type) -> None: ...

error: Incomplete

def get(type) -> None: ...
def get_types() -> None: ...
def init() -> None: ...
def lost() -> None: ...
def put(type, data) -> None: ...
def set_mode(mode) -> None: ...

SCRAP_TEXT: int
