from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete
from builtins import bytes as bytes

def contains(type: int) -> bool: ...
def get(type: int) -> bytes: ...
def get_types() -> list[int]: ...
def init() -> None: ...
def lost() -> None: ...
def put(type: int, data: bytes) -> None: ...
def set_mode(mode: Incomplete) -> None: ...

SCRAP_TEXT: int
