import renpy

def contains(type): ...

error = renpy.pygame.error.error

def get(type): ...
def get_types(): ...
def init(): ...
def lost(): ...
def put(type, data): ...
def set_mode(mode): ...

SCRAP_TEXT: int
