import renpy

Rect = renpy.pygame.rect.Rect

class Surface:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __repr__(self, /): ...
    def __setstate__(self, __pyx_state): ...
    def __sizeof__(self): ...
    def blit(self, source: "Surface", dest, area=None, special_flags: int = 0): ...
    def convert(self, surface=None): ...
    def convert_alpha(self, surface: "Surface" = None): ...
    def copy(self): ...
    def fill(self, color, rect=None, special_flags=0): ...
    def from_data(self, data): ...
    def get_abs_offset(self): ...
    def get_abs_parent(self): ...
    def get_alpha(self): ...
    def get_at(self, pos): ...
    def get_at_mapped(self, pos): ...
    def get_bitsize(self): ...
    def get_bounding_rect(self, min_alpha=1): ...
    def get_buffer(self): ...
    def get_bytesize(self): ...
    def get_clip(self): ...
    def get_colorkey(self): ...
    def get_flags(self): ...
    def get_height(self): ...
    def get_locked(self): ...
    def get_locks(self): ...
    def get_losses(self): ...
    def get_masks(self): ...
    def get_offset(self): ...
    def get_parent(self): ...
    def get_pitch(self): ...
    def get_rect(self, **kwargs): ...
    def get_shifts(self): ...
    def get_size(self): ...
    def get_view(self, kind="2"): ...
    def get_width(self): ...
    def lock(self, lock=None): ...
    def map_rgb(self, color): ...
    def mustlock(self): ...
    def scroll(self, dx: int = 0, dy: int = 0): ...
    def set_alpha(self, value, flags=0): ...
    def set_at(self, pos, color): ...
    def set_clip(self, rect): ...
    def set_colorkey(self, color, flags=0): ...
    def set_masks(self, masks): ...
    def set_shifts(self, shifts): ...
    def subsurface(self, *args): ...
    def unlock(self, lock=None): ...
    def unmap_rgb(self, pixel): ...

error = renpy.pygame.error.error

SRCALPHA: int
total_size: int
