import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete

Rect = renpy.pygame.rect.Rect

class Surface:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def __sizeof__(self) -> int: ...
    def blit(self, source: Surface, dest, area=None, special_flags: int = 0): ...
    def convert(self, surface=None) -> None: ...
    def convert_alpha(self, surface: Surface = None): ...
    def copy(self) -> None: ...
    def fill(self, color, rect=None, special_flags: int = 0) -> None: ...
    def from_data(self, data) -> None: ...
    def get_abs_offset(self) -> None: ...
    def get_abs_parent(self) -> None: ...
    def get_alpha(self) -> None: ...
    def get_at(self, pos) -> None: ...
    def get_at_mapped(self, pos) -> None: ...
    def get_bitsize(self) -> None: ...
    def get_bounding_rect(self, min_alpha: int = 1) -> None: ...
    def get_buffer(self) -> None: ...
    def get_bytesize(self) -> None: ...
    def get_clip(self) -> None: ...
    def get_colorkey(self) -> None: ...
    def get_flags(self) -> None: ...
    def get_height(self) -> None: ...
    def get_locked(self) -> None: ...
    def get_locks(self) -> None: ...
    def get_losses(self) -> None: ...
    def get_masks(self) -> None: ...
    def get_offset(self) -> None: ...
    def get_parent(self) -> None: ...
    def get_pitch(self) -> None: ...
    def get_rect(self, **kwargs) -> None: ...
    def get_shifts(self) -> None: ...
    def get_size(self) -> tuple[int, int]: ...
    def get_view(self, kind: str = "2") -> None: ...
    def get_width(self) -> None: ...
    def lock(self, lock=None) -> None: ...
    def map_rgb(self, color) -> None: ...
    def mustlock(self) -> None: ...
    def scroll(self, dx: int = 0, dy: int = 0): ...
    def set_alpha(self, value, flags: int = 0) -> None: ...
    def set_at(self, pos, color) -> None: ...
    def set_clip(self, rect) -> None: ...
    def set_colorkey(self, color, flags: int = 0) -> None: ...
    def set_masks(self, masks) -> None: ...
    def set_shifts(self, shifts) -> None: ...
    def subsurface(self, *args) -> None: ...
    def unlock(self, lock=None) -> None: ...
    def unmap_rgb(self, pixel) -> None: ...

SRCALPHA: int
total_size: int
