import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete
from renpy.color import Color, ColorLike
from renpy.types import Unused
from typing import Literal

Rect = renpy.pygame.rect.Rect

class Surface:
    def __init__(
        self,
        size: tuple[int, int],
        flags: int = 0,
        depth: "int|Surface" = 32,
        masks: tuple[int, int, int, int] | None = None,
    ) -> None: ...
    def __reduce__(self) -> None: ...
    def __sizeof__(self) -> int: ...
    def blit(
        self,
        source: "Surface",
        dest: Rect | tuple[int, int, int, int],
        area: Incomplete | None = None,
        special_flags: int = 0,
    ) -> Incomplete: ...
    def convert(self, surface: "Surface|None" = None) -> "Surface": ...
    def convert_alpha(self, surface: "Surface|None" = None) -> "Surface": ...
    def copy(self) -> "Surface": ...
    def fill(
        self, color: ColorLike, rect: Rect | tuple[int, int, int, int] | None = None, special_flags: int = 0
    ) -> Rect: ...
    def from_data(self, data: bytes) -> None: ...
    def get_abs_offset(self) -> tuple[int, int]: ...
    def get_abs_parent(self) -> "Surface": ...
    def get_alpha(self) -> int | None: ...
    def get_at(self, pos: tuple[int, int]) -> Color: ...
    def get_at_mapped(self, pos: tuple[int, int]) -> int: ...
    def get_bitsize(self) -> int: ...
    def get_bounding_rect(self, min_alpha: int = 1) -> Rect: ...
    def get_buffer(self) -> Incomplete: ...
    def get_bytesize(self) -> int: ...
    def get_clip(self) -> tuple[int, int, int, int]: ...
    def get_colorkey(self) -> Color | None: ...
    def get_flags(self) -> int: ...
    def get_height(self) -> int: ...
    def get_locked(self) -> Literal[True] | None: ...
    def get_locks(self) -> list["Surface"]: ...
    def get_losses(self) -> tuple[int, int, int, int]: ...
    def get_masks(self) -> tuple[int, int, int, int]: ...
    def get_offset(self) -> tuple[int, int]: ...
    def get_parent(self) -> "Surface|None": ...
    def get_pitch(self) -> int: ...
    def get_rect(self, **kwargs) -> Rect: ...
    def get_shifts(self) -> tuple[int, int, int, int]: ...
    def get_size(self) -> tuple[int, int]: ...
    def get_view(self, kind: str = "2") -> None: ...
    def get_width(self) -> int: ...
    def lock(self, lock: "Surface|None" = None) -> None: ...
    def map_rgb(self, color: ColorLike) -> int: ...
    def mustlock(self) -> bool: ...
    def scroll(self, dx: int = 0, dy: int = 0) -> None: ...
    def set_alpha(self, value: int | None, flags: int = 0) -> None: ...
    def set_at(self, pos: tuple[int, int], color: ColorLike) -> None: ...
    def set_clip(self, rect: Rect | tuple[int, int, int, int] | None) -> None: ...
    def set_colorkey(self, color: ColorLike | None, flags: int = 0) -> None: ...
    def set_masks(self, masks: Unused) -> None: ...
    def set_shifts(self, shifts: Unused) -> None: ...
    def subsurface(self, *args: Rect | int) -> "Surface": ...
    def unlock(self, lock: "Surface|None" = None) -> None: ...
    def unmap_rgb(self, pixel: int) -> Color: ...

SRCALPHA: int
total_size: int
