from _typeshed import Incomplete as Incomplete

def toascii(raw): ...
def initsysfonts_win32(): ...
def initsysfonts_darwin(): ...
def initsysfonts_unix(path: str = "fc-list"): ...
def create_aliases() -> None: ...

Sysfonts: Incomplete
Sysalias: Incomplete

def initsysfonts() -> None: ...
def font_constructor(fontpath, size, bold, italic): ...
def SysFont(name, size, bold: bool = False, italic: bool = False, constructor=None): ...
def get_fonts(): ...
def match_font(name, bold: int = 0, italic: int = 0): ...
