from renpy.text.font import Font as Font

def toascii(raw: bytes | str) -> bytes: ...
def initsysfonts_win32() -> dict[str, list[str]]: ...
def initsysfonts_darwin() -> dict[str, list[str]]: ...
def initsysfonts_unix(path: str = "fc-list") -> dict[str, list[str]]: ...
def create_aliases() -> None: ...

Sysfonts: dict[str, list[str]]
Sysalias: dict[str, str]

def initsysfonts() -> None: ...
def font_constructor(fontpath: str, size: float, bold: bool, italic: bool) -> Font: ...
def SysFont(
    name: str | list[str], size: float, bold: bool = False, italic: bool = False, constructor: Font | None = None
) -> Font: ...
def get_fonts() -> list[str]: ...
def match_font(name: str, bold: int = 0, italic: int = 0) -> str | None: ...
