from _typeshed import Incomplete as Incomplete

def toascii(raw: Incomplete) -> Incomplete: ...
def initsysfonts_win32() -> Incomplete: ...
def initsysfonts_darwin() -> Incomplete: ...
def initsysfonts_unix(path: str = "fc-list") -> Incomplete: ...
def create_aliases() -> None: ...

Sysfonts: Incomplete
Sysalias: Incomplete

def initsysfonts() -> None: ...
def font_constructor(fontpath: Incomplete, size: Incomplete, bold: Incomplete, italic: Incomplete) -> Incomplete: ...
def SysFont(
    name: Incomplete, size: Incomplete, bold: bool = False, italic: bool = False, constructor: Incomplete = None
) -> Incomplete: ...
def get_fonts() -> Incomplete: ...
def match_font(name: Incomplete, bold: int = 0, italic: int = 0) -> Incomplete: ...
