from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete as Incomplete

error: Incomplete

def flip(surface: Surface, xbool: bool, ybool: bool): ...
def rotate(surface: Surface, angle): ...
def rotozoom(surface: Surface, angle: float, scale: float, smooth: int = 1): ...
def scale(surface: Surface, size, DestSurface: Surface = None): ...
def scale2x(surface: Surface, DestSurface: Surface = None): ...
def smoothscale(surface: Surface, size, DestSurface: Surface = None): ...
