import renpy

def _diff(dest: "Surface", a: "Surface", b: "Surface", same_color, different_color): ...

error = renpy.pygame.error.error

def flip(surface: "Surface", xbool: bool, ybool: bool): ...
def rotate(surface: "Surface", angle): ...
def rotozoom(surface: "Surface", angle: float, scale: float, smooth: int = 1): ...
def scale(surface: "Surface", size, DestSurface: "Surface" = None): ...
def scale2x(surface: "Surface", DestSurface: "Surface" = None): ...
def smoothscale(surface: "Surface", size, DestSurface: "Surface" = None): ...
