from _frozen_importlib import BuiltinImporter as BuiltinImporter

from renpy.pygame.surface import Surface as Surface

def flip(surface: Surface, xbool: bool, ybool: bool) -> Surface: ...
def rotate(surface: Surface, angle: float) -> Surface: ...
def rotozoom(surface: Surface, angle: float, scale: float, smooth: int = 1) -> Surface: ...
def scale(surface: Surface, size: tuple[int, int], DestSurface: Surface | None = None) -> Surface: ...
def scale2x(surface: Surface, DestSurface: Surface | None = None) -> Surface: ...
def smoothscale(surface: Surface, size: tuple[int, int], DestSurface: Surface | None = None) -> Surface: ...
