from collections.abc import Callable
from typing import Any, NamedTuple, TypeVar, overload

T = TypeVar("T")

libexec: str

class _LibExecFinder:
    in_find_spec: bool
    def __init__(self) -> None: ...
    def find_spec(self, fullname: str, path: Any | None = None, target: Any | None = None, /) -> Any | None: ...

__path__: list[str]
version_dict: dict[str, Any]
official: bool
nightly: bool
version_name: str
version_only: str

class VersionTuple(NamedTuple):
    major: int
    minor: int
    patch: int
    commit: int

version_tuple: VersionTuple
version: str
script_version: int
savegame_suffix: str
bytecode_version: int
windows: bool
macintosh: bool
linux: bool
android: bool
ios: bool
emscripten: bool
experimental: bool
arch: str
mobile: bool
macapp: bool
safe_mode_checked: bool
autoreload: bool
session: dict[str, Any]
backup_blacklist: set[str]
type_blacklist: tuple[type, ...]
name_blacklist: set[str]

class Backup:
    variables: dict[tuple[type, str], int]
    objects: dict[int, Any]
    names: dict[type, set[str]]
    def __init__(self) -> None: ...
    objects_pickle: bytes
    def backup(self) -> None: ...
    def backup_module(self, mod: type) -> None: ...
    def restore(self) -> None: ...

backup: Backup

@overload
def pure(fn: str) -> str: ...
@overload
def pure(fn: Callable) -> Callable: ...
def pure(fn: str | Callable) -> str | Callable: ...
def plog(depth: int, event: str, *args: object) -> None: ...
def import_all() -> None: ...
def post_import() -> None: ...
def issubmodule(sub: str, module: str) -> bool: ...
def reload_all() -> None: ...

# store: Any

# Generated by scripts/relative_imports.py, do not edit below this line.
from . import add_from as add_from
from . import arguments as arguments
from . import ast as ast
from . import astsupport as astsupport
from . import atl as atl
from . import audio as audio
from . import bootstrap as bootstrap
from . import character as character
from . import color as color
from . import compat as compat
from . import config as config
from . import cslots as cslots
from . import curry as curry
from . import debug as debug
from . import defaultstore as defaultstore
from . import display as display
from . import dump as dump
from . import easy as easy
from . import ecsign as ecsign
from . import editor as editor
from . import encryption as encryption
from . import error as error
from . import execution as execution
from . import exports as exports
from . import game as game
from . import gl2 as gl2
from . import importer as importer
from . import lexer as lexer
from . import lexersupport as lexersupport
from . import lint as lint
from . import loader as loader
from . import loadsave as loadsave
from . import log as log
from . import main as main
from . import memory as memory
from . import minstore as minstore
from . import object as object
from . import parameter as parameter
from . import parser as parser
from . import performance as performance
from . import persistent as persistent
from . import preferences as preferences
from . import pyanalysis as pyanalysis
from . import pydict as pydict
from . import pygame as pygame
from . import python as python
from . import revertable as revertable
from . import rollback as rollback
from . import savelocation as savelocation
from . import savetoken as savetoken
from . import screenlang as screenlang
from . import script as script
from . import scriptedit as scriptedit
from . import sl2 as sl2
from . import statements as statements
from . import store as store
from . import style as style
from . import styledata as styledata
from . import substitutions as substitutions
from . import test as test
from . import text as text
from . import tfd as tfd
from . import translation as translation
from . import types as types
from . import uguu as uguu
from . import ui as ui
from . import update as update
from . import util as util
from . import versions as versions
from . import warp as warp
from . import webloader as webloader
