from _typeshed import Incomplete as Incomplete

missing: Incomplete

def report_missing(target, filename, loc) -> None: ...

new_labels: Incomplete

def generate_label(target): ...
def process_file(fn) -> None: ...
def clear() -> None: ...
def add_from(): ...
