import renpy

missing: dict[str, list[tuple[tuple[str, int], str]]]

def report_missing(target: str, filename: str, loc: renpy.ast.NodeLocation) -> None: ...

new_labels: set[str]

def generate_label(target: str) -> str: ...
def process_file(fn: str) -> None: ...
def clear() -> None: ...
def add_from() -> bool: ...
