import argparse
from _typeshed import Incomplete
from renpy.compat import (
    PY2 as PY2,
    basestring as basestring,
    bchr as bchr,
    bord as bord,
    chr as chr,
    open as open,
    pystr as pystr,
    range as range,
    round as round,
    str as str,
    tobytes as tobytes,
    unicode as unicode,
)

commands: Incomplete
display: Incomplete
compile_commands: Incomplete

class ArgumentParser(argparse.ArgumentParser):
    group: Incomplete
    def __init__(self, second_pass: bool = True, description=None, require_command: bool = True) -> None: ...
    def add_argument(self, *args, **kwargs) -> None: ...
    def parse_known_args(self, *args, **kwargs): ...

def run(): ...
def compile(): ...
def quit(): ...
def rmpersistent(): ...
def register_command(name, function, uses_display: bool = False) -> None: ...
def bootstrap(): ...
def pre_init() -> None: ...
def post_init(): ...
def takes_no_arguments(description=None) -> None: ...

epic_arguments: Incomplete

def clean_epic_arguments() -> None: ...
def clean_macos_arguments() -> None: ...
