import argparse
from typing import Callable

commands: dict[str, Callable[[], bool]]
display: dict[str, bool]
compile_commands: set[str]

class ArgumentParser(argparse.ArgumentParser):
    group: "ArgumentParser"
    def __init__(
        self, second_pass: bool = True, description: str | None = None, require_command: bool = True
    ) -> None: ...
    def add_argument(self, *args, **kwargs) -> None: ...
    def parse_known_args(self, *args, **kwargs) -> tuple[argparse.Namespace, list[str]]: ...

def run() -> bool: ...
def compile() -> bool: ...
def quit() -> bool: ...
def rmpersistent() -> bool: ...
def register_command(name: str, function: Callable[[], bool], uses_display: bool = False) -> None: ...
def bootstrap() -> argparse.Namespace: ...
def pre_init() -> None: ...
def post_init() -> bool: ...
def takes_no_arguments(description: str | None = None) -> None: ...

epic_arguments: list[str] | None

def clean_epic_arguments() -> None: ...
def clean_macos_arguments() -> None: ...
