from _typeshed import Incomplete
import renpy
from renpy.parameter import Signature as Signature, ValuedParameter as ValuedParameter
from renpy.pyanalysis import Analysis as Analysis, GLOBAL_CONST as GLOBAL_CONST, NOT_CONST as NOT_CONST

def late_imports() -> None: ...
def compiling(loc) -> None: ...
def executing(loc) -> None: ...

warpers: Incomplete

def atl_warper(f): ...
@atl_warper
def pause(t): ...
@atl_warper
def instant(t): ...

class DualAngle:
    absolute: Incomplete
    relative: Incomplete
    def __init__(self, absolute, relative) -> None: ...
    @classmethod
    def from_any(cls, other): ...
    def __add__(self, other): ...
    def __sub__(self, other): ...
    def __mul__(self, other): ...
    __rmul__ = __mul__
    def __neg__(self): ...

def position_or_none(x): ...
def any_object(x): ...
def bool_or_none(x): ...
def float_or_none(x): ...
def matrix(x): ...
def mesh(x): ...

PROPERTIES: Incomplete
tuple_or_list: Incomplete

def interpolate(t, a, b, typ): ...
def interpolate_spline(t, spline, typ): ...
def get_catmull_rom_value(t, p_1, p0, p1, p2): ...

compile_queue: Incomplete

def compile_all() -> None: ...

NotInContext: Incomplete

class Context:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def eval(self, expr): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

class ATLTransformBase(renpy.object.Object):
    __version__: int
    parameters: Incomplete
    parent_transform: ATLTransformBase | None
    atl_st_offset: int
    predict_block: Incomplete
    nosave: Incomplete
    def after_upgrade(self, version): ...
    atl: Incomplete
    context: Incomplete
    block: Incomplete
    properties: Incomplete
    atl_state: Incomplete
    done: bool
    transform_event: Incomplete
    last_transform_event: Incomplete
    last_child_transform_event: Incomplete
    raw_child: Incomplete
    def __init__(self, atl, context, parameters) -> None: ...
    @property
    def transition(self): ...
    def get_block(self): ...
    st: Incomplete
    at: Incomplete
    st_offset: Incomplete
    at_offset: Incomplete
    child: Incomplete
    def take_execution_state(self, t) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def compile(self): ...
    def execute(self, trans, st, at): ...
    def predict_one(self) -> None: ...
    def visit(self): ...

class RawStatement:
    constant: Incomplete
    loc: Incomplete
    def __init__(self, loc) -> None: ...
    def compile(self, ctx) -> None: ...
    def predict(self, ctx) -> None: ...
    def mark_constant(self, analysis) -> None: ...

class Statement(renpy.object.Object):
    loc: Incomplete
    def __init__(self, loc) -> None: ...
    def execute(self, trans, st, state, events) -> None: ...
    def visit(self): ...

class RawBlock(RawStatement):
    animation: bool
    compiled_block: Incomplete
    statements: Incomplete
    def __init__(self, loc, statements, animation) -> None: ...
    def compile(self, ctx): ...
    def predict(self, ctx) -> None: ...
    def analyze(self, parameters=None) -> None: ...
    constant: Incomplete
    def compile_block(self) -> None: ...
    def mark_constant(self, analysis) -> None: ...

class Block(Statement):
    statements: Incomplete
    times: Incomplete
    def __init__(self, loc, statements) -> None: ...
    def execute(self, trans, st, state, events): ...
    def visit(self): ...

incompatible_props: Incomplete
compatible_pairs: Incomplete

def check_spline_types(value): ...

class RawMultipurpose(RawStatement):
    warp_function: Incomplete
    warper: Incomplete
    duration: Incomplete
    properties: Incomplete
    expressions: Incomplete
    splines: Incomplete
    revolution: Incomplete
    circles: str
    def __init__(self, loc) -> None: ...
    def add_warper(self, name, duration, warp_function) -> None: ...
    def add_property(self, name, exprs): ...
    def add_expression(self, expr, with_clause) -> None: ...
    def add_revolution(self, revolution) -> None: ...
    def add_circles(self, circles) -> None: ...
    def add_spline(self, name, exprs) -> None: ...
    def compile(self, ctx): ...
    constant: Incomplete
    def mark_constant(self, analysis) -> None: ...
    def predict(self, ctx) -> None: ...

class RawContainsExpr(RawStatement):
    expression: Incomplete
    def __init__(self, loc, expr) -> None: ...
    def compile(self, ctx): ...
    constant: Incomplete
    def mark_constant(self, analysis) -> None: ...

class RawChild(RawStatement):
    children: Incomplete
    def __init__(self, loc, child) -> None: ...
    def compile(self, ctx): ...
    constant: Incomplete
    def mark_constant(self, analysis) -> None: ...

class Child(Statement):
    child: Incomplete
    transition: Incomplete
    def __init__(self, loc, child, transition) -> None: ...
    def execute(self, trans, st, state, events): ...
    def visit(self): ...

class Interpolation(Statement):
    warper: Incomplete
    duration: Incomplete
    properties: Incomplete
    splines: Incomplete
    revolution: Incomplete
    circles: Incomplete
    def __init__(self, loc, warper, duration, properties, revolution, circles, splines) -> None: ...
    def execute(self, trans, st, state, events): ...

class RawRepeat(RawStatement):
    repeats: Incomplete
    def __init__(self, loc, repeats) -> None: ...
    def compile(self, ctx): ...
    constant: Incomplete
    def mark_constant(self, analysis) -> None: ...

class Repeat(Statement):
    repeats: Incomplete
    def __init__(self, loc, repeats) -> None: ...
    def execute(self, trans, st, state, events): ...

class RawParallel(RawStatement):
    blocks: Incomplete
    def __init__(self, loc, block) -> None: ...
    def compile(self, ctx): ...
    def predict(self, ctx) -> None: ...
    constant: Incomplete
    def mark_constant(self, analysis) -> None: ...

class Parallel(Statement):
    blocks: Incomplete
    def __init__(self, loc, blocks) -> None: ...
    def execute(self, trans, st, state, events): ...
    def visit(self): ...

class RawChoice(RawStatement):
    choices: Incomplete
    def __init__(self, loc, chance, block) -> None: ...
    def compile(self, ctx): ...
    def predict(self, ctx) -> None: ...
    constant: Incomplete
    def mark_constant(self, analysis) -> None: ...

class Choice(Statement):
    choices: Incomplete
    def __init__(self, loc, choices) -> None: ...
    def execute(self, trans, st, state, events): ...
    def visit(self): ...

class RawTime(RawStatement):
    time: Incomplete
    def __init__(self, loc, time) -> None: ...
    def compile(self, ctx): ...
    constant: Incomplete
    def mark_constant(self, analysis) -> None: ...

class Time(Statement):
    time: Incomplete
    def __init__(self, loc, time) -> None: ...
    def execute(self, trans, st, state, events): ...

class RawOn(RawStatement):
    handlers: Incomplete
    def __init__(self, loc, names, block) -> None: ...
    def compile(self, ctx): ...
    def predict(self, ctx) -> None: ...
    constant: Incomplete
    def mark_constant(self, analysis) -> None: ...

class On(Statement):
    handlers: Incomplete
    def __init__(self, loc, handlers) -> None: ...
    def execute(self, trans, st, state, events): ...
    def visit(self): ...

class RawEvent(RawStatement):
    name: Incomplete
    def __init__(self, loc, name) -> None: ...
    def compile(self, ctx): ...
    constant: Incomplete
    def mark_constant(self, analysis) -> None: ...

class Event(Statement):
    name: Incomplete
    def __init__(self, loc, name) -> None: ...
    def execute(self, trans, st, state, events): ...

class RawFunction(RawStatement):
    expr: Incomplete
    def __init__(self, loc, expr) -> None: ...
    def compile(self, ctx): ...
    constant: Incomplete
    def mark_constant(self, analysis) -> None: ...

class Function(Statement):
    function: Incomplete
    def __init__(self, loc, function) -> None: ...
    def execute(self, trans, st, state, events): ...

def parse_atl(l): ...
def deep_compare(a, b): ...
