import io
from _typeshed import TraceFunction as TraceFunction
from types import FrameType, TracebackType
from typing import Any, Callable, Never, TextIO

FSENCODING: str
old_stdout: TextIO | None
old_stderr: TextIO | None

def _setdefaultencoding(name: str) -> None: ...

class NullFile(io.IOBase):
    def write(self, s: str) -> None: ...
    def read(self, length: int | None = None) -> Never: ...
    def flush(self) -> None: ...

def null_files() -> None: ...

trace_file: io.TextIOWrapper | None
trace_local: Callable[[FrameType, str, Any], TraceFunction | None] | None

def trace_function(frame: FrameType, event: str, arg: Any) -> TraceFunction | None: ...
def enable_trace(level: int) -> None: ...
def mac_start(fn: str) -> None: ...
def popen_del(self, *args, **kwargs) -> None: ...
def get_alternate_base(basedir: str, always: bool = False) -> str: ...
def excepthook(type: type[BaseException], value: BaseException | None, traceback: TracebackType | None) -> None: ...
def relaunch() -> None: ...
def bootstrap(renpy_base: str) -> None: ...
