import re
from _typeshed import Incomplete
from typing import overload

_SHORT_COLOR_STRING_RE: re.Pattern[str]
_LONG_COLOR_STRING_RE: re.Pattern[str]
type ColorLike = "Color" | tuple[int, int, int, int] | tuple[int, int, int] | str

class Color(tuple[int, int, int, int]):
    _rgb: tuple[float, float, float] | None
    _hls: tuple[float, float, float] | None
    _hsv: tuple[float, float, float] | None
    _alpha: float | None
    _rgba: tuple[float, float, float, float] | None
    @overload
    def __new__(cls, color: Color) -> Color: ...
    @overload
    def __new__(cls, color: tuple[int, int, int, int]) -> Color: ...
    @overload
    def __new__(cls, color: tuple[int, int, int] | str, *, alpha: float = 1.0) -> Color: ...
    @overload
    def __new__(cls, *, hls: tuple[float, float, float], alpha: float = 1.0) -> Color: ...
    @overload
    def __new__(cls, *, hsv: tuple[float, float, float], alpha: float = 1.0) -> Color: ...
    @overload
    def __new__(cls, *, rgb: tuple[float, float, float], alpha: float = 1.0) -> Color: ...
    @overload
    def __new__(cls, *, alpha: float = 1.0) -> None: ...
    @property
    def hexcode(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getnewargs__(self) -> Incomplete: ...
    @property
    def rgb(self) -> tuple[float, float, float]: ...
    @property
    def rgba(self) -> tuple[float, float, float, float]: ...
    @property
    def premultiplied(self) -> tuple[float, float, float, float]: ...
    @property
    def hls(self) -> tuple[float, float, float]: ...
    @property
    def hsv(self) -> tuple[float, float, float]: ...
    @property
    def alpha(self) -> float: ...
    def normalize(self) -> Color: ...
    def __add__(self, other: ColorLike) -> Color: ...
    __radd__ = __add__
    def __sub__(self, other: ColorLike) -> Color: ...
    def __rsub__(self, other: ColorLike) -> Color: ...
    def __mul__(self, other: ColorLike) -> Color: ...
    __rmul__ = __mul__
    def _interpolate_tuple[T: tuple](self, a: T, b: T, fraction: float) -> T: ...
    def _interpolate_num[T: (float, int)](self, a: T, b: T, fraction: float) -> T: ...
    def interpolate(self, other: ColorLike, fraction: float) -> Color: ...
    def interpolate_hsv(self, other: str | Color | tuple[float, float, float], fraction: float) -> Color: ...
    def interpolate_hls(self, other: str | Color | tuple[float, float, float], fraction: float) -> Color: ...
    def tint(self, fraction: float) -> Color: ...
    def shade(self, fraction: float) -> Color: ...
    def opacity(self, opacity: float) -> Color: ...
    def rotate_hue(self, rotation: float) -> Color: ...
    def replace_hue(self, hue: float) -> Color: ...
    def multiply_hls_saturation(self, saturation: float) -> Color: ...
    def multiply_hsv_saturation(self, saturation: float) -> Color: ...
    def multiply_value(self, value: float) -> Color: ...
    def replace_hls_saturation(self, saturation: float) -> Color: ...
    def replace_hsv_saturation(self, saturation: float) -> Color: ...
    def replace_value(self, value: float) -> Color: ...
    def replace_lightness(self, lightness: float) -> Color: ...
    def replace_opacity(self, opacity: float) -> Color: ...
