from typing import overload

type ColorLike = "Color" | tuple[int, int, int, int] | tuple[int, int, int] | str

class Color(tuple[int, int, int, int]):
    @overload
    def __new__(cls, color: Color) -> Color: ...
    @overload
    def __new__(cls, color: tuple[int, int, int, int]) -> Color: ...
    @overload
    def __new__(cls, color: tuple[int, int, int] | str, *, alpha: float = 1.0) -> Color: ...
    @overload
    def __new__(cls, *, hls: tuple[float, float, float], alpha: float = 1.0) -> Color: ...
    @overload
    def __new__(cls, *, hsv: tuple[float, float, float], alpha: float = 1.0) -> Color: ...
    @overload
    def __new__(cls, *, rgb: tuple[float, float, float], alpha: float = 1.0) -> Color: ...
    @overload
    def __new__(cls, *, alpha: float = 1.0) -> None: ...
    @property
    def hexcode(self) -> str: ...
    def __getnewargs__(self): ...
    @property
    def rgb(self) -> tuple[float, float, float]: ...
    @property
    def rgba(self): ...
    @property
    def premultiplied(self): ...
    @property
    def hls(self): ...
    @property
    def hsv(self): ...
    @property
    def alpha(self): ...
    def normalize(self): ...
    def __add__(self, other: ColorLike): ...
    __radd__ = __add__
    def __sub__(self, other: ColorLike): ...
    def __rsub__(self, other: ColorLike): ...
    def __mul__(self, other: ColorLike): ...
    __rmul__ = __mul__
    def interpolate(self, other: ColorLike, fraction: float) -> Color: ...
    def interpolate_hsv(self, other: str | Color | tuple[float, float, float], fraction: float) -> Color: ...
    def interpolate_hls(self, other: str | Color | tuple[float, float, float], fraction: float) -> Color: ...
    def tint(self, fraction: float) -> Color: ...
    def shade(self, fraction: float) -> Color: ...
    def opacity(self, opacity: float) -> Color: ...
    def rotate_hue(self, rotation: float) -> Color: ...
    def replace_hue(self, hue: float) -> Color: ...
    def multiply_hls_saturation(self, saturation: float) -> Color: ...
    def multiply_hsv_saturation(self, saturation: float) -> Color: ...
    def multiply_value(self, value: float) -> Color: ...
    def replace_hls_saturation(self, saturation: float) -> Color: ...
    def replace_hsv_saturation(self, saturation: float) -> Color: ...
    def replace_value(self, value: float) -> Color: ...
    def replace_lightness(self, lightness: float) -> Color: ...
    def replace_opacity(self, opacity: float) -> Color: ...
