class Object:
    linenumber: int
    col_offset: int

class Slot[T]:
    number: int
    default_value: T
    intern: bool
    def __init__(self, default_value: T | None = None, intern: bool = False) -> None: ...
    def __get__(self, instance: Object, owner: type) -> T: ...
    def __set__(self, instance: Object, value: T) -> None: ...

class IntegerSlot:
    number: int
    default_value: int
    def __init__(self, default_value: int = 0) -> None: ...
    def __get__(self, instance: Object, owner: type) -> int: ...
    def __set__(self, instance: Object, value: int) -> None: ...
