from typing import Any

class CObject:
    col_offset: int
    linenumber: int
    def _kill(self) -> None: ...
    def _compress(self) -> None: ...
    def _decompress(self) -> None: ...

class CMetaclass(type):
    _cslot_count: int
    _cslot_setters: dict | None
    _cslot_fields: list | None
    _cslot_linenumbers: bool
    _cslot_has_getstate: bool
    def __new__(self, name: str, bases: tuple[type, ...], namespace: dict[str, Any]) -> CMetaclass: ...

class Metaclass(CMetaclass):
    def __new__(self, name: str, bases: tuple[type, ...], namespace: dict[str, Any]) -> Metaclass: ...

class Object(CObject, metaclass=Metaclass): ...

class Slot[T]:
    number: int
    default_value: T
    intern: bool
    def __init__(self, default_value: T | None = None, intern: bool = False) -> None: ...
    def __get__(self, instance: Object, owner: type) -> T: ...
    def __set__(self, instance: Object, value: T) -> None: ...

class IntegerSlot(Slot[int]): ...
