import functools
from _typeshed import Incomplete

class Curry:
    hash: Incomplete
    callable: Incomplete
    args: Incomplete
    kwargs: Incomplete
    __doc__: Incomplete
    def __init__(self, callable, *args, **kwargs) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

class Partial(functools.partial):
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

def curry(fn): ...
def partial(function, *args, **kwargs): ...
