import functools
from collections.abc import Callable
from typing import Any, TypeVar

T = TypeVar("T")

class Curry[T]:
    hash: int | None
    callable: Callable[..., T]
    args: tuple[Any, ...]
    kwargs: dict[str, Any]
    __doc__: str | None
    __name__: str | None
    def __init__(self, callable: Callable[..., T], *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> T: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Partial[T](functools.partial):
    __slots__: str | tuple[str, ...]
    def __call__(self, *args: Any, **kwargs: Any) -> T: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def curry[T](fn: Callable[..., T]) -> Partial[Partial[T]]: ...
def partial[T](function: Callable[..., T], *args: Any, **kwargs: Any) -> Partial[T]: ...
