import contextlib
from collections.abc import Callable, Generator, Iterable
from typing import Any, TypeVar, overload

from renpy.color import Color
from renpy.types import Displayable, DisplayableLike, Duplicatable

P = TypeVar("P")
R = TypeVar("R")

def lookup_displayable_prefix(d: str) -> Displayable | None: ...
def displayable_or_none(
    d: DisplayableLike | None, scope: dict[str, Any] | None = None, dynamic: bool = True
) -> Displayable | None: ...
@overload
def displayable(d: Displayable | str | list[str] | Color, scope: dict[str, Any] | None = None) -> Displayable: ...
@overload
def displayable[T: Duplicatable](d: T, scope: dict[str, Any] | None = None) -> T: ...
def displayable(d: DisplayableLike, scope: dict[str, Any] | None = None) -> Displayable | Duplicatable: ...
def dynamic_image(
    d: Any, scope: dict[str, Any] | None = None, prefix: str | None = None, search: list[str] | None = None
) -> Displayable | None: ...
def predict(d: DisplayableLike | None) -> None: ...
@contextlib.contextmanager
def timed(name: str) -> Generator[None]: ...
def split_properties(properties: dict[str, Any], *prefixes: str) -> list[dict[str, Any]]: ...
def to_list[T](value: T | Iterable[T], copy: bool = False) -> list[T]: ...
def to_tuple[T](value: T | Iterable[T]) -> tuple[T, ...]: ...
def run_callbacks[**P, R](
    cb: Callable[P, R] | list[Callable[P, R]] | None, *args: P.args, **kwargs: P.kwargs
) -> R | None: ...
