import contextlib
from collections.abc import Iterable
from renpy.types import Displayable as Displayable, DisplayableLike as DisplayableLike
from typing import Any, Callable, Generator

def lookup_displayable_prefix(d: str) -> Displayable | None: ...
def displayable_or_none(
    d: DisplayableLike | None, scope: dict[str, Any] | None = None, dynamic: bool = True
) -> Displayable | None: ...
def displayable(d: DisplayableLike, scope: dict[str, Any] | None = None) -> Displayable: ...
def dynamic_image(
    d: Any, scope: dict[str, Any] | None = None, prefix: str | None = None, search: list[str] | None = None
) -> Displayable | None: ...
def predict(d: DisplayableLike | None) -> None: ...
@contextlib.contextmanager
def timed(name: str) -> Generator[None, None, None]: ...
def split_properties(properties: dict[str, Any], *prefixes: str) -> list[dict[str, Any]]: ...
def to_list[T](value: T | Iterable[T], copy: bool = False) -> list[T]: ...
def to_tuple[T](value: T | Iterable[T]) -> tuple[T, ...]: ...
def run_callbacks[**P, R](
    cb: Callable[P, R] | list[Callable[P, R]] | None, *args: P.args, **kwargs: P.kwargs
) -> R | None: ...
