def generate_private_key() -> bytes | None: ...
def sign_data(data: bytes, private_key: bytes) -> bytes: ...
def verify_data(data: bytes, public_key: bytes, sign: bytes) -> bool: ...
def get_public_key_from_private(private_key: bytes) -> bytes | None: ...
def validate_private_key(private_key: bytes) -> bool: ...
def validate_public_key(public_key: bytes) -> bool: ...
def pem_to_der(pem: bytes | str) -> bytes: ...
def der_to_pem(der: bytes, name: str) -> bytes: ...
