from _typeshed import Incomplete

class Editor:
    def begin(self, new_window: bool = False, **kwargs: Incomplete) -> None: ...
    def end(self, **kwargs: Incomplete) -> None: ...
    def open(self, filename: str, line: int | None = None, **kwargs: Incomplete) -> None: ...
    has_projects: bool
    def open_project(self, directory: str) -> None: ...

class SystemEditor(Editor):
    def open(self, filename: str, line: int | None = None, **kwargs: Incomplete) -> None: ...

editor: Editor | None

def init() -> None: ...
def launch_editor(filenames: list[str], line: int | None = 1, transient: bool = False) -> bool: ...
