from _frozen_importlib import BuiltinImporter as BuiltinImporter

def secretbox_decrypt(cyphertext: bytes, key: bytes): ...
def secretbox_encrypt(message: bytes, key: bytes): ...

SECRETBOX_KEYBYTES: int
