import importlib.abc
import importlib.machinery
import importlib.resources.abc
import io
from _typeshed.importlib import MetaPathFinderProtocol
from collections.abc import Generator as Generator
from renpy.loader import TreeEntry as TreeEntry
from renpy.types import Unused as Unused
from types import CodeType, ModuleType
from typing import Iterable, Iterator, NamedTuple, Sequence

PREFER_LOADER: bool

class RenpyPath(importlib.resources.abc.Traversable):
    path: str
    tree: TreeEntry | None
    def __init__(self, path: str, tree: TreeEntry | None) -> None: ...
    @property
    def name(self) -> str: ...
    def iterdir(self) -> Iterator["importlib.resources.abc.Traversable"]: ...
    def is_dir(self) -> bool: ...
    def is_file(self) -> bool: ...
    def __truediv__(self, other: str) -> RenpyPath: ...
    def joinpath(self, *args: str) -> RenpyPath: ...
    def open(self, mode: str = "r", *args, **kwargs) -> io.BufferedReader | io.TextIOWrapper: ...
    def read_text(self, encoding=None) -> str: ...
    def read_bytes(self) -> bytes: ...

class RenpyResourceReader(importlib.resources.abc.TraversableResources):
    path: str
    def __init__(self, path: str) -> None: ...
    def files(self) -> importlib.resources.abc.Traversable: ...

class RenpyImporter(importlib.abc.MetaPathFinder, importlib.abc.InspectLoader):
    prefixes: list[str]
    _finder_cache: dict[str, RenpyImporter._ModuleInfo] | None
    def __init__(self) -> None: ...
    def add_prefix(self, prefix: str) -> None: ...
    class _ModuleInfo(NamedTuple):
        filename: str
        is_package: bool
        is_namespace: bool

    def _visit_dir(self, *path: str, files: Iterable[str]) -> Iterable[tuple[str, _ModuleInfo]]: ...
    def _cache_entries(self) -> dict[str, _ModuleInfo]: ...
    def _get_module_info(self, fullname: str) -> _ModuleInfo | None: ...
    def invalidate_caches(self) -> None: ...
    def find_spec(
        self, fullname: str, path: Sequence[str] | None, target: ModuleType | None = None
    ) -> importlib.machinery.ModuleSpec | None: ...
    def get_resource_reader(self, fullname: str) -> RenpyResourceReader | None: ...
    def is_package(self, fullname: str) -> bool: ...
    def get_source(self, fullname: str) -> str | None: ...
    def get_code(self, fullname: str) -> CodeType: ...
    def get_data(self, path: str) -> bytes: ...

meta_backup: list[MetaPathFinderProtocol]

def add_python_directory(path: str): ...
def init_importer() -> None: ...
def quit_importer() -> None: ...
