import importlib.abc
import importlib.resources.abc
import io
from _typeshed import Incomplete
from collections.abc import Generator
from renpy.loader import TreeEntry as TreeEntry
from typing import NamedTuple

PREFER_LOADER: bool

class RenpyPath(importlib.resources.abc.Traversable):
    path: str
    tree: TreeEntry | None
    def __init__(self, path: str, tree: TreeEntry | None) -> None: ...
    @property
    def name(self) -> str: ...
    def iterdir(self) -> Generator[Incomplete, None, Incomplete]: ...
    def is_dir(self) -> bool: ...
    def is_file(self) -> bool: ...
    def __truediv__(self, other: str) -> RenpyPath: ...
    def joinpath(self, *args: str) -> RenpyPath: ...
    def open(self, mode: str = "r", *args, **kwargs) -> io.BufferedReader | io.TextIOWrapper: ...
    def read_text(self, encoding=None) -> str: ...
    def read_bytes(self) -> bytes: ...

class RenpyResourceReader(importlib.resources.abc.TraversableResources):
    path: Incomplete
    def __init__(self, path: str) -> None: ...
    def files(self) -> importlib.resources.abc.Traversable: ...

class RenpyImporter(importlib.abc.MetaPathFinder, importlib.abc.InspectLoader):
    prefixes: list[str]
    def __init__(self) -> None: ...
    def add_prefix(self, prefix: str): ...
    class _ModuleInfo(NamedTuple):
        filename: str
        is_package: bool
        is_namespace: bool

    def invalidate_caches(self) -> None: ...
    def find_spec(self, fullname, path, target=None): ...
    def get_resource_reader(self, fullname: str) -> RenpyResourceReader | None: ...
    def is_package(self, fullname: str) -> bool: ...
    def get_source(self, fullname: str) -> str | None: ...
    def get_code(self, fullname: str): ...
    def get_data(self, path: str): ...

meta_backup: Incomplete

def add_python_directory(path: str): ...
def init_importer() -> None: ...
def quit_importer() -> None: ...
