def match_logical_word(s: str, pos: int, data: str) -> tuple[str, bool, int]: ...
def match_whitespace(data: str, pos: int, /) -> int | None: ...
def match_operator(data: str, pos: int, /) -> int | None: ...
def match_string(data: str, prefix_pos: int, pos: int, /) -> tuple[int, bool, int, int | None] | Literal[-1] | None: ...
