from _typeshed import Incomplete

python_builtins: Incomplete
renpy_builtins: Incomplete
image_prefixes: Incomplete
report_node: Incomplete
all_define_statements: Incomplete
all_default_statements: Incomplete
error_reported: bool

def report(msg, *args) -> None: ...

added: Incomplete

def add(msg, *args) -> None: ...
def problem_listing(header, problems) -> None: ...
def try_eval(where, expr, additional=None) -> None: ...
def try_compile(where, expr, additional=None) -> None: ...

imprecise_cache: Incomplete

def image_exists_imprecise(name): ...

precise_cache: Incomplete

def image_exists_precise(name): ...
def image_exists(name, expression, tag, precise: bool = True) -> None: ...

check_file_cache: Incomplete

def check_file(what, fn, directory=None) -> None: ...
def check_displayable(what, d): ...
def check_image(node) -> None: ...
def imspec(t): ...
def check_show(node, precise) -> None: ...
def precheck_show(node) -> None: ...
def check_hide(node) -> None: ...
def check_with(node) -> None: ...
def check_user(node) -> None: ...
def quote_text(s): ...
def text_checks(s) -> None: ...
def check_say(node) -> None: ...
def check_menu(node) -> None: ...
def check_jump(node) -> None: ...
def check_call(node) -> None: ...
def check_while(node) -> None: ...
def check_if(node) -> None: ...
def check_define(node, kind) -> None: ...
def check_redefined(node, kind) -> None: ...
def check_style_property_displayable(name, property, d): ...
def check_style(name, s) -> None: ...
def check_parameters(kind, node_name, parameter_info) -> None: ...
def check_label(node) -> None: ...
def check_screen(node) -> None: ...
def check_styles() -> None: ...
def check_init(node) -> None: ...
def check_transform(node) -> None: ...
def humanize(n): ...
def check_filename_encodings() -> None: ...

class Count:
    blocks: int
    words: int
    characters: int
    def __init__(self) -> None: ...
    def add(self, s) -> None: ...
    def tuple(self): ...

def common(n): ...
def report_character_stats(charastats): ...
def check_image_manipulators() -> None: ...
def check_unreachables(all_nodes) -> None: ...
def check_orphan_translations(none_lang_identifiers, translation_identifiers) -> None: ...
def check_python_warnings() -> None: ...
def lint(): ...
