import renpy
from typing import Literal, overload

python_builtins: set[str]
renpy_builtins: set[str]
image_prefixes: dict[str | None, bool] | None
report_node: renpy.ast.Node | None
all_define_statements: dict[str, renpy.ast.Define]
all_default_statements: dict[str, renpy.ast.Default]
error_reported: bool

def report(msg: str, *args) -> None: ...

added: dict[str, bool]

def add(msg: str, *args) -> None: ...
def problem_listing(header: str, problems: list[tuple[str, int, str]]) -> None: ...
def try_eval(where: str, expr: str, additional: str | None = None) -> None: ...
def try_compile(where: str, expr: str, additional: str | None = None) -> None: ...

imprecise_cache: set[tuple[str, ...]]

def image_exists_imprecise(name: tuple[str, ...]) -> bool: ...

precise_cache: set[tuple[str, ...]]

def image_exists_precise(name: tuple[str, ...]) -> bool: ...
def image_exists(name: tuple[str, ...], expression: str | None, tag: str | None, precise: bool = True) -> None: ...

check_file_cache: dict[str, bool]

def check_file(what: str, fn: str, directory: str | None = None) -> None: ...
def check_displayable(what: str, d: renpy.display.displayable.Displayable) -> None: ...
def check_image(node: renpy.ast.Image) -> None: ...
def imspec(
    t: renpy.ast.ImspecType,
) -> tuple[tuple[str, ...], str | None, str | None, list[str], str | None, int | None, list[str] | None]: ...
def check_show(node: renpy.ast.Show | renpy.ast.Scene, precise: bool) -> None: ...
def precheck_show(node: renpy.ast.Show | renpy.ast.Scene) -> None: ...
def check_hide(node: renpy.ast.Hide) -> None: ...
def check_with(node: renpy.ast.With) -> None: ...
def check_user(node: renpy.ast.UserStatement) -> None: ...
def quote_text(s: str) -> str: ...
def text_checks(s: str) -> None: ...
def check_say(node: renpy.ast.Say) -> None: ...
def check_menu(node: renpy.ast.Menu) -> None: ...
def check_jump(node: renpy.ast.Jump) -> None: ...
def check_call(node: renpy.ast.Call) -> None: ...
def check_while(node: renpy.ast.While) -> None: ...
def check_if(node: renpy.ast.If) -> None: ...
@overload
def check_define(node: renpy.ast.Define, kind: Literal["define"]) -> None: ...
@overload
def check_define(node: renpy.ast.Default, kind: Literal["default"]) -> None: ...
@overload
def check_redefined(node: renpy.ast.Define, kind: Literal["define"]) -> None: ...
@overload
def check_redefined(node: renpy.ast.Default, kind: Literal["default"]) -> None: ...
def check_style_property_displayable(name: str, property: str, d: renpy.display.displayable.Displayable) -> None: ...
def check_style(name: str, s: renpy.style.StyleCore) -> None: ...
def check_parameters(
    kind: str, node_name: renpy.ast.NodeName, parameter_info: renpy.parameter.ParameterInfo | None
) -> None: ...
def check_label(node: renpy.ast.Label) -> None: ...
def check_screen(node: renpy.ast.Screen) -> None: ...
def check_styles() -> None: ...
def check_init(node: renpy.ast.Init) -> None: ...
def check_transform(node: renpy.ast.Transform) -> None: ...
def humanize(n: int) -> str: ...
def check_filename_encodings() -> None: ...

class Count:
    blocks: int
    words: int
    characters: int
    def __init__(self) -> None: ...
    def add(self, s: str) -> None: ...
    def tuple(self) -> tuple[int, int, int]: ...

def common(n: renpy.ast.Node) -> bool: ...
def report_character_stats(charastats: dict[str, Count]) -> list[str | list[str]]: ...
def check_image_manipulators() -> None: ...
def check_unreachables(all_nodes: list[renpy.ast.Node]) -> None: ...
def check_orphan_translations(
    none_lang_identifiers: set[str | None],
    translation_identifiers: dict[str | None, list[renpy.ast.Translate | renpy.ast.TranslateSay]],
) -> None: ...
def check_python_warnings() -> None: ...
def lint() -> bool: ...
