import renpy
import threading
from collections.abc import Generator
from renpy.compat.pickle import loads as loads
from renpy.pygame.rwobject import RWopsIO as RWopsIO
from renpy.webloader import DownloadNeeded as DownloadNeeded
from typing import Callable, IO, Literal, TypedDict

class RemoteFileInfo(TypedDict):
    type: str
    size: str | list[int]

type AddCallback = Callable[[str | None, str, list[tuple[str | None, str]], set[str]], None]
type Handler = "type[RPAv3ArchiveHandler | RPAv2ArchiveHandler | RPAv1ArchiveHandler]"

def get_path(fn: str) -> str: ...

apks: list[android.apk.APK]
game_apks: list[android.apk.APK]
split_apks: list[android.apk.APK]

def find_apks() -> None: ...

archives: list[tuple[str, dict[str, list[tuple[int, int] | tuple[int, int, bytes]]]]]
lower_map: dict[str, str]

class ArchiveHandlers:
    exts: dict[str, list[tuple[bytes, Handler]]]
    peek: dict[str, int]
    def __init__(self) -> None: ...
    def append(self, handler: Handler) -> None: ...
    def spec(self, ext: str) -> tuple[int, list[tuple[bytes, Handler]]]: ...

archive_handlers: ArchiveHandlers

class RPAv3ArchiveHandler:
    archive_extension: str
    @staticmethod
    def get_supported_extensions() -> list[str]: ...
    @staticmethod
    def get_supported_headers() -> list[bytes]: ...
    @staticmethod
    def read_index(infile: IO) -> dict[str, list[tuple[int, int] | tuple[int, int, bytes]]]: ...

class RPAv2ArchiveHandler:
    archive_extension: str
    @staticmethod
    def get_supported_extensions() -> list[str]: ...
    @staticmethod
    def get_supported_headers() -> list[bytes]: ...
    @staticmethod
    def read_index(infile: IO) -> dict[str, list[tuple[int, int] | tuple[int, int, bytes]]]: ...

class RPAv1ArchiveHandler:
    archive_extension: str
    @staticmethod
    def get_supported_extensions() -> list[str]: ...
    @staticmethod
    def get_supported_headers() -> list[bytes]: ...
    @staticmethod
    def read_index(infile: IO) -> dict[str, list[tuple[int, int] | tuple[int, int, bytes]]]: ...

def index_files() -> None: ...
def index_archives() -> None: ...
def walkdir(path: str, elide: int | None = None) -> Generator[str, None, None]: ...

arc_files: list[tuple[str, str, str]]
common_files: list[tuple[str | None, str]]
game_files: list[tuple[str | None, str]]
loadable_cache: dict[str, bool]
remote_files: dict[str, RemoteFileInfo]
scandirfiles_callbacks: list[Callable[[AddCallback, set[str]], None]]
type TreeEntry = dict[str, "TreeEntry"] | Literal[True]
tree: TreeEntry

def scandirfiles() -> None: ...
def scandirfiles_from_apk(add: AddCallback, seen: set[str]) -> None: ...
def scandirfiles_from_remote_file(add: AddCallback, seen: set[str]) -> None: ...
def scandirfiles_from_filesystem(add: AddCallback, seen: set[str]) -> None: ...
def scandirfiles_from_archives(add: AddCallback, seen: set[str]) -> None: ...
def listdirfiles(common: bool = True, game: bool = True) -> list[tuple[str | None, str]]: ...

open_file = RWopsIO
file_open_callbacks: list[Callable[[str], IO | None]]

def load_core(name: str) -> IO | None: ...
def load_from_file_open_callback(name: str) -> IO | None: ...
def load_from_filesystem(name: str) -> IO | None: ...
def load_from_archive(name: str) -> IO | None: ...
def load_from_apk(name: str) -> IO | None: ...
def load_from_remote_file(name: str) -> None: ...
def check_name(name: str) -> None: ...
def get_prefixes(tl: bool = True, directory: str | None = None) -> list[str]: ...
def load(name: str, directory: str | None = None, tl: bool = True) -> IO: ...
def loadable_core(name: str) -> bool: ...
def loadable(name: str, tl: bool = True, directory: str | None = None) -> bool: ...
def transpath(path: str) -> str | None: ...
def transfn(name: bytes | str) -> str: ...

hash_cache: dict[str, int]

def get_hash(name: str) -> int: ...

needs_autoreload: set[str]
auto_mtimes: dict[str, float | None | renpy.object.Sentinel]
auto_thread: threading.Thread | None
auto_quit_flag: bool
auto_lock: threading.Condition
auto_blacklisted: renpy.object.Sentinel

def auto_mtime(fn: str) -> float | None: ...
def add_auto(fn: str, force: bool = False) -> None: ...

max_mtime: float

def auto_thread_function() -> None: ...
def check_git_index_lock() -> bool: ...

reloading: bool

def check_autoreload() -> None: ...
def auto_init() -> None: ...
def auto_quit() -> None: ...
