import abc
from renpy.types import Unused as Unused
from typing import Any, Callable, TextIO

sys_stdout: TextIO | None
sys_stderr: TextIO | None
real_stdout: TextIO | None
real_stderr: TextIO | None
log_file: Unused

class LogFile(TextIO, metaclass=abc.ABCMeta):
    name: str
    append: bool
    developer: bool
    flush: bool
    file: TextIO | None
    softspace: Unused
    newlines: Unused
    raw_write: bool
    def __init__(self, name: str, append: bool = False, developer: bool = False, flush: bool = True) -> None: ...
    def open(self) -> bool: ...
    def write(self, s: str | bytes, *args) -> None: ...
    def exception(self) -> None: ...

log_cache: dict[str, LogFile]

class TimeLog(list):
    duration: float
    def __init__(self, duration: float) -> None: ...
    def append(self, v: Any) -> None: ...
    def prune(self, now: float | None = None) -> None: ...

class StdioRedirector:
    real_file: TextIO | None
    buffer: str
    log: LogFile
    encoding: str
    def __init__(self) -> None: ...
    def write(self, s: str | bytes) -> None: ...
    def fileno(self) -> int: ...
    def isatty(self) -> bool: ...
    def writelines(self, lines: list[str | bytes]) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def get_callbacks(self) -> list[Callable[[str], None]]: ...

class StdoutRedirector(StdioRedirector):
    real_file = real_stdout
    def get_callbacks(self) -> Incomplete: ...

class StderrRedirector(StdioRedirector):
    real_file = real_stderr
    def get_callbacks(self) -> Incomplete: ...

def post_init() -> None: ...
