from _typeshed import Incomplete as Incomplete

last_clock: Incomplete

def log_clock(s) -> None: ...
def reset_clock() -> None: ...
def run(restart) -> None: ...
def load_rpe(fn) -> None: ...
def load_rpe_py(fn) -> None: ...
def choose_variants() -> None: ...
def load_build_info() -> None: ...
def main() -> None: ...
