from _typeshed import Incomplete as Incomplete

last_clock: Incomplete

def log_clock(s: Incomplete) -> None: ...
def reset_clock() -> None: ...
def run(restart: Incomplete) -> None: ...
def load_rpe(fn: Incomplete) -> None: ...
def load_rpe_py(fn: Incomplete) -> None: ...
def choose_variants() -> None: ...
def load_build_info() -> None: ...
def main() -> None: ...
