from _typeshed import Incomplete as Incomplete

last_clock: float

def log_clock(s: str) -> None: ...
def reset_clock() -> None: ...
def run(restart: Incomplete) -> None: ...
def load_rpe(fn: str) -> None: ...
def load_rpe_py(fn: str) -> None: ...
def choose_variants() -> None: ...
def load_build_info() -> None: ...
def main() -> None: ...
