from _typeshed import Incomplete as Incomplete

memory_log: Incomplete
constant_containers: Incomplete

def print_garbage(gen) -> None: ...
def write(s) -> None: ...
def cycle_finder(o, name): ...
def walk_memory(roots, seen=None): ...
def profile_memory_common(packages=["renpy", "store"], skip_constants: bool = False): ...
def profile_memory(fraction: float = 1.0, minimum: int = 0, skip_constants: bool = False) -> None: ...

old_usage: Incomplete
old_total: int

def diff_memory(update: bool = True, skip_constants: bool = False) -> None: ...
def profile_rollback() -> None: ...
def find_parents(cls) -> None: ...
