import collections
import renpy
from typing import Any

memory_log: renpy.log.LogFile
constant_containers: set[str]

def print_garbage(gen: int) -> None: ...
def write(s: str) -> None: ...
def cycle_finder(o: Any, name: str) -> None: ...
def walk_memory(
    roots: list[tuple[str, Any]], seen: dict[int, str] | None = None
) -> tuple[collections.defaultdict[str, int], dict[int, str]]: ...
def profile_memory_common(
    packages: list[str] = ["renpy", "store"], skip_constants: bool = False
) -> tuple[collections.defaultdict[str, int], dict[int, str]]: ...
def profile_memory(fraction: float = 1.0, minimum: int = 0, skip_constants: bool = False) -> None: ...

old_usage: collections.defaultdict[str, int]
old_total: int

def diff_memory(update: bool = True, skip_constants: bool = False) -> None: ...
def profile_rollback() -> None: ...
def find_parents(cls) -> None: ...
