from _typeshed import Incomplete as Incomplete

memory_log: Incomplete
constant_containers: Incomplete

def print_garbage(gen: Incomplete) -> None: ...
def write(s: Incomplete) -> None: ...
def cycle_finder(o: Incomplete, name: Incomplete) -> Incomplete: ...
def walk_memory(roots: Incomplete, seen: Incomplete = None) -> Incomplete: ...
def profile_memory_common(packages: Incomplete = ["renpy", "store"], skip_constants: bool = False) -> Incomplete: ...
def profile_memory(fraction: float = 1.0, minimum: int = 0, skip_constants: bool = False) -> None: ...

old_usage: Incomplete
old_total: int

def diff_memory(update: bool = True, skip_constants: bool = False) -> None: ...
def profile_rollback() -> None: ...
def find_parents(cls: Incomplete) -> None: ...
