from _typeshed import Incomplete
from renpy.lexer import (
    Lexer as Lexer,
    ParseError as ParseError,
    SubParse as SubParse,
    elide_filename as elide_filename,
    group_logical_lines as group_logical_lines,
    list_logical_lines as list_logical_lines,
    munge_filename as munge_filename,
    unelide_filename as unelide_filename,
)
from renpy.parameter import EMPTY_ARGUMENTS as EMPTY_ARGUMENTS, Parameter as Parameter

parse_errors: Incomplete
deferred_parse_errors: Incomplete

def parse_image_name(l, string: bool = False, nodash: bool = False): ...
def parse_simple_expression_list(l, image: bool = False): ...
def parse_image_specifier(l): ...
def parse_with(l, node): ...
def parse_menu(stmtl, loc, arguments): ...
def parse_parameters(l): ...
def parse_arguments(l): ...

class ParseTrie:
    default: Incomplete
    words: Incomplete
    def __init__(self) -> None: ...
    def add(self, name, function) -> None: ...
    def parse(self, l): ...

statements: Incomplete

def statement(keywords): ...
def if_statement(l, loc): ...
def IF_statement(l, loc): ...
def while_statement(l, loc): ...
def pass_statement(l, loc): ...
def menu_statement(l, loc): ...
def return_statement(l, loc): ...
def jump_statement(l, loc): ...
def call_statement(l, loc): ...
def scene_statement(l, loc): ...
def show_statement(l, loc): ...
def show_layer_statement(l, loc): ...
def camera_statement(l, loc): ...
def hide_statement(l, loc): ...
def with_statement(l, loc): ...
def image_statement(l, loc): ...
def define_statement(l, loc): ...
def default_statement(l, loc): ...
def transform_statement(l, loc): ...
def one_line_python(l, loc): ...
def python_statement(l, loc): ...
def label_statement(l, loc, init: bool = False): ...
def init_offset_statement(l, loc): ...
def init_label_statement(l, loc): ...
def init_statement(l, loc): ...
def rpy_statement(l, loc): ...
def screen_statement(l, loc): ...
def testcase_statement(l, loc): ...
def testsuite_statement(l, loc): ...
def translate_strings(init_loc, language, l): ...

translate_none_files: Incomplete

def translate_statement(l, loc): ...
def style_statement(l, loc): ...
def rpy_python(l, loc): ...
def finish_say(l, loc, who, what, attributes=None, temporary_attributes=None, interact: bool = True): ...
def say_attributes(l): ...
def say_statement(l, loc): ...
def parse_statement(l): ...
def parse_block(l): ...
def parse(fn, filedata=None, linenumber: int = 1): ...
def release_deferred_errors(): ...
def get_parse_errors(): ...
def report_parse_errors(): ...
