from _typeshed import Incomplete as Incomplete

fpl: Incomplete
DEPTH_LEVELS: int
running: bool

def clear() -> None: ...
def log(depth: Incomplete, event: Incomplete, *args: Incomplete) -> None: ...
def PPP(event: Incomplete, *args: Incomplete) -> None: ...
def analyze() -> None: ...
