from typing import Any

fpl: list[tuple[float, int, str, tuple[Any]]]
DEPTH_LEVELS: int
running: bool

def clear() -> None: ...
def log(depth: int, event: str, *args: Any) -> None: ...
def PPP(event: str, *args: Any) -> None: ...
def analyze() -> None: ...
