from _typeshed import Incomplete as Incomplete

fpl: Incomplete
DEPTH_LEVELS: int
running: bool

def clear() -> None: ...
def log(depth, event, *args) -> None: ...
def PPP(event, *args) -> None: ...
def analyze() -> None: ...
