class DictItems:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...
    def as_dict(self): ...

def find_changes(old: "DictItems", new: "DictItems", deleted): ...
