from _frozen_importlib import BuiltinImporter as BuiltinImporter

class DictItems:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def as_dict(self) -> None: ...

def find_changes(old: DictItems, new: DictItems, deleted): ...
