from _typeshed import Incomplete
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from typing import Any

class DictItems:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def as_dict(self) -> dict[str, Any]: ...

def find_changes(
    old: "DictItems", new: "DictItems", deleted: renpy.rollback.StoreDeleted
) -> dict[str, Incomplete] | None: ...
