import ast
import contextlib
from _typeshed import Incomplete as Incomplete
from collections.abc import Generator
from renpy.astsupport import hash32 as hash32
from renpy.pydict import DictItems as DictItems, find_changes as find_changes
from typing import Any

class StoreModule:
    def __reduce__(self): ...
    def __init__(self, d) -> None: ...
    def __setattr__(self, key, value) -> None: ...
    def __delattr__(self, key) -> None: ...

def get_store_module(name): ...

class StoreDict(dict):
    def __reduce__(self) -> None: ...
    old: Incomplete
    ever_been_changed: Incomplete
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def begin(self) -> None: ...
    def get_changes(self, cycle, previous): ...

def begin_stores() -> None: ...

store_dicts: Incomplete
store_modules: Incomplete
initialized_store_dicts: Incomplete

def create_store(name) -> None: ...

class StoreBackup:
    store: Incomplete
    old: Incomplete
    ever_been_changed: Incomplete
    def __init__(self) -> None: ...
    def backup_one(self, name) -> None: ...
    def restore_one(self, name) -> None: ...
    def restore(self) -> None: ...

clean_store_backup: StoreBackup | None

def make_clean_stores() -> None: ...
def clean_stores() -> None: ...
def clean_store(name) -> None: ...
def reset_store_changes(name) -> None: ...
def mark_changed(name: str, variable: str): ...

class LoadedVariables(ast.NodeVisitor):
    def visit_Name(self, node) -> None: ...
    def visit_MatchMapping(self, node) -> None: ...
    def visit_MatchStar(self, node) -> None: ...
    def visit_MatchAs(self, node) -> None: ...
    def visit_arg(self, node) -> None: ...
    loaded: Incomplete
    stored: Incomplete
    def find(self, node): ...

find_loaded_variables: Incomplete

class StarredVariables(ast.NodeVisitor):
    def visit_Starred(self, node) -> None: ...
    def visit_Name(self, node) -> None: ...
    starred: Incomplete
    def find(self, targets): ...

find_starred_variables: Incomplete

class FindStarredMatchPatterns(ast.NodeVisitor):
    vars: Incomplete
    def __init__(self) -> None: ...
    def visit_MatchStar(self, node: ast.MatchStar) -> Any: ...
    def visit_MatchMapping(self, node: ast.MatchMapping) -> Any: ...

def find_starred_match_patterns(node): ...

class WrapNode(ast.NodeTransformer):
    call_import_from: bool
    def __init__(self) -> None: ...
    def wrap_generator(self, node): ...
    def wrap_starred_assign(self, n, targets): ...
    def wrap_starred_for(self, node): ...
    def wrap_starred_with(self, node): ...
    def wrap_match_case(self, node): ...
    def visit_Assign(self, node: ast.Assign): ...
    def visit_AnnAssign(self, node: ast.AnnAssign): ...
    def visit_For(self, node): ...
    def visit_AsyncFor(self, node): ...
    def visit_With(self, node): ...
    def visit_AsyncWith(self, node): ...
    def visit_ClassDef(self, node: ast.ClassDef): ...
    def visit_GeneratorExp(self, node): ...
    def visit_SetComp(self, node): ...
    def visit_Set(self, node): ...
    def visit_ListComp(self, node): ...
    def visit_List(self, node): ...
    def visit_DictComp(self, node): ...
    def visit_Dict(self, node): ...
    def visit_Match(self, node: ast.Match): ...
    def visit_FunctionDef(self, node): ...
    def visit_ImportFrom(self, node): ...

wrap_node: Incomplete

def wrap_hide(tree) -> None: ...

compile_warnings: Incomplete

@contextlib.contextmanager
def save_warnings() -> Generator[None]: ...

file_compiler_flags: Incomplete
py_compile_cache: Incomplete
old_py_compile_cache: Incomplete

class LocationFixer:
    line_delta: int
    first_line_col_delta: int
    rest_line_col_delta: int
    def __init__(
        self,
        node: ast.Module | ast.Expression,
        line_delta: int = 0,
        first_line_col_delta: int = 0,
        rest_line_col_delta: int = 0,
    ) -> None: ...
    def fix(self, node: ast.stmt, lineno: int, col_offset: int): ...

def quote_eval(s): ...

IMMUTABLE_TYPES: Incomplete

def is_immutable_value(v): ...
def py_compile(
    source,
    mode,
    filename: str = "<none>",
    lineno: int = 1,
    ast_node: bool = False,
    cache: bool = True,
    py=None,
    hashcode=None,
    column: int = 0,
): ...
def py_exec_bytecode(bytecode, hide: bool = False, globals=None, locals=None, store: str = "store") -> None: ...
def py_exec(source, hide: bool = False, store=None) -> None: ...
def py_eval_bytecode(bytecode, globals=None, locals=None): ...
def py_eval(code, globals=None, locals=None): ...
def store_eval(code, globals=None, locals=None): ...
def raise_at_location(e, loc) -> None: ...

class StoreProxy:
    def __getattr__(self, k): ...
    def __setattr__(self, k, v) -> None: ...
    def __delattr__(self, k) -> None: ...

def method_unpickle(obj, name): ...
def module_pickle(module): ...
def module_unpickle(name): ...
def construct_None(*args) -> None: ...
