import renpy
import threading
from renpy.loadsave import SaveRecord as SaveRecord, clear_slot as clear_slot, safe_rename as safe_rename
from types import TracebackType
from typing import Any, Self

disk_lock: threading.RLock
tmp: str
pause_syncfs_count: int

def pause_syncfs() -> None: ...
def resume_syncfs() -> None: ...

class SyncfsLock:
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exception_type: type[BaseException] | None,
        exception_value: BaseException | None,
        exception_traceback: TracebackType | None,
    ) -> None: ...

def syncfs() -> None: ...

class FileLocation:
    directory: str
    active: bool
    mtimes: dict[str, float]
    persistent: str
    persistent_mtime: float
    persistent_data: renpy.persistent.Persistent | None
    def __init__(self, directory: str) -> None: ...
    def filename(self, slotname: str) -> str: ...
    def sync(self) -> None: ...
    def scan(self) -> None: ...
    def save(self, slotname: str, record: SaveRecord) -> None: ...
    def list(self) -> list[str]: ...
    def list_files(self) -> list[str]: ...
    def mtime(self, slotname: str) -> float | None: ...
    def path(self, filename: str) -> tuple[float, str | None]: ...
    def json(self, slotname: str) -> dict[str, Any] | None: ...
    def screenshot(self, slotname: str) -> renpy.display.im.ZipFileImage | None: ...
    def load(self, slotname: str) -> tuple[bytes, str]: ...
    def unlink(self, slotname: str) -> None: ...
    def rename(self, old: str, new: str) -> None: ...
    def copy(self, old: str, new: str) -> None: ...
    def load_persistent(self, *, consume: bool = False) -> list[tuple[float, renpy.persistent.Persistent]]: ...
    def save_persistent(self, data: renpy.persistent.Persistent) -> None: ...
    def unlink_persistent(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class MultiLocation:
    locations: list[FileLocation]
    def __init__(self) -> None: ...
    def active_locations(self) -> list[FileLocation]: ...
    def newest(self, slotname: str) -> FileLocation | None: ...
    def add(self, location: FileLocation) -> None: ...
    def save(self, slotname: str, record: SaveRecord) -> None: ...
    def list(self) -> list[str]: ...
    def list_files(self) -> list[str]: ...
    def path(self, filename: str) -> tuple[float, str | None]: ...
    def mtime(self, slotname: str) -> float | None: ...
    def json(self, slotname: str) -> dict[str, Any] | None: ...
    def screenshot(self, slotname: str) -> renpy.display.im.ZipFileImage | None: ...
    def load(self, slotname: str) -> tuple[bytes, str]: ...
    def unlink(self, slotname: str) -> None: ...
    def rename(self, old: str, new: str) -> None: ...
    def copy(self, old: str, new: str) -> None: ...
    def load_persistent(self, *, consume: bool = False) -> list[tuple[float, renpy.persistent.Persistent]]: ...
    def save_persistent(self, data: renpy.persistent.Persistent) -> None: ...
    def unlink_persistent(self) -> None: ...
    def scan(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

scan_thread: threading.Thread | None
quit_scan_thread: bool
scan_thread_condition: threading.Condition

def run_scan_thread() -> None: ...
def quit() -> None: ...
def init() -> None: ...
def zip_saves() -> bool: ...
def unzip_saves() -> bool: ...
