from _typeshed import Incomplete as Incomplete
from renpy.loadsave import clear_slot as clear_slot, safe_rename as safe_rename
from types import TracebackType

disk_lock: Incomplete
tmp: Incomplete
pause_syncfs_count: int

def pause_syncfs() -> None: ...
def resume_syncfs() -> None: ...

class SyncfsLock:
    def __enter__(self): ...
    def __exit__(
        self,
        exception_type: type[BaseException] | None,
        exception_value: BaseException | None,
        exception_traceback: TracebackType | None,
    ) -> None: ...

def syncfs() -> None: ...

class FileLocation:
    directory: Incomplete
    active: bool
    mtimes: Incomplete
    persistent: Incomplete
    persistent_mtime: Incomplete
    persistent_data: Incomplete
    def __init__(self, directory) -> None: ...
    def filename(self, slotname): ...
    def sync(self) -> None: ...
    def scan(self) -> None: ...
    def save(self, slotname, record) -> None: ...
    def list(self): ...
    def list_files(self): ...
    def mtime(self, slotname): ...
    def path(self, filename): ...
    def json(self, slotname): ...
    def screenshot(self, slotname): ...
    def load(self, slotname): ...
    def unlink(self, slotname) -> None: ...
    def rename(self, old, new) -> None: ...
    def copy(self, old, new) -> None: ...
    def load_persistent(self, *, consume: bool = False): ...
    def save_persistent(self, data) -> None: ...
    def unlink_persistent(self) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

class MultiLocation:
    locations: Incomplete
    def __init__(self) -> None: ...
    def active_locations(self): ...
    def newest(self, slotname): ...
    def add(self, location) -> None: ...
    def save(self, slotname, record) -> None: ...
    def list(self): ...
    def list_files(self): ...
    def path(self, filename): ...
    def mtime(self, slotname): ...
    def json(self, slotname): ...
    def screenshot(self, slotname): ...
    def load(self, slotname): ...
    def unlink(self, slotname) -> None: ...
    def rename(self, old, new) -> None: ...
    def copy(self, old, new) -> None: ...
    def load_persistent(self, *, consume: bool = False): ...
    def save_persistent(self, data) -> None: ...
    def unlink_persistent(self) -> None: ...
    def scan(self) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

scan_thread: Incomplete
quit_scan_thread: bool
scan_thread_condition: Incomplete

def run_scan_thread() -> None: ...
def quit() -> None: ...
def init() -> None: ...
def zip_saves(): ...
def unzip_saves(): ...
