from _typeshed import Incomplete as Incomplete

token_dir: str | None
signing_keys: list[str]
verifying_keys: list[str]
should_upgrade: bool

def encode_line(key: Incomplete, a: Incomplete, b: Incomplete = None) -> Incomplete: ...
def decode_line(line: Incomplete) -> Incomplete: ...
def sign_data(data: Incomplete) -> Incomplete: ...
def verify_data(data: Incomplete, signatures: Incomplete, check_verifying: bool = True) -> Incomplete: ...
def get_keys_from_signatures(signatures: Incomplete) -> Incomplete: ...
def check_load(log: Incomplete, signatures: Incomplete) -> Incomplete: ...
def check_persistent(data: Incomplete, signatures: Incomplete) -> Incomplete: ...
def create_token(filename: Incomplete) -> None: ...
def upgrade_savefile(fn: Incomplete) -> None: ...
def upgrade_all_savefiles() -> None: ...
def load_tokens(keys_fn: Incomplete) -> None: ...
def init_tokens() -> None: ...
def init() -> None: ...
def get_save_token_keys() -> Incomplete: ...
