token_dir: str | None
signing_keys: list[str]
verifying_keys: list[str]
should_upgrade: bool

def encode_line(key, a, b=None): ...
def decode_line(line): ...
def sign_data(data): ...
def verify_data(data, signatures, check_verifying: bool = True): ...
def get_keys_from_signatures(signatures): ...
def check_load(log, signatures): ...
def check_persistent(data, signatures): ...
def create_token(filename) -> None: ...
def upgrade_savefile(fn) -> None: ...
def upgrade_all_savefiles() -> None: ...
def load_tokens(keys_fn) -> None: ...
def init_tokens() -> None: ...
def init() -> None: ...
def get_save_token_keys(): ...
