token_dir: str | None
signing_keys: list[str]
verifying_keys: list[str]
should_upgrade: bool

def encode_line(key: str, a: bytes, b: bytes | None = None) -> str: ...
def decode_line(line: str) -> tuple[str, bytes, bytes | None]: ...
def sign_data(data: bytes) -> str: ...
def verify_data(data: bytes, signatures: str, check_verifying: bool = True) -> bool: ...
def get_keys_from_signatures(signatures: str) -> list[bytes]: ...
def check_load(log: bytes, signatures: str) -> bool: ...
def check_persistent(data: bytes, signatures: str) -> bool: ...
def create_token(filename: str) -> None: ...
def upgrade_savefile(fn: str) -> None: ...
def upgrade_all_savefiles() -> None: ...
def load_tokens(keys_fn: str) -> None: ...
def init_tokens() -> None: ...
def init() -> None: ...
def get_save_token_keys() -> list[str]: ...
