import renpy

lines: dict[tuple[str, int], "Line"]
files: set[str]

class Line:
    filename: str
    number: int
    start: int
    end: int
    end_delim: int
    text: str
    full_text: str
    def __init__(self, filename: str, number: int, start: int) -> None: ...
    def __repr__(self) -> str: ...

def load_lines(filename: str, elided_filename: str) -> None: ...
def ensure_loaded(filename: str) -> None: ...
def get_line_text(filename: str, linenumber: int) -> str | None: ...
def adjust_line_locations(filename: str, linenumber: int, char_offset: int, line_offset: int) -> None: ...
def insert_line_before(code: str, filename: str, linenumber: int) -> None: ...
def remove_line(filename: str, linenumber: int) -> None: ...
def get_full_text(filename: str, linenumber: int) -> str | None: ...
def nodes_on_line(filename: str, linenumber: int) -> list[renpy.ast.Node]: ...
def nodes_on_line_at_or_after(filename: str, linenumber: int) -> list[renpy.ast.Node]: ...
def first_and_last_nodes(nodes: list[renpy.ast.Node]) -> tuple[renpy.ast.Node, renpy.ast.Node]: ...
def adjust_ast_linenumbers(filename: str, linenumber: int, offset: int) -> None: ...
def add_to_ast_before(code: str, filename: str, linenumber: int) -> None: ...
def can_add_before(filename: str, linenumber: int) -> bool: ...
def remove_from_ast(filename: str, linenumber: int) -> None: ...

serial: int

def test_add() -> None: ...
def test_remove() -> None: ...
