from _typeshed import Incomplete

lines: dict[tuple[str, int], "Line"]
files: Incomplete

class Line:
    filename: Incomplete
    number: Incomplete
    start: Incomplete
    end: Incomplete
    end_delim: Incomplete
    text: str
    full_text: str
    def __init__(self, filename, number, start) -> None: ...

def load_lines(filename, elided_filename) -> None: ...
def ensure_loaded(filename) -> None: ...
def get_line_text(filename, linenumber): ...
def adjust_line_locations(filename, linenumber, char_offset, line_offset) -> None: ...
def insert_line_before(code, filename, linenumber) -> None: ...
def remove_line(filename, linenumber) -> None: ...
def get_full_text(filename, linenumber): ...
def nodes_on_line(filename, linenumber): ...
def nodes_on_line_at_or_after(filename, linenumber): ...
def first_and_last_nodes(nodes): ...
def adjust_ast_linenumbers(filename, linenumber, offset) -> None: ...
def add_to_ast_before(code, filename, linenumber) -> None: ...
def can_add_before(filename, linenumber): ...
def remove_from_ast(filename, linenumber) -> None: ...

serial: int

def test_add() -> None: ...
def test_remove() -> None: ...
