import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from typing import Any, Self
from renpy.display.displayable import Placement as Placement

class PropertyFunctionWrapper:
    def __reduce__(self) -> None: ...

Style = renpy.styledata.styleclass.Style
type StyleLike = "StyleCore | str | tuple[str, ...] | None"

class StyleCore:
    prefix: str
    prefix_offset: int
    properties: list[dict[str, Any]] = []
    parent: tuple[str, ...] | None
    name: tuple[str, ...] | None
    help: str | None

    def __init__(
        self,
        parent: "StyleCore|str|tuple|None",
        properties: dict[str, Any] | None = None,
        name: tuple[str, ...] | None = None,
        help: str | None = None,
        heavy: bool = True,
    ) -> None: ...
    def __delattr__(self, name: str) -> None: ...
    def __eq__(self, value): ...
    def __ge__(self, value): ...
    def __getitem__(self, key: tuple[str, ...]) -> "StyleCore": ...
    def __gt__(self, value): ...
    def __le__(self, value): ...
    def __lt__(self, value): ...
    def __ne__(self, value): ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def add_properties(self, properties: dict[str, Any]) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> Self: ...
    def delattr(self, property: str) -> None: ...
    def get_offset(self) -> int: ...
    def get_placement(
        self,
    ) -> Placement: ...
    def inspect(self) -> list[tuple[tuple[str, ...] | None, dict[str, Any]]]: ...
    def set_parent(self, parent: "StyleCore|str|tuple[str,...]|None") -> None: ...
    def set_prefix(self, prefix: str) -> None: ...
    def setattr(self, property: str, value: Any) -> None: ...
    def setdefault(self, **properties: Any) -> None: ...
    def take(self, other: "str|StyleCore") -> None: ...

class StyleManager:
    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> StyleCore: ...
    def __getitem__(self, name: str) -> StyleCore: ...
    def __setattr__(self, name: str, value: StyleCore) -> None: ...
    def __setitem__(self, name: str, value: StyleCore) -> None: ...
    def create(
        self, name: tuple[str, ...], parent: StyleCore | str | tuple[str, ...] | None, description: str | None = None
    ) -> None: ...
    def exists(self, name: str | tuple[str, ...]) -> bool: ...
    def get(self, name: str | tuple[str, ...]) -> None: ...
    def rebuild(self) -> None: ...

def backup() -> dict[tuple[str, ...], tuple[tuple[str, ...] | None, list[dict[str, Any]]]]: ...
def build_style(s: StyleCore): ...
def build_styles() -> None: ...
def copy_properties(p: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
def get_full_style(name: tuple[str, ...]) -> StyleCore: ...
def get_or_create_style(name: str) -> StyleCore: ...
def get_style(name: str) -> StyleCore: ...
def get_text_style(
    style: StyleCore | str | tuple[str, ...] | None, default: StyleCore | str | tuple[str, ...] | None
) -> StyleCore: ...
def get_tuple_name(s: StyleCore | str | tuple[str, ...] | None) -> tuple[str, ...] | None: ...
def init_inspect() -> None: ...
def rebuild(prepare_screens: bool = True) -> None: ...
def reset() -> None: ...
def restore(o: dict[tuple[str, ...], tuple[tuple[str, ...] | None, list[dict[str, Any]]]]) -> None: ...
def style_name_to_string(name: tuple[str, ...] | None) -> str: ...
def unbuild_style(s: StyleCore): ...

prefixed_all_properties: set[str]
all_properties: dict[str, list[str]]
prefix_priority: dict[str, int]
prefix_alts: dict[str, list[str]]
prefix_search: dict[str, list[str]]
affects: dict[str, list[str]]
styles: dict[tuple[str, ...], StyleCore]
