import renpy

class PropertyFunctionWrapper:
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...

Style = renpy.styledata.styleclass.Style

class StyleCore:
    def __init__(self, parent, properties=None, name=None, help=None, heavy=True): ...
    def __delattr__(self, name, /): ...
    def __eq__(self, value, /): ...
    def __ge__(self, value, /): ...
    def __getitem__(self, key, /): ...
    def __getstate__(self): ...
    def __gt__(self, value, /): ...
    def __le__(self, value, /): ...
    def __lt__(self, value, /): ...
    def __ne__(self, value, /): ...
    def __repr__(self, /): ...
    def __setattr__(self, name, value, /): ...
    def __setstate__(self, state): ...
    def _get(self, index: int): ...
    def _get_unoffset(self, index: int): ...
    def _hover_alt(self): ...
    def _visit_bar(self, pd): ...
    def _visit_frame(self, pd): ...
    def _visit_window(self, pd): ...
    def add_properties(self, properties): ...
    def clear(self): ...
    def copy(self): ...
    def delattr(self, property): ...
    def get_offset(self): ...
    def get_placement(self): ...
    def inspect(self): ...
    def set_parent(self, parent): ...
    def set_prefix(self, prefix): ...
    def setattr(self, property, value): ...
    def setdefault(self, **properties): ...
    def take(self, other): ...

class StyleManager:
    def __init__(
        self,
    ): ...
    def __getattr__(self, name): ...
    def __getitem__(self, name): ...
    def __setattr__(self, name, value): ...
    def __setitem__(self, name, value): ...
    def create(self, name, parent, description=None): ...
    def exists(self, name): ...
    def get(self, name): ...
    def rebuild(self): ...

def backup(): ...
def build_style(s: "StyleCore"): ...
def build_styles(): ...
def copy_properties(p): ...
def get_full_style(name): ...
def get_or_create_style(name): ...
def get_style(name): ...
def get_text_style(style, default): ...
def get_tuple_name(s): ...
def init_inspect(): ...
def rebuild(prepare_screens=True): ...
def reset(): ...
def restore(o): ...
def style_name_to_string(name): ...
def unbuild_style(s: "StyleCore"): ...

Style: "Any"
prefixed_all_properties: set
all_properties: "dict[str, list[str]]"
prefix_priority: "dict[str, int]"
prefix_alts: "dict[str, list[str]]"
prefix_search: "dict[str, list[str]]"
affects: "dict[str, list[str]]"
styles: "dict[str, Any]"
