import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from typing import Any

class PropertyFunctionWrapper:
    def __reduce__(self) -> None: ...

Style = renpy.styledata.styleclass.Style

class StyleCore:
    def __init__(self, parent, properties=None, name=None, help=None, heavy: bool = True) -> None: ...
    def __delattr__(self, name) -> None: ...
    def __eq__(self, value): ...
    def __ge__(self, value): ...
    def __getitem__(self, key) -> None: ...
    def __gt__(self, value): ...
    def __le__(self, value): ...
    def __lt__(self, value): ...
    def __ne__(self, value): ...
    def __setattr__(self, name, value, /) -> None: ...
    def add_properties(self, properties) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> None: ...
    def delattr(self, property) -> None: ...
    def get_offset(self) -> None: ...
    def get_placement(
        self,
    ) -> tuple[float | None, float | None, float | None, float | None, float | None, float | None, bool]: ...
    def inspect(self) -> None: ...
    def set_parent(self, parent) -> None: ...
    def set_prefix(self, prefix) -> None: ...
    def setattr(self, property, value) -> None: ...
    def setdefault(self, **properties) -> None: ...
    def take(self, other) -> None: ...

class StyleManager:
    def __init__(self) -> None: ...
    def __getattr__(self, name) -> None: ...
    def __getitem__(self, name) -> None: ...
    def __setattr__(self, name, value) -> None: ...
    def __setitem__(self, name, value) -> None: ...
    def create(self, name, parent, description=None) -> None: ...
    def exists(self, name) -> None: ...
    def get(self, name) -> None: ...
    def rebuild(self) -> None: ...

def backup() -> None: ...
def build_style(s: StyleCore): ...
def build_styles() -> None: ...
def copy_properties(p) -> None: ...
def get_full_style(name) -> None: ...
def get_or_create_style(name) -> None: ...
def get_style(name) -> None: ...
def get_text_style(style, default) -> None: ...
def get_tuple_name(s) -> None: ...
def init_inspect() -> None: ...
def rebuild(prepare_screens: bool = True) -> None: ...
def reset() -> None: ...
def restore(o) -> None: ...
def style_name_to_string(name) -> None: ...
def unbuild_style(s: StyleCore): ...

prefixed_all_properties: set
all_properties: dict[str, list[str]]
prefix_priority: dict[str, int]
prefix_alts: dict[str, list[str]]
prefix_search: dict[str, list[str]]
affects: dict[str, list[str]]
styles: dict[str, Any]
