from _typeshed import Incomplete as Incomplete
from collections.abc import Generator

update_translations: Incomplete
flags: Incomplete
formatter: Incomplete
SIMPLE_NAME: Incomplete

def interpolate(s, scope): ...
def parse(s) -> Generator[Incomplete]: ...
def convert(value, conv, scope): ...
def substitute(s, scope=None, force: bool = False, translate: bool = True): ...
def ___(s): ...
