import re
import string
from typing import Any, Generator, Literal, MutableMapping, overload

update_translations: bool
flags: frozenset
formatter: string.Formatter
SIMPLE_NAME: re.Pattern[str]

def interpolate(s: str, scope: MutableMapping[str, Any]) -> str: ...
def parse(s: str) -> Generator[tuple[str, str | None, str | None, str | None]]: ...
@overload
def convert[T](value: T, conv: Literal[""], scope: MutableMapping[str, Any]) -> T: ...
@overload
def convert(value: Any, conv: str, scope: MutableMapping[str, Any]) -> str: ...
def substitute(
    s: str, scope: MutableMapping[str, Any] | None = None, force: bool = False, translate: bool = True
) -> tuple[str, bool]: ...
def ___(s: str) -> str: ...
