def colorChooser(title, initialColor=None) -> None: ...
def encode(s) -> None: ...
def inputBox(title, message, defaultinput: str = "") -> None: ...
def messageBox(title, message, dialogtype, icon, defaultbutton) -> None: ...
def notifyPopup(title, message, icon) -> None: ...
def openFileDialog(
    title, defaultPathAndFile, filters, singleFilterDescription, allowMultipleSelects: bool = False
) -> None: ...
def saveFileDialog(title, defaultPathAndFile, filters, singleFilterDescription) -> None: ...
def selectFolderDialog(title, defaultPath) -> None: ...
