from typing import Any

def colorChooser(title: str, initialColor: Any = None) -> str | None: ...
def encode(s: str) -> str: ...
def inputBox(title: str, message: str, defaultinput: str = "") -> str | None: ...
def messageBox(title: str, message: str, dialogtype: str, icon: str, defaultbutton: int) -> int | None: ...
def notifyPopup(title: str, message: str, icon: str) -> None: ...
def openFileDialog(
    title: str,
    defaultPathAndFile: str,
    filters: list[tuple[str, str]],
    singleFilterDescription: str,
    allowMultipleSelects: bool = False,
) -> str | None: ...
def saveFileDialog(
    title: str, defaultPathAndFile: str, filters: list[tuple[str, str]], singleFilterDescription: str
) -> str | None: ...
def selectFolderDialog(title: str, defaultPath: str) -> str | None: ...
