from _typeshed import Incomplete as Incomplete

def colorChooser(title: Incomplete, initialColor: Incomplete = None) -> None: ...
def encode(s: Incomplete) -> None: ...
def inputBox(title: Incomplete, message: Incomplete, defaultinput: str = "") -> None: ...
def messageBox(
    title: Incomplete, message: Incomplete, dialogtype: Incomplete, icon: Incomplete, defaultbutton: Incomplete
) -> None: ...
def notifyPopup(title: Incomplete, message: Incomplete, icon: Incomplete) -> None: ...
def openFileDialog(
    title: Incomplete,
    defaultPathAndFile: Incomplete,
    filters: Incomplete,
    singleFilterDescription: Incomplete,
    allowMultipleSelects: bool = False,
) -> None: ...
def saveFileDialog(
    title: Incomplete, defaultPathAndFile: Incomplete, filters: Incomplete, singleFilterDescription: Incomplete
) -> None: ...
def selectFolderDialog(title: Incomplete, defaultPath: Incomplete) -> None: ...
