from _typeshed import Incomplete as Incomplete

queue: Incomplete
to_unlink: Incomplete
queue_lock: Incomplete

class XMLHttpRequest:
    id: Incomplete
    def __init__(self, filename) -> None: ...
    def __del__(self) -> None: ...
    @property
    def readyState(self): ...
    @property
    def status(self): ...
    @property
    def statusText(self): ...

class XMLHttpRequest:
    done: bool
    error: Incomplete
    def __init__(self, filename) -> None: ...
    @property
    def readyState(self): ...
    @property
    def status(self): ...
    @property
    def statusText(self): ...

class DownloadNeeded(Exception):
    relpath: Incomplete
    rtype: Incomplete
    size: Incomplete
    def __init__(self, relpath, rtype, size) -> None: ...

class ReloadRequest:
    relpath: Incomplete
    rtype: Incomplete
    data: Incomplete
    gc_gen: int
    xhr: Incomplete
    def __init__(self, relpath, rtype, data) -> None: ...
    def download_completed(self): ...

def enqueue(relpath, rtype, data) -> None: ...
def process_downloaded_resources() -> None: ...
def extend(relpath) -> None: ...
