import threading

queue: list[ReloadRequest]
to_unlink: dict[str, float]
queue_lock: threading.RLock

class XMLHttpRequest:
    id: int
    def __init__(self, filename: str) -> None: ...
    def __del__(self) -> None: ...
    @property
    def readyState(self) -> int: ...
    @property
    def status(self) -> int: ...
    @property
    def statusText(self) -> str: ...

class XMLHttpRequest:
    done: bool
    error: str | None
    def __init__(self, filename: str) -> None: ...
    @property
    def readyState(self) -> int: ...
    @property
    def status(self) -> int: ...
    @property
    def statusText(self) -> str: ...

class DownloadNeeded(Exception):
    relpath: str
    rtype: str
    size: str | list[int]
    def __init__(self, relpath: str, rtype: str, size: str | list[int]) -> None: ...

class ReloadRequest:
    relpath: str
    rtype: str
    data: str | None
    gc_gen: int
    xhr: XMLHttpRequest
    def __init__(self, relpath: str, rtype: str, data: str | None) -> None: ...
    def download_completed(self) -> bool: ...
    def __repr__(self) -> str: ...

def enqueue(relpath: str, rtype: str, data: str | None) -> None: ...
def process_downloaded_resources() -> None: ...
def extend(relpath: str) -> None: ...
