# Generated by scripts/relative_imports.py, do not edit below this line.

from .__numbered_gamepad import EventWatcher as EventWatcher
from .__numbered_gamepad import _constant as _constant
from .__numbered_gamepad import calibrate as calibrate

__all__ = [
    "EventWatcher",
    "_constant",
    "calibrate",
]
