from _typeshed import Incomplete
from typing import Any
from pyobjus import objc_arr as objc_arr
from renpy.ui import Action

_constant: bool
background: str

class Product:
    product: Incomplete
    identifier: Incomplete
    google: Incomplete
    amazon: Incomplete
    ios: Incomplete
    price: Incomplete
    consumable: Incomplete
    def __init__(
        self,
        product: Incomplete,
        identifier: Incomplete,
        google: Incomplete,
        amazon: Incomplete,
        ios: Incomplete,
        consumable: Incomplete,
    ) -> None: ...

class NoneBackend:
    def get_store_name(self) -> None: ...
    def purchase(self, p: Incomplete, interact: bool = True) -> Incomplete: ...
    def restore_purchases(self, interact: bool = True) -> None: ...
    def has_purchased(self, p: Incomplete) -> Incomplete: ...
    def consume(self, p: Incomplete) -> Incomplete: ...
    def is_deferred(self, p: Incomplete) -> Incomplete: ...
    def get_price(self, p: Incomplete) -> None: ...
    def init(self) -> None: ...
    def request_review(self) -> Incomplete: ...

class AndroidBackend:
    store: Incomplete
    store_name: Incomplete
    def __init__(self, store: Incomplete, store_name: Incomplete) -> None: ...
    def get_store_name(self) -> Incomplete: ...
    def identifier(self, p: Incomplete) -> Incomplete: ...
    def wait_for_result(self, interact: bool = True) -> None: ...
    def purchase(self, p: Incomplete, interact: bool = True) -> None: ...
    def restore_purchases(self, interact: bool = True) -> None: ...
    def has_purchased(self, p: Incomplete) -> Incomplete: ...
    def consume(self, p: Incomplete) -> Incomplete: ...
    def is_deferred(self, p: Incomplete) -> Incomplete: ...
    def get_price(self, p: Incomplete) -> Incomplete: ...
    def request_review(self) -> Incomplete: ...
    def init(self) -> None: ...

IAPHelper: Incomplete
NSMutableArray: Incomplete

class IOSBackend:
    helper: Incomplete
    validated_products: bool
    def __init__(self) -> None: ...
    def get_store_name(self) -> Incomplete: ...
    def set_title(self) -> None: ...
    def identifier(self, p: Incomplete) -> Incomplete: ...
    def wait_for_result(self, interact: bool = True) -> None: ...
    def validate_products(self, interact: Incomplete) -> Incomplete: ...
    def purchase(self, p: Incomplete, interact: bool = True) -> None: ...
    def restore_purchases(self, interact: bool = True) -> None: ...
    def has_purchased(self, p: Incomplete) -> Incomplete: ...
    def consume(self, p: Incomplete) -> Incomplete: ...
    def is_deferred(self, p: Incomplete) -> Incomplete: ...
    def get_price(self, p: Incomplete) -> Incomplete: ...
    def request_review(self) -> Incomplete: ...
    def init(self) -> None: ...

backend: Incomplete
products: Incomplete

def register(
    product: Incomplete,
    identifier: Incomplete = None,
    amazon: Incomplete = None,
    google: Incomplete = None,
    ios: Incomplete = None,
    consumable: bool = False,
) -> None: ...
def with_background(f: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
def restore(interact: bool = True) -> None: ...

class Restore(Action):
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

def get_product(product: Incomplete) -> Incomplete: ...
def purchase(product: Incomplete, interact: bool = True, consumable: bool = False) -> Incomplete: ...

class Purchase(Action):
    product: Incomplete
    sensitive: bool
    success: Incomplete
    def __init__(self, product: Incomplete, success: Incomplete = None) -> None: ...
    def __call__(self) -> None: ...
    def should_be_sensitive(self) -> Incomplete: ...
    def get_sensitive(self) -> bool: ...
    def periodic(self, st: float) -> float | None: ...

def has_purchased(product: Incomplete) -> Incomplete: ...
def is_deferred(product: Incomplete) -> Incomplete: ...
def get_price(product: Incomplete) -> Incomplete: ...
def get_store_name() -> Incomplete: ...
def request_review() -> Incomplete: ...
def missing_products() -> Incomplete: ...
def init_android() -> Incomplete: ...
def init() -> None: ...
