from typing import Any

from pyobjus import objc_arr as objc_arr
from renpy.ui import Action

_constant: bool
background: str

class Product:
    product: str
    identifier: str
    google: str
    amazon: str
    ios: str
    price: str | None
    consumable: bool
    def __init__(
        self,
        product: str,
        identifier: str,
        google: str,
        amazon: str,
        ios: str,
        consumable: bool,
    ) -> None: ...

class NoneBackend:
    def get_store_name(self) -> None: ...
    def purchase(self, p: Product, interact: bool = True) -> bool: ...
    def restore_purchases(self, interact: bool = True) -> None: ...
    def has_purchased(self, p: Product) -> bool: ...
    def consume(self, p: Product) -> bool: ...
    def is_deferred(self, p: Product) -> bool: ...
    def get_price(self, p: Product) -> str | None: ...
    def init(self) -> None: ...
    def request_review(self) -> bool: ...

class AndroidBackend:
    store: Any
    store_name: str
    def __init__(self, store: Any, store_name: str) -> None: ...
    def get_store_name(self) -> str: ...
    def identifier(self, p: Product) -> str: ...
    def wait_for_result(self, interact: bool = True) -> None: ...
    def purchase(self, p: Product, interact: bool = True) -> bool: ...
    def restore_purchases(self, interact: bool = True) -> None: ...
    def has_purchased(self, p: Product) -> bool: ...
    def consume(self, p: Product) -> bool: ...
    def is_deferred(self, p: Product) -> bool: ...
    def get_price(self, p: Product) -> str | None: ...
    def request_review(self) -> bool: ...
    def init(self) -> None: ...

IAPHelper: Any
NSMutableArray: Any

class IOSBackend:
    helper: Any
    validated_products: bool
    def __init__(self) -> None: ...
    def get_store_name(self) -> str: ...
    def set_title(self) -> None: ...
    def identifier(self, p: Product) -> str: ...
    def wait_for_result(self, interact: bool = True) -> None: ...
    def validate_products(self, interact: bool) -> bool: ...
    def purchase(self, p: Product, interact: bool = True) -> bool: ...
    def restore_purchases(self, interact: bool = True) -> None: ...
    def has_purchased(self, p: Product) -> bool: ...
    def consume(self, p: Product) -> bool: ...
    def is_deferred(self, p: Product) -> bool: ...
    def get_price(self, p: Product) -> str | None: ...
    def request_review(self) -> bool: ...
    def init(self) -> None: ...

backend: NoneBackend | AndroidBackend | IOSBackend
products: dict[str, Product]

def register(
    product: str,
    identifier: str | None = None,
    amazon: str | None = None,
    google: str | None = None,
    ios: str | None = None,
    consumable: bool = False,
) -> None: ...
def with_background(f: Any, *args: Any, **kwargs: Any) -> Any: ...
def restore(interact: bool = True) -> None: ...

class Restore(Action):
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

def get_product(product: str) -> Product: ...
def purchase(product: str, interact: bool = True, consumable: bool = False) -> bool: ...

class Purchase(Action):
    product: Product
    sensitive: bool
    success: Action | None
    def __init__(self, product: Product, success: Action | None = None) -> None: ...
    def __call__(self) -> None: ...
    def should_be_sensitive(self) -> bool: ...
    def get_sensitive(self) -> bool: ...
    def periodic(self, st: float) -> float | None: ...

def has_purchased(product: str) -> bool: ...
def is_deferred(product: str) -> bool: ...
def get_price(product: str) -> str | None: ...
def get_store_name() -> str | None: ...
def request_review() -> bool: ...
def missing_products() -> list[str]: ...
def init_android() -> AndroidBackend | None: ...
def init() -> None: ...
