from _typeshed import Incomplete
from renpy.types import Unused
from renpy.ui import Action

_constant: bool
backends: list[Backend]

class Backend:
    def register(self, name: str, **kwargs: Incomplete) -> None: ...
    def grant(self, name: str) -> None: ...
    def clear(self, name: str) -> None: ...
    def clear_all(self) -> None: ...
    def progress(self, name: str, complete: int | None) -> None: ...
    def has(self, name: str) -> bool: ...

class PersistentBackend(Backend):
    stat_max: dict[str, int]
    def __init__(self) -> None: ...
    def register(self, name: str, stat_max: int | None = None, **kwargs: Incomplete) -> None: ...
    def grant(self, name: str) -> None: ...
    def clear(self, name: str) -> None: ...
    def clear_all(self) -> None: ...
    def has(self, name: str) -> bool: ...
    def progress(self, name: str, completed: int | None) -> None: ...

def merge(old: set[str] | None, new: set[str] | None, current: Unused) -> set[str]: ...
def merge_progress(old: dict[str, int] | None, new: dict[str, int] | None, current: Unused) -> dict[str, int]: ...
def register(name: str, **kwargs: Incomplete) -> None: ...
def grant(name: str) -> None: ...
def clear(name: str) -> None: ...
def clear_all() -> None: ...
def get_progress(name: str) -> int: ...
def progress(name: str, complete: int | None, total=None) -> None: ...
def grant_progress(name: str, complete: int | None, total: Unused = None) -> None: ...
def has(name: str) -> bool: ...
def sync() -> None: ...

class Sync(Action):
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...
