import builtins
from typing import Any

__all__ = ["PY2", "open", "basestring", "str", "pystr", "range", "round", "bord", "bchr", "tobytes", "chr", "unicode"]

PY2: bool
python_open = open
open = builtins.open
compat_open = open
basestring: tuple[type]
pystr = str
unicode = str
str = builtins.str

def bord(s: bytes) -> int: ...
def bchr(i: int) -> bytes: ...
def tobytes(s: Any) -> bytes: ...

chr = builtins.chr
range = builtins.range
round = builtins.round

# Generated by scripts/relative_imports.py, do not edit below this line.
from . import fixes as fixes
from . import pickle as pickle
