import ast
import tokenize
from _typeshed import Incomplete as Incomplete
from typing import Iterator

def fix_octal_numbers(tokens: Iterator[tokenize.TokenInfo]) -> Incomplete: ...
def fix_spaceship(tokens: Iterator[tokenize.TokenInfo]) -> Incomplete: ...
def fix_backtick_repr(tokens: Iterator[tokenize.TokenInfo]) -> Incomplete: ...
def fix_print(line: list[tokenize.TokenInfo]) -> Incomplete: ...
def fix_raise(line: list[tokenize.TokenInfo]) -> Incomplete: ...
def fix_lines(tokens: Iterator[tokenize.TokenInfo]) -> Incomplete: ...
def fix_tokens(source: str) -> Incomplete: ...

class ReorderGlobals(ast.NodeTransformer):
    globals: Incomplete
    def __init__(self) -> None: ...
    def visit_Global(self, node: Incomplete) -> Incomplete: ...
    def visit_FunctionDef(self, node: ast.FunctionDef) -> Incomplete: ...

reorder_globals: Incomplete

def fix_ast(tree: Incomplete) -> Incomplete: ...
