import ast
import tokenize
from _typeshed import Incomplete
from typing import Iterator

def fix_octal_numbers(tokens: Iterator[tokenize.TokenInfo]): ...
def fix_spaceship(tokens: Iterator[tokenize.TokenInfo]): ...
def fix_backtick_repr(tokens: Iterator[tokenize.TokenInfo]): ...
def fix_print(line: list[tokenize.TokenInfo]): ...
def fix_raise(line: list[tokenize.TokenInfo]): ...
def fix_lines(tokens: Iterator[tokenize.TokenInfo]): ...
def fix_tokens(source: str): ...

class ReorderGlobals(ast.NodeTransformer):
    globals: Incomplete
    def __init__(self) -> None: ...
    def visit_Global(self, node): ...
    def visit_FunctionDef(self, node: ast.FunctionDef): ...

reorder_globals: Incomplete

def fix_ast(tree): ...
