import renpy

Displayable = renpy.display.displayable.Displayable

class RenderTransform:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...
    def render(self, widtho, heighto, st, at): ...

absolute = renpy.display.position.absolute

def get_poi(state): ...
def nogil_copy(src, dest): ...
def relative_for_crop(n, base, limit): ...
