import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter

Displayable = renpy.display.displayable.Displayable

class RenderTransform:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def render(self, widtho, heighto, st, at) -> None: ...

absolute = renpy.display.position.absolute

def get_poi(state) -> None: ...
def nogil_copy(src, dest) -> None: ...
def relative_for_crop(n, base, limit) -> None: ...
