import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from renpy.pygame.surface import Surface as Surface
from renpy.display.render import Render as Render

Displayable = renpy.display.displayable.Displayable

class RenderTransform:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def __setstate__(self, /, __pyx_state) -> None: ...
    def render(self, widtho: float, heighto: float, st: float, at: float) -> Render: ...

absolute = renpy.display.position.absolute

def get_poi(state: renpy.display.transform.TransformState) -> tuple[float, float, float] | None: ...
def nogil_copy(src: Surface, dest: Surface) -> None: ...
def relative_for_crop(n: int | absolute, base: float, limit: int) -> int: ...
