import renpy
from _typeshed import Incomplete
from renpy.display.displayable import Displayable as Displayable
from typing import Any, NotRequired, TypedDict

import_time: Incomplete
TIMEEVENT: Incomplete
PERIODIC: Incomplete
REDRAW: Incomplete
EVENTNAME: Incomplete
ALL_EVENTS: set[int]
enabled_events: set[int]
input_events: set[int]
PERIODIC_INTERVAL: int
null: renpy.display.layout.Null | None
time_base: float
time_mult: float
relx: int
rely: int

def init_time() -> None: ...
def get_time() -> float: ...
def get_size() -> tuple[int, int]: ...
def displayable_by_tag(layer: str, tag: str) -> Displayable | None: ...

class IgnoreEvent(Exception): ...

class EndInteraction(Exception):
    value: Incomplete
    def __init__(self, value: Any) -> None: ...

class MouseMove:
    start: Incomplete
    duration: Incomplete
    end_x: Incomplete
    end_y: Incomplete
    def __init__(self, x: int, y: int, duration: float | None) -> None: ...
    def perform(self) -> bool: ...

def get_safe_mode() -> bool: ...

class RendererInfo(TypedDict):
    renderer: str
    resizable: bool
    additive: bool
    models: bool
    gpu_vendor: NotRequired[str]
    gpu_name: NotRequired[str]
    gpu_driver_version: NotRequired[str]

class Renderer:
    texture_cache: Incomplete
    info: RendererInfo
    def get_texture_size(self) -> None: ...
    def update(self, force: bool = False) -> None: ...
    def init(self, virtual_size) -> None: ...
    def quit(self) -> None: ...
    def resize(self) -> None: ...
    def can_block(self) -> None: ...
    def should_redraw(self, needs_redraw, first_pass, can_block) -> None: ...
    def mutated_surface(self, surf) -> None: ...
    def load_texture(self, surf, transient: bool = False) -> None: ...
    def ready_one_texture(self) -> None: ...
    def kill_textures(self) -> None: ...
    def solid_texture(self, w, h, color) -> None: ...
    def draw_screen(self, surftree, flip: bool = True) -> None: ...
    def render_to_texture(self, what, alpha) -> None: ...
    def is_pixel_opaque(self, what, x, y) -> None: ...
    def get_half(self, what) -> None: ...
    def translate_point(self, x, y): ...
    def untranslate_point(self, x, y): ...
    def mouse_event(self, ev): ...
    def get_mouse_pos(self): ...
    def set_mouse_pos(self, x, y) -> None: ...
    def screenshot(self, surftree) -> None: ...
    def event_peek_sleep(self) -> None: ...
    def get_physical_size(self) -> None: ...

initial_maximum_framerate: float

class Interface:
    screenshot: Incomplete
    screenshot_surface: Incomplete
    old_scene: Incomplete
    transition: Incomplete
    suppress_transition: bool
    quick_quit: bool
    force_redraw: bool
    restart_interaction: bool
    pushed_event: Incomplete
    ticks: int
    mouse: str
    timeout_time: Incomplete
    last_event: Incomplete
    current_context: Incomplete
    roll_forward: Incomplete
    fullscreen: bool
    preloads: Incomplete
    init_time: Incomplete
    frame_time: int
    interact_time: Incomplete
    quit_time: int
    in_quit_event: bool
    time_event: Incomplete
    redraw_event: Incomplete
    mouse_focused: bool
    keyboard_focused: bool
    layer_properties: Incomplete
    shown_window: bool
    ignore_touch: bool
    clear_screenshot: bool
    audio_paused: bool
    ongoing_transition: Incomplete
    instantiated_transition: Incomplete
    transition_time: Incomplete
    transition_from: Incomplete
    old_root_transform: Incomplete
    transition_info_stack: Incomplete
    event_time: int
    mouse_event_time: Incomplete
    show_mouse: bool
    display_reset: bool
    profile_once: bool
    thread: Incomplete
    input_event_time: Incomplete
    window_caption: Incomplete
    safe_mode: bool
    bgscreenshot_needed: bool
    bgscreenshot_event: Incomplete
    bgscreenshot_surface: Incomplete
    mouse_move: Incomplete
    text_editing: Incomplete
    text_rect: Incomplete
    old_text_rect: Incomplete
    touch: Incomplete
    touch_keyboard: Incomplete
    started: bool
    fullscreen_video: bool
    dpi_scale: Incomplete
    maximum_framerate_time: float
    start_interact: bool
    frame_times: Incomplete
    frame_duration: Incomplete
    cursor_cache: dict | None
    old_mouse: Incomplete
    transition_delay: Incomplete
    first_frame: bool
    force_prediction: bool
    interaction_counter: int
    mod: int
    invoke_queue: Incomplete
    last_screensaver: Incomplete
    last_emscripten_preload_time: float
    def __init__(self) -> None: ...
    def setup_nvdrs(self) -> None: ...
    def setup_dpi_scaling(self): ...
    def get_display_layout(self): ...
    def on_move(self, pos) -> None: ...
    def start(self) -> None: ...
    def post_init(self) -> None: ...
    def after_first_frame(self) -> None: ...
    def set_screensaver(self) -> None: ...
    def set_icon(self) -> None: ...
    def set_window_caption(self, force: bool = False) -> None: ...
    def iconify(self) -> None: ...
    def get_draw_constructors(self): ...
    def kill_textures(self, keep_const_size: bool = False) -> None: ...
    def kill_surfaces(self) -> None: ...
    minimized: bool
    def before_resize(self) -> None: ...
    def set_mode(self) -> None: ...
    surftree: Incomplete
    def draw_screen(self, root_widget, fullscreen_video, draw) -> None: ...
    def take_screenshot(self, scale, background: bool = False, keep_existing: bool = False) -> None: ...
    def check_background_screenshot(self) -> None: ...
    def get_screenshot(self): ...
    def lose_screenshot(self) -> None: ...
    def save_screenshot(self, filename): ...
    def screenshot_to_bytes(self, size=None): ...
    def show_window(self) -> None: ...
    def do_with(self, trans, paired, clear: bool = False): ...
    def with_none(self, overlay: bool = True) -> None: ...
    def end_transitions(self) -> None: ...
    def get_ongoing_transition(self, layer=None): ...
    def set_transition(self, transition, layer=None, force: bool = False) -> None: ...
    def event_peek(self, sleep: bool = True): ...
    def event_poll(self): ...
    def event_wait(self): ...
    def compute_overlay(self) -> None: ...
    def compute_scene(self, scene_lists): ...
    def quit_event(self) -> None: ...
    def set_mouse(self, cursor) -> None: ...
    def hide_mouse(self) -> None: ...
    def is_mouse_visible(self): ...
    def get_mouse_names(self): ...
    def get_mouse_name(self, cache_only: bool = False, interaction: bool = True): ...
    def update_mouse(self, mouse_displayable) -> None: ...
    def set_mouse_pos(self, x, y, duration) -> None: ...
    def drawn_since(self, seconds_ago): ...
    def mobile_save(self) -> None: ...
    def mobile_unlink(self) -> None: ...
    def check_android_start(self) -> None: ...
    def check_suspend(self, ev): ...
    def enter_context(self) -> None: ...
    def post_time_event(self) -> None: ...
    def after_longpress(self) -> None: ...
    def text_event_in_queue(self): ...
    def update_text_rect(self) -> None: ...
    def maximum_framerate(self, t) -> None: ...
    trans_pause: Incomplete
    def interact(
        self,
        clear: bool = True,
        suppress_window: bool = False,
        trans_pause: bool = False,
        pause=None,
        pause_modal: bool = False,
        **kwargs,
    ): ...
    def consider_gc(self) -> None: ...
    prediction_coroutine: Incomplete
    did_autosave: bool
    did_persistent: bool
    def idle_frame(self, expensive) -> None: ...
    take_layer_displayable: Incomplete
    suppress_overlay: Incomplete
    suppress_underlay: Incomplete
    def interact_core(
        self,
        show_mouse: bool = True,
        trans_pause: bool = False,
        suppress_overlay: bool = False,
        suppress_underlay: bool = False,
        mouse: str | None = None,
        preloads=[],
        roll_forward=None,
        pause=None,
        pause_start: float = 0.0,
        pause_modal=None,
    ): ...
    def timeout(self, offset) -> None: ...
    def finish_pending(self) -> None: ...
    def exec_js_cmd(self) -> None: ...
