import renpy
import threading
from _typeshed import Incomplete as Incomplete
from renpy.display.displayable import Displayable as Displayable
from renpy.display.layout import MultiBox as MultiBox, Null as Null
from renpy.display.render import Render as Render
from renpy.display.transform import Transform as Transform
from renpy.display.transition import TransitionFunction as TransitionFunction
from renpy.pygame.event import EventType as EventType
from renpy.pygame.mouse import ColorCursor as ColorCursor
from renpy.pygame.surface import Surface as Surface
from typing import Any, Callable, Never, NotRequired, TypedDict

import_time: float
TIMEEVENT: int
PERIODIC: int
REDRAW: int
EVENTNAME: int
ALL_EVENTS: set[int]
enabled_events: set[int]
input_events: set[int]
PERIODIC_INTERVAL: int
null: renpy.display.layout.Null | None
time_base: float
time_mult: float
relx: int
rely: int

def init_time() -> None: ...
def get_time() -> float: ...
def get_size() -> tuple[int, int] | None: ...
def displayable_by_tag(layer: str, tag: str) -> Displayable | None: ...

class IgnoreEvent(Exception): ...

class EndInteraction(Exception):
    value: Any
    def __init__(self, value: Any) -> None: ...

class MouseMove:
    start: float
    duration: float
    end_x: int
    end_y: int
    def __init__(self, x: int, y: int, duration: float | None) -> None: ...
    def perform(self) -> bool: ...

def get_safe_mode() -> bool: ...

class RendererInfo(TypedDict):
    renderer: str
    resizable: bool
    additive: bool
    models: bool
    gpu_vendor: NotRequired[str]
    gpu_name: NotRequired[str]
    gpu_driver_version: NotRequired[str]

class Renderer:
    texture_cache: dict[Surface, Never]
    info: RendererInfo
    def get_texture_size(self) -> tuple[int, int]: ...
    def update(self, force: bool = False) -> bool: ...
    def init(self, virtual_size: tuple[int, int]) -> bool: ...
    def quit(self) -> None: ...
    def resize(self) -> None: ...
    def can_block(self) -> bool: ...
    def should_redraw(self, needs_redraw: bool, first_pass: bool, can_block: bool) -> bool: ...
    def mutated_surface(self, surf: Surface) -> None: ...
    def load_texture(self, surf: Surface, transient: bool = False) -> Surface: ...
    def ready_one_texture(self) -> bool: ...
    def kill_textures(self) -> None: ...
    def solid_texture(self, w: int, h: int, color: tuple[int, int, int, int]) -> Surface: ...
    def draw_screen(self, surftree: Render, flip: bool = True) -> None: ...
    def render_to_texture(self, what: Incomplete, alpha: bool) -> Incomplete: ...
    def is_pixel_opaque(self, what: Incomplete, x: Incomplete, y: Incomplete) -> bool: ...
    def get_half(self, what: Never) -> Never: ...
    def translate_point(self, x: float, y: float) -> tuple[int, int]: ...
    def untranslate_point(self, x: float, y: float) -> tuple[int, int]: ...
    def mouse_event(self, ev: Event) -> tuple[int, int]: ...
    def get_mouse_pos(self) -> tuple[int, int]: ...
    def set_mouse_pos(self, x: float, y: float) -> None: ...
    def screenshot(self, surftree: Render) -> Surface: ...
    def event_peek_sleep(self) -> None: ...
    def get_physical_size(self) -> tuple[int, int]: ...

initial_maximum_framerate: float

class Interface:
    screenshot: bytes | None
    screenshot_surface: Surface | None
    old_scene: dict[str | None, MultiBox]
    transition: dict[str | None, TransitionFunction]
    suppress_transition: bool
    quick_quit: bool
    force_redraw: bool
    restart_interaction: bool
    pushed_event: EventType | None
    ticks: int
    mouse: str
    timeout_time: float | None
    last_event: EventType | None
    current_context: Never
    roll_forward: Any | None
    fullscreen: bool
    preloads: Never
    init_time: float
    frame_time: float
    interact_time: float | None
    quit_time: float
    in_quit_event: bool
    time_event: EventType
    redraw_event: EventType
    mouse_focused: bool
    keyboard_focused: bool
    layer_properties: dict[str, dict[str, Any]]
    shown_window: bool
    ignore_touch: bool
    clear_screenshot: bool
    audio_paused: bool
    ongoing_transition: dict[str | None, TransitionFunction]
    instantiated_transition: dict[str | None, Displayable]
    transition_time: dict[str | None, float]
    transition_from: dict[str | None, MultiBox]
    old_root_transform: Transform | None
    transition_info_stack: Never
    event_time: float
    mouse_event_time: float | None
    show_mouse: bool
    display_reset: bool
    profile_once: bool
    thread: threading.Thread
    input_event_time: float
    window_caption: str | None
    safe_mode: bool
    bgscreenshot_needed: bool
    bgscreenshot_event: threading.Event
    bgscreenshot_surface: Surface | None
    mouse_move: MouseMove | None
    text_editing: EventType | None
    text_rect: tuple[int, int, int, int] | None
    old_text_rect: tuple[int, int, int, int] | None
    touch: bool
    touch_keyboard: bool
    started: bool
    fullscreen_video: bool
    dpi_scale: float
    maximum_framerate_time: float
    start_interact: bool
    frame_times: list[float]
    frame_duration: float
    cursor_cache: dict[str | None, list[ColorCursor]] | None
    old_mouse: bool | ColorCursor | None
    transition_delay: dict[str, float]
    first_frame: bool
    force_prediction: bool
    interaction_counter: int
    mod: int
    invoke_queue: list[tuple[Callable[..., Any | None], tuple[Any], dict[str, Any]]]
    last_screensaver: bool | None
    last_emscripten_preload_time: float
    def __init__(self) -> None: ...
    def setup_nvdrs(self) -> None: ...
    def setup_dpi_scaling(self) -> float: ...
    def get_display_layout(self) -> tuple[tuple[int, int, int, int], ...]: ...
    def on_move(self, pos: tuple[int, int]) -> None: ...
    def start(self) -> None: ...
    def post_init(self) -> None: ...
    def after_first_frame(self) -> None: ...
    def set_screensaver(self) -> None: ...
    def set_icon(self) -> None: ...
    def set_window_caption(self, force: bool = False) -> None: ...
    def iconify(self) -> None: ...
    def get_draw_constructors(self) -> list[tuple[str, Renderer]]: ...
    def kill_textures(self, keep_const_size: bool = False) -> None: ...
    def kill_surfaces(self) -> None: ...
    minimized: bool
    def before_resize(self) -> None: ...
    def set_mode(self) -> None: ...
    surftree: Render
    def draw_screen(self, root_widget: Displayable, fullscreen_video: bool, draw: bool) -> None: ...
    def take_screenshot(
        self, scale: tuple[float, float], background: bool = False, keep_existing: bool = False
    ) -> None: ...
    def check_background_screenshot(self) -> None: ...
    def get_screenshot(self) -> bytes | None: ...
    def lose_screenshot(self) -> None: ...
    def save_screenshot(self, filename: str) -> bool: ...
    def screenshot_to_bytes(self, size: tuple[float, float] | None = None) -> bytes | None: ...
    def show_window(self) -> None: ...
    def do_with(
        self, trans: TransitionFunction | None, paired: TransitionFunction | None, clear: bool = False
    ) -> Any | bool | None: ...
    def with_none(self, overlay: bool = True) -> None: ...
    def end_transitions(self) -> None: ...
    def get_ongoing_transition(self, layer: str | None = None) -> TransitionFunction | None: ...
    def set_transition(
        self, transition: TransitionFunction | None, layer: str | None = None, force: bool = False
    ) -> None: ...
    def event_peek(self, sleep: bool = True) -> EventType | None: ...
    def event_poll(self) -> EventType: ...
    def event_wait(self) -> EventType: ...
    def compute_overlay(self) -> None: ...
    def compute_scene(self, scene_lists: renpy.display.scenelists.SceneLists) -> dict[str | None, MultiBox]: ...
    def quit_event(self) -> None: ...
    def set_mouse(self, cursor: bool | ColorCursor) -> None: ...
    def hide_mouse(self) -> None: ...
    def is_mouse_visible(self) -> bool: ...
    def get_mouse_names(self) -> list[str]: ...
    def get_mouse_name(self, cache_only: bool = False, interaction: bool = True) -> str: ...
    def update_mouse(self, mouse_displayable: Displayable | None) -> None: ...
    def set_mouse_pos(self, x: int, y: int, duration: float | None) -> None: ...
    def drawn_since(self, seconds_ago: float) -> bool: ...
    def mobile_save(self) -> None: ...
    def mobile_unlink(self) -> None: ...
    def check_android_start(self) -> None: ...
    def check_suspend(self, ev: EventType) -> bool: ...
    def enter_context(self) -> None: ...
    def post_time_event(self) -> None: ...
    def after_longpress(self) -> None: ...
    def text_event_in_queue(self) -> bool: ...
    def update_text_rect(self) -> None: ...
    def maximum_framerate(self, t: float | None) -> None: ...
    trans_pause: bool
    def interact(
        self,
        clear: bool = True,
        suppress_window: bool = False,
        trans_pause: bool = False,
        pause: float | None = None,
        pause_modal: bool | None = False,
        **kwargs,
    ) -> Any | None: ...
    def consider_gc(self) -> None: ...
    prediction_coroutine: Incomplete
    did_autosave: bool
    did_persistent: bool
    def idle_frame(self, expensive: bool) -> None: ...
    take_layer_displayable: Callable[[renpy.display.layout.Layer], None] | None
    suppress_overlay: bool
    suppress_underlay: bool
    def interact_core(
        self,
        show_mouse: bool = True,
        trans_pause: bool = False,
        suppress_overlay: bool = False,
        suppress_underlay: bool = False,
        mouse: str | None = None,
        preloads: Never = [],
        roll_forward: Any | None = None,
        pause: float | None = None,
        pause_start: float | None = 0.0,
        pause_modal: bool | None = None,
    ) -> tuple[bool, Any | None]: ...
    def timeout(self, offset: float) -> None: ...
    def finish_pending(self) -> None: ...
    def exec_js_cmd(self) -> None: ...
