import renpy
from _typeshed import Incomplete as Incomplete
from renpy.display.render import Render as Render
from renpy.object import Object as Object
from renpy.pygame.event import EventType as EventType
from typing import Any, Callable, Literal, Self, TypedDict, Unpack

type Placement = tuple[float | None, float | None, float | None, float | None, float | None, float | None, bool]

def place(width: float, height: float, sw: float, sh: float, placement: Placement) -> tuple[float, float]: ...

class DisplayableArguments(renpy.object.Object):
    name: tuple[str, ...]
    args: tuple[str, ...]
    prefix: str | None
    lint: bool
    class _DisplayableArguments(TypedDict, total=False):
        name: tuple[str, ...]
        args: tuple[str, ...]
        prefix: str | None
        lint: bool

    def copy(self, **kwargs: Unpack[_DisplayableArguments]) -> DisplayableArguments: ...
    def extraneous(self) -> None: ...

default_style: renpy.style.Style

class Displayable(renpy.object.Object):
    focusable: bool | None
    full_focus_name: tuple[str, int] | None
    role: str
    transform_event: str | None
    transform_event_responder: bool
    _main: Displayable | None
    _composite_parts: list["Displayable"]
    _location: tuple[str, int] | None
    _uses_scope: bool
    _args: Incomplete
    _duplicatable: bool
    _clipping: bool
    _tooltip: Any | None
    _box_skip: bool
    _offer_size: tuple[int, int] | None
    _draggable: bool
    delay: float | None
    id: str | None
    def __ne__(self, o): ...
    style: Incomplete
    focus_name: Incomplete
    default: Incomplete
    def __init__(
        self,
        focus: str | None = None,
        default: bool = False,
        style: str = "default",
        _args: DisplayableArguments | None = None,
        tooltip: Any | None = None,
        default_focus: bool = False,
        **properties: Any,
    ) -> None: ...
    def _copy(self, args: DisplayableArguments | None = None) -> Self: ...
    def _duplicate(self, args: DisplayableArguments | None = None) -> Self: ...
    def _get_tooltip(self) -> Any | None: ...
    def _in_current_store(self) -> Self: ...
    def _unique(self) -> None: ...
    def parameterize(self, name, parameters): ...
    def _equals(self, o: object): ...
    def _repr_info(self) -> str | None: ...
    def __repr__(self) -> str: ...
    def find_focusable(self, callback: Callable[[Displayable | None, str], None], focus_name: str): ...
    def focus(self, default: bool = False): ...
    def unfocus(self, default: bool = False): ...
    def is_focused(self) -> bool: ...
    def set_style_prefix(self, prefix: str, root: bool): ...
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...
    def event(self, ev: renpy.pygame.event.EventType, x: float, y: float, st: float) -> Any | None: ...
    def get_placement(self) -> Placement: ...
    def visit_all(self, callback: Callable[[Displayable], None], seen: set[int] | None = None): ...
    def visit(self) -> list[Displayable | None]: ...
    def per_interact(self) -> None: ...
    def predict_one(self) -> None: ...
    def predict_one_action(self) -> None: ...
    def place(
        self,
        dest: renpy.display.render.Render | None,
        x: float,
        y: float,
        width: float,
        height: float,
        surf: renpy.display.render.Render,
        main: bool = True,
    ) -> tuple[float, float]: ...
    _store_transform_event: bool
    def set_transform_event(self, event: str): ...
    def _handles_event(self, event: str) -> bool: ...
    def _hide(self, st: float, at: float, kind: Literal["hide", "replace", "cancel"]) -> Displayable | None: ...
    def _show(self) -> None: ...
    def _target(self) -> Displayable: ...
    def _change_transform_child(self, child) -> Self: ...
    def _clear(self) -> None: ...
    def _tts_common(self, default_alt: str | None = None, reverse: bool = False, raw: bool = False) -> str: ...
    def _tts(self, raw: bool) -> str: ...
    def _tts_all(self, raw: bool) -> str: ...
