from _typeshed import Incomplete

focus_storage: Incomplete

def capture_focus(name: str = "default") -> None: ...
def clear_capture_focus(name: str = "default") -> None: ...
def get_focus_rect(name: str = "default"): ...

class Focus:
    widget: Incomplete
    arg: Incomplete
    x: Incomplete
    y: Incomplete
    w: Incomplete
    h: Incomplete
    screen: Incomplete
    def __init__(self, widget, arg, x, y, w, h, screen) -> None: ...
    def copy(self): ...
    def inside(self, rect): ...
    def inset_rect(self): ...

argument: Incomplete
screen_of_focused: Incomplete
screen_of_focused_names: Incomplete
screen_of_last_focused_names: Incomplete
grab: Incomplete
global_focus: Incomplete
focus_type: str
pending_focus_type: str
tooltip: Incomplete
last_tooltip: Incomplete
override: Incomplete

def set_focused(widget, arg, screen) -> None: ...
def get_focused(): ...
def get_mouse(): ...
def get_tooltip(screen=None, last: bool = False): ...
def set_grab(widget) -> None: ...
def get_grab(): ...

focus_list: Incomplete

def take_focuses() -> None: ...
def focus_coordinates(): ...

replaced_by: Incomplete
modal_generation: int
old_max_default: int
old_max_default_focus_name: Incomplete

def mark_modal() -> None: ...
def before_interact(roots) -> None: ...
def change_focus(newfocus, default: bool = False): ...
def clear_focus() -> None: ...
def force_focus(d, arg=None): ...
def mouse_handler(ev, x, y, default: bool = False): ...
def focus_extreme(xmul, ymul, wmul, hmul): ...
def check_keyboard_focus() -> None: ...
def points_dist(x0, y0, x1, y1, xfudge, yfudge): ...
def horiz_line_dist(ax0, ay0, ax1, ay1, bx0, by0, bx1, by1): ...
def verti_line_dist(ax0, ay0, ax1, ay1, bx0, by0, bx1, by1): ...
def focus_nearest(
    from_x0, from_y0, from_x1, from_y1, to_x0, to_y0, to_x1, to_y1, line_dist, condition, xmul, ymul, wmul, hmul
): ...
def focus_ordered(delta): ...
def key_handler(ev): ...
