import renpy.pygame as pygame
from renpy.display.displayable import Displayable as Displayable
from renpy.display.screen import ScreenDisplayable as ScreenDisplayable
from typing import Any, Callable, Iterable, Literal

focus_storage: dict[str, tuple[float, float, float, float]]

def capture_focus(name: str = "default") -> None: ...
def clear_capture_focus(name: str = "default") -> None: ...
def get_focus_rect(name: str = "default") -> tuple[float, float, float, float] | None: ...

class Focus:
    widget: Displayable
    arg: Any
    x: float
    y: float
    w: float
    h: float
    screen: ScreenDisplayable
    def __init__(
        self, widget: Displayable, arg: Any, x: float, y: float, w: float, h: float, screen: ScreenDisplayable
    ) -> None: ...
    def copy(self) -> Focus: ...
    def __repr__(self) -> str: ...
    def inside(self, rect: tuple[float, float, float, float]) -> bool: ...
    def inset_rect(self) -> tuple[float, float, float, float]: ...

argument: Any
screen_of_focused: ScreenDisplayable | None
screen_of_focused_names: set[str]
screen_of_last_focused_names: set[str]
grab: Displayable | None
global_focus: Focus | None
focus_type: Literal["keyboard", "mouse"]
pending_focus_type: Literal["keyboard", "mouse"]
tooltip: Any | None
last_tooltip: Any | None
override: tuple[str | tuple[str, ...] | ScreenDisplayable | None, str, str | None] | None

def set_focused(widget: Displayable | None, arg: Any, screen: ScreenDisplayable | None) -> None: ...
def get_focused() -> Displayable | None: ...
def get_mouse() -> str | None: ...
def get_tooltip(screen: str | None = None, last: bool = False) -> Any | None: ...
def set_grab(widget: Displayable | None) -> None: ...
def get_grab() -> Displayable | None: ...

focus_list: list[Focus]

def take_focuses() -> None: ...
def focus_coordinates() -> tuple[float, float, float, float] | tuple[None, None, None, None]: ...

replaced_by: dict[int, Displayable]
modal_generation: int
old_max_default: int
old_max_default_focus_name: tuple[str, int] | None

def mark_modal() -> None: ...
def before_interact(roots: Iterable[Displayable]) -> None: ...
def change_focus(newfocus: Focus | None, default: bool = False) -> Any | None: ...
def clear_focus() -> None: ...
def force_focus(d: Displayable, arg: Any = None) -> Any | None: ...
def mouse_handler(ev: pygame.event.EventType | None, x: int, y: int, default: bool = False) -> Any | None: ...
def focus_extreme(xmul: float, ymul: float, wmul: float, hmul: float) -> Any | None: ...
def check_keyboard_focus() -> None: ...
def points_dist(x0: float, y0: float, x1: float, y1: float, xfudge: float, yfudge: float) -> float: ...
def horiz_line_dist(
    ax0: float, ay0: float, ax1: float, ay1: float, bx0: float, by0: float, bx1: float, by1: float
) -> float: ...
def verti_line_dist(
    ax0: float, ay0: float, ax1: float, ay1: float, bx0: float, by0: float, bx1: float, by1: float
) -> float: ...
def focus_nearest(
    from_x0: float,
    from_y0: float,
    from_x1: float,
    from_y1: float,
    to_x0: float,
    to_y0: float,
    to_x1: float,
    to_y1: float,
    line_dist: Callable[[float, float, float, float, float, float, float, float], float],
    condition: Callable[[tuple[float, float, float, float], tuple[float, float, float, float]], bool],
    xmul: float,
    ymul: float,
    wmul: float,
    hmul: float,
) -> Any | None: ...
def focus_ordered(delta: int) -> Any | None: ...
def key_handler(ev: pygame.event.EventType) -> Any | None: ...
