from _typeshed import Incomplete as Incomplete

DIRECTIONS: Incomplete

def dispatch_gesture(gesture) -> None: ...

class GestureRecognizer:
    x: Incomplete
    y: Incomplete
    def __init__(self) -> None: ...
    min_component: Incomplete
    min_stroke: Incomplete
    current_stroke: Incomplete
    stroke_length: int
    strokes: Incomplete
    def start(self, x, y) -> None: ...
    def take_point(self, x, y) -> None: ...
    def finish(self): ...
    def cancel(self) -> None: ...
    def event(self, ev, x, y): ...

recognizer: Incomplete
