from renpy.pygame.event import EventType as EventType
from typing import Any

DIRECTIONS: list[str]

def dispatch_gesture(gesture: str) -> Any | None: ...

class GestureRecognizer:
    x: int
    y: int
    def __init__(self) -> None: ...
    min_component: float
    min_stroke: float
    current_stroke: str | None
    stroke_length: int
    strokes: list[str]
    def start(self, x: int, y: int) -> None: ...
    def take_point(self, x: int, y: int) -> None: ...
    def finish(self) -> Any | None: ...
    def cancel(self) -> None: ...
    def event(self, ev: EventType, x: float, y: float) -> Any | None: ...

recognizer: GestureRecognizer
