from _typeshed import Incomplete
from concurrent.futures import ThreadPoolExecutor
from typing import Any, Literal

type Surface = renpy.pygame.Surface

class CacheEntry:
    what: Incomplete
    surf: Surface | None
    texture: Any | None
    bounds: Incomplete
    time: int
    def __init__(self, what: ImageBase, surf: Surface, bounds: tuple[int, int, int, int]) -> None: ...
    def size(self) -> int: ...

class Cache:
    time: int
    cache: dict[ImageBase, CacheEntry]
    cache_size: int
    preloads: list[ImageBase]
    first_preload_in_tick: bool
    lock: Incomplete
    preload_lock: Incomplete
    keep_preloading: bool
    preload_blacklist: set[ImageBase]
    cache_limit: int
    in_preload_pass: bool
    preload_thread: Incomplete
    decode_pool: ThreadPoolExecutor | None
    decode_pool_workers: int
    added: set[ImageBase]
    load_log: list[tuple[float, str, bool]]
    def __init__(self) -> None: ...
    def done(self) -> bool: ...
    def get_total_size(self) -> int: ...
    def get_current_size(self, generations: int) -> int: ...
    def init(self) -> None: ...
    def quit(self) -> None: ...
    def clear(self) -> None: ...
    def clear_variable_size(self) -> None: ...
    def get_renders(self) -> list["renpy.display.render.Render"]: ...
    def tick(self) -> None: ...
    def end_tick(self) -> None: ...
    def get(self, image: ImageBase, predict: bool = False, texture: bool = False, render: bool = False) -> Any: ...
    def kill(self, ce: CacheEntry): ...
    def cleanout(self) -> bool: ...
    def flush_file(self, fn: str): ...
    def preload_texture(self, im: ImageBase): ...
    def get_texture(self, im: ImageBase): ...
    def preload_image(self, im: ImageBase): ...
    def start_prediction(self) -> None: ...
    def get_decode_pool(self) -> ThreadPoolExecutor | None: ...
    def preload_thread_main(self) -> None: ...
    def preload_thread_pass(self) -> None: ...
    def add_load_log(self, filename: str): ...

cache: Incomplete

def free_memory() -> None: ...

class ImageBase(renpy.display.displayable.Displayable):
    __version__: int
    optimize_bounds: bool
    oversample: int | None
    pixel_perfect: bool
    obsolete: bool
    obsolete_list: list[tuple[str, int, str]]
    mipmap: Literal["auto", True, False, None]
    fail: Incomplete
    const_size: bool
    cache: bool
    def after_upgrade(self, version) -> None: ...
    rle: Incomplete
    identity: Incomplete
    def __init__(self, *args, **properties) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def load(self) -> Surface: ...
    def render(self, w, h, st, at) -> renpy.display.render.Render: ...
    def get_placement(self): ...
    def predict_one(self) -> None: ...
    def predict_files(self) -> list[str]: ...
    def get_hash(self) -> int: ...
    def get_oversample(self) -> int: ...
    def get_oversampled_image(self) -> ImageBase: ...

ignored_images: set[str]
images_to_ignore: set[str]

class Image(ImageBase):
    obsolete: bool
    is_svg: bool
    dpi: int
    filename: Incomplete
    pixel_perfect: Incomplete
    const_size: Incomplete
    def __init__(self, filename: str, dpi: int = 96, **properties) -> None: ...
    def get_oversampled_image(self): ...
    def get_hash(self): ...
    def get_oversample(self): ...
    def load(self, unscaled: bool = False): ...
    def predict_files(self): ...

class Data(ImageBase):
    obsolete: bool
    data: Incomplete
    filename: Incomplete
    const_size: bool
    def __init__(self, data: bytes, filename: str, **properties) -> None: ...
    def load(self): ...

class ZipFileImage(ImageBase):
    obsolete: bool
    zipfilename: Incomplete
    filename: Incomplete
    const_size: bool
    def __init__(self, zipfilename: str, filename: str, mtime: int = 0, **properties) -> None: ...
    def load(self): ...
    def predict_files(self): ...

class Null(ImageBase):
    obsolete: bool
    color: Incomplete
    const_size: bool
    def __init__(self, color=(0, 0, 0, 0), **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

class UnoptimizedTexture(ImageBase):
    obsolete: bool
    image: Incomplete
    const_size: Incomplete
    def __init__(self, im, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

def image(arg, loose: bool = False, **properties): ...
def expand_bounds(
    bounds: tuple[int, int, int, int], size: tuple[int, int], amount: int
) -> tuple[int, int, int, int]: ...
def ensure_bounds_divide_evenly(bounds: tuple[int, int, int, int], n: int) -> tuple[int, int, int, int]: ...
def load_image(im) -> renpy.display.render.Render: ...
def load_surface(im) -> Surface: ...
def load_rgba(data: bytes, size: tuple[int, int]) -> Any: ...
def unoptimized_texture(d): ...
def render_for_texture(d, width, height, st, at): ...
def reset_module() -> None: ...

class Composite(ImageBase):
    size: Incomplete
    positions: Incomplete
    images: Incomplete
    oversample: Incomplete
    const_size: Incomplete
    def __init__(self, size, *args, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

class Scale(ImageBase):
    image: Incomplete
    oversample: Incomplete
    width: Incomplete
    height: Incomplete
    bilinear: Incomplete
    const_size: bool
    def __init__(self, im, width, height, bilinear: bool = True, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

class FactorScale(ImageBase):
    image: Incomplete
    oversample: Incomplete
    width: Incomplete
    height: Incomplete
    bilinear: Incomplete
    const_size: Incomplete
    def __init__(self, im, width, height=None, bilinear: bool = True, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

class Flip(ImageBase):
    image: Incomplete
    oversample: Incomplete
    horizontal: Incomplete
    vertical: Incomplete
    const_size: Incomplete
    def __init__(self, im, horizontal: bool = False, vertical: bool = False, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

class Rotozoom(ImageBase):
    image: Incomplete
    oversample: Incomplete
    angle: Incomplete
    zoom: Incomplete
    const_size: Incomplete
    def __init__(self, im, angle, zoom, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

class Crop(ImageBase):
    image: Incomplete
    oversample: Incomplete
    x: Incomplete
    y: Incomplete
    w: Incomplete
    h: Incomplete
    const_size: bool
    def __init__(self, im, x, y=None, w=None, h=None, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

ramp_cache: Incomplete

def ramp(start, end): ...

identity: Incomplete

class Map(ImageBase):
    image: Incomplete
    oversample: Incomplete
    rmap: Incomplete
    gmap: Incomplete
    bmap: Incomplete
    amap: Incomplete
    force_alpha: Incomplete
    const_size: Incomplete
    def __init__(self, im, rmap=..., gmap=..., bmap=..., amap=..., force_alpha: bool = False, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

class Twocolor(ImageBase):
    image: Incomplete
    oversample: Incomplete
    white: Incomplete
    black: Incomplete
    force_alpha: Incomplete
    def __init__(self, im, white, black, force_alpha: bool = False, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

class Recolor(ImageBase):
    image: Incomplete
    oversample: Incomplete
    rmul: Incomplete
    gmul: Incomplete
    bmul: Incomplete
    amul: Incomplete
    force_alpha: Incomplete
    const_size: Incomplete
    def __init__(
        self,
        im,
        rmul: int = 255,
        gmul: int = 255,
        bmul: int = 255,
        amul: int = 255,
        force_alpha: bool = False,
        **properties,
    ) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

class Blur(ImageBase):
    image: Incomplete
    oversample: Incomplete
    rx: Incomplete
    ry: Incomplete
    const_size: Incomplete
    def __init__(self, im, xrad, yrad=None, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

class MatrixColor(ImageBase):
    image: Incomplete
    oversample: Incomplete
    matrix: Incomplete
    const_size: Incomplete
    def __init__(self, im, matrix, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

class matrix(tuple):
    def __new__(cls, *args): ...
    def mul(self, a, b): ...
    def scalar_mul(self, other): ...
    def vector_mul(self, o): ...
    def __add__(self, other): ...
    __radd__ = __add__
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __mul__(self, other): ...
    def __rmul__(self, other): ...
    @staticmethod
    def identity(): ...
    @staticmethod
    def saturation(level, desat=(0.2126, 0.7152, 0.0722)): ...
    @staticmethod
    def desaturate(): ...
    @staticmethod
    def tint(r, g, b): ...
    @staticmethod
    def invert(): ...
    @staticmethod
    def brightness(b): ...
    @staticmethod
    def opacity(o): ...
    @staticmethod
    def contrast(c): ...
    @staticmethod
    def hue(h): ...
    @staticmethod
    def colorize(black_color, white_color): ...

def Grayscale(im, desat=(0.2126, 0.7152, 0.0722), **properties): ...
def Sepia(im, tint=(1.0, 0.94, 0.76), desat=(0.2126, 0.7152, 0.0722), **properties): ...
def Color(im, color): ...
def Alpha(image, alpha, **properties): ...

class Tile(ImageBase):
    image: Incomplete
    oversample: Incomplete
    size: Incomplete
    const_size: bool
    def __init__(self, im, size=None, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...

class AlphaMask(ImageBase):
    base: Incomplete
    mask: Incomplete
    oversample: Incomplete
    const_size: Incomplete
    def __init__(self, base, mask, **properties) -> None: ...
    def get_hash(self): ...
    def load(self): ...
    def predict_files(self): ...
