import renpy
from renpy.display.displayable import Displayable as Displayable
from renpy.display.render import render as render
from renpy.object import Object as Object
from renpy.types import Unused as Unused

cached: Unused

class ImageMapCrop(Displayable):
    child: Displayable
    rect: tuple[float, float, float, float]
    def __init__(self, child: Displayable, rect: tuple[float, float, float, float]) -> None: ...
    def visit(self) -> list[Displayable | None]: ...
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...

class ImageCacheCrop(Displayable):
    def __init__(self, cache, index) -> None: ...
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...

class ImageMapCache(renpy.object.Object):
    enable: bool
    def __init__(self, enable: bool) -> None: ...
    def crop(self, d: Displayable, rect: tuple[float, float, float, float]) -> ImageMapCrop: ...
    def finish(self) -> None: ...
