import renpy
from _typeshed import SupportsRichComparison as SupportsRichComparison
from renpy.display.displayable import (
    Displayable as Displayable,
    Placement as Placement,
    DisplayableArguments as DisplayableArguments,
)
from renpy.display.render import Render as Render, render as render
from renpy.pygame.event import EventType as EventType
from renpy.types import Unused as Unused
from typing import Any, Callable, Literal, Self
from _typeshed import Incomplete as Incomplete

images: dict[tuple[str, ...], Displayable]
image_attributes: dict[str, dict[tuple[str, ...], Displayable]]
image_names: list[str]

def list_images() -> list[str]: ...
def get_available_image_tags() -> list[str]: ...
def get_available_image_attributes(tag: str, attributes: tuple[str, ...] = ()) -> list[tuple[str, ...]]: ...
def get_tag_method(tag: str, method: str) -> Unused | None: ...
def check_image_attributes(tag: str, attributes: list[str]) -> tuple[str, ...] | None: ...
def get_ordered_image_attributes(
    tag: str, attributes: tuple[str, ...] = (), sort: Callable[[str], SupportsRichComparison] | None = None
) -> list[str]: ...
def register_image(name: tuple[str, ...], d: Displayable) -> None: ...
def image_exists(name: str | tuple[str, ...], exact: bool = False) -> bool: ...
def get_registered_image(name: str | tuple[str, ...]) -> Displayable | None: ...
def wrap_render(child: Displayable, w: float, h: float, st: float, at: float) -> Render: ...

class ImageNotFound(LookupError):
    tag: str
    attributes: tuple[str, ...]
    def __init__(self, tag: str, *attributes: str) -> None: ...
    def get_suggestion(self) -> str | None: ...

class ImageReference(Displayable):
    nosave: list[str]
    target: Displayable | None
    old_transform: renpy.display.transform.Transform | None
    param_target: renpy.display.transform.Transform | None
    __version__: int
    def after_upgrade(self, version: int) -> None: ...
    name: str | tuple[str, ...] | Displayable
    def __init__(self, name: str | tuple[str, ...] | Displayable, **properties) -> None: ...
    def _repr_info(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, o: object) -> bool: ...
    def _target(self) -> Displayable: ...
    def find_target(self) -> bool: ...
    _duplicatable: bool
    def _duplicate(self, args: DisplayableArguments | None) -> ImageReference: ...
    def _unique(self) -> None: ...
    def _in_current_store(self) -> Self: ...
    def _handles_event(self, event: str) -> bool: ...
    def _hide(self, st: float, at: float, kind: Literal["hide", "replace", "cancel"]) -> Displayable | None: ...
    def set_transform_event(self, event: str) -> None: ...
    def event(self, ev: EventType, x: float, y: float, st: float) -> Any | None: ...
    def render(self, width: int, height: int, st: float, at: float) -> renpy.display.render.Render: ...
    def get_placement(self) -> Placement: ...
    def visit(self) -> list[Displayable]: ...

class DynamicImage(Displayable):
    nosave: list[str]
    target: Displayable | None
    raw_target: Displayable | None
    locked: bool
    hash_name: str | tuple[str, ...] | None
    scope: dict[str, Any] | None
    name: str | list[str]
    _uses_scope: bool
    _duplicatable: bool
    def __init__(self, name: str | list[str], scope: dict[str, Any] | None = None, **properties) -> None: ...
    def _scope(self, scope: Incomplete, update: Incomplete) -> Incomplete: ...
    def _repr_info(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, o: object) -> bool: ...
    def _target(self) -> Self | Displayable: ...
    def set_style_prefix(self, prefix: str, root: bool) -> None: ...
    def find_target(self, scope: dict[str, Any] | None = None, update: bool = True) -> bool | None: ...
    def _duplicate(self, args: DisplayableArguments | None) -> DynamicImage: ...
    def _unique(self) -> None: ...
    def _in_current_store(self) -> Self: ...
    def _handles_event(self, event: str) -> bool: ...
    def _hide(self, st: float, at: float, kind: Literal["hide", "replace", "cancel"]) -> Displayable | None: ...
    def set_transform_event(self, event: str) -> None: ...
    def event(self, ev: EventType, x: float, y: float, st: float) -> Any | None: ...
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...
    def get_placement(self) -> Placement: ...
    def visit(self) -> list[Displayable]: ...
    def per_interact(self) -> None: ...

class ShownImageInfo(renpy.object.Object):
    __version__: int
    attributes: dict[tuple[str | None, str], tuple[str, ...]]
    shown: set[tuple[str | None, str]]
    def __init__(self, old: ShownImageInfo | None = None) -> None: ...
    def after_upgrade(self, version: int) -> None: ...
    def get_attributes(self, layer: str | None, tag: str, default: tuple[str, ...] = ()) -> tuple[str, ...]: ...
    def showing(self, layer: str | None, name: tuple[str, ...], exact: bool = False) -> bool | None: ...
    def get_showing_tags(self, layer: str | None) -> set[str]: ...
    def get_hidden_tags(self, layer: str | None) -> set[str]: ...
    def predict_scene(self, layer: str | None) -> None: ...
    def predict_show(self, layer: str | None, name: tuple[str, ...], show: bool = True) -> None: ...
    def predict_hide(self, layer: str | None, name: tuple[str, ...]) -> None: ...
    def apply_attributes(self, layer: str | None, tag: str, name: tuple[str, ...]) -> tuple[str, ...] | None: ...
    def choose_image(
        self, tag: str, required: list[str], optional: list[str], exception_name: tuple[str, ...]
    ) -> tuple[str, ...] | None: ...

Image = renpy.display.im.image
Solid = renpy.display.imagelike.Solid
Frame = renpy.display.imagelike.Frame
ImageButton = renpy.display.behavior.ImageButton
