import renpy
from _typeshed import Incomplete as Incomplete
from renpy.display.displayable import Displayable as Displayable
from renpy.display.render import Render as Render, render as render
from renpy.object import Object as Object

images: Incomplete
image_attributes: Incomplete
image_names: Incomplete

def list_images(): ...
def get_available_image_tags(): ...
def get_available_image_attributes(tag, attributes=()): ...
def get_tag_method(tag, method): ...
def check_image_attributes(tag, attributes): ...
def get_ordered_image_attributes(tag, attributes=(), sort=None): ...
def register_image(name, d) -> None: ...
def image_exists(name, exact: bool = False): ...
def get_registered_image(name): ...
def wrap_render(child, w, h, st, at): ...

class ImageNotFound(LookupError):
    tag: Incomplete
    attributes: Incomplete
    def __init__(self, tag: str, *attributes: str) -> None: ...
    def get_suggestion(self): ...

class ImageReference(Displayable):
    nosave: Incomplete
    target: Displayable | None
    old_transform: Incomplete
    param_target: Incomplete
    __version__: int
    def after_upgrade(self, version) -> None: ...
    name: Incomplete
    def __init__(self, name, **properties) -> None: ...
    def __hash__(self): ...
    def __eq__(self, o): ...
    def find_target(self): ...
    def set_transform_event(self, event): ...
    def event(self, ev, x, y, st): ...
    def render(self, width, height, st, at): ...
    def get_placement(self): ...
    def visit(self): ...

class DynamicImage(Displayable):
    nosave: Incomplete
    target: Displayable | None
    raw_target: Displayable | None
    locked: bool
    hash_name: Incomplete
    scope: Incomplete
    name: Incomplete
    def __init__(self, name, scope=None, **properties) -> None: ...
    def __hash__(self): ...
    def __eq__(self, o): ...
    def set_style_prefix(self, prefix, root) -> None: ...
    def find_target(self, scope=None, update: bool = True): ...
    def set_transform_event(self, event): ...
    def event(self, ev, x, y, st): ...
    def render(self, width, height, st, at): ...
    def get_placement(self): ...
    def visit(self): ...
    def per_interact(self): ...

class ShownImageInfo(renpy.object.Object):
    __version__: int
    attributes: Incomplete
    shown: Incomplete
    def __init__(self, old=None) -> None: ...
    def after_upgrade(self, version) -> None: ...
    def get_attributes(self, layer, tag, default=()): ...
    def showing(self, layer, name, exact: bool = False): ...
    def get_showing_tags(self, layer): ...
    def get_hidden_tags(self, layer): ...
    def predict_scene(self, layer) -> None: ...
    def predict_show(self, layer, name, show: bool = True) -> None: ...
    def predict_hide(self, layer, name) -> None: ...
    def apply_attributes(self, layer, tag, name): ...
    def choose_image(self, tag, required, optional, exception_name): ...

Image = renpy.display.im.image
Solid = renpy.display.imagelike.Solid
Frame = renpy.display.imagelike.Frame
ImageButton = renpy.display.behavior.ImageButton
