import types
from collections.abc import Callable
from types import CodeType
from typing import TYPE_CHECKING, Any, Literal, Protocol, Self

import renpy
from renpy.display.displayable import Displayable as Displayable
from renpy.display.displayable import DisplayableArguments as DisplayableArguments
from renpy.display.displayable import Placement as Placement
from renpy.display.position import absolute as absolute
from renpy.display.scenelists import AtList as AtList
from renpy.pygame.event import EventType
from renpy.types import DisplayableLike as DisplayableLike

if TYPE_CHECKING:
    class DynamicDisplayableFunction(Protocol):
        def __call__(self, st: float, at: float, *args: Any, **kwargs: Any) -> tuple[Displayable, float | None]: ...

compute_raw: Callable[[renpy.types.Position, float], int | float | absolute]

def xyminimums(style: renpy.style.Style, width: float, height: float) -> tuple[float, float]: ...

class Null(renpy.display.displayable.Displayable):
    width: float
    height: float
    def __init__(self, width: float = 0, height: float = 0, **properties: Any) -> None: ...
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...

class Container(renpy.display.displayable.Displayable):
    _list_type = list
    children: list[Displayable]
    child: Displayable | None
    offsets: list[tuple[float, float]]
    def __init__(self, *args: Displayable, **properties: Any) -> None: ...
    def set_transform_event(self, event: str) -> None: ...
    def _handles_event(self, event: str) -> bool: ...
    def set_style_prefix(self, prefix: str, root: bool) -> None: ...
    def _duplicate(self, args: DisplayableArguments | None = None) -> Container: ...
    _duplicatable: bool
    def _unique(self) -> None: ...
    def _in_current_store(self) -> Self: ...
    def add(self, d: DisplayableLike) -> None: ...
    def _clear(self) -> None: ...
    def remove(self, d: Displayable) -> None: ...
    def update(self) -> None: ...
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...
    def event(self, ev: renpy.pygame.event.EventType, x: float, y: float, st: float) -> Any | None: ...
    def visit(self) -> list[Displayable]: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None
    ) -> bool: ...

def Composite(
    size: tuple[float, float], *args: tuple[float, float] | DisplayableLike, **properties: Any
) -> MultiBox: ...

LiveComposite = Composite

class Position(Container):
    def __init__(
        self, child: DisplayableLike, style: renpy.style.StyleLike = "image_placement", **properties: Any
    ) -> None: ...
    offsets: list[tuple[float, float]]
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...
    def get_placement(self) -> Placement: ...

class Grid(Container):
    allow_underfull: bool | None
    gridmap: list[tuple[int, int]] | None
    cols: int
    rows: int
    transpose: bool
    right_to_left: bool
    bottom_to_top: bool
    def __init__(
        self,
        cols: int,
        rows: int,
        padding: int | None = None,
        transpose: bool = False,
        style: renpy.style.StyleLike = "grid",
        allow_underfull: bool | None = None,
        *,
        right_to_left: bool = False,
        bottom_to_top: bool = False,
        **properties: Any,
    ) -> None: ...
    offsets: list[tuple[float, float]]
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...
    def add(self, d: DisplayableLike) -> None: ...
    def per_interact(self) -> None: ...
    def generate_gridmap(self) -> list[tuple[int, int]]: ...

class IgnoreLayers(Exception): ...

def default_modal_function(
    ev: renpy.pygame.event.EventType | None, x: float, y: float, w: float | None, h: float | None
) -> bool: ...
def check_modal(
    modal: bool | Callable[[renpy.pygame.event.EventType | None, float, float, float | None, float | None], bool],
    ev: renpy.pygame.event.EventType | None,
    x: float,
    y: float,
    w: float | None,
    h: float | None,
) -> bool: ...

class MultiBox(Container):
    layer_name: str | None
    first: bool
    order_reverse: bool
    layout: str | None
    _layer_at_list: tuple[float | None, AtList] | None
    _camera_list: tuple[float | None, AtList] | None
    layers: dict[str, MultiBox] | None
    untransformed_layer: MultiBox | None
    adjust_times: bool
    _clipping: bool
    default_layout: str | None
    start_times: list[float | bool | None]
    anim_times: list[float | bool | None]
    scene_list: list[renpy.display.scenelists.SceneListEntry] | None
    def __init__(
        self,
        spacing: int | None = None,
        layout: str | None = None,
        style: renpy.style.StyleLike = "default",
        **properties: Any,
    ) -> None: ...
    def _clear(self) -> None: ...
    def _in_current_store(self) -> Self: ...
    def _classname(self) -> str: ...
    def add(
        self, widget: Displayable, start_time: float | bool | None = None, anim_time: float | bool | None = None
    ) -> None: ...
    def append_scene_list(self, l: list[renpy.display.scenelists.SceneListEntry]) -> None: ...
    def update_times(self) -> None: ...
    offsets: list[tuple[float, float]]
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...
    def event(self, ev: EventType, x: float, y: float, st: float) -> Any | None: ...
    def _tts(self, raw: bool) -> str: ...

def Fixed(**properties: Any) -> MultiBox: ...

class SizeGroup(renpy.object.Object):
    members: list[Displayable]
    _width: int | None
    computing_width: bool
    def __init__(self) -> None: ...
    def width(self, width: int, height: int, st: float, at: float) -> int: ...

size_groups: dict[str, SizeGroup]

class Window(Container):
    window_size: tuple[float, float]
    current_child: Displayable | None
    def __init__(
        self, child: DisplayableLike | None = None, style: renpy.style.StyleLike = "window", **properties: Any
    ) -> None: ...
    def visit(self) -> list[Displayable]: ...
    def get_child(self) -> Displayable | None: ...
    def per_interact(self) -> None: ...
    offsets: list[tuple[float, float]]
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...
    def event(self, ev: EventType, x: float, y: float, st: float) -> Any | None: ...

def dynamic_displayable_compat(st: float, at: float, expr: str) -> tuple[Displayable, None]: ...

class DynamicDisplayable(renpy.display.displayable.Displayable):
    nosave: list[str]
    _duplicatable: bool
    raw_child: Displayable | None
    last_st: float
    last_at: float
    child: Displayable | None
    def after_setstate(self) -> None: ...
    predict_function: Callable[..., Displayable | list[Displayable]] | None
    function: DynamicDisplayableFunction
    args: tuple[Any, ...]
    kwargs: dict[str, Any]
    def __init__(self, function: DynamicDisplayableFunction | str, *args: Any, **kwargs: Any) -> None: ...
    def _duplicate(self, args: DisplayableArguments | None = None) -> DynamicDisplayable: ...
    def visit(self) -> list[Displayable]: ...
    def update(self, st: float, at: float) -> None: ...
    def per_interact(self) -> None: ...
    def render(self, w: float, h: float, st: float, at: float) -> renpy.display.render.Render: ...
    def predict_one(self) -> None: ...
    def get_placement(self) -> Placement | None: ...
    def event(self, ev: EventType, x: float, y: float, st: float) -> Any | None: ...

cond_cache: dict[str, CodeType]

def condition_switch_pick(switch: list[tuple[str | bool | None, Displayable]]) -> Displayable: ...
def condition_switch_show(
    st: float, at: float, switch: list[tuple[str | bool | None, Displayable]], predict_all: bool | None = None
) -> tuple[Displayable, None]: ...
def condition_switch_predict(
    switch: list[tuple[str | bool | None, Displayable]], predict_all: bool | None = None
) -> list[Displayable]: ...
def ConditionSwitch(*args: str | bool | None | DisplayableLike, **kwargs: Any) -> Position: ...
def ShowingSwitch(*args: str | tuple[str, ...] | None | DisplayableLike, **kwargs: Any) -> Position: ...

class IgnoresEvents(Container):
    def __init__(self, child: DisplayableLike, **properties: Any) -> None: ...
    def render(self, w: float, h: float, st: float, at: float) -> renpy.display.render.Render: ...
    def get_placement(self) -> Placement: ...
    def event(self, ev: EventType, x: float, y: float, st: float) -> Any | None: ...

def Crop(
    rect: tuple[float, float, float, float], child: DisplayableLike, **properties: Any
) -> renpy.display.motion.Transform: ...

LiveCrop = Crop

class Side(Container):
    possible_positions: set[str]
    sized: bool
    def after_setstate(self) -> None: ...
    positions: tuple[str, ...]
    def __init__(
        self, positions: str | list[str], style: renpy.style.StyleLike = "side", **properties: Any
    ) -> None: ...
    def add(self, d: DisplayableLike) -> None: ...
    def _clear(self) -> None: ...
    def per_interact(self) -> None: ...
    cwidth: float
    cheight: float
    top: float
    bottom: float
    left: float
    right: float
    offsets: list[tuple[float, float]]
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...

class Alpha(renpy.display.displayable.Displayable):
    start: float
    end: float
    time: float
    child: Displayable
    repeat: bool
    anim_timebase: bool
    time_warp: Callable[[float], float] | None
    def __init__(
        self,
        start: float,
        end: float,
        time: float,
        child: DisplayableLike | None = None,
        repeat: bool = False,
        bounce: bool = False,
        anim_timebase: bool = False,
        time_warp: Callable[[float], float] | None = None,
        **properties: Any,
    ) -> None: ...
    def visit(self) -> list[Displayable]: ...
    def render(self, height: float, width: float, st: float, at: float) -> renpy.display.render.Render: ...

class AdjustTimes(Container):
    start_time: float | None
    anim_time: float | None
    def __init__(
        self, child: DisplayableLike, start_time: float | None, anim_time: float | None, **properties: Any
    ) -> None: ...
    def adjusted_times(self) -> tuple[float, float]: ...
    offsets: list[tuple[float, float]]
    def render(self, w: float, h: float, st: float, at: float) -> renpy.display.render.Render: ...
    def event(self, ev: EventType, x: float, y: float, st: float) -> Any | None: ...
    def get_placement(self) -> Placement: ...

class MatchTimes(Container):
    target: AdjustTimes
    def __init__(self, child: DisplayableLike, target: AdjustTimes, **properties: Any) -> None: ...
    offsets: list[tuple[float, float]]
    def render(self, w: int, h: int, st: float, at: float) -> renpy.display.render.Render: ...
    def get_placement(self) -> Placement: ...

class Tile(Container):
    def __init__(self, child: DisplayableLike, style: renpy.style.StyleLike = "tile", **properties: Any) -> None: ...
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...

LiveTile = Tile

class Flatten(Container):
    drawable_resolution: bool
    def __init__(self, child: DisplayableLike, drawable_resolution: bool = True, **properties: Any) -> None: ...
    offsets: list[tuple[float, float]]
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...
    def get_placement(self) -> Placement: ...

class AlphaMask(Container):
    invert: bool
    _duplicatable: bool
    mask: Displayable
    def __init__(
        self, child: DisplayableLike, mask: DisplayableLike, invert: bool = False, **properties: Any
    ) -> None: ...
    def _duplicate(self, args: DisplayableArguments | None = None) -> AlphaMask: ...
    def _unique(self) -> None: ...
    def visit(self) -> list[Displayable]: ...
    offsets: list[tuple[float, float]]
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...

class NearRect(Container):
    preferred_side: Literal["left", "top", "right", "bottom"]
    invert_offsets: bool
    possible_positions: set[str]
    parent_rect: tuple[float, float, float, float] | None
    focus_rect: str | None
    hide_parent_rect: tuple[float, float, float, float] | None
    def __init__(
        self,
        child: DisplayableLike | None = None,
        rect: tuple[float, float, float, float] | None = None,
        focus: str | None = None,
        preferred_side: Literal["left", "top", "right", "bottom", False] = False,
        invert_offsets: bool = False,
        replaces: Self | None = None,
        **properties: Any,
    ) -> None: ...
    def per_interact(self) -> None: ...
    offsets: list[tuple[float, float]]
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...
    def event(self, ev: EventType, x: float, y: float, st: float) -> Any | None: ...
    def _tts(self, raw: bool) -> str: ...

class Layer(AdjustTimes):
    layers: dict[str, Displayable]
    layer: str
    _clipping: bool
    def __init__(self, layer: str, **properties: Any) -> None: ...
    start_time: float | None
    anim_time: float | None
    def add(self, d: DisplayableLike, st: float | None = None, at: float | None = None) -> None: ...
    def visit_all(self, callback: Callable[[Displayable], None], seen: set[int] | None = None) -> None: ...
    def per_interact(self) -> None: ...
