from _frozen_importlib import BuiltinImporter as BuiltinImporter
from typing import Literal, Sequence, Self, overload

class Matrix:
    def __init__(self, l: Sequence[float]) -> None: ...
    def __eq__(self, value): ...
    def __ge__(self, value): ...
    def __gt__(self, value): ...
    def __le__(self, value): ...
    def __lt__(self, value): ...
    def __ne__(self, value): ...
    def __rmul__(self, value) -> None: ...
    @staticmethod
    def identity() -> Matrix: ...
    def inverse(self) -> Matrix: ...
    def is_2d_null(self) -> bool: ...
    def is_unit_aligned(self) -> bool: ...
    @staticmethod
    def offset(x: float, y: float, z: float) -> Matrix: ...
    @staticmethod
    def perspective(w: float, h: float, n: float, p: float, f: float) -> Matrix: ...
    @staticmethod
    def rotate(x: float, y: float, z: float) -> Matrix: ...
    @staticmethod
    def scale(x: float, y: float, z: float) -> Matrix: ...
    @staticmethod
    def screen_projection(w: float, h: float) -> Matrix: ...
    def take(self, other: Matrix) -> Self: ...
    @staticmethod
    def texture_projection(w: float, h: float) -> Matrix: ...
    @overload
    def transform(
        self, x: float, y: float, z: float = 0.0, w: float = 1.0, *, components: Literal[4]
    ) -> tuple[float, float, float, float]: ...
    @overload
    def transform(
        self, x: float, y: float, z: float = 0.0, w: float = 1.0, *, components: Literal[3]
    ) -> tuple[float, float, float]: ...
    @overload
    def transform(
        self, x: float, y: float, z: float = 0.0, w: float = 1.0, components: Literal[2] = ...
    ) -> tuple[float, float]: ...
    def transform(
        self, x: float, y: float, z: float = 0.0, w: float = 1.0, components: int = 2
    ) -> tuple[float, ...]: ...
    def transpose(self) -> Matrix: ...
    xdx: float
    ydx: float
    zdx: float
    wdx: float
    xdy: float
    ydy: float
    zdy: float
    wdy: float
    xdz: float
    ydz: float
    zdz: float
    wdz: float
    xdw: float
    ydw: float
    zdw: float
    wdw: float

class Matrix2D(Matrix):
    def __init__(self, xdx: float, xdy: float, ydx: float, ydy: float) -> None: ...
    xdx: float
    ydx: float
    zdx: float
    wdx: float
    xdy: float
    ydy: float
    zdy: float
    wdy: float
    xdz: float
    ydz: float
    zdz: float
    wdz: float
    xdw: float
    ydw: float
    zdw: float
    wdw: float

def identity_matrix() -> Matrix: ...
def offset_matrix(x: float, y: float, z: float) -> Matrix: ...
def perspective_matrix(w: float, h: float, n: float, p: float, f: float) -> Matrix: ...
def rotate_matrix(x: float, y: float, z: float) -> Matrix: ...
def scale_matrix(x: float, y: float, z: float) -> Matrix: ...
def screen_projection_matrix(w: float, h: float) -> Matrix: ...
def texture_projection_matrix(w: float, h: float) -> Matrix: ...
