import renpy
from _typeshed import Incomplete

class Texture:
    texture_wrap: Incomplete
    displayable: Incomplete
    focus: Incomplete
    main: Incomplete
    fit: Incomplete
    def __init__(self, displayable, focus, main, fit, texture_wrap) -> None: ...

class Model(renpy.display.displayable.Displayable):
    size: Incomplete
    textures: Incomplete
    shaders: Incomplete
    uniforms: Incomplete
    properties: Incomplete
    def __init__(self, size=None, **properties) -> None: ...
    def grid_mesh(self, width, height): ...
    def texture(self, displayable, focus: bool = False, main: bool = False, fit: bool = False, texture_wrap=None): ...
    def child(self, displayable, fit: bool = False): ...
    def shader(self, shader): ...
    def uniform(self, name, value): ...
    def property(self, name, value): ...
    def set_style_prefix(self, prefix, root) -> None: ...
    def visit(self): ...
    def render(self, width, height, st, at): ...
