from _typeshed import Incomplete as Incomplete

def convert_and_call(function, src, dst, *args) -> None: ...
def pixellate(src, dst, avgwidth, avgheight, outwidth, outheight) -> None: ...
def scale(s, size): ...

bo32: Incomplete
bo_cache: Incomplete

def byte_offset(src): ...
def endian_order(src, r, g, b, a): ...
def linmap(src, dst, rmap, gmap, bmap, amap) -> None: ...

save_png: Incomplete

def map(src, dst, rmap, gmap, bmap, amap) -> None: ...
def blur(src, wrk, dst, xrad, yrad=None) -> None: ...
def twomap(src, dst, white, black) -> None: ...
def alpha_munge(src, dst, amap) -> None: ...
def bilinear_scale(
    src, dst, sx: int = 0, sy: int = 0, sw=None, sh=None, dx: int = 0, dy: int = 0, dw=None, dh=None, precise: int = 0
) -> None: ...

self: Incomplete
blend: Incomplete

def imageblend(a, b, dst, img, amap) -> None: ...
def colormatrix(src, dst, matrix) -> None: ...
def subpixel(src, dst, x, y) -> None: ...
def premultiply_alpha(src): ...
