from _typeshed import Incomplete as Incomplete
from renpy.pygame.surface import Surface as Surface
from typing import Any, Callable, Sequence, TypeVar

T = TypeVar("T")

def convert_and_call(function: Callable[..., Any], src: Surface, dst: Surface, *args) -> None: ...
def pixellate(src: Surface, dst: Surface, avgwidth: int, avgheight: int, outwidth: int, outheight: int) -> None: ...
def scale(s: Surface, size: tuple[int, int]) -> Surface: ...

bo32: dict[int, int]
bo_cache: list[int] | None

def byte_offset(src: Surface) -> list[int]: ...
def endian_order(src: Surface, r: T, g: T, b: T, a: T) -> list[T]: ...
def linmap(src: Surface, dst: Surface, rmap: int, gmap: int, bmap: int, amap: int) -> None: ...

save_png: Incomplete

def map(src: Surface, dst: Surface, rmap: bytes, gmap: bytes, bmap: bytes, amap: bytes) -> None: ...
def blur(src: Surface, wrk: Surface, dst: Surface, xrad: float, yrad: float | None = None) -> None: ...
def twomap(src: Surface, dst: Surface, white: tuple[int, int, int, int], black: tuple[int, int, int, int]) -> None: ...
def alpha_munge(src: Surface, dst: Surface, amap: bytes) -> None: ...
def bilinear_scale(
    src: Surface,
    dst: Surface,
    sx: int = 0,
    sy: int = 0,
    sw: int | None = None,
    sh: int | None = None,
    dx: int = 0,
    dy: int = 0,
    dw: int | None = None,
    dh: int | None = None,
    precise: int = 0,
) -> None: ...

self: Incomplete
blend: Incomplete

def imageblend(a: Surface, b: Surface, dst: Surface, img: Surface, amap: bytes) -> None: ...
def colormatrix(src: Surface, dst: Surface, matrix: Sequence[float]) -> None: ...
def subpixel(src: Surface, dst: Surface, x: float, y: float) -> None: ...
def premultiply_alpha(src: Surface) -> Surface: ...
