from renpy.types import Position as Position
from typing import Any, SupportsIndex, overload

class absolute(float):
    def __divmod__(self, value: float) -> tuple[absolute, absolute]: ...
    def __rdivmod__(self, value: float) -> tuple[absolute, absolute]: ...
    def __add__(self, value: float) -> absolute: ...
    def __radd__(self, value: float) -> absolute: ...
    def __sub__(self, value: float) -> absolute: ...
    def __rsub__(self, value: float) -> absolute: ...
    def __mul__(self, value: float) -> absolute: ...
    def __rmul__(self, value: float) -> absolute: ...
    def __truediv__(self, value: float) -> absolute: ...
    def __rtruediv__(self, value: float) -> absolute: ...
    def __floordiv__(self, value: float) -> absolute: ...
    def __rfloordiv__(self, value: float) -> absolute: ...
    def __mod__(self, value: float) -> absolute: ...
    def __rmod__(self, value: float) -> absolute: ...
    def __pow__(self, value: float, mod: None = None) -> Any: ...
    def __rpow__(self, value: float, mod: None = None) -> Any: ...
    def __neg__(self) -> absolute: ...
    def __pos__(self) -> absolute: ...
    def __abs__(self) -> absolute: ...
    @overload
    def __round__(self, ndigits: None = None) -> int: ...
    @overload
    def __round__(self, ndigits: SupportsIndex) -> absolute: ...
    def conjugate(self) -> absolute: ...
    def fromhex(self, s: str) -> absolute: ...
    @overload
    @staticmethod
    def compute_raw(value: position, room: float) -> float: ...
    @overload
    @staticmethod
    def compute_raw[T: int | float | absolute](value: T, room: float) -> T: ...
    @staticmethod
    def compute(value: Position, room: float) -> absolute: ...

class position:
    absolute: _absolute
    relative: float
    @overload
    def __new__(cls, _: position) -> position: ...
    @overload
    def __new__(cls, absolute: int | _absolute = 0) -> position: ...
    @overload
    def __new__(cls, relative: float = 0.0) -> position: ...
    @overload
    def __new__(cls, absolute: int | float, relative: float) -> position: ...
    @classmethod
    def from_any(cls, value: Position) -> position: ...
    def simplify(self) -> Position: ...
    def __eq__(self, other: object) -> bool: ...
    def __add__(self, value: position) -> position: ...
    __radd__ = __add__
    def __sub__(self, value: position) -> position: ...
    def __rsub__(self, value: position) -> position: ...
    def __mul__(self, value: int | float) -> position: ...
    __rmul__ = __mul__
    def __truediv__(self, value: int | float) -> position: ...
    def __rtruediv__(self, value: int | float) -> position: ...
    def __pos__(self) -> position: ...
    def __neg__(self) -> position: ...
    def __hash__(self) -> int: ...
