from _typeshed import Incomplete as Incomplete
from collections.abc import Generator

image: Incomplete
predicted: Incomplete
predicting: bool
screens: Incomplete
tlids = list[str | None]

def displayable(d): ...
def screen(_screen_name, *args, **kwargs) -> None: ...
def reset() -> None: ...
def prediction_coroutine(root_widget) -> Generator[Incomplete, None, Incomplete]: ...
