import io
import renpy

window: renpy.pygame.display.Window | None
progress_bar: ProgressBar | None
start_time: float

class ProgressBar:
    foreground: renpy.pygame.surface.Surface
    background: renpy.pygame.surface.Surface
    def __init__(self, foreground: str | io.IOBase, background: str | io.IOBase) -> None: ...
    def convert_alpha(self, surface: renpy.pygame.surface.Surface | None = None) -> None: ...
    def get_size(self) -> tuple[int, int]: ...
    def get_at(self, pos: tuple[int, int]) -> renpy.color.Color: ...
    def draw(self, target: renpy.pygame.surface.Surface, done: int) -> None: ...

def find_file(base_name: str, root: str) -> str | None: ...
def start(basedir: str, gamedir: str) -> None: ...

last_pump_time: int
pump_count: int
pump_clock: int
pump_total: int

def pump_window() -> None: ...

done: bool

def end() -> None: ...
def sleep() -> None: ...

progress_kind: str | None

def progress(kind: str, done: int, total: int) -> None: ...
