from _typeshed import Incomplete as Incomplete
from renpy.pygame.surface import Surface as Surface

def real(s): ...
def scale(n): ...
def real_bilinear(src, size): ...
def real_transform_scale(surf, size): ...
def image_load_unscaled(f, hint, convert: bool = True): ...
def image_save_unscaled(surf, filename) -> None: ...
def surface_scale(full): ...

real_renpy_pixellate: Incomplete
real_renpy_transform: Incomplete

def real_smoothscale(src: Surface, size: tuple[float, float], dest: Incomplete = None) -> Surface: ...

smoothscale = real_smoothscale
