from collections.abc import Callable
from io import IOBase
from typing import Any

from renpy.pygame.surface import Surface as Surface
from renpy.types import Unused as Unused

def real(s: Surface) -> Surface: ...
def scale(n: int | float) -> int | float: ...
def real_bilinear(src: Surface, size: tuple[int, int]) -> Surface: ...
def real_transform_scale(surf: Surface, size: tuple[int, int]) -> Surface: ...
def image_load_unscaled(f: str | IOBase, hint: str, convert: bool = True) -> Surface: ...
def image_save_unscaled(surf: Surface, filename: str) -> None: ...
def surface_scale(full: Surface) -> Surface: ...

real_renpy_pixellate: Callable[..., Any]
real_renpy_transform: Callable[..., Any]

def real_smoothscale(src: Surface, size: tuple[float, float], dest: Surface | None = None) -> Surface: ...

smoothscale = real_smoothscale
