from _typeshed import Incomplete as Incomplete
from io import IOBase
from renpy.pygame.surface import Surface as Surface
from renpy.types import Unused as Unused

def real(s: Unused) -> Unused: ...
def scale(n: Unused) -> Unused: ...
def real_bilinear(src: Unused, size: Unused) -> Unused: ...
def real_transform_scale(surf: Surface, size: tuple[int, int]) -> Surface: ...
def image_load_unscaled(f: str | IOBase, hint: str, convert: bool = True) -> Surface: ...
def image_save_unscaled(surf: Surface, filename: str) -> None: ...
def surface_scale(full: Surface) -> Surface: ...

real_renpy_pixellate: Incomplete
real_renpy_transform: Incomplete

def real_smoothscale(src: Surface, size: tuple[float, float], dest: Surface | None = None) -> Surface: ...

smoothscale = real_smoothscale
