import renpy
from _typeshed import Incomplete as Incomplete
from renpy.atl import RawStatement as RawStatement
from renpy.display.displayable import Displayable as Displayable
from renpy.display.dragdrop import DragGroup as DragGroup
from renpy.display.image import ShownImageInfo as ShownImageInfo
from renpy.display.layout import MultiBox as MultiBox
from renpy.display.motion import Transform as Transform
from renpy.object import Object as Object
from typing import Any, Callable, Generator

type AtType = Transform | Callable[[Displayable], Displayable]
type AtList = list[AtType]
ordered_layers: list[str]
layers: frozenset[str]
sticky_layers: frozenset[str]

def init_layers() -> None: ...

class SceneListEntry(renpy.object.Object):
    tag: str | None
    zorder: int
    show_time: float | None
    animation_time: float | None
    displayable: Displayable
    name: tuple[str, ...] | None
    def __init__(
        self,
        tag: str | None,
        zorder: int,
        show_time: float | None,
        animation_time: float | None,
        displayable: Displayable,
        name: tuple[str, ...] | None,
    ) -> None: ...
    def __iter__(self) -> Incomplete: ...
    def __getitem__(self, index: Incomplete) -> Incomplete: ...
    def copy(self) -> Incomplete: ...
    def update_time(self, time: float) -> SceneListEntry: ...

class SceneLists(renpy.object.Object):
    __version__: int
    camera_list: dict[str, tuple[float | None, AtList]]
    camera_transform: dict[str, Transform | None]
    config_layer_transform: dict[str, list[Transform] | None]
    def after_setstate(self) -> None: ...
    at_list: dict[str, dict[str, AtList]]
    layer_at_list: dict[str, tuple[float | None, AtList]]
    shown_window: bool
    additional_transient: list[tuple[str, str | None, str | None]]
    drag_group: renpy.display.dragdrop.DragGroup | None
    shown: ShownImageInfo
    layer_transform: dict[str, Transform | None]
    sticky_tags: dict[str, str]
    def after_upgrade(self, version: int) -> None: ...
    layers: dict[str, list[SceneListEntry]]
    focused: Displayable | None
    music: Incomplete
    def __init__(self, oldsl: SceneLists | None, shown: ShownImageInfo) -> None: ...
    def set_transient_prefix(self, layer: str, tag: str | None, prefix: str | None) -> None: ...
    def replace_transient(self, prefix: str | None = "hide") -> None: ...
    def transient_is_empty(self) -> bool: ...
    def transform_state(
        self, old_thing: Displayable | None, new_thing: Displayable, execution: bool = False
    ) -> Transform | Displayable: ...
    def find_index(
        self, layer: str, tag: str | Displayable | None, zorder: int | None, behind: list[str]
    ) -> tuple[int, int | None, int]: ...
    def add(
        self,
        layer: str,
        thing: Displayable,
        key: str | None = None,
        zorder: int | None = 0,
        behind: list[str] = [],
        at_list: AtList = [],
        name: tuple[str, ...] | None = None,
        atl: RawStatement | None = None,
        default_transform: Transform | None = None,
        transient: bool = False,
        keep_st: bool = False,
    ) -> Incomplete: ...
    def hide_or_replace(self, layer: str, index: int, prefix: str | None) -> bool: ...
    def get_all_displayables(self, current: bool = False) -> list[Displayable]: ...
    def get_all_layer_tag_displayable(self) -> Generator[tuple[str, str | None, Displayable], None, None]: ...
    def remove_above(self, layer: str, thing: str | Displayable) -> None: ...
    def remove(self, layer: str, thing: str | Displayable | None, prefix: str | None = "hide") -> None: ...
    def clear(self, layer: str, hide: bool = False) -> None: ...
    def set_layer_at_list(self, layer: str, at_list: AtList, reset: bool = True, camera: bool = False) -> None: ...
    def set_times(self, time: float) -> None: ...
    def showing(self, layer: str, name: tuple[str, ...]) -> bool | None: ...
    def get_showing_tags(self, layer: str) -> set[str]: ...
    def get_sorted_tags(self, layer: str) -> list[str]: ...
    def make_layer(self, layer: str, properties: dict[str, Any]) -> MultiBox: ...
    def transform_layer(
        self,
        layer: str,
        d: MultiBox,
        layer_at_list: tuple[float | None, AtList] | None = None,
        camera_list: tuple[float | None, AtList] | None = None,
    ) -> MultiBox: ...
    def remove_hide_replaced(self, layer: str, tag: str) -> None: ...
    def remove_hidden(self) -> None: ...
    def remove_all_hidden(self) -> None: ...
    def get_displayable_by_tag(self, layer: str, tag: str) -> Displayable | None: ...
    def get_displayable_by_name(self, layer: str, name: tuple[str, ...]) -> Displayable | None: ...
    def get_image_bounds(
        self, layer: str, tag: str, width: float, height: float
    ) -> tuple[float, float, float, float] | None: ...
    def get_zorder_list(self, layer: str) -> list[tuple[str, int]]: ...
    def change_zorder(self, layer: str, tag: str, zorder: int) -> None: ...

class _HasTransforms:
    at_list: bool
    camera: bool
    config_layer_transforms: bool

def layer_has_transforms(layer: str) -> _HasTransforms: ...
def scene_lists(index: int = -1) -> SceneLists: ...
