import renpy
from _typeshed import Incomplete as Incomplete
from renpy.display.displayable import Displayable as Displayable
from renpy.object import Object as Object
from typing import Generator

ordered_layers: Incomplete
layers: Incomplete
sticky_layers: Incomplete

def init_layers() -> None: ...

class SceneListEntry(renpy.object.Object):
    tag: Incomplete
    zorder: Incomplete
    show_time: Incomplete
    animation_time: Incomplete
    displayable: Incomplete
    name: Incomplete
    def __init__(self, tag, zorder, show_time, animation_time, displayable, name) -> None: ...
    def __iter__(self): ...
    def __getitem__(self, index): ...
    def copy(self): ...
    def update_time(self, time): ...

class SceneLists(renpy.object.Object):
    __version__: int
    camera_list: Incomplete
    camera_transform: Incomplete
    config_layer_transform: Incomplete
    def after_setstate(self) -> None: ...
    at_list: Incomplete
    layer_at_list: Incomplete
    shown_window: bool
    additional_transient: Incomplete
    drag_group: Incomplete
    shown: Incomplete
    layer_transform: Incomplete
    sticky_tags: Incomplete
    def after_upgrade(self, version) -> None: ...
    layers: Incomplete
    focused: Incomplete
    music: Incomplete
    def __init__(self, oldsl, shown) -> None: ...
    def set_transient_prefix(self, layer, tag, prefix) -> None: ...
    def replace_transient(self, prefix: str | None = "hide") -> None: ...
    def transient_is_empty(self): ...
    def transform_state(self, old_thing, new_thing, execution: bool = False): ...
    def find_index(self, layer, tag, zorder, behind): ...
    def add(
        self,
        layer,
        thing,
        key=None,
        zorder: int = 0,
        behind=[],
        at_list=[],
        name=None,
        atl=None,
        default_transform=None,
        transient: bool = False,
        keep_st: bool = False,
    ) -> None: ...
    def hide_or_replace(self, layer, index, prefix): ...
    def get_all_displayables(self, current: bool = False): ...
    def get_all_layer_tag_displayable(
        self,
    ) -> Generator[tuple[str, str | None, renpy.display.displayable.Displayable], None, None]: ...
    def remove_above(self, layer, thing) -> None: ...
    def remove(self, layer: str, thing: str | tuple | Displayable, prefix: str | None = "hide") -> None: ...
    def clear(self, layer, hide: bool = False) -> None: ...
    def set_layer_at_list(self, layer, at_list, reset: bool = True, camera: bool = False) -> None: ...
    def set_times(self, time) -> None: ...
    def showing(self, layer, name): ...
    def get_showing_tags(self, layer): ...
    def get_sorted_tags(self, layer): ...
    def make_layer(self, layer, properties): ...
    def transform_layer(self, layer, d, layer_at_list=None, camera_list=None): ...
    def remove_hide_replaced(self, layer, tag) -> None: ...
    def remove_hidden(self) -> None: ...
    def remove_all_hidden(self) -> None: ...
    def get_displayable_by_tag(self, layer, tag): ...
    def get_displayable_by_name(self, layer, name): ...
    def get_image_bounds(self, layer, tag, width, height): ...
    def get_zorder_list(self, layer): ...
    def change_zorder(self, layer, tag, zorder): ...

class _HasTransforms:
    at_list: bool
    camera: bool
    config_layer_transforms: bool

def layer_has_transforms(layer): ...
def scene_lists(index: int = -1): ...
