import renpy.pygame as pygame
from _typeshed import Incomplete as Incomplete
from pydot import Any as Any
from renpy.color import ColorLike as ColorLike
from renpy.display.matrix import Matrix as Matrix, Matrix2D as Matrix2D
from renpy.display.render import (
    BLIT as BLIT,
    DISSOLVE as DISSOLVE,
    FLATTEN as FLATTEN,
    IDENTITY as IDENTITY,
    IMAGEDISSOLVE as IMAGEDISSOLVE,
    PIXELLATE as PIXELLATE,
    Render as Render,
    blit_lock as blit_lock,
)
from renpy.pygame.surface import Surface as PygameSurface
from renpy.types import Unused as Unused
from typing import Sequence

type AreaType = tuple[float, float, float, float]
type ForcedType = tuple[float, float, float, float, AreaType]

class Clipper:
    blits: list[tuple[float, float, float, float, AreaType, PygameSurface, Incomplete]]
    old_blits: list[tuple[float, float, float, float, AreaType, PygameSurface, Incomplete]]
    forced: set[ForcedType]
    old_forced: set[ForcedType]
    mutated: set[int]
    def __init__(self) -> None: ...
    def compute(self, full_redraw: bool) -> tuple[AreaType | None, Sequence[AreaType]]: ...

clippers: list[Clipper]

def surface(w: int, h: int, alpha: bool) -> PygameSurface: ...
def copy_surface(surf) -> PygameSurface: ...
def draw_special(what: Render, dest: PygameSurface, x: int, y: int) -> None: ...
def draw(
    dest: PygameSurface | Clipper,
    clip: AreaType | None,
    what: Render | PygameSurface,
    xo: float,
    yo: float,
    screen: bool,
) -> None: ...
def draw_transformed(
    dest,
    clip: AreaType | None,
    what: Render | PygameSurface,
    xo: float,
    yo: float,
    alpha: float,
    forward: Matrix | None,
    reverse: Matrix | None,
) -> None: ...
def do_draw_screen(screen_render, full_redraw, swdraw): ...

class SWDraw:
    display_info: pygame.display.Info | None
    def __init__(self) -> None: ...
    suppressed_blit: bool
    next_frame: int
    info: dict[str, Any]
    scale_factor: float
    screen: PygameSurface | None
    window: PygameSurface | None
    def reset(self) -> None: ...
    def get_texture_size(self) -> tuple[int, int]: ...
    draw_per_virt: float
    virt_to_draw: Matrix2D
    draw_to_virt: Matrix2D
    full_redraw: bool
    fullscreen_surface: Unused
    def init(self, virtual_size: tuple[int, int]) -> bool: ...
    def update(self, force: bool = True) -> None: ...
    def resize(self) -> None: ...
    def quit(self) -> None: ...
    def translate_point(self, x: float, y: float) -> tuple[float, float]: ...
    def untranslate_point(self, x: float, y: float) -> tuple[float, float]: ...
    def mouse_event(self, ev: pygame.event.EventType) -> tuple[float, float]: ...
    def get_mouse_pos(self) -> tuple[float, float]: ...
    def set_mouse_pos(self, x: float, y: float) -> None: ...
    def screenshot(self, surftree: Render) -> PygameSurface: ...
    def can_block(self) -> bool: ...
    def should_redraw(self, needs_redraw: bool, first_pass: bool, can_block: bool) -> bool: ...
    def draw_screen(self, surftree: Render) -> None: ...
    def render_to_texture(self, render: Render, alpha: bool) -> PygameSurface: ...
    def is_pixel_opaque(self, what: Render) -> bool: ...
    def mutated_surface(self, surf: PygameSurface) -> None: ...
    def load_texture(
        self, surf: PygameSurface, transient: bool = False, properties: dict[str, Any] = {}
    ) -> PygameSurface: ...
    def ready_one_texture(self) -> bool: ...
    def solid_texture(self, w: int, h: int, color: ColorLike) -> PygameSurface: ...
    def kill_textures(self) -> None: ...
    def event_peek_sleep(self) -> None: ...
    def get_physical_size(self) -> tuple[int, int]: ...
