from _typeshed import Incomplete
import renpy
from renpy.atl import (
    DualAngle as DualAngle,
    any_object as any_object,
    bool_or_none as bool_or_none,
    float_or_none as float_or_none,
    matrix as matrix,
    mesh as mesh,
    position_or_none as position_or_none,
)
from renpy.display.accelerator import RenderTransform as RenderTransform
from renpy.display.displayable import Displayable as Displayable
from renpy.display.layout import Container as Container
from renpy.display.position import absolute as absolute, position as position
from typing import Any

class Camera(renpy.object.Object):
    layer: Incomplete
    def __init__(self, layer: str = "master") -> None: ...

null: Incomplete

def get_null(): ...
def first_not_none(*args): ...
def limit_angle(n): ...

class TextureUniform:
    name: Incomplete
    def __init__(self, name) -> None: ...
    def __get__(self, instance, owner): ...
    def __set__(self, instance, value) -> None: ...

class TransformState(renpy.object.Object):
    last_angle: float
    last_relative_anchorangle: float
    last_absolute_anchorangle: float
    last_events: bool
    available_width: int
    available_height: int
    radius_type = absolute
    radius_sign: int
    relative_anchor_radius_sign: int
    absolute_anchor_radius_sign: int
    texture_uniforms: Incomplete
    inherited_xpos: Incomplete
    inherited_ypos: Incomplete
    inherited_xanchor: Incomplete
    inherited_yanchor: Incomplete
    def __init__(self) -> None: ...
    xpos: Incomplete
    ypos: Incomplete
    xanchor: Incomplete
    yanchor: Incomplete
    xoffset: Incomplete
    yoffset: Incomplete
    subpixel: Incomplete
    def take_state(self, ts) -> None: ...
    def diff(self, newts): ...
    def get(self, prop): ...
    def get_placement(self, cxoffset: int = 0, cyoffset: int = 0): ...
    def get_xalign(self): ...
    def set_xalign(self, v) -> None: ...
    xalign: Incomplete
    def get_yalign(self): ...
    def set_yalign(self, v) -> None: ...
    yalign: Incomplete
    @staticmethod
    def scale(value, available): ...
    def get_around(self): ...
    def set_around(self, value) -> None: ...
    def set_alignaround(self, value) -> None: ...
    around: Incomplete
    alignaround: Incomplete
    def get_anchoraround(self): ...
    def set_anchoraround(self, value) -> None: ...
    anchoraround: Incomplete
    def get_pos_polar_vector(self): ...
    def get_angle(self, vector=None): ...
    def get_radius(self, vector=None): ...
    def set_angle(self, angle) -> None: ...
    def set_radius(self, radius) -> None: ...
    def set_pos_from_angle_and_radius(self, angle, radius) -> None: ...
    angle: Incomplete
    radius: Incomplete
    def get_anchor_polar_vector(self): ...
    def get_anchorangle(self, polar_vectors=None): ...
    def get_anchorradius(self, polar_vectors=None): ...
    def set_anchorangle(self, angle) -> None: ...
    def set_anchorradius(self, anchorradius) -> None: ...
    def set_anchor_from_anchorangle_and_anchorradius(
        self, absolute_anchorangle, relative_anchorangle, absolute_anchorradius, relative_anchorradius
    ) -> None: ...
    anchorangle: Incomplete
    anchorradius: Incomplete
    def get_pos(self): ...
    def set_pos(self, value) -> None: ...
    pos: Incomplete
    def get_anchor(self): ...
    def set_anchor(self, value) -> None: ...
    anchor: Incomplete
    def set_align(self, value) -> None: ...
    align: Incomplete
    def get_offset(self): ...
    def set_offset(self, value) -> None: ...
    offset: Incomplete
    def get_xysize(self): ...
    def set_xysize(self, value) -> None: ...
    xysize: Incomplete
    def set_size(self, value) -> None: ...
    size: Incomplete
    def set_xcenter(self, value) -> None: ...
    def get_xpos(self): ...
    def set_ycenter(self, value) -> None: ...
    def get_ypos(self): ...
    xcenter: Incomplete
    ycenter: Incomplete
    def set_xycenter(self, value) -> None: ...
    xycenter: Incomplete
    def get_reset(self): ...
    def set_reset(self, value) -> None: ...

RESET_STATE: Incomplete

def simplify_position(v): ...

class Proxy:
    name: Incomplete
    def __init__(self, name) -> None: ...
    def __get__(self, instance, owner): ...
    def __set__(self, instance, value): ...

class Transform(Container):
    __version__: int
    transform_event_responder: bool
    active: bool
    state: Incomplete
    hide_request: bool
    hide_response: bool
    st: int
    at: int
    st_offset: int
    at_offset: int
    child_st_base: int
    style_arg: str
    replaced_request: bool
    replaced_response: bool
    def after_upgrade(self, version) -> None: ...
    DEFAULT_ARGUMENTS: Incomplete
    children: Incomplete
    arguments = DEFAULT_ARGUMENTS
    child_size: Incomplete
    original_child: Incomplete
    kwargs: Incomplete
    function: Incomplete
    forward: renpy.display.matrix.Matrix | None
    reverse: renpy.display.matrix.Matrix | None
    render_size: Incomplete
    def __init__(
        self,
        child=None,
        function=None,
        style: str = "default",
        focus=None,
        default: bool = False,
        _args=None,
        *,
        reset: bool = False,
        **kwargs,
    ) -> None: ...
    def visit(self): ...
    def default_function(self, state, st, at) -> None: ...
    last_child_transform_event: Incomplete
    def set_transform_event(self, event) -> None: ...
    def take_state(self, t) -> None: ...
    def take_execution_state(self, t) -> None: ...
    def copy(self): ...
    def adjust_for_fps(self, st, at): ...
    child: Incomplete
    def set_child(self, child, duplicate: bool = True) -> None: ...
    def update_state(self) -> None: ...
    def render(self, width, height, st, at): ...
    def event(self, ev, x, y, st): ...
    def __call__(self, child=None, take_state: bool = True, _args=None): ...
    def get_placement(self): ...
    def update(self) -> None: ...

class ATLTransform(renpy.atl.ATLTransformBase, Transform):
    raw_child: Incomplete
    def __init__(self, atl, child=None, context={}, parameters=None, **properties) -> None: ...
    hide_response: bool
    replaced_response: bool
    active: bool
    def update_state(self) -> None: ...

style_properties: Incomplete
all_properties: Incomplete
diff2_properties: Incomplete
diff4_properties: Incomplete
uniforms: Incomplete
gl_properties: Incomplete

def add_property(name: str, atl: Any = ..., default: Any = None, diff: int | None = 2) -> None: ...
def add_uniform(name, uniform_type) -> None: ...
def add_gl_property(name) -> None: ...

ALIASES: Incomplete
