import renpy
import renpy.atl
from _typeshed import Incomplete as Incomplete
from renpy.atl import (
    DualAngle as DualAngle,
    any_object as any_object,
    bool_or_none as bool_or_none,
    float_or_none as float_or_none,
    matrix as matrix,
    mesh as mesh,
    position_or_none as position_or_none,
)
from renpy.display.accelerator import RenderTransform as RenderTransform
from renpy.display.displayable import (
    Displayable as Displayable,
    DisplayableArguments as DisplayableArguments,
    Placement as Placement,
)
from renpy.display.layout import Container as Container
from renpy.display.matrix import Matrix as Matrix
from renpy.display.position import absolute as absolute, position as position
from renpy.object import Object as Object
from renpy.types import DisplayableLike as DisplayableLike, Position as Position
from typing import Any, Callable, Literal, TypeVar, overload

T = TypeVar("T")

class Camera(renpy.object.Object):
    layer: str
    def __init__(self, layer: str = "master") -> None: ...

null: renpy.display.layout.Null | None

def get_null() -> renpy.display.layout.Null: ...
def first_not_none(*args: Any | None) -> Any | None: ...
def limit_angle(n: float) -> float: ...

class TextureUniform:
    name: str
    def __init__(self, name: str) -> None: ...
    def __get__(self, instance: Incomplete, owner: Incomplete) -> Incomplete: ...
    def __set__(self, instance: Incomplete, value: Any) -> None: ...

class TransformState(renpy.object.Object):
    last_angle: float | None
    last_relative_anchorangle: float
    last_absolute_anchorangle: float
    last_events: bool
    available_width: int
    available_height: int
    radius_type = absolute
    radius_sign: int
    relative_anchor_radius_sign: int
    absolute_anchor_radius_sign: int
    texture_uniforms: Incomplete
    inherited_xpos: Incomplete
    inherited_ypos: Incomplete
    inherited_xanchor: Incomplete
    inherited_yanchor: Incomplete
    def __init__(self) -> None: ...
    xpos: Incomplete
    ypos: Incomplete
    xanchor: Incomplete
    yanchor: Incomplete
    xoffset: Incomplete
    yoffset: Incomplete
    subpixel: Incomplete
    def take_state(self, ts: TransformState) -> None: ...
    def diff(self, newts: TransformState) -> dict[str, tuple[Any, Any]]: ...
    def get(self, prop: str) -> Any | None: ...
    def get_placement(self, cxoffset: float = 0, cyoffset: float = 0) -> Placement: ...
    def get_xalign(self) -> Position | None: ...
    def set_xalign(self, v: Position | None) -> None: ...
    xalign: Incomplete
    def get_yalign(self) -> Position | None: ...
    def set_yalign(self, v: Position | None) -> None: ...
    yalign: Incomplete
    @staticmethod
    def scale(value: Position, available: float) -> float: ...
    def get_around(self) -> tuple[float, float]: ...
    def set_around(self, value: tuple[float, float]) -> None: ...
    def set_alignaround(self, value: tuple[float, float]) -> None: ...
    around: Incomplete
    alignaround: Incomplete
    def get_anchoraround(self) -> tuple[float, float]: ...
    def set_anchoraround(self, value: tuple[float, float]) -> None: ...
    anchoraround: Incomplete
    def get_pos_polar_vector(self) -> tuple[float, float]: ...
    def get_angle(self, vector: tuple[float, float] | None = None) -> float: ...
    def get_radius(self, vector: tuple[float, float] | None = None) -> float: ...
    def set_angle(self, angle: float) -> None: ...
    def set_radius(self, radius: float) -> None: ...
    def set_pos_from_angle_and_radius(self, angle: float, radius: float) -> None: ...
    angle: Incomplete
    radius: Incomplete
    def get_anchor_polar_vector(self) -> tuple[tuple[absolute, absolute], tuple[float, float]]: ...
    def get_anchorangle(
        self, polar_vectors: tuple[tuple[absolute, absolute], tuple[float, float]] | None = None
    ) -> DualAngle: ...
    def get_anchorradius(
        self, polar_vectors: tuple[tuple[absolute, absolute], tuple[float, float]] | None = None
    ) -> position: ...
    def set_anchorangle(self, angle: DualAngle | float) -> None: ...
    def set_anchorradius(self, anchorradius: Position) -> None: ...
    def set_anchor_from_anchorangle_and_anchorradius(
        self,
        absolute_anchorangle: absolute,
        relative_anchorangle: float,
        absolute_anchorradius: absolute,
        relative_anchorradius: float,
    ) -> None: ...
    anchorangle: Incomplete
    anchorradius: Incomplete
    def get_pos(self) -> tuple[Position | None, Position | None]: ...
    def set_pos(self, value: tuple[Position | None, Position | None]) -> None: ...
    pos: Incomplete
    def get_anchor(self) -> tuple[Position | None, Position | None]: ...
    def set_anchor(self, value: tuple[Position | None, Position | None]) -> None: ...
    anchor: Incomplete
    def set_align(self, value: tuple[Position | None, Position | None]) -> None: ...
    align: Incomplete
    def get_offset(self) -> tuple[float, float]: ...
    def set_offset(self, value: tuple[float, float]) -> None: ...
    offset: Incomplete
    def get_xysize(self) -> tuple[Position | None, Position | None]: ...
    def set_xysize(self, value: tuple[Position | None, Position | None] | None) -> None: ...
    xysize: Incomplete
    def set_size(self, value: tuple[Position | None, Position | None] | None) -> None: ...
    size: Incomplete
    def set_xcenter(self, value: Position | None) -> None: ...
    def get_xpos(self) -> Position | None: ...
    def set_ycenter(self, value: Position | None) -> None: ...
    def get_ypos(self) -> Position | None: ...
    xcenter: Incomplete
    ycenter: Incomplete
    def set_xycenter(self, value: tuple[Position | None, Position | None] | None) -> None: ...
    xycenter: Incomplete
    def get_reset(self) -> bool: ...
    def set_reset(self, value: bool) -> None: ...
    _reset: Incomplete

RESET_STATE: TransformState

@overload
def simplify_position(v: Position) -> Position: ...
@overload
def simplify_position(v: tuple[Position, ...]) -> tuple[Position, ...]: ...

class Proxy:
    name: str
    def __init__(self, name: str) -> None: ...
    def __get__(self, instance, owner): ...
    def __set__(self, instance, value): ...

class Transform(Container):
    __version__: int
    transform_event_responder: bool
    active: bool
    state: TransformState
    hide_request: bool
    hide_response: bool
    st: int
    at: int
    st_offset: int
    at_offset: int
    child_st_base: int
    style_arg: str
    replaced_request: bool
    replaced_response: bool
    def after_upgrade(self, version: int) -> None: ...
    DEFAULT_ARGUMENTS: dict[str, dict[str, Any]]
    children: list[Displayable]
    arguments = DEFAULT_ARGUMENTS
    child_size: tuple[int, int]
    original_child: Displayable | None
    kwargs: dict[str, Any]
    function: Callable[[Transform, float, float], float | None] | None
    forward: renpy.display.matrix.Matrix | None
    reverse: renpy.display.matrix.Matrix | None
    render_size: tuple[float, float]
    def __init__(
        self,
        child: DisplayableLike | None = None,
        function: Callable[[Transform, float, float], float | None] | None = None,
        style: str = "default",
        focus: str | None = None,
        default: bool = False,
        _args: DisplayableArguments | None = None,
        *,
        reset: bool = False,
        **kwargs,
    ) -> None: ...
    def visit(self) -> list[Displayable]: ...
    def default_function(self, state: Transform, st: float, at: float) -> None: ...
    last_child_transform_event: str
    def set_transform_event(self, event: str) -> None: ...
    def take_state(self, t: Transform) -> None: ...
    def take_execution_state(self, t: Transform) -> None: ...
    def copy(self) -> Transform: ...
    def _change_transform_child(self, child: Transform | Displayable | None) -> Transform: ...
    def _handles_event(self, event: str) -> bool: ...
    def adjust_for_fps(self, st: float, at: float) -> tuple[float, float]: ...
    def _hide(self, st: float, at: float, kind: Literal["hide", "replace", "cancel"]) -> Displayable | None: ...
    child: Displayable | None
    def set_child(self, child: DisplayableLike, duplicate: bool = True) -> None: ...
    def update_state(self) -> None: ...
    def render(self, width: float, height: float, st: float, at: float) -> renpy.display.render.Render: ...
    def event(self, ev: renpy.pygame.event.Event, x: float, y: float, st: float) -> Any | None: ...
    def __call__(
        self, child: DisplayableLike | None = None, take_state: bool = True, _args: DisplayableArguments | None = None
    ) -> Transform: ...
    _duplicatable: bool
    def _unique(self) -> None: ...
    def get_placement(self) -> Placement: ...
    def update(self) -> None: ...
    def _duplicate(self, args: DisplayableArguments | None) -> Transform: ...
    def _in_current_store(self) -> Transform: ...
    def _repr_info(self) -> str: ...

class ATLTransform(renpy.atl.ATLTransformBase, Transform):
    raw_child: Displayable | None
    def __init__(
        self, atl: renpy.atl.RawBlock, child: Displayable | None = None, context={}, parameters=None, **properties
    ) -> None: ...
    hide_response: bool
    replaced_response: bool
    active: bool
    def update_state(self) -> None: ...
    def _repr_info(self) -> str: ...

style_properties: set[str]
all_properties: set[str]
diff2_properties: set[str]
diff4_properties: set[str]
uniforms: set[str]
gl_properties: set[str]

def add_property(name: str, atl: Any = ..., default: Any = None, diff: int | None = 2) -> None: ...
def add_uniform(name: str, uniform_type: str) -> None: ...
def add_gl_property(name: str) -> None: ...

ALIASES: dict[str, Any]
