import re
import subprocess
from _typeshed import Incomplete as Incomplete
from renpy.display.displayable import Displayable as Displayable

class TTSDone(str): ...
class TTSRoot(Exception): ...

root: Displayable | None
last: str
last_raw: str
process: subprocess.Popen | None

def periodic() -> None: ...
def is_active() -> bool: ...

class AndroidTTS:
    TextToSpeech: Incomplete
    tts: Incomplete
    def __init__(self) -> None: ...
    def speak(self, s: str) -> None: ...
    def stop(self) -> None: ...

class AppleTTS:
    objc_str: Incomplete
    AVSpeechUtterance: Incomplete
    synth: Incomplete
    def __init__(self) -> None: ...
    def speak(self, s: str) -> None: ...
    def stop(self) -> None: ...

platform_tts: AndroidTTS | AppleTTS | None

def default_tts_function(s: str) -> None: ...
def stop_tts() -> None: ...

tts_substitutions: list[tuple[re.Pattern, str]]

def init() -> None: ...
def apply_substitutions(s: str) -> str: ...

tts_queue: list[str]
last_spoken: str

def tick() -> None: ...
def tts(s: str) -> None: ...
def speak(s: str, translate: bool = True, force: bool = False) -> None: ...
def speak_extra_alt() -> None: ...
def set_root(d: Displayable | None) -> None: ...

old_self_voicing: bool
notify_text: str | None
last_group_alt: str | None

def displayable(d: Displayable | None) -> None: ...
