import re
import subprocess
from typing import Any

from _typeshed import Incomplete as Incomplete
from renpy.display.displayable import Displayable as Displayable

class TTSDone(str): ...
class TTSRoot(Exception): ...

root: Displayable | None
last: str
last_raw: str
process: subprocess.Popen[bytes] | None

def periodic() -> None: ...
def is_active() -> bool: ...

class AndroidTTS:
    TextToSpeech: Incomplete
    tts: Incomplete
    def __init__(self) -> None: ...
    def speak(self, s: str) -> None: ...
    def stop(self) -> None: ...

class AppleTTS:
    objc_str: Incomplete
    AVSpeechUtterance: Incomplete
    synth: Incomplete
    voices: dict[str, str]
    def __init__(self) -> None: ...
    def speak(self, s: str) -> None: ...
    def stop(self) -> None: ...

platform_tts: AndroidTTS | AppleTTS | LinuxTTS | WindowsTTS | WebTTS | None

def default_tts_function(s: str) -> None: ...
def stop_tts() -> None: ...

tts_substitutions: list[tuple[re.Pattern, str]]

def init() -> None: ...
def apply_substitutions(s: str) -> str: ...

tts_queue: list[str]
last_spoken: str

def tick() -> None: ...
def tts(s: str) -> None: ...
def speak(s: str, translate: bool = True, force: bool = False) -> None: ...
def speak_extra_alt() -> None: ...
def set_root(d: Displayable | None) -> None: ...

old_self_voicing: bool
notify_text: str | None
last_group_alt: str | None

def displayable(d: Displayable | None) -> None: ...

class LinuxTTS:
    process: subprocess.Popen | None
    def __init__(self) -> None: ...
    def is_speaking(self) -> bool: ...
    def speak(self, s) -> None: ...
    def stop(self) -> None: ...
    def get_tts_voices(self) -> list[str]: ...

class WindowsTTS:
    process: subprocess.Popen | None
    def __init__(self) -> None: ...
    def is_speaking(self) -> bool: ...
    def speak(self, s) -> None: ...
    def stop(self) -> None: ...
    def get_tts_voices(self) -> list[str]: ...

class WebTTS:
    def is_speaking(self) -> bool: ...
    def speak(self, s) -> None: ...
    def stop(self) -> None: ...
    def get_tts_voices(self) -> list[str]: ...

_tts_voices_cache: list[str] | None

def get_tts_voices() -> list[str]: ...

VOICE_RE: re.Pattern[str]

def get_voice(text: str = "") -> tuple[str | None, str]: ...
