from _typeshed import Incomplete as Incomplete

def none_is_null(o: Incomplete) -> Incomplete: ...
def none_is_0(o: Incomplete) -> Incomplete: ...
def expand_focus_mask(v: Incomplete) -> Incomplete: ...
def expand_outlines(l: Incomplete) -> Incomplete: ...

ANCHORS: Incomplete

def expand_anchor(v: Incomplete) -> Incomplete: ...
