from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

def expand_anchor(v: Incomplete) -> None: ...
def expand_focus_mask(v: Incomplete) -> None: ...
def expand_outlines(l: Incomplete) -> None: ...
def none_is_0(o: Incomplete) -> None: ...
def none_is_null(o: Incomplete) -> None: ...
