from _frozen_importlib import BuiltinImporter as BuiltinImporter

def expand_anchor(v) -> None: ...
def expand_focus_mask(v) -> None: ...
def expand_outlines(l) -> None: ...
def none_is_0(o) -> None: ...
def none_is_null(o) -> None: ...
