from _frozen_importlib import BuiltinImporter as BuiltinImporter
from collections.abc import Callable

import renpy
from _typeshed import Incomplete as Incomplete
from renpy.display.matrix import Matrix as Matrix
from renpy.display.position import absolute as absolute
from renpy.types import Position as Position

class Style(renpy.style.StyleCore):
    additive: float
    alpha: float
    blend: Incomplete | None
    blur: float | None
    corner1: tuple[Position | None, Position | None] | None
    corner2: tuple[Position | None, Position | None] | None
    crop: tuple[Position | None, Position | None, Position | None, Position | None] | None
    crop_relative: bool | None
    debug: Incomplete | None
    delay: float
    events: bool
    fit: str | None
    fps: float | None
    matrixanchor: tuple[Position | None, Position | None] | None
    matrixcolor: Matrix | Callable | None
    matrixtransform: Matrix | Callable | None
    maxsize: tuple[int, int] | None
    mesh: renpy.gl2.gl2mesh2.Mesh2 | renpy.gl2.gl2mesh3.Mesh3 | tuple | bool
    mesh_pad: Incomplete | None
    nearest: bool | None
    perspective: Incomplete | None
    rotate: float | None
    rotate_pad: bool
    point_to: Incomplete | None
    orientation: tuple[float, float, float] | None
    xrotate: float | None
    yrotate: float | None
    zrotate: float | None
    shader: Incomplete | None
    show_cancels_hide: bool
    subpixel: bool
    transform_anchor: bool
    zoom: float

    xanchoraround: Position | None
    xanchor: Position | None
    xaround: Position | None
    xoffset: absolute
    xpan: float | None
    xpos: Position | None
    xsize: Position | None
    xtile: int
    xzoom: float

    yanchoraround: Position | None
    yanchor: Position | None
    yaround: Position | None
    yoffset: absolute
    ypan: float | None
    ypos: Position | None
    ysize: Position | None
    ytile: int
    yzoom: float

    zpos: float
    zzoom: bool

# activate_activate_sound
# activate_adjust_spacing
# activate_aft_bar
# activate_aft_gutter
# activate_align
# activate_alt
# activate_altruby_style
# activate_anchor
# activate_antialias
# activate_area
# activate_axis
# activate_background
# activate_bar_invert
# activate_bar_resizing
# activate_bar_vertical
# activate_base_bar
# activate_black_color
# activate_bold
# activate_bottom_bar
# activate_bottom_gutter
# activate_bottom_margin
# activate_bottom_padding
# activate_box_align
# activate_box_first_spacing
# activate_box_justify
# activate_box_layout
# activate_box_reverse
# activate_box_spacing
# activate_box_wrap
# activate_box_wrap_spacing
# activate_caret
# activate_child
# activate_clipping
# activate_color
# activate_debug
# activate_drop_shadow
# activate_drop_shadow_color
# activate_emoji_font
# activate_enable_hover
# activate_extra_alt
# activate_first_indent
# activate_first_spacing
# activate_fit_first
# activate_focus_mask
# activate_focus_rect
# activate_font
# activate_font_features
# activate_fore_bar
# activate_fore_gutter
# activate_foreground
# activate_group_alt
# activate_hinting
# activate_hover_sound
# activate_hyperlink_functions
# activate_instance
# activate_italic
# activate_justify
# activate_kerning
# activate_key_events
# activate_keyboard_focus
# activate_keyboard_focus_insets
# activate_language
# activate_layout
# activate_left_bar
# activate_left_gutter
# activate_left_margin
# activate_left_padding
# activate_line_leading
# activate_line_overlap_split
# activate_line_spacing
# activate_margin
# activate_maximum
# activate_min_width
# activate_minimum
# activate_minwidth
# activate_mipmap
# activate_modal
# activate_mouse
# activate_newline_indent
# activate_offset
# activate_order_reverse
# activate_outline_scaling
# activate_outlines
# activate_padding
# activate_pos
# activate_prefer_emoji
# activate_reading_order
# activate_rest_indent
# activate_right_bar
# activate_right_gutter
# activate_right_margin
# activate_right_padding
# activate_ruby_line_leading
# activate_ruby_style
# activate_shaper
# activate_size
# activate_size_group
# activate_slow_abortable
# activate_slow_cps
# activate_slow_cps_multiplier
# activate_slow_speed
# activate_sound
# activate_spacing
# activate_strikethrough
# activate_subpixel
# activate_subtitle_width
# activate_text_align
# activate_text_y_fudge
# activate_textalign
# activate_textshader
# activate_thumb
# activate_thumb_align
# activate_thumb_offset
# activate_thumb_shadow
# activate_time_policy
# activate_top_bar
# activate_top_gutter
# activate_top_margin
# activate_top_padding
# activate_underline
# activate_unscrollable
# activate_vertical
# activate_xalign
# activate_xanchor
# activate_xcenter
# activate_xfill
# activate_xfit
# activate_xmargin
# activate_xmaximum
# activate_xminimum
# activate_xoffset
# activate_xpadding
# activate_xpos
# activate_xsize
# activate_xspacing
# activate_xycenter
# activate_xysize
# activate_yalign
# activate_yanchor
# activate_ycenter
# activate_yfill
# activate_yfit
# activate_ymargin
# activate_ymaximum
# activate_yminimum
# activate_yoffset
# activate_ypadding
# activate_ypos
# activate_ysize
# activate_yspacing
# adjust_spacing
# aft_bar
# aft_gutter
# align
# alt
# altruby_style
# anchor
# antialias
# area
# axis
# background
# bar_invert
# bar_resizing
# bar_vertical
# base_bar
# black_color
# bold
# bottom_bar
# bottom_gutter
# bottom_margin
# bottom_padding
# box_align
# box_first_spacing
# box_justify
# box_layout
# box_reverse
# box_spacing
# box_wrap
# box_wrap_spacing
# caret
# child
# clipping
# color
# debug
# drop_shadow
# drop_shadow_color
# emoji_font
# enable_hover
# extra_alt
# first_indent
# first_spacing
# fit_first
# focus_mask
# focus_rect
# font
# font_features
# fore_bar
# fore_gutter
# foreground
# group_alt
# hinting
# hover_activate_sound
# hover_adjust_spacing
# hover_aft_bar
# hover_aft_gutter
# hover_align
# hover_alt
# hover_altruby_style
# hover_anchor
# hover_antialias
# hover_area
# hover_axis
# hover_background
# hover_bar_invert
# hover_bar_resizing
# hover_bar_vertical
# hover_base_bar
# hover_black_color
# hover_bold
# hover_bottom_bar
# hover_bottom_gutter
# hover_bottom_margin
# hover_bottom_padding
# hover_box_align
# hover_box_first_spacing
# hover_box_justify
# hover_box_layout
# hover_box_reverse
# hover_box_spacing
# hover_box_wrap
# hover_box_wrap_spacing
# hover_caret
# hover_child
# hover_clipping
# hover_color
# hover_debug
# hover_drop_shadow
# hover_drop_shadow_color
# hover_emoji_font
# hover_enable_hover
# hover_extra_alt
# hover_first_indent
# hover_first_spacing
# hover_fit_first
# hover_focus_mask
# hover_focus_rect
# hover_font
# hover_font_features
# hover_fore_bar
# hover_fore_gutter
# hover_foreground
# hover_group_alt
# hover_hinting
# hover_hover_sound
# hover_hyperlink_functions
# hover_instance
# hover_italic
# hover_justify
# hover_kerning
# hover_key_events
# hover_keyboard_focus
# hover_keyboard_focus_insets
# hover_language
# hover_layout
# hover_left_bar
# hover_left_gutter
# hover_left_margin
# hover_left_padding
# hover_line_leading
# hover_line_overlap_split
# hover_line_spacing
# hover_margin
# hover_maximum
# hover_min_width
# hover_minimum
# hover_minwidth
# hover_mipmap
# hover_modal
# hover_mouse
# hover_newline_indent
# hover_offset
# hover_order_reverse
# hover_outline_scaling
# hover_outlines
# hover_padding
# hover_pos
# hover_prefer_emoji
# hover_reading_order
# hover_rest_indent
# hover_right_bar
# hover_right_gutter
# hover_right_margin
# hover_right_padding
# hover_ruby_line_leading
# hover_ruby_style
# hover_shaper
# hover_size
# hover_size_group
# hover_slow_abortable
# hover_slow_cps
# hover_slow_cps_multiplier
# hover_slow_speed
# hover_sound
# hover_spacing
# hover_strikethrough
# hover_subpixel
# hover_subtitle_width
# hover_text_align
# hover_text_y_fudge
# hover_textalign
# hover_textshader
# hover_thumb
# hover_thumb_align
# hover_thumb_offset
# hover_thumb_shadow
# hover_time_policy
# hover_top_bar
# hover_top_gutter
# hover_top_margin
# hover_top_padding
# hover_underline
# hover_unscrollable
# hover_vertical
# hover_xalign
# hover_xanchor
# hover_xcenter
# hover_xfill
# hover_xfit
# hover_xmargin
# hover_xmaximum
# hover_xminimum
# hover_xoffset
# hover_xpadding
# hover_xpos
# hover_xsize
# hover_xspacing
# hover_xycenter
# hover_xysize
# hover_yalign
# hover_yanchor
# hover_ycenter
# hover_yfill
# hover_yfit
# hover_ymargin
# hover_ymaximum
# hover_yminimum
# hover_yoffset
# hover_ypadding
# hover_ypos
# hover_ysize
# hover_yspacing
# hyperlink_functions
# idle_activate_sound
# idle_adjust_spacing
# idle_aft_bar
# idle_aft_gutter
# idle_align
# idle_alt
# idle_altruby_style
# idle_anchor
# idle_antialias
# idle_area
# idle_axis
# idle_background
# idle_bar_invert
# idle_bar_resizing
# idle_bar_vertical
# idle_base_bar
# idle_black_color
# idle_bold
# idle_bottom_bar
# idle_bottom_gutter
# idle_bottom_margin
# idle_bottom_padding
# idle_box_align
# idle_box_first_spacing
# idle_box_justify
# idle_box_layout
# idle_box_reverse
# idle_box_spacing
# idle_box_wrap
# idle_box_wrap_spacing
# idle_caret
# idle_child
# idle_clipping
# idle_color
# idle_debug
# idle_drop_shadow
# idle_drop_shadow_color
# idle_emoji_font
# idle_enable_hover
# idle_extra_alt
# idle_first_indent
# idle_first_spacing
# idle_fit_first
# idle_focus_mask
# idle_focus_rect
# idle_font
# idle_font_features
# idle_fore_bar
# idle_fore_gutter
# idle_foreground
# idle_group_alt
# idle_hinting
# idle_hover_sound
# idle_hyperlink_functions
# idle_instance
# idle_italic
# idle_justify
# idle_kerning
# idle_key_events
# idle_keyboard_focus
# idle_keyboard_focus_insets
# idle_language
# idle_layout
# idle_left_bar
# idle_left_gutter
# idle_left_margin
# idle_left_padding
# idle_line_leading
# idle_line_overlap_split
# idle_line_spacing
# idle_margin
# idle_maximum
# idle_min_width
# idle_minimum
# idle_minwidth
# idle_mipmap
# idle_modal
# idle_mouse
# idle_newline_indent
# idle_offset
# idle_order_reverse
# idle_outline_scaling
# idle_outlines
# idle_padding
# idle_pos
# idle_prefer_emoji
# idle_reading_order
# idle_rest_indent
# idle_right_bar
# idle_right_gutter
# idle_right_margin
# idle_right_padding
# idle_ruby_line_leading
# idle_ruby_style
# idle_shaper
# idle_size
# idle_size_group
# idle_slow_abortable
# idle_slow_cps
# idle_slow_cps_multiplier
# idle_slow_speed
# idle_spacing
# idle_strikethrough
# idle_subpixel
# idle_subtitle_width
# idle_text_align
# idle_text_y_fudge
# idle_textalign
# idle_textshader
# idle_thumb
# idle_thumb_align
# idle_thumb_offset
# idle_thumb_shadow
# idle_time_policy
# idle_top_bar
# idle_top_gutter
# idle_top_margin
# idle_top_padding
# idle_underline
# idle_unscrollable
# idle_vertical
# idle_xalign
# idle_xanchor
# idle_xcenter
# idle_xfill
# idle_xfit
# idle_xmargin
# idle_xmaximum
# idle_xminimum
# idle_xoffset
# idle_xpadding
# idle_xpos
# idle_xsize
# idle_xspacing
# idle_xycenter
# idle_xysize
# idle_yalign
# idle_yanchor
# idle_ycenter
# idle_yfill
# idle_yfit
# idle_ymargin
# idle_ymaximum
# idle_yminimum
# idle_yoffset
# idle_ypadding
# idle_ypos
# idle_ysize
# idle_yspacing
# insensitive_activate_sound
# insensitive_adjust_spacing
# insensitive_aft_bar
# insensitive_aft_gutter
# insensitive_align
# insensitive_alt
# insensitive_altruby_style
# insensitive_anchor
# insensitive_antialias
# insensitive_area
# insensitive_axis
# insensitive_background
# insensitive_bar_invert
# insensitive_bar_resizing
# insensitive_bar_vertical
# insensitive_base_bar
# insensitive_black_color
# insensitive_bold
# insensitive_bottom_bar
# insensitive_bottom_gutter
# insensitive_bottom_margin
# insensitive_bottom_padding
# insensitive_box_align
# insensitive_box_first_spacing
# insensitive_box_justify
# insensitive_box_layout
# insensitive_box_reverse
# insensitive_box_spacing
# insensitive_box_wrap
# insensitive_box_wrap_spacing
# insensitive_caret
# insensitive_child
# insensitive_clipping
# insensitive_color
# insensitive_debug
# insensitive_drop_shadow
# insensitive_drop_shadow_color
# insensitive_emoji_font
# insensitive_enable_hover
# insensitive_extra_alt
# insensitive_first_indent
# insensitive_first_spacing
# insensitive_fit_first
# insensitive_focus_mask
# insensitive_focus_rect
# insensitive_font
# insensitive_font_features
# insensitive_fore_bar
# insensitive_fore_gutter
# insensitive_foreground
# insensitive_group_alt
# insensitive_hinting
# insensitive_hover_sound
# insensitive_hyperlink_functions
# insensitive_instance
# insensitive_italic
# insensitive_justify
# insensitive_kerning
# insensitive_key_events
# insensitive_keyboard_focus
# insensitive_keyboard_focus_insets
# insensitive_language
# insensitive_layout
# insensitive_left_bar
# insensitive_left_gutter
# insensitive_left_margin
# insensitive_left_padding
# insensitive_line_leading
# insensitive_line_overlap_split
# insensitive_line_spacing
# insensitive_margin
# insensitive_maximum
# insensitive_min_width
# insensitive_minimum
# insensitive_minwidth
# insensitive_mipmap
# insensitive_modal
# insensitive_mouse
# insensitive_newline_indent
# insensitive_offset
# insensitive_order_reverse
# insensitive_outline_scaling
# insensitive_outlines
# insensitive_padding
# insensitive_pos
# insensitive_prefer_emoji
# insensitive_reading_order
# insensitive_rest_indent
# insensitive_right_bar
# insensitive_right_gutter
# insensitive_right_margin
# insensitive_right_padding
# insensitive_ruby_line_leading
# insensitive_ruby_style
# insensitive_shaper
# insensitive_size
# insensitive_size_group
# insensitive_slow_abortable
# insensitive_slow_cps
# insensitive_slow_cps_multiplier
# insensitive_slow_speed
# insensitive_spacing
# insensitive_strikethrough
# insensitive_subpixel
# insensitive_subtitle_width
# insensitive_text_align
# insensitive_text_y_fudge
# insensitive_textalign
# insensitive_textshader
# insensitive_thumb
# insensitive_thumb_align
# insensitive_thumb_offset
# insensitive_thumb_shadow
# insensitive_time_policy
# insensitive_top_bar
# insensitive_top_gutter
# insensitive_top_margin
# insensitive_top_padding
# insensitive_underline
# insensitive_unscrollable
# insensitive_vertical
# insensitive_xalign
# insensitive_xanchor
# insensitive_xcenter
# insensitive_xfill
# insensitive_xfit
# insensitive_xmargin
# insensitive_xmaximum
# insensitive_xminimum
# insensitive_xoffset
# insensitive_xpadding
# insensitive_xpos
# insensitive_xsize
# insensitive_xspacing
# insensitive_xycenter
# insensitive_xysize
# insensitive_yalign
# insensitive_yanchor
# insensitive_ycenter
# insensitive_yfill
# insensitive_yfit
# insensitive_ymargin
# insensitive_ymaximum
# insensitive_yminimum
# insensitive_yoffset
# insensitive_ypadding
# insensitive_ypos
# insensitive_ysize
# insensitive_yspacing
# instance
# italic
# justify
# kerning
# key_events
# keyboard_focus
# keyboard_focus_insets
# language
# layout
# left_bar
# left_gutter
# left_margin
# left_padding
# line_leading
# line_overlap_split
# line_spacing
# margin
# maximum
# min_width
# minimum
# minwidth
# mipmap
# modal
# mouse
# newline_indent
# offset
# order_reverse
# outline_scaling
# outlines
# padding
# pos
# prefer_emoji
# reading_order
# rest_indent
# right_bar
# right_gutter
# right_margin
# right_padding
# ruby_line_leading
# ruby_style
# selected_activate_activate_sound
# selected_activate_adjust_spacing
# selected_activate_aft_bar
# selected_activate_aft_gutter
# selected_activate_align
# selected_activate_alt
# selected_activate_altruby_style
# selected_activate_anchor
# selected_activate_antialias
# selected_activate_area
# selected_activate_axis
# selected_activate_background
# selected_activate_bar_invert
# selected_activate_bar_resizing
# selected_activate_bar_vertical
# selected_activate_base_bar
# selected_activate_black_color
# selected_activate_bold
# selected_activate_bottom_bar
# selected_activate_bottom_gutter
# selected_activate_bottom_margin
# selected_activate_bottom_padding
# selected_activate_box_align
# selected_activate_box_first_spacing
# selected_activate_box_justify
# selected_activate_box_layout
# selected_activate_box_reverse
# selected_activate_box_spacing
# selected_activate_box_wrap
# selected_activate_box_wrap_spacing
# selected_activate_caret
# selected_activate_child
# selected_activate_clipping
# selected_activate_color
# selected_activate_debug
# selected_activate_drop_shadow
# selected_activate_drop_shadow_color
# selected_activate_emoji_font
# selected_activate_enable_hover
# selected_activate_extra_alt
# selected_activate_first_indent
# selected_activate_first_spacing
# selected_activate_fit_first
# selected_activate_focus_mask
# selected_activate_focus_rect
# selected_activate_font
# selected_activate_font_features
# selected_activate_fore_bar
# selected_activate_fore_gutter
# selected_activate_foreground
# selected_activate_group_alt
# selected_activate_hinting
# selected_activate_hover_sound
# selected_activate_hyperlink_functions
# selected_activate_instance
# selected_activate_italic
# selected_activate_justify
# selected_activate_kerning
# selected_activate_key_events
# selected_activate_keyboard_focus
# selected_activate_keyboard_focus_insets
# selected_activate_language
# selected_activate_layout
# selected_activate_left_bar
# selected_activate_left_gutter
# selected_activate_left_margin
# selected_activate_left_padding
# selected_activate_line_leading
# selected_activate_line_overlap_split
# selected_activate_line_spacing
# selected_activate_margin
# selected_activate_maximum
# selected_activate_min_width
# selected_activate_minimum
# selected_activate_minwidth
# selected_activate_mipmap
# selected_activate_modal
# selected_activate_mouse
# selected_activate_newline_indent
# selected_activate_offset
# selected_activate_order_reverse
# selected_activate_outline_scaling
# selected_activate_outlines
# selected_activate_padding
# selected_activate_pos
# selected_activate_prefer_emoji
# selected_activate_reading_order
# selected_activate_rest_indent
# selected_activate_right_bar
# selected_activate_right_gutter
# selected_activate_right_margin
# selected_activate_right_padding
# selected_activate_ruby_line_leading
# selected_activate_ruby_style
# selected_activate_shaper
# selected_activate_size
# selected_activate_size_group
# selected_activate_slow_abortable
# selected_activate_slow_cps
# selected_activate_slow_cps_multiplier
# selected_activate_slow_speed
# selected_activate_sound
# selected_activate_spacing
# selected_activate_strikethrough
# selected_activate_subpixel
# selected_activate_subtitle_width
# selected_activate_text_align
# selected_activate_text_y_fudge
# selected_activate_textalign
# selected_activate_textshader
# selected_activate_thumb
# selected_activate_thumb_align
# selected_activate_thumb_offset
# selected_activate_thumb_shadow
# selected_activate_time_policy
# selected_activate_top_bar
# selected_activate_top_gutter
# selected_activate_top_margin
# selected_activate_top_padding
# selected_activate_underline
# selected_activate_unscrollable
# selected_activate_vertical
# selected_activate_xalign
# selected_activate_xanchor
# selected_activate_xcenter
# selected_activate_xfill
# selected_activate_xfit
# selected_activate_xmargin
# selected_activate_xmaximum
# selected_activate_xminimum
# selected_activate_xoffset
# selected_activate_xpadding
# selected_activate_xpos
# selected_activate_xsize
# selected_activate_xspacing
# selected_activate_xycenter
# selected_activate_xysize
# selected_activate_yalign
# selected_activate_yanchor
# selected_activate_ycenter
# selected_activate_yfill
# selected_activate_yfit
# selected_activate_ymargin
# selected_activate_ymaximum
# selected_activate_yminimum
# selected_activate_yoffset
# selected_activate_ypadding
# selected_activate_ypos
# selected_activate_ysize
# selected_activate_yspacing
# selected_adjust_spacing
# selected_aft_bar
# selected_aft_gutter
# selected_align
# selected_alt
# selected_altruby_style
# selected_anchor
# selected_antialias
# selected_area
# selected_axis
# selected_background
# selected_bar_invert
# selected_bar_resizing
# selected_bar_vertical
# selected_base_bar
# selected_black_color
# selected_bold
# selected_bottom_bar
# selected_bottom_gutter
# selected_bottom_margin
# selected_bottom_padding
# selected_box_align
# selected_box_first_spacing
# selected_box_justify
# selected_box_layout
# selected_box_reverse
# selected_box_spacing
# selected_box_wrap
# selected_box_wrap_spacing
# selected_caret
# selected_child
# selected_clipping
# selected_color
# selected_debug
# selected_drop_shadow
# selected_drop_shadow_color
# selected_emoji_font
# selected_enable_hover
# selected_extra_alt
# selected_first_indent
# selected_first_spacing
# selected_fit_first
# selected_focus_mask
# selected_focus_rect
# selected_font
# selected_font_features
# selected_fore_bar
# selected_fore_gutter
# selected_foreground
# selected_group_alt
# selected_hinting
# selected_hover_activate_sound
# selected_hover_adjust_spacing
# selected_hover_aft_bar
# selected_hover_aft_gutter
# selected_hover_align
# selected_hover_alt
# selected_hover_altruby_style
# selected_hover_anchor
# selected_hover_antialias
# selected_hover_area
# selected_hover_axis
# selected_hover_background
# selected_hover_bar_invert
# selected_hover_bar_resizing
# selected_hover_bar_vertical
# selected_hover_base_bar
# selected_hover_black_color
# selected_hover_bold
# selected_hover_bottom_bar
# selected_hover_bottom_gutter
# selected_hover_bottom_margin
# selected_hover_bottom_padding
# selected_hover_box_align
# selected_hover_box_first_spacing
# selected_hover_box_justify
# selected_hover_box_layout
# selected_hover_box_reverse
# selected_hover_box_spacing
# selected_hover_box_wrap
# selected_hover_box_wrap_spacing
# selected_hover_caret
# selected_hover_child
# selected_hover_clipping
# selected_hover_color
# selected_hover_debug
# selected_hover_drop_shadow
# selected_hover_drop_shadow_color
# selected_hover_emoji_font
# selected_hover_enable_hover
# selected_hover_extra_alt
# selected_hover_first_indent
# selected_hover_first_spacing
# selected_hover_fit_first
# selected_hover_focus_mask
# selected_hover_focus_rect
# selected_hover_font
# selected_hover_font_features
# selected_hover_fore_bar
# selected_hover_fore_gutter
# selected_hover_foreground
# selected_hover_group_alt
# selected_hover_hinting
# selected_hover_hover_sound
# selected_hover_hyperlink_functions
# selected_hover_instance
# selected_hover_italic
# selected_hover_justify
# selected_hover_kerning
# selected_hover_key_events
# selected_hover_keyboard_focus
# selected_hover_keyboard_focus_insets
# selected_hover_language
# selected_hover_layout
# selected_hover_left_bar
# selected_hover_left_gutter
# selected_hover_left_margin
# selected_hover_left_padding
# selected_hover_line_leading
# selected_hover_line_overlap_split
# selected_hover_line_spacing
# selected_hover_margin
# selected_hover_maximum
# selected_hover_min_width
# selected_hover_minimum
# selected_hover_minwidth
# selected_hover_mipmap
# selected_hover_modal
# selected_hover_mouse
# selected_hover_newline_indent
# selected_hover_offset
# selected_hover_order_reverse
# selected_hover_outline_scaling
# selected_hover_outlines
# selected_hover_padding
# selected_hover_pos
# selected_hover_prefer_emoji
# selected_hover_reading_order
# selected_hover_rest_indent
# selected_hover_right_bar
# selected_hover_right_gutter
# selected_hover_right_margin
# selected_hover_right_padding
# selected_hover_ruby_line_leading
# selected_hover_ruby_style
# selected_hover_shaper
# selected_hover_size
# selected_hover_size_group
# selected_hover_slow_abortable
# selected_hover_slow_cps
# selected_hover_slow_cps_multiplier
# selected_hover_slow_speed
# selected_hover_sound
# selected_hover_spacing
# selected_hover_strikethrough
# selected_hover_subpixel
# selected_hover_subtitle_width
# selected_hover_text_align
# selected_hover_text_y_fudge
# selected_hover_textalign
# selected_hover_textshader
# selected_hover_thumb
# selected_hover_thumb_align
# selected_hover_thumb_offset
# selected_hover_thumb_shadow
# selected_hover_time_policy
# selected_hover_top_bar
# selected_hover_top_gutter
# selected_hover_top_margin
# selected_hover_top_padding
# selected_hover_underline
# selected_hover_unscrollable
# selected_hover_vertical
# selected_hover_xalign
# selected_hover_xanchor
# selected_hover_xcenter
# selected_hover_xfill
# selected_hover_xfit
# selected_hover_xmargin
# selected_hover_xmaximum
# selected_hover_xminimum
# selected_hover_xoffset
# selected_hover_xpadding
# selected_hover_xpos
# selected_hover_xsize
# selected_hover_xspacing
# selected_hover_xycenter
# selected_hover_xysize
# selected_hover_yalign
# selected_hover_yanchor
# selected_hover_ycenter
# selected_hover_yfill
# selected_hover_yfit
# selected_hover_ymargin
# selected_hover_ymaximum
# selected_hover_yminimum
# selected_hover_yoffset
# selected_hover_ypadding
# selected_hover_ypos
# selected_hover_ysize
# selected_hover_yspacing
# selected_hyperlink_functions
# selected_idle_activate_sound
# selected_idle_adjust_spacing
# selected_idle_aft_bar
# selected_idle_aft_gutter
# selected_idle_align
# selected_idle_alt
# selected_idle_altruby_style
# selected_idle_anchor
# selected_idle_antialias
# selected_idle_area
# selected_idle_axis
# selected_idle_background
# selected_idle_bar_invert
# selected_idle_bar_resizing
# selected_idle_bar_vertical
# selected_idle_base_bar
# selected_idle_black_color
# selected_idle_bold
# selected_idle_bottom_bar
# selected_idle_bottom_gutter
# selected_idle_bottom_margin
# selected_idle_bottom_padding
# selected_idle_box_align
# selected_idle_box_first_spacing
# selected_idle_box_justify
# selected_idle_box_layout
# selected_idle_box_reverse
# selected_idle_box_spacing
# selected_idle_box_wrap
# selected_idle_box_wrap_spacing
# selected_idle_caret
# selected_idle_child
# selected_idle_clipping
# selected_idle_color
# selected_idle_debug
# selected_idle_drop_shadow
# selected_idle_drop_shadow_color
# selected_idle_emoji_font
# selected_idle_enable_hover
# selected_idle_extra_alt
# selected_idle_first_indent
# selected_idle_first_spacing
# selected_idle_fit_first
# selected_idle_focus_mask
# selected_idle_focus_rect
# selected_idle_font
# selected_idle_font_features
# selected_idle_fore_bar
# selected_idle_fore_gutter
# selected_idle_foreground
# selected_idle_group_alt
# selected_idle_hinting
# selected_idle_hover_sound
# selected_idle_hyperlink_functions
# selected_idle_instance
# selected_idle_italic
# selected_idle_justify
# selected_idle_kerning
# selected_idle_key_events
# selected_idle_keyboard_focus
# selected_idle_keyboard_focus_insets
# selected_idle_language
# selected_idle_layout
# selected_idle_left_bar
# selected_idle_left_gutter
# selected_idle_left_margin
# selected_idle_left_padding
# selected_idle_line_leading
# selected_idle_line_overlap_split
# selected_idle_line_spacing
# selected_idle_margin
# selected_idle_maximum
# selected_idle_min_width
# selected_idle_minimum
# selected_idle_minwidth
# selected_idle_mipmap
# selected_idle_modal
# selected_idle_mouse
# selected_idle_newline_indent
# selected_idle_offset
# selected_idle_order_reverse
# selected_idle_outline_scaling
# selected_idle_outlines
# selected_idle_padding
# selected_idle_pos
# selected_idle_prefer_emoji
# selected_idle_reading_order
# selected_idle_rest_indent
# selected_idle_right_bar
# selected_idle_right_gutter
# selected_idle_right_margin
# selected_idle_right_padding
# selected_idle_ruby_line_leading
# selected_idle_ruby_style
# selected_idle_shaper
# selected_idle_size
# selected_idle_size_group
# selected_idle_slow_abortable
# selected_idle_slow_cps
# selected_idle_slow_cps_multiplier
# selected_idle_slow_speed
# selected_idle_spacing
# selected_idle_strikethrough
# selected_idle_subpixel
# selected_idle_subtitle_width
# selected_idle_text_align
# selected_idle_text_y_fudge
# selected_idle_textalign
# selected_idle_textshader
# selected_idle_thumb
# selected_idle_thumb_align
# selected_idle_thumb_offset
# selected_idle_thumb_shadow
# selected_idle_time_policy
# selected_idle_top_bar
# selected_idle_top_gutter
# selected_idle_top_margin
# selected_idle_top_padding
# selected_idle_underline
# selected_idle_unscrollable
# selected_idle_vertical
# selected_idle_xalign
# selected_idle_xanchor
# selected_idle_xcenter
# selected_idle_xfill
# selected_idle_xfit
# selected_idle_xmargin
# selected_idle_xmaximum
# selected_idle_xminimum
# selected_idle_xoffset
# selected_idle_xpadding
# selected_idle_xpos
# selected_idle_xsize
# selected_idle_xspacing
# selected_idle_xycenter
# selected_idle_xysize
# selected_idle_yalign
# selected_idle_yanchor
# selected_idle_ycenter
# selected_idle_yfill
# selected_idle_yfit
# selected_idle_ymargin
# selected_idle_ymaximum
# selected_idle_yminimum
# selected_idle_yoffset
# selected_idle_ypadding
# selected_idle_ypos
# selected_idle_ysize
# selected_idle_yspacing
# selected_insensitive_activate_sound
# selected_insensitive_adjust_spacing
# selected_insensitive_aft_bar
# selected_insensitive_aft_gutter
# selected_insensitive_align
# selected_insensitive_alt
# selected_insensitive_altruby_style
# selected_insensitive_anchor
# selected_insensitive_antialias
# selected_insensitive_area
# selected_insensitive_axis
# selected_insensitive_background
# selected_insensitive_bar_invert
# selected_insensitive_bar_resizing
# selected_insensitive_bar_vertical
# selected_insensitive_base_bar
# selected_insensitive_black_color
# selected_insensitive_bold
# selected_insensitive_bottom_bar
# selected_insensitive_bottom_gutter
# selected_insensitive_bottom_margin
# selected_insensitive_bottom_padding
# selected_insensitive_box_align
# selected_insensitive_box_first_spacing
# selected_insensitive_box_justify
# selected_insensitive_box_layout
# selected_insensitive_box_reverse
# selected_insensitive_box_spacing
# selected_insensitive_box_wrap
# selected_insensitive_box_wrap_spacing
# selected_insensitive_caret
# selected_insensitive_child
# selected_insensitive_clipping
# selected_insensitive_color
# selected_insensitive_debug
# selected_insensitive_drop_shadow
# selected_insensitive_drop_shadow_color
# selected_insensitive_emoji_font
# selected_insensitive_enable_hover
# selected_insensitive_extra_alt
# selected_insensitive_first_indent
# selected_insensitive_first_spacing
# selected_insensitive_fit_first
# selected_insensitive_focus_mask
# selected_insensitive_focus_rect
# selected_insensitive_font
# selected_insensitive_font_features
# selected_insensitive_fore_bar
# selected_insensitive_fore_gutter
# selected_insensitive_foreground
# selected_insensitive_group_alt
# selected_insensitive_hinting
# selected_insensitive_hover_sound
# selected_insensitive_hyperlink_functions
# selected_insensitive_instance
# selected_insensitive_italic
# selected_insensitive_justify
# selected_insensitive_kerning
# selected_insensitive_key_events
# selected_insensitive_keyboard_focus
# selected_insensitive_keyboard_focus_insets
# selected_insensitive_language
# selected_insensitive_layout
# selected_insensitive_left_bar
# selected_insensitive_left_gutter
# selected_insensitive_left_margin
# selected_insensitive_left_padding
# selected_insensitive_line_leading
# selected_insensitive_line_overlap_split
# selected_insensitive_line_spacing
# selected_insensitive_margin
# selected_insensitive_maximum
# selected_insensitive_min_width
# selected_insensitive_minimum
# selected_insensitive_minwidth
# selected_insensitive_mipmap
# selected_insensitive_modal
# selected_insensitive_mouse
# selected_insensitive_newline_indent
# selected_insensitive_offset
# selected_insensitive_order_reverse
# selected_insensitive_outline_scaling
# selected_insensitive_outlines
# selected_insensitive_padding
# selected_insensitive_pos
# selected_insensitive_prefer_emoji
# selected_insensitive_reading_order
# selected_insensitive_rest_indent
# selected_insensitive_right_bar
# selected_insensitive_right_gutter
# selected_insensitive_right_margin
# selected_insensitive_right_padding
# selected_insensitive_ruby_line_leading
# selected_insensitive_ruby_style
# selected_insensitive_shaper
# selected_insensitive_size
# selected_insensitive_size_group
# selected_insensitive_slow_abortable
# selected_insensitive_slow_cps
# selected_insensitive_slow_cps_multiplier
# selected_insensitive_slow_speed
# selected_insensitive_spacing
# selected_insensitive_strikethrough
# selected_insensitive_subpixel
# selected_insensitive_subtitle_width
# selected_insensitive_text_align
# selected_insensitive_text_y_fudge
# selected_insensitive_textalign
# selected_insensitive_textshader
# selected_insensitive_thumb
# selected_insensitive_thumb_align
# selected_insensitive_thumb_offset
# selected_insensitive_thumb_shadow
# selected_insensitive_time_policy
# selected_insensitive_top_bar
# selected_insensitive_top_gutter
# selected_insensitive_top_margin
# selected_insensitive_top_padding
# selected_insensitive_underline
# selected_insensitive_unscrollable
# selected_insensitive_vertical
# selected_insensitive_xalign
# selected_insensitive_xanchor
# selected_insensitive_xcenter
# selected_insensitive_xfill
# selected_insensitive_xfit
# selected_insensitive_xmargin
# selected_insensitive_xmaximum
# selected_insensitive_xminimum
# selected_insensitive_xoffset
# selected_insensitive_xpadding
# selected_insensitive_xpos
# selected_insensitive_xsize
# selected_insensitive_xspacing
# selected_insensitive_xycenter
# selected_insensitive_xysize
# selected_insensitive_yalign
# selected_insensitive_yanchor
# selected_insensitive_ycenter
# selected_insensitive_yfill
# selected_insensitive_yfit
# selected_insensitive_ymargin
# selected_insensitive_ymaximum
# selected_insensitive_yminimum
# selected_insensitive_yoffset
# selected_insensitive_ypadding
# selected_insensitive_ypos
# selected_insensitive_ysize
# selected_insensitive_yspacing
# selected_instance
# selected_italic
# selected_justify
# selected_kerning
# selected_key_events
# selected_keyboard_focus
# selected_keyboard_focus_insets
# selected_language
# selected_layout
# selected_left_bar
# selected_left_gutter
# selected_left_margin
# selected_left_padding
# selected_line_leading
# selected_line_overlap_split
# selected_line_spacing
# selected_margin
# selected_maximum
# selected_min_width
# selected_minimum
# selected_minwidth
# selected_mipmap
# selected_modal
# selected_mouse
# selected_newline_indent
# selected_offset
# selected_order_reverse
# selected_outline_scaling
# selected_outlines
# selected_padding
# selected_pos
# selected_prefer_emoji
# selected_reading_order
# selected_rest_indent
# selected_right_bar
# selected_right_gutter
# selected_right_margin
# selected_right_padding
# selected_ruby_line_leading
# selected_ruby_style
# selected_shaper
# selected_size
# selected_size_group
# selected_slow_abortable
# selected_slow_cps
# selected_slow_cps_multiplier
# selected_slow_speed
# selected_spacing
# selected_strikethrough
# selected_subpixel
# selected_subtitle_width
# selected_text_align
# selected_text_y_fudge
# selected_textalign
# selected_textshader
# selected_thumb
# selected_thumb_align
# selected_thumb_offset
# selected_thumb_shadow
# selected_time_policy
# selected_top_bar
# selected_top_gutter
# selected_top_margin
# selected_top_padding
# selected_underline
# selected_unscrollable
# selected_vertical
# selected_xalign
# selected_xanchor
# selected_xcenter
# selected_xfill
# selected_xfit
# selected_xmargin
# selected_xmaximum
# selected_xminimum
# selected_xoffset
# selected_xpadding
# selected_xpos
# selected_xsize
# selected_xspacing
# selected_xycenter
# selected_xysize
# selected_yalign
# selected_yanchor
# selected_ycenter
# selected_yfill
# selected_yfit
# selected_ymargin
# selected_ymaximum
# selected_yminimum
# selected_yoffset
# selected_ypadding
# selected_ypos
# selected_ysize
# selected_yspacing
# shaper
# size
# size_group
# slow_abortable
# slow_cps
# slow_cps_multiplier
# slow_speed
# spacing
# strikethrough
# subpixel
# subtitle_width
# text_align
# text_y_fudge
# textalign
# textshader
# thumb
# thumb_align
# thumb_offset
# thumb_shadow
# time_policy
# top_bar
# top_gutter
# top_margin
# top_padding
# underline
# unscrollable
# vertical
# xalign
# xanchor
# xcenter
# xfill
# xfit
# xmargin
# xmaximum
# xminimum
# xoffset
# xpadding
# xpos
# xsize
# xspacing
# xycenter
# xysize
# yalign
# yanchor
# ycenter
# yfill
# yfit
# ymargin
# ymaximum
# yminimum
# yoffset
# ypadding
# ypos
# ysize
# yspacing
