import collections
from collections.abc import Callable
from typing import Any

import renpy
from renpy.display.render import Render

_constant: bool
ticket: Any

def retrieve_stats() -> None: ...
def store_stats() -> None: ...
def list_achievements() -> list[str]: ...
def get_achievement(name: str) -> bool | None: ...
def grant_achievement(name: str) -> bool: ...
def clear_achievement(name: str) -> bool: ...
def indicate_achievement_progress(name: str, cur_progress: int, max_progress: int) -> bool: ...
def get_float_stat(name: str) -> float | None: ...
def set_float_stat(name: str, value: float) -> bool: ...
def get_int_stat(name: str) -> int | None: ...
def set_int_stat(name: str, value: int) -> bool: ...
def is_subscribed_app(appid: int) -> bool: ...
def get_current_game_language() -> str: ...
def get_steam_ui_language() -> str: ...
def get_current_beta_name() -> str | None: ...
def dlc_installed(appid: int) -> bool: ...
def install_dlc(appid: int) -> None: ...
def uninstall_dlc(appid: int) -> None: ...
def dlc_progress(appid: int) -> tuple[int, int] | None: ...
def get_app_build_id() -> int: ...
def is_overlay_enabled() -> bool: ...

last_needs_present_call: int

def overlay_needs_present() -> bool: ...
def set_overlay_notification_position(position: int) -> None: ...
def activate_overlay(dialog: str) -> None: ...
def activate_overlay_to_web_page(url: str) -> None: ...
def activate_overlay_to_store(appid: int, flag: int | None = None) -> None: ...
def get_persona_name() -> str: ...
def get_csteam_id() -> int: ...
def get_account_id() -> int: ...
def get_session_ticket(identity: int | None = None) -> Any: ...
def cancel_ticket() -> None: ...
def get_game_badge_level(series: int, foil: bool) -> int: ...
def get_subscribed_items(include_disabled: bool = False) -> list[Any]: ...
def get_subscribed_item_path(item_id: int) -> str: ...
def set_timeline_state_description(description: str, time_delta: float = 0.0) -> None: ...
def clear_timeline_state_description(time_delta: float) -> None: ...
def add_timeline_event(
    icon: str,
    title: str,
    description: str,
    priority: int = 0,
    start_offset: float = 0.0,
    duration: float = 0.0,
    possible_clip: int | None = None,
) -> None: ...
def set_timeline_game_mode(mode: int) -> None: ...
def start_game_phase(identifier: str) -> None: ...
def end_game_phase() -> None: ...
def import_api() -> None: ...

callback_handlers: collections.defaultdict[str, list[Any]]
callback_state: renpy.rollback.NoRollback

def periodic() -> None: ...

keyboard_mode: str
keyboard_primed: bool
keyboard_showing: float | None
keyboard_shift: bool
keyboard_baseline: float
keyboard_text_area: tuple[float, float, float, float]

def prime_keyboard() -> None: ...
def keyboard_periodic() -> None: ...
def keyboard_dismissed(cb: Callable) -> None: ...

class _KeyboardShift(renpy.display.layout.Container):
    text_rect: tuple[int, int, int, int]
    last_offset: int
    rendered_offset: int
    delay: float
    def __init__(
        self,
        new_widget: renpy.display.displayable.Displayable,
        old_widget: renpy.display.displayable.Displayable,
        **properties,
    ) -> None: ...
    offsets: list[tuple[float, float]]
    def render(self, width: float, height: float, st: float, at: float) -> Render: ...
