from _typeshed import Incomplete
from typing import Any

import renpy
from renpy.ui import Action
from renpy.display.render import Render
from renpy.pygame.event import EventType

_constant: bool
tag_blacklist: Incomplete
scene_tags: Incomplete
show_tags: Incomplete
blacklist_prefixed_tags: bool
transforms: Incomplete
transitions: Incomplete
audio_channels: Incomplete
voice_channel: str
audio_patterns: Incomplete
audio_channel_patterns: Incomplete
audio_files: Incomplete
spacing: int
director_spacing: int
other_spacing: int
viewport_height: int
state: Incomplete
UNINTERESTING_NODES: Incomplete
ALONE_NODES: Incomplete

def audio_code_to_filename(channel: Incomplete, fn: Incomplete) -> Incomplete: ...
def audio_filename_to_code(channel: Incomplete, fn: Incomplete) -> Incomplete: ...
def audio_filename_to_display(channel: Incomplete, fn: Incomplete) -> Incomplete: ...
def is_play(n: Incomplete) -> Incomplete: ...
def is_queue(n: Incomplete) -> Incomplete: ...
def is_stop(n: Incomplete) -> Incomplete: ...
def is_voice(n: Incomplete) -> Incomplete: ...
def is_interesting(n: Incomplete) -> Incomplete: ...
def interact_base() -> Incomplete: ...
def after_load() -> None: ...
def interact() -> None: ...
def line_log_callback(lle: Incomplete) -> None: ...
def init() -> None: ...
def command() -> Incomplete: ...
def get_scene_show_hide_statement() -> Incomplete: ...
def quote_audio() -> Incomplete: ...
def get_play_queue_statement() -> Incomplete: ...
def get_stop_statement() -> Incomplete: ...
def get_voice_statement() -> Incomplete: ...
def get_statement() -> Incomplete: ...
def update_ast(force: bool = False) -> None: ...
def dump_script() -> None: ...
def pick_tag() -> None: ...
def find_statement(filename: Incomplete, line: Incomplete, delta: Incomplete, limit: int = 10) -> Incomplete: ...
def needs_space(filename: Incomplete, line: Incomplete) -> Incomplete: ...
def is_spacing(filename: Incomplete, line: Incomplete) -> Incomplete: ...
def adjust_spacing_before(filename: Incomplete, line: Incomplete) -> None: ...
def add_spacing(filename: Incomplete, line: Incomplete) -> None: ...
def remove_spacing(filename: Incomplete, line: Incomplete) -> None: ...
def get_tags() -> Incomplete: ...
def get_attributes() -> Incomplete: ...
def get_transforms() -> Incomplete: ...
def get_image_attributes() -> Incomplete: ...
def get_ordered_attributes() -> Incomplete: ...
def get_behind_tags(exclude: Incomplete = None) -> Incomplete: ...

class Start(Action):
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

class Stop(Action):
    def __call__(self) -> None: ...

class AddStatement(Action):
    lle: Incomplete
    sensitive: Incomplete
    def __init__(self, lle: Incomplete) -> None: ...
    def get_sensitive(self) -> bool: ...
    def __call__(self) -> None: ...

def is_scene_show_hide_editable(node: Incomplete) -> Incomplete: ...

class ChangeStatement(Action):
    lle: Incomplete
    tag: Incomplete
    attributes: Incomplete
    transforms: Incomplete
    transition: Incomplete
    behind: Incomplete
    channel: Incomplete
    audio: Incomplete
    sensitive: bool
    kind: Incomplete
    def __init__(self, lle: Incomplete, node: Incomplete) -> None: ...
    def get_sensitive(self) -> bool: ...
    def __call__(self) -> None: ...

class SetKind(Action):
    kind: Incomplete
    def __init__(self, kind: Incomplete) -> None: ...
    def __call__(self) -> None: ...

class SetTag(Action):
    tag: Incomplete
    def __init__(self, tag: Incomplete) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class ToggleAttribute(Action):
    attribute: Incomplete
    def __init__(self, attribute: Incomplete) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class ToggleNegativeAttribute(Action):
    attribute: Incomplete
    negative: Incomplete
    def __init__(self, attribute: Incomplete) -> None: ...
    def __call__(self) -> None: ...

class SetList(Action):
    l: Incomplete
    v: Incomplete
    def __init__(self, l: Incomplete, v: Incomplete) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class ToggleList(Action):
    l: Incomplete
    v: Incomplete
    def __init__(self, l: Incomplete, v: Incomplete) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class SetTransition(Action):
    transition: Incomplete
    def __init__(self, transition: Incomplete) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class SetChannel(Action):
    channel: Incomplete
    def __init__(self, channel: Incomplete) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class SetAudio(Action):
    filename: Incomplete
    def __init__(self, filename: Incomplete) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class Commit(Action):
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

class Reset(Action):
    def __call__(self) -> None: ...

class Cancel(Action):
    def __call__(self) -> None: ...

class Remove(Action):
    def __call__(self) -> None: ...

class SemiModal(renpy.display.displayable.Displayable):
    child: Incomplete
    w: int
    h: int
    def __init__(self, child: Incomplete) -> None: ...
    def per_interact(self) -> None: ...
    def render(self, width: float, height: float, st: float, at: float) -> Render: ...
    def event(self, ev: EventType, x: float, y: float, st: float) -> Any | None: ...
    def get_placement(self) -> Incomplete: ...
    def visit(self) -> Incomplete: ...

def component_key(s: Incomplete) -> Incomplete: ...
