from typing import Any

import renpy
from renpy.display.render import Render
from renpy.pygame.event import EventType
from renpy.ui import Action

_constant: bool
tag_blacklist: set[str]
scene_tags: set[str]
show_tags: set[str]
blacklist_prefixed_tags: bool
transforms: list[str]
transitions: list[str]
audio_channels: list[str]
voice_channel: str
audio_patterns: list[str]
audio_channel_patterns: dict[str, list[str]]
audio_files: dict[str, list[str]]
spacing: int
director_spacing: int
other_spacing: int
viewport_height: int
state: renpy.rollback.NoRollback | None
UNINTERESTING_NODES: tuple[type, ...]
ALONE_NODES: tuple[type, ...]

def audio_code_to_filename(channel: str, fn: str) -> str: ...
def audio_filename_to_code(channel: str, fn: str) -> str: ...
def audio_filename_to_display(channel: str, fn: str) -> str: ...
def is_play(n: renpy.ast.Node) -> bool: ...
def is_queue(n: renpy.ast.Node) -> bool: ...
def is_stop(n: renpy.ast.Node) -> bool: ...
def is_voice(n: renpy.ast.Node) -> bool: ...
def is_interesting(n: renpy.ast.Node) -> bool: ...
def interact_base() -> None: ...
def after_load() -> None: ...
def interact() -> None: ...
def line_log_callback(lle: renpy.execution.LineLogEntry) -> None: ...
def init() -> None: ...
def command() -> str | None: ...
def get_scene_show_hide_statement() -> str | None: ...
def quote_audio() -> str: ...
def get_play_queue_statement() -> str | None: ...
def get_stop_statement() -> str | None: ...
def get_voice_statement() -> str | None: ...
def get_statement() -> str | None: ...
def update_ast(force: bool = False) -> None: ...
def dump_script() -> None: ...
def pick_tag() -> None: ...
def find_statement(filename: str, line: int, delta: int, limit: int = 10) -> renpy.ast.Node | None: ...
def needs_space(filename: str, line: int) -> bool: ...
def is_spacing(filename: str, line: int) -> bool: ...
def adjust_spacing_before(filename: str, line: int) -> None: ...
def add_spacing(filename: str, line: int) -> None: ...
def remove_spacing(filename: str, line: int) -> None: ...
def get_tags() -> list[str]: ...
def get_attributes() -> list[str]: ...
def get_transforms() -> list[str]: ...
def get_image_attributes() -> list[str]: ...
def get_ordered_attributes() -> list[str]: ...
def get_behind_tags(exclude: set[str] | None = None) -> list[str]: ...

class Start(Action):
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

class Stop(Action):
    def __call__(self) -> None: ...

class AddStatement(Action):
    lle: renpy.execution.LineLogEntry
    sensitive: bool
    def __init__(self, lle: renpy.execution.LineLogEntry) -> None: ...
    def get_sensitive(self) -> bool: ...
    def __call__(self) -> None: ...

def is_scene_show_hide_editable(node: renpy.ast.Node) -> bool: ...

class ChangeStatement(Action):
    lle: Any
    tag: str
    attributes: list[str]
    transforms: list[str]
    transition: str | None
    behind: list[str]
    channel: str | None
    audio: str | None
    sensitive: bool
    kind: str
    def __init__(self, lle: Any, node: Any) -> None: ...
    def get_sensitive(self) -> bool: ...
    def __call__(self) -> None: ...

class SetKind(Action):
    kind: str
    def __init__(self, kind: str) -> None: ...
    def __call__(self) -> None: ...

class SetTag(Action):
    tag: str
    def __init__(self, tag: str) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class ToggleAttribute(Action):
    attribute: str
    def __init__(self, attribute: str) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class ToggleNegativeAttribute(Action):
    attribute: str
    negative: bool
    def __init__(self, attribute: str) -> None: ...
    def __call__(self) -> None: ...

class SetList(Action):
    l: list
    v: Any
    def __init__(self, l: list, v: Any) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class ToggleList(Action):
    l: list
    v: Any
    def __init__(self, l: list, v: Any) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class SetTransition(Action):
    transition: str
    def __init__(self, transition: str) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class SetChannel(Action):
    channel: str
    def __init__(self, channel: str) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class SetAudio(Action):
    filename: str
    def __init__(self, filename: str) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

class Commit(Action):
    def __call__(self) -> None: ...
    def get_sensitive(self) -> bool: ...

class Reset(Action):
    def __call__(self) -> None: ...

class Cancel(Action):
    def __call__(self) -> None: ...

class Remove(Action):
    def __call__(self) -> None: ...

class SemiModal(renpy.display.displayable.Displayable):
    child: renpy.display.displayable.Displayable
    w: int
    h: int
    def __init__(self, child: renpy.display.displayable.Displayable) -> None: ...
    def per_interact(self) -> None: ...
    def render(self, width: float, height: float, st: float, at: float) -> Render: ...
    def event(self, ev: EventType, x: float, y: float, st: float) -> Any | None: ...
    def get_placement(self) -> dict[str, Any]: ...
    def visit(self) -> list[renpy.display.displayable.Displayable | None]: ...

def component_key(s: str) -> str: ...
