from renpy.display.displayable import Displayable
from renpy.display.render import Render

path: list[str]

class Icon(Displayable):
    name: str
    def __init__(self, name: str, style: str = "icon", **properties) -> None: ...
    def find_image(self, prefix: str) -> Displayable | str: ...
    def render(self, width: float, height: float, st: float, at: float) -> Render: ...
    STATES: list[str]
    def visit(self) -> list[Displayable]: ...
