# Adapted from https://github.com/renpy/renpy/blob/master/scripts/relative_imports.py

import ast
import pathlib
from typing import cast
from .config import config

ROOT = pathlib.Path(__file__).parent.parent
HEADER = "# Generated by scripts/relative_imports.py, do not edit below this line."


class ModuleInfo:
    name: str
    full_name: str
    path: pathlib.Path
    submodules: "dict[str, ModuleInfo]"
    files: list[str]

    def __init__(self, name: str, full_name: str, path: pathlib.Path):
        self.name = name
        self.full_name = full_name
        self.path = path
        self.submodules = {}
        self.files = []


def find_modules() -> ModuleInfo:
    root = ModuleInfo(name="renpy", full_name="renpy", path=config.pyi_path / "renpy-stubs")

    # Gather and sort all relevant files
    files = sorted(p for pattern in ("**/*.pyi", "**/*.pyx") for p in config.pyi_path.glob(pattern))

    for path in files:
        # Convert path to parts: renpy-stubs/common.pyi -> ["renpy", "common"]
        parts = list(path.relative_to(config.pyi_path).with_suffix("").parts)

        if parts[-1] == "__init__":
            parts.pop()

        if parts and parts[0] == "renpy-stubs":
            parts[0] = "renpy"

        if len(parts) < 2 or parts[0] != "renpy":
            continue

        # Build the tree
        node = root
        for part in parts[1:-1]:
            if part not in node.submodules:
                node.submodules[part] = ModuleInfo(
                    name=part, full_name=node.full_name + "." + part, path=node.path / part
                )
            node = node.submodules[part]

        node.files.append(parts[-1])

    return root


def build_store_string(module_info: ModuleInfo) -> str:
    lines: list[str] = []
    all_imports: list[str] = []

    for mod in module_info.files:
        module_path = module_info.path / (mod + ".pyi")
        if not module_path.exists():
            continue

        try:
            content = module_path.read_text(encoding="utf-8")
            module = ast.parse(content)
        except Exception:
            continue

        import_names: list[str] = []
        for node in module.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                import_names.append(node.name)
            elif isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        import_names.append(target.id)
            elif isinstance(node, ast.AnnAssign):
                if isinstance(node.target, ast.Name):
                    import_names.append(node.target.id)

        if not import_names:
            continue

        all_imports.extend(import_names)
        import_names_as = [f"{name} as {name}" for name in import_names]

        single_line = f"from .{mod} import {', '.join(import_names_as)}"
        if len(single_line) <= 100:
            lines.append(single_line)
        else:
            joined = ",\n    ".join(import_names_as)
            lines.append(f"from .{mod} import (\n    {joined}\n)")

    if all_imports:
        unique_imports = list(dict.fromkeys(all_imports))  # preserve order, remove duplicates
        lines.append("")
        lines.append("__all__ = [")
        lines.extend(f'    "{name}",' for name in unique_imports)
        lines.append("]")

    return "\n".join(lines) + "\n"


def generate(module_info: ModuleInfo) -> None:
    # fn = module_info.name.replace("renpy", "renpy-stubs", 1).replace(".", "/") + "/__init__.pyi"
    # p = config.pyi_path / fn
    p = module_info.path / "__init__.pyi"

    text = ""
    if p.exists():
        text = p.read_text("utf-8")

        text = text.split("\n")
        new_text = []

        for i in text:
            if i == HEADER:
                break

            new_text.append(i)

        text = "\n".join(new_text)

        text = text.rstrip("\n")
        text = text + "\n\n"

    text += HEADER + "\n"

    if module_info.full_name.startswith("renpy.store"):
        for submod in module_info.submodules.keys():
            text += f"from . import {submod} as {submod}\n"

        text += "\n"
        text += build_store_string(module_info)
    else:
        for mod in module_info.files:
            # text += f"    from . import {mod} as {mod}\n"
            text += f"from . import {mod} as {mod}\n"

    p.write_text(text.lstrip("\n"), "utf-8", newline="\n")


def recursive_generate(module_info: ModuleInfo):
    generate(module_info)

    for submod in module_info.submodules.values():
        recursive_generate(submod)


def main():
    module_info = find_modules()
    recursive_generate(module_info)


if __name__ == "__main__":
    main()
