# Adapted from https://github.com/renpy/renpy/blob/master/scripts/relative_imports.py

import pathlib
import collections
from .config import config

ROOT = pathlib.Path(__file__).parent.parent
HEADER = "# Generated by scripts/relative_imports.py, do not edit below this line."

GENERATED_MODULES: str = ""


def find_modules():
    """
    Finds the names of all modules.
    """

    modules: list[str] = GENERATED_MODULES.split()

    patterns = ["**/*.pyi", "**/*.pyx"]

    for pattern in patterns:
        for i in config.pyi_path.glob(pattern):
            i = i.relative_to(config.pyi_path)
            mod = i.with_suffix("").as_posix().replace("/", ".")
            if mod.endswith(".__init__"):
                mod = mod[:-9]

            mod = mod.replace("renpy-stubs.", "renpy.")
            modules.append(mod)

    modules.sort()

    package_modules = collections.defaultdict[str, list[str]](list)

    for mod in modules:
        package, _, module = mod.rpartition(".")

        if not package.startswith("renpy"):
            continue

        package_modules[package].append(module)

    return package_modules


def generate(package: str, modules: list[str]):
    if package == "renpy.common":
        return

    fn = package.replace("renpy", "renpy-stubs").replace(".", "/") + "/__init__.pyi"
    p = config.pyi_path / fn

    text = p.read_text("utf-8")

    text = text.split("\n")
    new_text = []

    for i in text:
        if i == HEADER:
            break

        new_text.append(i)

    text = "\n".join(new_text)

    text = text.rstrip("\n")
    text = text + "\n\n\n"

    text += HEADER + "\n"
    # text += "import typing\n"
    # text += "\n"
    # text += "if typing.TYPE_CHECKING:\n"

    for mod in modules:
        # text += f"    from . import {mod} as {mod}\n"
        text += f"from . import {mod} as {mod}\n"

    p.write_text(text, "utf-8")


def main():
    package_modules = find_modules()
    for package, modules in package_modules.items():
        generate(package, modules)


if __name__ == "__main__":
    main()
