from _typeshed import Incomplete
from renpy.ui import Action
from renpy.character import ADVCharacter, Character as Character

active: bool
shown: Incomplete
db_filename: str
cols: int
rows: int
default_area: Incomplete
area_property: str
properties: Incomplete
properties_order: Incomplete
properties_callback: Incomplete
expand_area: Incomplete
db: Incomplete
frame: Incomplete
thoughtframe: Incomplete
layer: str
retain_layer: str
clear_retain_statements: Incomplete

class ToggleShown(Action):
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...

def scene_callback(layer: Incomplete) -> None: ...
def character_callback(event: Incomplete, interact: bool = True, **kwargs: Incomplete) -> None: ...

class BubbleCharacter(ADVCharacter):
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def bubble_default_properties(self, image_tag: Incomplete) -> Incomplete: ...
    def expand_area(self, area: Incomplete, properties_key: Incomplete) -> Incomplete: ...
    def do_add(self, who: Incomplete, what: Incomplete, multiple: bool = False) -> None: ...
    def do_show(
        self,
        who: Incomplete,
        what: Incomplete,
        multiple: Incomplete = None,
        retain: Incomplete = None,
        extra_properties: Incomplete = None,
    ) -> Incomplete: ...

class CycleBubbleProperty(Action):
    image_tag: Incomplete
    tlid: Incomplete
    def __init__(self, image_tag: Incomplete, tlid: Incomplete) -> None: ...
    def get_selected(self) -> bool: ...
    def __call__(self) -> None: ...
    def alternate(self) -> None: ...

class ToggleClearRetain(Action):
    tlid: Incomplete
    def __init__(self, tlid: Incomplete) -> None: ...
    def get_selected(self) -> bool: ...
    def __call__(self) -> None: ...
    def alternate(self) -> None: ...

class SetWindowArea(Action):
    image_tag: Incomplete
    tlid: Incomplete
    def __init__(self, image_tag: Incomplete, tlid: Incomplete) -> None: ...
    def __call__(self) -> None: ...
    def get_selected(self) -> bool: ...
    def finished(self, rect: Incomplete) -> None: ...
    def alternate(self) -> None: ...

def GetCurrentDialogue() -> Incomplete: ...

character: Incomplete

def statement_callback(statement: Incomplete) -> None: ...

tag_properties: Incomplete
current_dialogue: Incomplete
