from renpy.sl2.slparser import Keyword as Keyword, PrefixStyle as PrefixStyle, Style as Style
from typing import Sequence

position_property_names: list[str]
position_properties: list[Style | Keyword]
text_position_properties: list[PrefixStyle]
side_position_properties: list[PrefixStyle | Keyword]
viewport_position_properties: list[PrefixStyle]
scrollbar_position_properties: list[PrefixStyle | Keyword]
vscrollbar_position_properties: list[PrefixStyle | Keyword]
text_property_names: list[str]
text_properties: list[Style]
text_text_properties: list[PrefixStyle]
margin_properties: list[Style]
padding_properties: list[Style]
window_properties: list[Style]
button_properties: list[Style | Keyword]
bar_property_names: list[str]
bar_properties: list[Style]
scrollbar_bar_properties: list[PrefixStyle]
vscrollbar_bar_properties: list[PrefixStyle]
box_property_names: list[str]
box_properties: list[Style]
grid_properties: list[Style]
ui_properties: list[Keyword]
property_groups: dict[str, Sequence[Style | Keyword]]
