# Generated by scripts/relative_imports.py, do not edit below this line.

from .__numbered_textshader_ren import _constant as _constant, adjust_duration as adjust_duration

__all__ = [
    "_constant",
    "adjust_duration",
]
