import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

class GL2Draw:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def can_block(self) -> None: ...
    def draw_screen(self, render_tree: Incomplete, flip: bool = True, screenshot: bool = False) -> None: ...
    def event_peek_sleep(self) -> None: ...
    def flip(self) -> None: ...
    def get_mouse_pos(self) -> None: ...
    def get_physical_size(self) -> None: ...
    def get_texture_size(self) -> None: ...
    def get_window_position(self, physical_size: Incomplete = None) -> None: ...
    def init(self, virtual_size: Incomplete) -> None: ...
    def init_fbo(self) -> None: ...
    def is_pixel_opaque(self, what: Incomplete) -> None: ...
    def kill_textures(self) -> None: ...
    def load_all_textures(self, what: Incomplete) -> None: ...
    def load_texture(self, surf: Incomplete, transient: bool = False, properties: dict = {}) -> None: ...
    def mouse_event(self, ev: Incomplete) -> None: ...
    def mutated_surface(self, surf: Incomplete) -> None: ...
    def on_resize(self, first: bool = False, full_reset: bool = False) -> None: ...
    def quit(self) -> None: ...
    def quit_fbo(self) -> None: ...
    def ready_one_texture(self) -> None: ...
    def render_to_texture(self, what: Incomplete, alpha: bool = True, properties: dict = {}) -> None: ...
    def resize(self) -> None: ...
    def screenshot(self, render_tree: Incomplete) -> None: ...
    def select_framerate(self) -> None: ...
    def select_gl_attributes(self, gles: Incomplete) -> None: ...
    def select_physical_size(self, physical_size: Incomplete) -> None: ...
    def set_mouse_pos(self, x: Incomplete, y: Incomplete) -> None: ...
    def should_redraw(self, needs_redraw: Incomplete, first_pass: Incomplete, can_block: Incomplete) -> None: ...
    def solid_texture(self, w: Incomplete, h: Incomplete, color: Incomplete) -> None: ...
    def translate_point(self, x: Incomplete, y: Incomplete) -> None: ...
    def untranslate_point(self, x: Incomplete, y: Incomplete) -> None: ...
    def update(self, force: bool = False) -> None: ...

class GL2DrawingContext:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def merge_uniforms(self, uniforms: dict) -> Incomplete: ...

def Literal(*args, **kwds) -> None: ...

ShaderCache = renpy.gl2.gl2shadercache.ShaderCache
Surface = renpy.pygame.surface.Surface
Texture = renpy.gl2.gl2texture.Texture

def draw_render(
    what: Incomplete, drawable_width: int, drawable_height: int, projection: Matrix, invert_front_face: bool = False
) -> Incomplete: ...
def set_cull_face(cull_face: Incomplete) -> None: ...

standard_uniforms: set[str]
BIG_PIXELS: int
current_invert_front_face: int
vsync: int
