import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete
from renpy.display.matrix import Matrix
from renpy.display.render import Render
from renpy.uguu.uguu import GLuint
from renpy.gl2.gl2model import GL2Model
from renpy.gl2.gl2texture import TextureLoader
from renpy.types import Unused
from typing import Literal, Any

ShaderCache = renpy.gl2.gl2shadercache.ShaderCache
Surface = renpy.pygame.surface.Surface
Texture = renpy.gl2.gl2texture.Texture

standard_uniforms: set[str]
BIG_PIXELS: int
current_cull_face: Literal["ccw", "cw", None]
current_invert_front_face: bool
vsync: int
frame_times: list[float]

class GL2Draw:
    gles: bool
    angle: bool
    did_init: bool
    window: Surface | None
    virtual_size: tuple[Incomplete, Incomplete] | None
    physical_size: tuple[Incomplete, Incomplete] | None
    drawable_size: tuple[int, int]
    virtual_box: tuple[float, float, float, float]
    physical_box: tuple[float, float, float, float]
    last_redraw_time: float
    redraw_period: float
    info: dict[str, Any]
    old_fullscreen: bool
    fullscreen_surface: Unused
    display_info: renpy.pygame.display.Info | None
    # clip_cache: tuple[Incomplete, Incomplete]
    # default_clip: tuple[Incomplete, Incomplete]
    dpi_scale: float
    shader_cache: ShaderCache | None
    ever_set_position: bool
    # clip_rtt_box: tuple[Incomplete, Incomplete]
    draw_per_phys: float
    drawable_viewport: tuple[float, float, float, float]
    draw_per_virt: float
    virt_to_draw: Matrix
    draw_to_virt: Matrix
    auto_mipmap: bool
    draw_transform: Matrix
    fast_redraw_frames: int
    color_dbuffer: GLuint
    depth_renderbuffer: GLuint
    fbo: GLuint
    color_renderbuffer_1px: GLuint
    depth_renderbuffer_1px: GLuint
    fbo_1px: GLuint
    texture_loader: TextureLoader
    default_fbo: GLuint
    current_fbo: GLuint
    maximized: bool

    def __init__(self, name: str) -> None: ...
    def can_block(self) -> bool: ...
    def draw_screen(self, render_tree: Incomplete, flip: bool = True, screenshot: bool = False) -> None: ...
    def event_peek_sleep(self) -> None: ...
    def flip(self) -> None: ...
    def get_mouse_pos(self) -> tuple[int, int]: ...
    def get_physical_size(self) -> tuple[int, int]: ...
    def get_texture_size(self) -> tuple[int, int]: ...
    def get_window_position(self, physical_size: tuple[float, float] | None = None) -> tuple[int, int]: ...
    def init(self, virtual_size: Incomplete) -> bool: ...
    def init_fbo(self) -> None: ...
    def is_pixel_opaque(self, what: Render | Surface | GL2Model) -> int: ...
    def kill_textures(self) -> None: ...
    def load_all_textures(self, what: Render | Surface | GL2Model) -> None: ...
    def load_texture(
        self, surf: Surface, transient: bool = False, properties: dict[Incomplete, Incomplete] = {}
    ) -> Incomplete: ...
    def mouse_event(self, ev: renpy.pygame.event.EventType) -> tuple[int, int]: ...
    def mutated_surface(self, surf: Surface) -> None: ...
    def on_resize(self, first: bool = False, full_reset: bool = False) -> None: ...
    def quit(self) -> None: ...
    def quit_fbo(self) -> None: ...
    def ready_one_texture(self) -> bool: ...
    def render_to_texture(
        self, what: Render | Surface | GL2Model, alpha: bool = True, properties: dict = {}
    ) -> Incomplete: ...
    def resize(self) -> None: ...
    def screenshot(self, render_tree: Incomplete) -> Incomplete: ...
    def select_framerate(self) -> None: ...
    def select_gl_attributes(self, gles: float) -> None: ...
    def select_physical_size(self, physical_size: tuple[float, float]) -> tuple[int, int]: ...
    def set_mouse_pos(self, x: float, y: float) -> None: ...
    def should_redraw(self, needs_redraw: bool, first_pass: bool, can_block: bool) -> bool: ...
    def solid_texture(self, w: int, h: int, color: tuple[int, int, int, int]) -> GL2Model: ...
    def translate_point(self, x: float, y: float) -> tuple[int, int]: ...
    def untranslate_point(self, x: float, y: float) -> tuple[int, int]: ...
    def update(self, force: bool = False) -> bool: ...

class GL2DrawingContext:
    projection_matrix = Matrix
    view_matrix = Matrix
    projectionview_matrix = Matrix
    model_matrix = Matrix
    def __init__(self) -> None: ...
    def merge_uniforms(self, uniforms: dict[Incomplete, Incomplete]) -> None: ...

def draw_render(
    what: Render | Surface | GL2Model,
    drawable_width: int,
    drawable_height: int,
    projection: Matrix,
    invert_front_face: bool = False,
) -> None: ...
def set_cull_face(cull_face: Literal["ccw", "cw", None]) -> None: ...
