from _frozen_importlib import BuiltinImporter as BuiltinImporter

class GL2Model:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def copy(self) -> GL2Model: ...
    def get_size(self) -> None: ...
    def get_texture(self, i: int) -> GL2Model: ...
    def load(self) -> None: ...
    def scale(self, factor: float): ...
    def set_texture(self, i: int, texture: GL2Model) -> None: ...
    def subsurface(self, rect) -> None: ...
