import renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from renpy.gl2.gl2mesh import Mesh as Mesh

class Mesh3(renpy.gl2.gl2mesh.Mesh):
    def __init__(self, layout: AttributeLayout, points: int, triangles: int) -> None: ...
    def crop(self, p: Polygon) -> Mesh3: ...
    def get_point0(self) -> tuple[float, float, float, float]: ...
    def get_points(self) -> list[tuple[float, float, float, float]]: ...
    @staticmethod
    def rectangle(pl: float, pb: float, pr: float, pt: float) -> Mesh3: ...
    @staticmethod
    def texture_rectangle(
        pl: float, pb: float, pr: float, pt: float, tl: float, tb: float, tr: float, tt: float
    ) -> Mesh3: ...
