from _frozen_importlib import BuiltinImporter as BuiltinImporter

class AttributeLayout:
    def __reduce__(self) -> None: ...
    def add_attribute(self, name, length) -> None: ...

class Mesh:
    def __reduce__(self) -> None: ...
    def get_triangles(self) -> None: ...
    def set_attribute_data(self, attributes) -> None: ...
    def set_geometry_data(self, geometry) -> None: ...
    def set_triangle_data(self, triangles) -> None: ...
