class GL2Model:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __repr__(self, /): ...
    def __setstate__(self, __pyx_state): ...
    def copy(self) -> "GL2Model": ...
    def get_size(self): ...
    def get_texture(self, i: int) -> "GL2Model": ...
    def load(self): ...
    def scale(self, factor: float): ...
    def set_texture(self, i: int, texture: "GL2Model") -> None: ...
    def subsurface(self, rect): ...
