from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

class AttributeLayout:
    def __reduce__(self) -> None: ...
    def add_attribute(self, name: Incomplete, length: Incomplete) -> None: ...

class Mesh:
    def __reduce__(self) -> None: ...
    def get_triangles(self) -> None: ...
    def set_attribute_data(self, attributes: Incomplete) -> None: ...
    def set_geometry_data(self, geometry: Incomplete) -> None: ...
    def set_triangle_data(self, triangles: Incomplete) -> None: ...
