import renpy

class Mesh3(renpy.gl2.gl2mesh.Mesh):
    def __init__(self, layout: "AttributeLayout", points: int, triangles: int): ...
    def __reduce__(self): ...
    def __repr__(self, /): ...
    def __setstate__(self, __pyx_state): ...
    def crop(self, p: "Polygon") -> "Mesh3": ...
    def get_point0(self): ...
    def get_points(self): ...
    @staticmethod
    def rectangle(pl: float, pb: float, pr: float, pt: float): ...
    @staticmethod
    def texture_rectangle(pl: float, pb: float, pr: float, pt: float, tl: float, tb: float, tr: float, tt: float): ...
