from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

class GL2Model:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def copy(self) -> GL2Model: ...
    def get_size(self) -> None: ...
    def get_texture(self, i: int) -> GL2Model: ...
    def load(self) -> None: ...
    def scale(self, factor: float) -> Incomplete: ...
    def set_texture(self, i: int, texture: GL2Model) -> None: ...
    def subsurface(self, rect: Incomplete) -> None: ...
