from _frozen_importlib import BuiltinImporter as BuiltinImporter

class Polygon:
    def __init__(self, allocate_points: int) -> None: ...
    def __reduce__(self) -> None: ...
    def copy(self) -> Polygon: ...
    def ensure_winding(self) -> None: ...
    @staticmethod
    def from_list(l: list) -> Incomplete: ...
    def intersect(self, p: Polygon) -> Polygon: ...
    def multiply_matrix(self, m: Matrix) -> Polygon: ...
    def multiply_matrix_inplace(self, m: Matrix) -> None: ...
    def offset(self, x: float, y: float) -> Polygon: ...
    def offset_inplace(self, x: float, y: float) -> None: ...
    @staticmethod
    def rectangle(l: float, b: float, r: float, t: float) -> Incomplete: ...
