from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

class Attribute:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...

class Program:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def draw(self, context: GL2DrawingContext, model: GL2Model, mesh: Mesh) -> Incomplete: ...
    def draw_ftl(self, texture: int, mesh: Mesh) -> Incomplete: ...
    def find_variables(self, source: Incomplete, seen_uniforms: set, samplers: int) -> Incomplete: ...
    def load(self) -> None: ...

class ShaderError(Exception): ...

class Variable:
    def __init__(self, shader_name: Incomplete, line: Incomplete) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    storage: str | None
    type: str | None
    name: str | None
    array: int | None
    line: str

def generate_uniform_setter(
    shader_name: str, location: int, uniform_name: str, uniform_type: str, array: int | None, sampler: int
) -> Incomplete: ...
