import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from renpy.gl2.gl2model import GL2Model as GL2Model
from _typeshed import Incomplete

class GLTexture(renpy.gl2.gl2model.GL2Model):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def add_mipmap(self) -> None: ...
    def allocate_texture(self, tex: int, tw: int, th: int, properties={}) -> Incomplete: ...
    def from_render(self, what: Incomplete, properties: Incomplete) -> None: ...
    def from_surface(self, surface: Incomplete, properties: Incomplete) -> None: ...
    def get_number(self) -> None: ...
    def get_texture(self, i: int) -> GL2Model: ...
    def load(self) -> None: ...
    def load_gltexture(self) -> None: ...
    def load_gltexture_premultiplied(self) -> None: ...
    def mipmap_texture(self, tex: int, tw: int, th: int, properties={}) -> Incomplete: ...
    def should_have_mipmaps(self, properties: Incomplete) -> None: ...
    def subsurface(self, rect: Incomplete) -> None: ...

class Texture(GLTexture): ...

class TextureLoader:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def cleanup(self) -> None: ...
    def get_texture_size(self) -> None: ...
    def init(self) -> None: ...
    def load_one_surface(
        self, surf: Incomplete, bl: Incomplete, bt: Incomplete, br: Incomplete, bb: Incomplete, properties: Incomplete
    ) -> None: ...
    def load_surface(self, surf: Incomplete, properties: Incomplete) -> None: ...
    def quit(self) -> None: ...
    def ready_one_texture(self) -> None: ...
    def render_to_texture(self, what: Incomplete, properties: Incomplete) -> None: ...
    def texture_axis(self, length: Incomplete, limit: Incomplete, border: Incomplete) -> None: ...
