import renpy as renpy
from _frozen_importlib import BuiltinImporter as BuiltinImporter
from renpy.gl2.gl2model import GL2Model as GL2Model

class GLTexture(renpy.gl2.gl2model.GL2Model):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def add_mipmap(self) -> None: ...
    def allocate_texture(self, tex: int, tw: int, th: int, properties={}): ...
    def from_render(self, what, properties) -> None: ...
    def from_surface(self, surface, properties) -> None: ...
    def get_number(self) -> None: ...
    def get_texture(self, i: int) -> GL2Model: ...
    def load(self) -> None: ...
    def load_gltexture(self) -> None: ...
    def load_gltexture_premultiplied(self) -> None: ...
    def mipmap_texture(self, tex: int, tw: int, th: int, properties={}): ...
    def should_have_mipmaps(self, properties) -> None: ...
    def subsurface(self, rect) -> None: ...

class Texture(GLTexture): ...

class TextureLoader:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> None: ...
    def cleanup(self) -> None: ...
    def get_texture_size(self) -> None: ...
    def init(self) -> None: ...
    def load_one_surface(self, surf, bl, bt, br, bb, properties) -> None: ...
    def load_surface(self, surf, properties) -> None: ...
    def quit(self) -> None: ...
    def ready_one_texture(self) -> None: ...
    def render_to_texture(self, what, properties) -> None: ...
    def texture_axis(self, length, limit, border) -> None: ...
