from _frozen_importlib import BuiltinImporter as BuiltinImporter

class Getter:
    def __init__(self, uniform_name: str) -> None: ...

class ContextGetter(Getter): ...
class DrawableSizeGetter(Getter): ...

class InverseGetter(Getter):
    def __init__(self, uniform_name: str, getter: Getter) -> None: ...

class InverseTransposeGetter(Getter):
    def __init__(self, uniform_name: str, getter: Getter) -> None: ...

class LODBiasGetter(Getter): ...
class ModelGetter(Getter): ...
class ModelSizeGetter(Getter): ...

class PremultiplyGetter(Getter):
    def __init__(self, uniform_name: str, getter: Getter) -> None: ...

class ProjectionGetter(Getter): ...
class ProjectionViewGetter(Getter): ...
class RandomGetter(Getter): ...
class Res0Getter(Getter): ...
class Res1Getter(Getter): ...
class Res2Getter(Getter): ...
class Res3Getter(Getter): ...

class ResGetter(Getter):
    def __init__(self, uniform_name: str, getter: Getter) -> None: ...

class Tex0Getter(Getter): ...
class Tex1Getter(Getter): ...
class Tex2Getter(Getter): ...
class Tex3Getter(Getter): ...
class TimeGetter(Getter): ...

class TransformMatrixGetter(Getter):
    def __init__(self, uniform_name: str) -> None: ...

class TransposeGetter(Getter):
    def __init__(self, uniform_name: str, getter: Getter) -> None: ...

class ViewGetter(Getter): ...
class ViewportGetter(Getter): ...
class VirtualSizeGetter(Getter): ...

class Setter:
    def __init__(self, uniform_name: str, uniform_type: str, location: int, getter: Getter) -> None: ...

class FloatSetter(Setter): ...
class IVec2Setter(Setter): ...
class IVec3Setter(Setter): ...
class IVec4Setter(Setter): ...
class IntSetter(Setter): ...
class Mat2Setter(Setter): ...
class Mat3Setter(Setter): ...
class Mat4Setter(Setter): ...

class Sampler2DSetter(Setter):
    def __init__(self, uniform_name: str, uniform_type: str, location: int, getter: Getter, sampler: int) -> None: ...

class Vec2Setter(Setter): ...
class Vec3Setter(Setter): ...
class Vec4Setter(Setter): ...

class ArraySetter(Setter):
    def __init__(self, uniform_name: str, uniform_type: str, location: int, getter: Getter, length: int) -> None: ...

class FloatArraySetter(ArraySetter): ...
class IVec2ArraySetter(ArraySetter): ...
class IVec3ArraySetter(ArraySetter): ...
class IVec4ArraySetter(ArraySetter): ...
class IntArraySetter(ArraySetter): ...
class Vec2ArraySetter(ArraySetter): ...
class Vec3ArraySetter(ArraySetter): ...
class Vec4ArraySetter(ArraySetter): ...

NON_ARRAY_SETTERS: dict[str, type[Setter]]
ARRAY_SETTERS: dict[str, type[ArraySetter]]
TEXTURE_SCALING: dict[str, tuple[int, int]]
UNIFORM_GETTER_CLASSES: dict[str, tuple[type[Getter], str]]

def generate_uniform_setter(
    shader_name: str, location: int, uniform_name: str, uniform_type: str, array: int | None, sampler: int
) -> tuple[Setter, int]: ...
