from _frozen_importlib import BuiltinImporter as BuiltinImporter
from typing import Any

class ArraySetter(Setter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class ContextGetter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class DrawableSizeGetter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class FloatArraySetter(ArraySetter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class FloatSetter(Setter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Getter:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class IVec2ArraySetter(ArraySetter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class IVec2Setter(Setter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class IVec3ArraySetter(ArraySetter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class IVec3Setter(Setter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class IVec4ArraySetter(ArraySetter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class IVec4Setter(Setter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class IntArraySetter(ArraySetter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class IntSetter(Setter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class InverseGetter(Getter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class InverseTransposeGetter(Getter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class LODBiasGetter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Mat2Setter(Setter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Mat3Setter(Setter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Mat4Setter(Setter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class ModelGetter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class ModelSizeGetter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class PremultiplyGetter(Getter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class ProjectionGetter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class ProjectionViewGetter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class RandomGetter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Res0Getter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Res1Getter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Res2Getter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Res3Getter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class ResGetter(Getter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Sampler2DSetter(Setter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Setter:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Tex0Getter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Tex1Getter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Tex2Getter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Tex3Getter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class TimeGetter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class TransformMatrixGetter(Getter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class TransposeGetter(Getter):
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Vec2ArraySetter(ArraySetter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Vec2Setter(Setter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Vec3ArraySetter(ArraySetter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Vec3Setter(Setter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Vec4ArraySetter(ArraySetter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Vec4Setter(Setter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class ViewGetter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class ViewportGetter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class VirtualSizeGetter(Getter):
    def __reduce__(self) -> str | tuple[Any, ...]: ...

def generate_uniform_setter(
    shader_name: str, location: int, uniform_name: str, uniform_type: str, array: int | None, sampler: int
) -> Incomplete: ...
