from typing import Protocol

class MotionBase(Protocol):
    duration: float
    def get(
        self, st: float, fade_st: float | None, do_fade_in: bool, do_fade_out: bool
    ) -> dict[tuple[str, str], tuple[float, float]]: ...
    def wait(self, st: float, fade_st: float | None, do_fade_in: bool, do_fade_out: bool) -> float | None: ...

class MotionSegment(Protocol):
    duration: float
    def get(self, t: float) -> float: ...
    def wait(self, t: float) -> float: ...

def cosine_easing(done: float) -> float: ...

class Linear(MotionSegment):
    duration: float
    y0: float
    y1: float
    def __init__(self, x0: float, y0: float, x1: float, y1: float) -> None: ...
    def get(self, t: float) -> float: ...
    def wait(self, t: float) -> float: ...

class Step(MotionSegment):
    duration: float
    y0: float
    y1: float
    def __init__(self, x0: float, y0: float, x1: float, y1: float) -> None: ...
    def get(self, t: float) -> float: ...
    def wait(self, t: float) -> float: ...

class InvStep(MotionSegment):
    duration: float
    y0: float
    y1: float
    def __init__(self, x0: float, y0: float, x1: float, y1: float) -> None: ...
    def get(self, t: float) -> float: ...
    def wait(self, t: float) -> float: ...

class Bezier(MotionSegment):
    duration: float
    x0: int
    x1: float
    x2: float
    x3: float
    y0: float
    y1: float
    y2: float
    y3: float
    def __init__(
        self, x0: float, y0: float, x1: float, y1: float, x2: float, y2: float, x3: float, y3: float
    ) -> None: ...
    def get(self, t: float) -> float: ...
    def wait(self, t: float) -> float: ...

class Motion(MotionBase):
    filename: str
    duration: float
    curves: dict[tuple[str, str], list[MotionSegment]]
    fades: dict[tuple[str, str], tuple[float, float]]
    def __init__(self, filename: str, fadein: float, fadeout: float) -> None: ...
    def get(
        self, st: float, fade_st: float | None, do_fade_in: bool, do_fade_out: bool
    ) -> dict[tuple[str, str], tuple[float, float]]: ...
    def wait(self, st: float, fade_st: float | None, do_fade_in: bool, do_fade_out: bool) -> float | None: ...

class NullMotion(MotionBase):
    duration: float
    def get(
        self, st: float, fade_st: float | None, do_fade_in: bool, do_fade_out: bool
    ) -> dict[tuple[str, str], tuple[float, float]]: ...
    def wait(self, st: float, fade_st: float | None, do_fade_in: bool, do_fade_out: bool) -> float | None: ...
