from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete

class AlignedMemory:
    def __init__(self, /, *args, **kwargs) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...

class Live2DModel:
    def __init__(self, fn: Incomplete) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def blend_opacity(self, name: Incomplete, blend: Incomplete, value: Incomplete, weight: float = 1.0) -> None: ...
    def blend_parameter(self, name: Incomplete, blend: Incomplete, value: Incomplete, weight: float = 1.0) -> None: ...
    def finish_parameters(self) -> None: ...
    def get_size(self) -> None: ...
    def render(self, textures: Incomplete, zoom: Incomplete) -> None: ...
    def reset_parameters(self) -> None: ...
    def set_parameter(self, name: Incomplete, value: Incomplete, weight: float = 1.0) -> None: ...
    def set_part_opacity(self, name: Incomplete, value: Incomplete) -> None: ...
    parameters: dict[str, Parameter]
    parts: dict[str, Part]
    parameter_groups: dict
    opacity_groups: dict

class Parameter:
    def __init__(
        self, index: Incomplete, name: Incomplete, minimum: Incomplete, maximum: Incomplete, default: Incomplete
    ) -> None: ...

class Part:
    def __init__(self, index: Incomplete, name: Incomplete, default_opacity: Incomplete) -> None: ...

def load(dll: Incomplete) -> None: ...
def post_init() -> None: ...
