from _frozen_importlib import BuiltinImporter as BuiltinImporter
from _typeshed import Incomplete
from renpy.display.render import Render

class AlignedMemory:
    def __init__(self, size: int, alignment: int, data: bytes) -> None: ...

class Live2DModel:
    moc_version: Incomplete
    parameters: dict[str, Parameter]
    parts: dict[str, Part]
    parameter_groups: dict[str, list[str]]
    opacity_groups: dict[Incomplete, Incomplete]

    def __init__(self, fn: str) -> None: ...
    def blend_opacity(self, name: str, blend: str, value: float, weight: float = 1.0) -> None: ...
    def blend_parameter(self, name: str, blend: str, value: float, weight: float = 1.0) -> None: ...
    def finish_parameters(self) -> None: ...
    def get_size(self) -> tuple[float, float]: ...
    def render(self, textures: list[Incomplete], zoom: float) -> Render: ...
    def reset_parameters(self) -> None: ...
    def set_parameter(self, name: str, value: float, weight: float = 1.0) -> None: ...
    def set_part_opacity(self, name: str, value: float) -> None: ...

class Parameter:
    def __init__(self, index: int, name: str, minimum: float, maximum: float, default: float) -> None: ...

class Part:
    def __init__(self, index: int, name: str, default_opacity: float) -> None: ...

def load(dll: str) -> bool: ...
def post_init() -> None: ...
