class AlignedMemory:
    def __init__(self, /, *args, **kwargs): ...
    def __reduce__(self): ...
    def __setstate__(self, __pyx_state): ...

class Live2DModel:
    def __init__(self, fn): ...
    def __reduce__(self): ...
    def __repr__(self): ...
    def __setstate__(self, __pyx_state): ...
    def blend_opacity(self, name, blend, value, weight=1.0): ...
    def blend_parameter(self, name, blend, value, weight=1.0): ...
    def finish_parameters(self): ...
    def get_size(self): ...
    def render(self, textures, zoom): ...
    def reset_parameters(self): ...
    def set_parameter(self, name, value, weight=1.0): ...
    def set_part_opacity(self, name, value): ...

    parameters: "dict[str, Parameter]"
    parts: "dict[str, Part]"
    parameter_groups: dict
    opacity_groups: dict

class Parameter:
    def __init__(self, index, name, minimum, maximum, default): ...

    pass

class Part:
    def __init__(self, index, name, default_opacity): ...

    pass

def load(dll): ...
def post_init(): ...
