from _typeshed import Incomplete as Incomplete

def cosine_easing(done): ...

class Linear:
    duration: Incomplete
    y0: Incomplete
    y1: Incomplete
    def __init__(self, x0, y0, x1, y1) -> None: ...
    def get(self, t): ...
    def wait(self, t): ...

class Step:
    duration: Incomplete
    y0: Incomplete
    y1: Incomplete
    def __init__(self, x0, y0, x1, y1) -> None: ...
    def get(self, t): ...
    def wait(self, t): ...

class InvStep:
    duration: Incomplete
    y0: Incomplete
    y1: Incomplete
    def __init__(self, x0, y0, x1, y1) -> None: ...
    def get(self, t): ...
    def wait(self, t): ...

class Bezier:
    duration: Incomplete
    x0: int
    x1: Incomplete
    x2: Incomplete
    x3: Incomplete
    y0: Incomplete
    y1: Incomplete
    y2: Incomplete
    y3: Incomplete
    def __init__(self, x0, y0, x1, y1, x2, y2, x3, y3) -> None: ...
    def get(self, t): ...
    def wait(self, t): ...

class Motion:
    filename: Incomplete
    duration: Incomplete
    curves: Incomplete
    fades: Incomplete
    def __init__(self, filename, fadein, fadeout) -> None: ...
    def get(self, st, fade_st, do_fade_in, do_fade_out): ...
    def wait(self, st, fade_st, do_fade_in, do_fade_out): ...

class NullMotion:
    duration: float
    def get(self, st, fade_st, do_fade_in, do_fade_out): ...
    def wait(self, st, fade_st, do_fade_in, do_fade_out): ...
