from _typeshed import Incomplete

mouse_pos: tuple[int, int] | None
mouse_buttons: Incomplete

def get_mouse_pos(x: int, y: int) -> tuple[int, int]: ...
def post(event_type: int, **kwargs) -> None: ...
def move_mouse(x: int, y: int) -> None: ...
def press_mouse(button: int) -> None: ...
def release_mouse(button: int) -> None: ...
def click_mouse(button: int, x: int, y: int) -> None: ...
def scroll_mouse(amount: int, x: int, y: int) -> None: ...
def reset() -> None: ...
