from _typeshed import Incomplete
from renpy.test.testast import Node as Node

code_to_unicode: Incomplete
unicode_to_code: Incomplete

def get_keycode(node: Node, keysym: str) -> tuple[int, str | None, int]: ...
def down(node: Node, keysym: str) -> None: ...
def up(node: Node, keysym: str) -> None: ...
def queue_keysym(node: Node, name: str) -> None: ...
