from dataclasses import dataclass

@dataclass
class TestReportSettings:
    hide_header: bool = ...
    hide_execution: str = ...
    hide_summary: bool = ...
    report_detailed: bool = ...
    report_skipped: bool = ...

@dataclass
class TestSettings:
    enable_all: bool = ...
    focus_trials: int = ...
    force: bool = ...
    vc_revision: str = ...
    maximum_framerate: bool = ...
    overwrite_screenshots: bool = ...
    screenshot_directory: str = ...
    timeout: float = ...
    transition_timeout: float = ...
    report = ...
