import abc
import renpy
from dataclasses import dataclass, field
from enum import Enum
from renpy.error import (
    ANSIColors as ANSIColors,
    ExceptionPrintContext as ExceptionPrintContext,
    FrameSummary as FrameSummary,
)
from renpy.test.testast import (
    Assert as Assert,
    BaseTestBlock as BaseTestBlock,
    TestCase as TestCase,
    TestHook as TestHook,
    TestSuite as TestSuite,
)
from renpy.test.testsettings import _test as _test
from renpy.test.types import RenpyTestAssertionError as RenpyTestAssertionError
from _typeshed import Incomplete as Incomplete

def format_seconds(seconds: float) -> str: ...

class OutcomeStatus(Enum):
    NOT_RUN = "not_run"
    PENDING = "pending"
    PASSED = "passed"
    XFAILED = "xfailed"
    FAILED = "failed"
    XPASSED = "xpassed"
    SKIPPED = "skipped"

@dataclass
class BaseOutcome:
    test_block: BaseTestBlock = field(repr=False)
    name: str = ...
    full_path: str = ...
    parent: BaseOutcome | None = field(default=None, repr=False)
    num_asserts: int = ...
    num_asserts_passed: int = ...
    num_asserts_xfailed: int = ...
    num_asserts_failed: int = ...
    num_asserts_xpassed: int = ...
    start_time: float = field(default=0.0, repr=False)
    end_time: float = field(default=0.0, repr=False)
    duration: float = ...
    status: OutcomeStatus = ...
    exception: str = ...
    def begin(self) -> None: ...
    def finalize_time(self) -> None: ...
    def end(self, status: OutcomeStatus | None = None) -> None: ...

@dataclass
class TestHookOutcome(BaseOutcome):
    test_block: TestHook = field(repr=False)

@dataclass
class TestCaseOutcome(BaseOutcome):
    test_block: TestCase = field(repr=False)

@dataclass
class TestSuiteOutcome(TestCaseOutcome):
    test_block: TestSuite = field(repr=False)
    name: str = ...
    children: list[BaseOutcome] = field(default_factory=list, repr=False)
    num_testsuites: int = ...
    num_testsuites_passed: int = ...
    num_testsuites_xfailed: int = ...
    num_testsuites_failed: int = ...
    num_testsuites_xpassed: int = ...
    num_testsuites_skipped: int = ...
    num_testcases: int = ...
    num_testcases_passed: int = ...
    num_testcases_xfailed: int = ...
    num_testcases_failed: int = ...
    num_testcases_xpassed: int = ...
    num_testcases_skipped: int = ...
    num_hooks: int = ...
    num_hooks_passed: int = ...
    num_hooks_xfailed: int = ...
    num_hooks_failed: int = ...
    num_hooks_xpassed: int = ...
    num_hooks_skipped: int = ...
    def get_child_by_test_block(self, test_block: BaseTestBlock) -> BaseOutcome: ...
    status = ...
    def end(self, status: OutcomeStatus | None = None) -> None: ...

class OutcomeManager(TestSuiteOutcome):
    @property
    def num_testsuites_not_run(self) -> int: ...
    @property
    def num_testcases_not_run(self) -> int: ...
    @property
    def num_hooks_not_run(self) -> int: ...
    root: TestSuite
    children: list[BaseOutcome]
    def __init__(self, root: TestSuite) -> None: ...
    def build_outcome_hierarchy(self, suite: TestSuite, parent_outcome: TestSuiteOutcome) -> list[BaseOutcome]: ...
    def get_outcome_by_test_block(self, test_block: BaseTestBlock) -> BaseOutcome: ...

def get_exception_string(
    epc: renpy.error.ExceptionPrintContext, exception: Exception, run_stack: list[renpy.error.FrameSummary]
) -> str: ...
def get_assertion_error_string(epc: renpy.error.ExceptionPrintContext, assert_node: Assert, node_name: str) -> str: ...

class Reporter(abc.ABC):
    epc: renpy.error.ExceptionPrintContext
    def __init__(self) -> None: ...
    def test_run_start(self, outcomes: OutcomeManager) -> None: ...
    def test_run_end(self, outcomes: OutcomeManager) -> None: ...
    def test_suite_start(self, outcome: TestSuiteOutcome, depth: int = 0) -> None: ...
    def test_suite_end(self, outcome: TestSuiteOutcome, depth: int = 0) -> None: ...
    def test_case_start(self, outcome: TestCaseOutcome, depth: int = 0) -> None: ...
    def test_case_end(self, outcome: TestCaseOutcome, depth: int = 0) -> None: ...
    def test_hook_start(self, outcome: TestHookOutcome, depth: int = 0) -> None: ...
    def test_hook_end(self, outcome: TestHookOutcome, depth: int = 0) -> None: ...
    def test_case_skipped(self, outcome: TestCaseOutcome, depth: int = 0) -> None: ...
    def log_assert(self, assert_node: Assert, status: OutcomeStatus, node_name: str = "") -> None: ...
    def log_exception(self, exception: Exception, run_stack: list[renpy.error.FrameSummary], xfailed: bool) -> None: ...
    def log_message(self, message: str) -> None: ...
    def on_reload(self) -> None: ...

class ConsoleReporter(Reporter):
    _is_last_line_written_by_reporter: bool
    def __init__(self) -> None: ...
    def stdout_callback(self, text: str) -> None: ...
    def _erase_line(self) -> bool: ...
    def _print(self, text: str, end: str = "\n") -> None: ...
    def _format_with_status_color(self, msg: str, status: OutcomeStatus | None) -> str: ...
    def _get_status_text(self, status: OutcomeStatus) -> str: ...
    def _print_detailed_outcome(self, outcome: BaseOutcome, depth: int = -1) -> None: ...
    def _print_summarized_outcomes(self, outcome: OutcomeManager) -> None: ...
    def test_run_start(self, outcomes: Incomplete) -> None: ...
    def test_run_end(self, outcomes: Incomplete) -> None: ...
    def test_suite_start(self, outcome: Incomplete, depth: int = 0) -> None: ...
    def test_suite_end(self, outcome: Incomplete, depth: int = 0) -> None: ...
    def test_case_start(self, outcome: Incomplete, depth: int = 0) -> None: ...
    def test_case_end(self, outcome: Incomplete, depth: int = 0) -> None: ...
    def test_hook_start(self, outcome: Incomplete, depth: int = 0) -> None: ...
    def test_hook_end(self, outcome: Incomplete, depth: int = 0) -> None: ...
    def test_case_skipped(self, outcome: Incomplete, depth: int = 0) -> None: ...
    def log_assert(self, assert_node: Incomplete, status: Incomplete, node_name: str = "") -> None: ...
    def log_exception(self, exception: Incomplete, run_stack: Incomplete, xfailed: Incomplete) -> None: ...
    def log_message(self, message: Incomplete) -> None: ...
    def on_reload(self) -> None: ...

class ReporterManager:
    reporters: list["Reporter"]
    outcome_manager: OutcomeManager | None
    suites: list[TestSuite]
    testcase: TestCase | None
    hook: TestHook | None
    def initialize_test_outcomes(self, suite: TestSuite) -> None: ...
    @property
    def has_failed(self) -> bool: ...
    def add_reporter(self, reporter: Reporter) -> None: ...
    def test_run_start(self) -> None: ...
    def test_run_end(self) -> None: ...
    def test_suite_start(self, suite: TestSuite, depth: int = 0) -> None: ...
    def test_suite_end(self, suite: TestSuite, status: OutcomeStatus | None = None, depth: int = 0) -> None: ...
    def test_case_start(self, test_case: TestCase, depth: int = 0) -> None: ...
    def test_case_end(self, test_case: TestCase, status: OutcomeStatus | None = None, depth: int = 0) -> None: ...
    def test_hook_start(self, hook: TestHook, depth: int = 0) -> None: ...
    def test_hook_end(self, hook: TestHook, status=None, depth: int = 0) -> None: ...
    def test_case_skipped(self, test_case: TestCase, depth: int = 0) -> None: ...
    def log_assert(self, assert_node: Assert) -> None: ...
    def _determine_assert_status(self, assert_node: Assert, outcome: BaseOutcome) -> OutcomeStatus: ...
    def _update_assert_counters(self, outcome: BaseOutcome, status: OutcomeStatus) -> None: ...
    def log_exception(
        self, exception: Exception, run_stack: list[renpy.error.FrameSummary], xfailed: bool = False
    ) -> None: ...
    def log_message(self, message: str) -> None: ...
    def on_reload(self) -> None: ...
    def _current_test_block(self) -> BaseTestBlock: ...
    def _get_current_outcomes(self) -> BaseOutcome: ...

reporter: ReporterManager
