import renpy.test.testast as testast
from _typeshed import Incomplete
from renpy.lexer import Lexer as Lexer
from renpy.test.types import HookType as HookType, NodeLocation as NodeLocation
from typing import Any, Collection

test_statements: Incomplete

def test_statement(keywords): ...
def exit_statement(l: Lexer, loc: NodeLocation) -> testast.Exit: ...
def if_statement(l: Lexer, loc: NodeLocation) -> testast.If: ...
def pass_statement(l: Lexer, loc: NodeLocation) -> testast.Pass: ...
def advance_statement(l: Lexer, loc: NodeLocation) -> testast.Advance | testast.Until: ...
def click_statement(l: Lexer, loc: NodeLocation) -> testast.Click | testast.Until: ...
def drag_statement(l: Lexer, loc: NodeLocation) -> testast.Drag: ...
def keysym_statement(l: Lexer, loc: NodeLocation) -> testast.Keysym | testast.Until: ...
def move_statement(l: Lexer, loc: NodeLocation) -> testast.Move | testast.Until: ...
def pause_statement(l: Lexer, loc: NodeLocation) -> testast.Pause | testast.Until: ...
def run_statement(l: Lexer, loc: NodeLocation) -> testast.Action | testast.Until: ...
def scroll_statement(l: Lexer, loc: NodeLocation) -> testast.Scroll | testast.Until: ...
def skip_statement(l: Lexer, loc: NodeLocation) -> testast.Skip | testast.Until: ...
def type_statement(l: Lexer, loc: NodeLocation) -> testast.Type | testast.Until: ...
def testsuite_statement(l: Lexer, loc: NodeLocation) -> testast.TestSuite: ...
def testcase_statement(l: Lexer, loc: NodeLocation) -> testast.TestCase: ...
def assert_statement(l: Lexer, loc: NodeLocation) -> testast.Assert: ...
def screenshot_statement(l: Lexer, loc: NodeLocation) -> testast.Screenshot: ...
def python_statement(l: Lexer, loc: NodeLocation) -> testast.Python: ...
def one_line_python_statement(l: Lexer, loc: NodeLocation) -> testast.Python: ...
def parse_block(
    l: Lexer, loc: NodeLocation, keywords: Collection[str] | None = None
) -> tuple[testast.Block, dict[str, Any]]: ...
def parse_hook(l: Lexer, loc: NodeLocation, hook_type: HookType) -> testast.TestHook: ...
def parse_testcase_parameters(l: Lexer, loc: NodeLocation) -> list[dict[str, Any]]: ...
def parse_statement(l: Lexer, loc: NodeLocation) -> testast.Node: ...
def parse_selector(l: Lexer, loc: NodeLocation) -> testast.Selector | None: ...
def parse_condition(l: Lexer, loc: NodeLocation, left: testast.Condition | None = None) -> testast.Condition: ...
def parse_until(l: Lexer, loc: NodeLocation, left: testast.Node) -> testast.Until | None: ...
