import renpy.test.testreporter as testreporter
from _typeshed import Incomplete as Incomplete
from renpy.error import FrameSummary as FrameSummary
from renpy.test.testast import (
    BaseTestBlock as BaseTestBlock,
    Exit as Exit,
    Node as Node,
    TestCase as TestCase,
    TestHook as TestHook,
    TestSuite as TestSuite,
)
from renpy.test.types import (
    HookType as HookType,
    NodeLocation as NodeLocation,
    NodeState as NodeState,
    RenpyTestTimeoutError as RenpyTestTimeoutError,
)
from typing import Any, Callable

initialized: bool
global_testsuite_name: str
reached_labels: set[str]
suite_stack: list[TestSuite]
scope_stack: list[dict[str, Any]]
testcases: dict[str, TestCase]
node_executor: NodeExecutor
phase_controller: TestPhaseController

def exception_handler(exc: Exception) -> bool: ...
def execute() -> None: ...
def initialize(specified_test: str) -> None: ...
def has_default_testcase() -> bool: ...
def on_reload() -> None: ...
def is_in_test() -> bool: ...
def pop_suite_stack() -> None: ...
def push_suite_stack(suite: TestSuite) -> None: ...
def push_scope_stack(new_scope: dict[str, Any]) -> None: ...
def quit_handler() -> int: ...
def set_next_execution_node(next_node: Node | None) -> None: ...
def add_reached_label(label: str, abnormal: bool) -> None: ...
def get_current_scope() -> dict: ...
def scoped_eval(expr: str, store: str = "store") -> Any: ...
def scoped_exec(source: str, hide: bool = False, store: str = "store") -> None: ...
def link_top_level_testcase_to_parent(node: TestCase) -> None: ...
def add_child_testcases(parent: TestCase) -> None: ...
def register_testcase(node: TestCase, parent: TestSuite | None = None) -> None: ...

global_test_suite: TestSuite | None

def setup_global_test_suite() -> TestSuite: ...
def get_testcase_by_id(id: str) -> TestCase: ...
def process_only_flag() -> None: ...
def select_testcase(node: TestCase) -> None: ...
def update_suite_enabled_flag(node: TestSuite) -> None: ...

class NodeExecutor:
    node: Node | None
    node_state: NodeState | None
    node_has_started: bool
    next_node: Node | None
    old_state: NodeState | None
    old_loc: NodeLocation | None
    last_state_change: float
    end_callbacks: list[Callable] | None
    def __init__(self, node: Node | None = None) -> None: ...
    def reinitialize(self, node: Node | None) -> None: ...
    def set_next_node(self, next: Node | None) -> None: ...
    def set_end_callback(self, callback: Callable | list[Callable]) -> None: ...
    start: Incomplete
    def execute(self) -> None: ...
    def move_to_next_node_if_possible(self) -> None: ...
    def check_for_timeout(self, now) -> None: ...
    def cleanup_after_error(self) -> None: ...
    def update_last_state_change(self, now) -> None: ...
    @property
    def done(self) -> bool: ...

class TestPhaseController:
    active_phase: BaseExecutionPhase
    next_phase: BaseExecutionPhase | None
    def __init__(self, root_suite: TestSuite) -> None: ...
    @property
    def is_running(self) -> bool: ...
    def update(self) -> None: ...
    def transition_to_new_phase(self, new_state: BaseExecutionPhase | None) -> None: ...
    def handle_exception(self, exc: Exception) -> None: ...
    def get_frame_stack(self) -> list[FrameSummary]: ...
    def quit(self) -> None: ...

class BaseExecutionPhase:
    block: BaseTestBlock | None
    def enter(self) -> None: ...
    def error(self, status: testreporter.OutcomeStatus) -> BaseExecutionPhase | None: ...
    def update(self) -> BaseExecutionPhase | None: ...

class HookPhase(BaseExecutionPhase):
    def error(self, status): ...

class HookLoopPhase(HookPhase):
    suite_depth: int
    hook_type: HookType
    next_phase: type[BaseExecutionPhase]
    reverse: bool
    def __init__(self, reverse: bool = False) -> None: ...
    def enter(self) -> None: ...
    block: Incomplete
    def update(self) -> BaseExecutionPhase | None: ...
    def should_hook_run(self, hook: TestHook | None) -> bool: ...

class StartPhase(BaseExecutionPhase):
    root_suite: Incomplete
    def __init__(self, root_suite: TestSuite) -> None: ...
    def enter(self) -> None: ...
    def update(self) -> BaseExecutionPhase | None: ...

class EndPhase(BaseExecutionPhase):
    def enter(self) -> None: ...

class NextTestTransitionPhase(BaseExecutionPhase):
    def update(self) -> BaseExecutionPhase | None: ...

class BeforeTestSuitePhase(HookLoopPhase):
    hook_type: Incomplete
    next_phase: Incomplete
    reverse: bool
    def __init__(self) -> None: ...

class AddSubSuitePhase(BaseExecutionPhase):
    def enter(self) -> None: ...
    def update(self) -> BaseExecutionPhase | None: ...

class SuiteSetupPhase(HookPhase):
    block: Incomplete
    def enter(self) -> None: ...
    def update(self) -> BaseExecutionPhase | None: ...

class BeforeTestCasePhase(HookLoopPhase):
    hook_type: Incomplete
    next_phase: Incomplete
    reverse: bool
    def __init__(self) -> None: ...

class TestCasePhase(BaseExecutionPhase):
    block: Incomplete
    def enter(self) -> None: ...
    def error(self, status) -> BaseExecutionPhase | None: ...
    def update(self) -> BaseExecutionPhase | None: ...

class AfterTestCasePhase(HookLoopPhase):
    hook_type: Incomplete
    next_phase: Incomplete
    reverse: bool
    def __init__(self) -> None: ...

class TestCaseParameterCyclePhase(BaseExecutionPhase):
    def update(self) -> BaseExecutionPhase | None: ...

class SuiteTeardownPhase(HookPhase):
    block: Incomplete
    def enter(self) -> None: ...
    def update(self) -> BaseExecutionPhase | None: ...
    def error(self, status): ...

class RemoveSubSuitePhase(BaseExecutionPhase):
    def enter(self) -> None: ...
    def update(self) -> BaseExecutionPhase | None: ...

class AfterTestSuitePhase(HookLoopPhase):
    hook_type: Incomplete
    next_phase: Incomplete
    reverse: bool
    def __init__(self) -> None: ...

class TestSuiteParameterCyclePhase(BaseExecutionPhase):
    def update(self) -> BaseExecutionPhase | None: ...

class GlobalParameterCyclePhase(BaseExecutionPhase):
    def update(self) -> BaseExecutionPhase | None: ...

def test_command() -> bool: ...
