from renpy.display.displayable import Displayable as Displayable
from renpy.display.focus import Focus as Focus
from renpy.test.types import Position as Position

def find_focus(pattern: str, raw: bool) -> Focus | None: ...
def relative_to_absolute(posx: int | float, width: int) -> int: ...
def find_position(f: Focus | Displayable | None, position: Position | tuple[None, None]) -> tuple[int, int]: ...
def focus_from_displayable(d: Displayable) -> Focus | None: ...
